Repository truenas/middleware, pull requests merged in 2018-05, with the labels that each got.

#1242 fix(stable)be less restrictive on same share NFS exports
  gui/sharing/forms.py
Labels: review

#1222 fix(nfs): Be less restrictive about multiple NFS share of the same dataset
  gui/sharing/forms.py
  src/freenas/etc/ix.rc.d/ix-nfsd
  src/freenas/etc/ix.rc.d/ix_pf_late
  src/middlewared/middlewared/etc_files/nfsd.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py
  src/middlewared/middlewared/schema.py
Labels: review

#1220 Add first pass attempt at a Jenkins pipeline which removes ixbuild
  Jenkinsfile
  jenkins/Jenkins-depends.sh
  jenkins/Jenkinsfile-PR
Labels: WIP, enhancement, review

#1240 Write API functional tests for Init/Shutdown Scripts
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  tests/api2/initshutdownscript.py
  tests/runtest.py
Labels: api tests, review

#1252 fix(stable) remove intrusive freenas-debug modules
  src/freenas/usr/local/bin/freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/dtrace/dtrace.sh
  src/freenas/usr/local/libexec/freenas-debug/flame/dtstackcollapse_flame.pl
  src/freenas/usr/local/libexec/freenas-debug/flame/flame.sh
  src/freenas/usr/local/libexec/freenas-debug/flame/flame_kern_stacks.dtrace
  src/freenas/usr/local/libexec/freenas-debug/flame/flame_ustack.dtrace
  src/freenas/usr/local/libexec/freenas-debug/flame/flamegraph.pl
  src/freenas/usr/local/libexec/freenas-debug/latency/disklatencycmd.d
  src/freenas/usr/local/libexec/freenas-debug/latency/latency.sh
  src/freenas/usr/local/libexec/freenas-debug/slow_ops/slow_ops.sh
  src/freenas/usr/local/libexec/freenas-debug/slow_ops/zfslower.d
Labels: bug, review

#1245 Add System Advanced tests
  tests/api2/system_advanced.py
Labels: review

#1254 fix(middlewared/zfs): setting value on inherited attributes
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1250 feat(gui): initialize variables properly for HA update check
  gui/system/views.py
Labels: review

#1249 feat(gui): initialize variables properly for HA update check
  gui/system/views.py
Labels: review

#1247 Update method added to Disk plugin
  gui/storage/forms.py
  gui/storage/models.py
  src/middlewared/middlewared/plugins/disk.py
Labels: review

#1259 Write API functional tests for snmp
  src/middlewared/middlewared/plugins/snmp.py
  tests/api2/snmp.py
Labels: review

#1264 fix(master) fix typo in table name
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
Labels: review

#1265 fix(stable) fix typo in table name
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
Labels: review

#1266 fix(master) replace jq with json.tool in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: review

#1267 fix(stable) replace jq with json.tool in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: review

#1268 Add Static Route tests
  src/middlewared/middlewared/plugins/network.py
  tests/api2/staticroute.py
  tests/functions.py
Labels: review

#1260 Write API functional tests for dyndns
  tests/api2/dyndns.py
Labels: review

#1273 Tests added for Disk plugin
  tests/api2/disk.py
  tests/runtest.py
Labels: review

#1274 Queue Support for Jenkins
  jenkins/Jenkinsfile-PR
Labels: review

#1269 Allow self signed certificates
  gui/common/freenasldap.py
  src/freenas/usr/local/libexec/nas/generate_sssd_conf.py
Labels: review

#1270 Allow self signed certificates
  gui/common/freenasldap.py
  src/freenas/usr/local/libexec/nas/generate_sssd_conf.py
Labels: review

#1276 Shut pam_sss up when authenticating local users
  src/middlewared/middlewared/etc_files/pam.d/ftp
  src/middlewared/middlewared/etc_files/pam.d/ftpd
  src/middlewared/middlewared/etc_files/pam.d/login
  src/middlewared/middlewared/etc_files/pam.d/netatalk
  src/middlewared/middlewared/etc_files/pam.d/samba
  src/middlewared/middlewared/etc_files/pam.d/sshd
  src/middlewared/middlewared/etc_files/pam.d/su
  src/middlewared/middlewared/etc_files/pam.d/sudo
Labels: review

#1277 Shut pam_sss up when authenticating local users
  src/middlewared/middlewared/etc_files/pam.d/ftp
  src/middlewared/middlewared/etc_files/pam.d/ftpd
  src/middlewared/middlewared/etc_files/pam.d/login
  src/middlewared/middlewared/etc_files/pam.d/netatalk
  src/middlewared/middlewared/etc_files/pam.d/samba
  src/middlewared/middlewared/etc_files/pam.d/sshd
  src/middlewared/middlewared/etc_files/pam.d/su
  src/middlewared/middlewared/etc_files/pam.d/sudo
Labels: review

#1261 Add check to see if nis is enabled
  src/freenas/etc/ix.rc.d/ix-nis
Labels: review

#1275 Jenkins Performance Update
  jenkins/Jenkinsfile-PR
Labels: review

#1282 fix(stable) Add check to see if nis is enabled
  src/freenas/etc/ix.rc.d/ix-nis
Labels: review

#1281 fix(nfs): Fix maproot/mapall not having default null values in create
  src/middlewared/middlewared/plugins/nfs.py
Labels: review

#1280 Fix Queued issue
  jenkins/Jenkinsfile-PR
Labels: review

#1283 Backport system.advanced.config
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1272 feat(middlewared/system): add `buildtime` to system.info
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/utils/__init__.py
Labels: review

#1284 fix(master) remove parallel routines for freenas-debug
  src/freenas/usr/local/bin/freenas-debug
Labels: review

#1285 fix(stable) remove parallel routines for freenas-debug
  src/freenas/usr/local/bin/freenas-debug
Labels: review

#1286 fix(api): handle ValidationErrors from middleware
  gui/api/utils.py
Labels: review

#1287 Update License button needs to say "I agree" instead of "OK".
  gui/templates/support/license_update.html
Labels: review

#1278 Write API functional tests for ups
  tests/api2/ups.py
Labels: review

#1289 Update License button needs to say "I agree" instead of "OK".
  gui/templates/support/license_update.html
Labels: review

#1290 fix(sharing/cifs): Add defaults to keys that need it.
  src/middlewared/middlewared/plugins/smb.py
Labels: review

#1291 fix(api/resources): Pass through force attribute to ZFS replace
  docs/api/resources/storage.rst
  gui/api/resources.py
Labels: review

#1296 fix(api): iscsi target group broke in middlewared conversion
  gui/services/forms.py
Labels: review

#1297 Fix iSCSI tests
  tests/api1/iscsi.py
  tests/runtest.py
Labels: review

#1298 fix(middlewared/service): remove CRASHED state
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1293 fix(zfs/dataset): Umount before deletion
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1294 fix(sharing/afp): Add missing default values
  src/middlewared/middlewared/plugins/afp.py
Labels: review

#1299 feat(restful): allow GET in a subresource (/{service}/id/{id}/)
  src/middlewared/middlewared/restful.py
Labels: review

#1300 fix(ngix-middlewared): remove path from proxy_pass to disable decoding
  src/freenas/etc/ix.rc.d/ix-nginx
Labels: review

#1305 Fix alert deletion
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1307 Fix alerts on ha
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/plugins/alert.py
Labels: review

#1309 Address @william-gr's review
  src/middlewared/middlewared/plugins/disk.py
Labels: review

#1308 fix(disk.sync_all)
  src/freenas/etc/ix.rc.d/ix-syncdisks
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/pytest/functional/test_0025_disk.py
Labels: review

#1301 catia needs to come before zfsacl
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1310 Fix builds
  jenkins/Jenkinsfile-PR
Labels: review

#1311 feat(api): add endpoint to zfs remove a disk
  docs/api/resources/storage.rst
  gui/api/resources.py
Labels: review

#1313 feat(middlewared/pool): add `compressratio` to `pool.dataset.query`
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1279 Vcenter Plugin moved to Middlewared
  gui/vcp/forms.py
  gui/vcp/migrations/0002_auto_20180523_1943.py
  gui/vcp/models.py
  gui/vcp/plugin.py
  gui/vcp/utils.py
  gui/vcp/views.py
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/notifier.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/plugins/vcenter.py
  src/middlewared/middlewared/service_exception.py
  src/middlewared/middlewared/validators.py
Labels: review

#1312 Minor fixes for ISCSI plugin
  src/middlewared/middlewared/plugins/iscsi.py
Labels: review

#1314 fix(smart): Temporarily enable monitoring for all NVMe devices if at …
  src/freenas/etc/ix.rc.d/ix-smartd
Labels: review

#1316 Make run_in_io_thread accept kwargs
  src/middlewared/middlewared/main.py
Labels: review

#1317 Revert "fix(smart): Temporarily enable monitoring for all NVMe devices if at …"
  src/freenas/etc/ix.rc.d/ix-smartd
Labels: review

#1320 Start nslcd on boot
  src/freenas/etc/ix.rc.d/ix-ldap
  src/freenas/etc/rc.conf.local
Labels: review

#1292 Convert Storage:Permissions to Middlewared
  src/middlewared/middlewared/plugins/pool.py
Labels: review
