Repository truenas/middleware, pull requests merged in 2018-08, with the labels that each got.

#1609 fix(master) alert truenas HA customers properly
  src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
  src/middlewared/middlewared/plugins/unscheduled_reboot_alert.py
Labels: review

#1615 fix(stable) alert truenas HA customers properly
  src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
  src/middlewared/middlewared/plugins/unscheduled_reboot_alert.py
Labels: review

#1607 tkt-28203: Allow customer to declare system to be in production via UI
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/templates/supportticket.html
  gui/support/forms.py
  gui/support/views.py
  gui/system/hook.py
  gui/system/migrations/0026_keyvalue.py
  gui/system/models.py
  gui/templates/support/home.html
  gui/templates/system/index.html
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/keyvalue.py
Labels: backport-11.3, review

#1604 tkt-27756: Show cloud sync logs for all statuses
  gui/api/resources.py
Labels: backport-11.3, review

#1618 Legacy UI updated to format a wider cron syntax
  gui/api/resources.py
  gui/common/forms.py
  gui/freeadmin/static/lib/js/freeadmin/form/Cron.js
  gui/storage/models.py
  gui/tasks/models.py
Labels: review

#1619 tkt-40066: Nginx rule fix for plugins
  src/freenas/etc/ix.rc.d/ix-nginx
Labels: review

#1620 Nic choices updated to support vnet
  gui/choices.py
Labels: review

#1622 Organizational Unit field added to Certs
  gui/system/forms.py
  gui/system/migrations/0027_add_organizational_unit.py
  gui/system/models.py
  src/middlewared/middlewared/plugins/crypto.py
Labels: review

#1623 Extent Devices list sorted in Legacy UI
  gui/services/forms.py
Labels: review

#1621 fix(middlewared): rollback VM creation if anything goes wrong
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1649 tkt-38943: Disallowing unwanted version downgrades in legacy
  gui/freeadmin/static/lib/js/freeadmin/Update.js
Labels: review

#1650 tkt-39223: - Update RancherOS to 1.4.
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1652 tkt-33270: Bump freenas-migrate93 repo
  nas_ports/freenas/freenas-migrate93/Makefile
  nas_ports/freenas/freenas-migrate93/distinfo
Labels: review

#1653 tkt-33270: Bump freenas-migrate93 repo
  nas_ports/freenas/freenas-migrate93/Makefile
  nas_ports/freenas/freenas-migrate93/distinfo
Labels: review

#1654 tkt-40788: fix(middlewared/stats): use CallError on rrdtool failure
  src/middlewared/middlewared/plugins/stats.py
Labels: review

#1647 Hide User & Group base fields - They aren't supported right now
  gui/directoryservice/forms.py
Labels: review

#1646 Secret sauce for enabling multi channel in Samba
  src/freenas-sysctl/services.c
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1645 Freenas/11.1 stable ticket 37878
  src/freenas-sysctl/directoryservice.c
  src/freenas-sysctl/middlewared.c
  src/freenas-sysctl/utils.c
Labels: review

#1644 Freenas/11.1 stable ticket 40724
  gui/system/forms.py
  gui/system/migrations/0022_cert_serial.py
  gui/system/models.py
Labels: review

#1641 Freenas/11.1 stable ticket 40708
  gui/directoryservice/forms.py
  gui/directoryservice/migrations/0005_idmap_ad.py
  gui/directoryservice/models.py
  gui/directoryservice/utils.py
  gui/directoryservice/views.py
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1640 do not grant extra privileges to users
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1639 Remove leftover NT4 node
  src/freenas-sysctl/directoryservice.c
Labels: review

#1637 Close out block and PEP8 fixes
  gui/services/models.py
Labels: review

#1635 Freenas/11.1 stable ticket 40680
  gui/common/freenasdc.py
  gui/common/freenasldap.py
  gui/common/system.py
  src/freenas/etc/directoryservice/rc.LDAP
Labels: review

#1630 catia needs to come before zfsacl
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1632 Log netatalk to its own file
  src/freenas/etc/newsyslog.conf
  src/freenas/usr/local/libexec/nas/generate_afpd_conf.py
Labels: review

#1633 Ticket: #36588
  src/freenas/etc/directoryservice/DomainController/ctl
Labels: review

#1627 Allow /etc/find_alias_for_smtplib.sh to be used by sudoers
  src/freenas/usr/local/etc/sudoers
Labels: review

#1626 Allow binding to loopback address
  gui/choices.py
  gui/services/forms.py
  gui/services/views.py
  gui/system/models.py
Labels: review

#1629 Freenas/11.1 stable ticket 40644
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1628 Monitor mdnsd and restart if necessary. Avoid tracebacks.
  src/middlewared/middlewared/plugins/mdns.py
Labels: review

#1642 Freenas/11.1 stable ticket 40716
  gui/services/forms.py
  gui/services/models.py
  gui/services/utils.py
Labels: review

#1624 tkt-33453: tkt#33453 - additional fixes related to AD restarts
  gui/common/freenasldap.py
  src/freenas/etc/directoryservice/ActiveDirectory/ctl
  src/middlewared/middlewared/plugins/service_monitor.py
Labels: review

#1631 Freenas/11.1 stable ticket 34134
  nas_ports/freenas/freenas-files/Makefile
  src/fix_ea/Makefile
  src/fix_ea/fix_ea.c
Labels: review

#1636 Place winbind after nis and ldap in nsswitch.conf
  src/middlewared/middlewared/etc_files/nsswitch.conf
Labels: review

#1638 Freenas/11.1 stable ticket 40692
  src/middlewared/middlewared/plugins/mdns.py
Labels: review

#1655 Fix dependency
  gui/system/migrations/0022_cert_serial.py
Labels: review

#1657 Fix pr 1655 devel
  gui/system/migrations/0022_cert_serial.py
  gui/system/migrations/0027_merge_20180807_0638.py
  gui/system/migrations/0028_merge_20180807_0642.py
Labels: review

#1625 tkt-39762: Bug fix for enhancing cron syntax in legacy UI
  gui/api/resources.py
  gui/common/forms.py
Labels: review

#1658 tkt-36948: feat(plugin/jail): Use callback to return plugin progress
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1656 Fix pr 1655 master
  gui/system/migrations/0022_cert_serial.py
  gui/system/migrations/0027_merge_20180807_0638.py
Labels: review

#1651 tkt-40780: Bug fix for api v1
  gui/account/forms.py
  src/middlewared/middlewared/plugins/account.py
Labels: review

#1660 tkt-41044: Bug fix for serial field in certs for 11.1/U-6
  gui/common/ssl.py
  gui/system/forms.py
Labels: review

#1665 tkt-41104: Bug fix for iscsi targetgroup in api v1
  gui/services/forms.py
Labels: review

#1664 tkt-41052: Bug fix for zvol/dataset creation
  gui/choices.py
Labels: review

#1667 tkt-36473: feat(zsh): improve prompt and add useful bindkeys
  src/freenas/root/.zshrc
Labels: review

#1662 tkt-41068: Fix exception when dismissing alert that has gone away
  src/middlewared/middlewared/plugins/alert.py
Labels: review

#1659 tkt-40500: fix(middlewared/vm): refactor how memory is accounted
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1668 tkt-40768: Revert "fix(snmp/zilstat) dtrace was triggering off zil_lwb_write_sta…
  src/freenas/usr/local/bin/zilstat
Labels: review

#1671 tkt-41064: feat(middlewared/vm): return vm status in vm.query
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1673 tkt-40181: fix(middlewared/vm): do not allow multiple VMs with same name
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1663 tkt-40968: Fix KeyError when creating/updating cloud sync tasks
  src/middlewared/middlewared/plugins/backup.py
Labels: review

#1672 tkt-41172: rm(telemetry): it has not been used for ages
  gui/system/forms.py
  src/freenas/etc/crontab
  src/freenas/usr/local/bin/telemetry-cron.sh
  src/freenas/usr/local/bin/telemetry-gather.py
  src/freenas/usr/local/bin/telemetryuploader
Labels: review

#1675 tkt-41272: fix(dyndns): Properly encode passwords in inadyn config
  src/freenas/etc/ix.rc.d/ix-inadyn
Labels: backport-11.2, review

#1677 tkt-41056: fix(smart): Remove redundant mrsas checks
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
Labels: backport-11.2, review

#1676 tkt-41395: fix(dyndns): Properly encode passwords in inadyn config
  src/freenas/etc/ix.rc.d/ix-inadyn
Labels: review

#1678 tkt-41400: fix(smart): Remove redundant mrsas checks
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
Labels: review

#1679 tkt-41410: fix(middlewared/etc): catch up etc changes brought by John to 11.1 re…
  src/middlewared/middlewared/etc_files/dhclient.conf
  src/middlewared/middlewared/etc_files/local/nss_ldap.conf
  src/middlewared/middlewared/etc_files/local/openldap/ldap.conf
  src/middlewared/middlewared/etc_files/master.passwd
  src/middlewared/middlewared/etc_files/nsswitch.conf
Labels: review

#1669 tkt-40492: feat(plugins): Return a dict with the return value
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1614 tkt#33453 fix AD restart issues
  gui/common/freenasldap.py
  src/freenas/etc/directoryservice/ActiveDirectory/ctl
  src/middlewared/middlewared/plugins/service_monitor.py
Labels: review

#1681 tkt-40864: Do boot-time disk.multipath_sync after ZFS volume imports
  src/freenas/etc/ix.rc.d/ix-syncdisks
  src/freenas/etc/ix.rc.d/ix-syncmultipaths
Labels: review

#1680 tkt-41435: Allow netgroups in NFS share authorized hosts and IP addresses
  src/middlewared/middlewared/plugins/nfs.py
Labels: review

#1683 tkt-41568: Fix 41568
  gui/freeadmin/options.py
  gui/middleware/form.py
  gui/services/views.py
  gui/storage/views.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/service_exception.py
Labels: review

#1682 Updated Charset choices in Middlewared for smb plugin
  gui/choices.py
  gui/services/forms.py
  gui/services/models.py
  src/middlewared/middlewared/plugins/smb.py
Labels: review

#1690 Bug fix
  gui/services/forms.py
Labels: review

#1685 tkt-41580: fix(middlewared/vm): make sure sectorsize is an int
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1686 tkt-41598: fix(middlewared/vm): validate DISK device
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1687 tkt-40976: Ip usage validator added in middlewared
  src/middlewared/middlewared/plugins/jail.py
  src/middlewared/middlewared/validators.py
Labels: review

#1688 tkt-41196: fix(fndebug/jails): Add iocage to this
  src/freenas/usr/local/bin/freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/jails_ng/jails_ng.sh
Labels: review

#1689 tkt-40460: Adjust destination path in mountpoints for jails
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1691 Validation improved for jails fstab
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1696 fix(master) fix misleading verbiage in freenas-debug modules
  src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
  src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh
  src/freenas/usr/local/libexec/freenas-debug/domain_controller/domain_controller.sh
  src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: review

#1605 tkt#39982 -- optimizations for large AD environment
  gui/common/freenasldap.py
Labels: review

#1692 tkt-40548: fix(jails/fstab): Don't allow adding mount to a running jail
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1694 tkt-40344: fix(middlewared): use text/html content type
  src/middlewared/middlewared/webui_auth.py
Labels: review

#1700 tkt-37802: fix(jails/fstab): Make sure we escape spaces how fstab likes
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1699 tkt-39453: feat(plugins/list_local_version): Return an array like remote plugin listing
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1693 tkt-41694: Improve validation for jail creation
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1701 tkt-42006: Update documentation for unlocking volume
  docs/api/resources/storage.rst
Labels: review

#1698 tkt-40512: Put threshold of 8 sequential failures for NTP connection alert.
  src/middlewared/middlewared/alert/source/ntp_status.py
Labels: review

#1702 tkt-42090: Improved arcstat. Added -a option to automatically print all valid st…
  src/freenas/usr/local/bin/arcstat.py
Labels: review

#1705 tkt-42048: Rsync bug fix
  src/middlewared/middlewared/plugins/rsync.py
Labels: review

#1707 tkt-42413: fix(alert): Show node name for TrueNAS alerts
  gui/freeadmin/site.py
  gui/templates/freeadmin/alert_status.html
Labels: review

#1703 tkt-42257 - keep AD in configured state even if service start fails
  src/freenas/etc/directoryservice/ActiveDirectory/ctl
  src/freenas/etc/ix.rc.d/ix-activedirectory
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1708 tkt-42371: fix(middlewared/vm): typo
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1709 tkt-42024: Add support for multiple countries with same key in Middlewared
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1710 tkt-41640: feat(cloud_sync): Google Team Drive support
  src/middlewared/middlewared/rclone/remote/google_drive.py
Labels: review

#1714 tkt-42809: Fix integration tests requests to API v2 being anonymous by default
  tests/functions.py
Labels: redmine, review

#1712 tkt-27525: Cloud Sync Upload/Download speed control
  gui/tasks/admin.py
  gui/tasks/forms.py
  gui/tasks/migrations/0007_auto_20180823_1117.py
  gui/tasks/models.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1713 tkt-42581: Fix for jail ip format during validation
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1717 tkt-42851: Fix SMART debug
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
Labels: backport-11.1, redmine, review

#1716 tkt-42725: fix(collectd): Add LogOnce option for df plugin
  src/freenas/etc/ix.rc.d/ix-collectd
Labels: review

#1721 tkt-41435: fix(nfs): Disable checking hostname existence allowing netgroups to b…
  src/middlewared/middlewared/plugins/nfs.py
Labels: review

#1725 tkt-42761: fix(plugins): Append N/A for version and revision if INDEX doesn't exist
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1723 tkt-41136: Exclude option for cloud sync
  gui/api/utils.py
  gui/freeadmin/models/__init__.py
  gui/freeadmin/models/fields.py
  gui/middleware/form.py
  gui/tasks/admin.py
  gui/tasks/forms.py
  gui/tasks/migrations/0008_auto_20180826_0835.py
  gui/tasks/models.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1726 Fix travis
  gui/freeadmin/models/__init__.py
  gui/tasks/admin.py
Labels: review

#1715 fix(master) read data from file descriptor using OS syscalls
  src/middlewared/middlewared/plugins/unscheduled_reboot_alert.py
Labels: review

#1730 tkt-43415: fix(middlewared): race condition on send_event
  src/middlewared/middlewared/main.py
Labels: review

#1722 tkt-42749: Fix NTP issues
  src/middlewared/middlewared/alert/source/ntp_status.py
Labels: review

#1732 tkt-43580: feat(middlewared): wait longer for middlewared and scream loudly if f…
  nas_ports/freenas/py-middlewared/files/middlewared.in
Labels: review

#1733 tkt-43635: feat(middlewared): add loop debug flag
  src/middlewared/Makefile
  src/middlewared/middlewared/main.py
Labels: redmine, review

#1735 tkt-41060: Bug fix for validation in jail plugin
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1738 tkt-43811: fix(middlewared): deadlock on thread pool
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/pipe.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/config.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/ntp.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/plugins/vcenter.py
  src/middlewared/middlewared/plugins/vm.py
  src/middlewared/middlewared/plugins/vmware.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/rclone/remote/s3.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/utils/__init__.py
Labels: review
