Repository truenas/middleware, pull requests merged in 2018-07, with the labels that each got.

#1468 Add ability to write out null byte at end of EA's
  nas_ports/freenas/freenas-files/Makefile
  src/fix_afp_ea/fix_afp_ea.c
  src/fix_ea/Makefile
  src/fix_ea/fix_ea.c
Labels: review

#1459 feat(plugin/vm): Add selectable time to VM creation
  gui/choices.py
  gui/vm/migrations/0007_vm_time.py
  gui/vm/models.py
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1464 Fix update methods that update fields omitted in request to default v…
  src/middlewared/middlewared/plugins/afp.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/domain_controller.py
  src/middlewared/middlewared/plugins/dyndns.py
  src/middlewared/middlewared/plugins/ftp.py
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/lldp.py
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/plugins/snmp.py
  src/middlewared/middlewared/plugins/ssh.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/plugins/tftp.py
  src/middlewared/middlewared/plugins/ups.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: review

#1472 Storage:Volumes:Change Permission to Middlewared
  gui/api/resources.py
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/storage/forms.py
  gui/storage/views.py
Labels: review

#1473 fix(oldgui): Hide Auxiliary Arguments from Cloud Sync task
  gui/tasks/admin.py
  gui/tasks/forms.py
Labels: review

#1480 Standalone tool to fix AFP files with EA corruption
  src/fix_ea/fix_ea.c
Labels: review

#1478 tkt-36118: fix(migration): skip migration on fresh install
  gui/system/migrations/0024_rename_bes.py
Labels: review

#1481 Remove stuff added by merge conflicts from webui
  src/fix_ea/fix_ea.c
Labels: review

#1479 tkt-35998: fix(smart): Support mrsas passed-through disks on CAM bus 0
  src/middlewared/middlewared/common/camcontrol/__init__.py
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/pytest/unit/common/camcontrol/test.py
  src/middlewared/middlewared/pytest/unit/common/camcontrol/test_camcontrol.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Labels: backport-11.2, review

#1484 tkt-35998: fix(smart): No need to check for /dev/ses, it won't appear there
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Labels: review

#1486 tkt-29825: fix(oldgui): Allow saving cloud sync even if bucket listing failed
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
  gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
Labels: backport-11.2, review

#1488 fix(oldgui): Hide Auxiliary Arguments from Cloud Sync task
  gui/tasks/admin.py
  gui/tasks/forms.py
Labels: review

#1491 Don't give `set +e` chance to fire without real reason.
  src/freenas-installer/etc/install.sh
Labels: review

#1415 feat(middlewared/system): add system.health event source
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1470 fix(smart): Fix smartd.conf being empty on first boot due to race condition
  src/freenas/etc/ix.rc.d/ix-etc
Labels: review

#1436 pool.scrub tests
  tests/api2/pool_scrub.py
Labels: review

#1427 Display paused scrub state as Paused
  gui/middleware/notifier.py
  gui/middleware/zfs.py
  gui/storage/views.py
  gui/templates/storage/scrub_confirm.html
  gui/templates/storage/volumestatus_datagrid.html
  gui/templates/system/alertservice_edit.html
  gui/templates/system/bootenv_datagrid.html
Labels: review

#1498 fix(api): avoid traceback if disk in iscsi extent does not exist
  gui/api/resources.py
Labels: review

#1426 Join latest job to cloud sync tasks
  gui/api/resources.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1496 Fix typo in install_loader
  src/freenas-installer/etc/install.sh
Labels: review

#1466 Downloading config bug fix
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/templates/system/manualupdate_wizard_0.html
  gui/templates/system/manualupdate_wizard_1.html
Labels: review

#1465 Vmware sync support added for snapshots in API v1
  docs/api/resources/storage.rst
  gui/api/resources.py
  gui/storage/forms.py
Labels: review

#1460 URL changed for FreeNAS logo in legacy UI
  gui/templates/base.html
Labels: review

#1454 WebDAV shares namespace change
  gui/sharing/forms.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: review

#1453 Unlock volume with Recovery key in API v1
  docs/api/resources/storage.rst
  gui/storage/forms.py
Labels: review

#1440 Bug fix when updating VMWare
  src/middlewared/middlewared/plugins/vmware.py
Labels: review

#1437 iSCSI Portal IP bug fix
  gui/services/forms.py
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/network.py
Labels: review

#1411 Traceback fixed for validation errors in S3
  gui/services/views.py
Labels: review

#1407 Unique constraint failed for volume scrubs, this commit fixes that
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1420 Remove warning that vfs_full_audit may cause transfer problems with the
  gui/sharing/admin.py
Labels: review

#1501 adding env to falling test in cloud sync
  tests/api2/cloud_sync.py
  tests/api2/pool_import_disk.py
Labels: review

#1497 Ticket #28063 Write local SID to correct DB file
  src/freenas/etc/ix.rc.d/ix-post-samba
  src/freenas/etc/ix.rc.d/ix-pre-samba
Labels: review

#1369 Turn off SMB1
  gui/services/forms.py
  src/freenas-sysctl/services.c
Labels: review

#1371 Log netatalk to its own file
  src/freenas/etc/newsyslog.conf
  src/freenas/usr/local/libexec/nas/generate_afpd_conf.py
Labels: review

#1370 Add unix_primary_group and unix_nss_info to idmap_ad configuration
  gui/directoryservice/forms.py
  gui/directoryservice/migrations/0005_idmap_ad.py
  gui/directoryservice/models.py
  gui/directoryservice/utils.py
  gui/directoryservice/views.py
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1502 --fast list option for cloud sync
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
  gui/tasks/widgets.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/rclone/base.py
  src/middlewared/middlewared/rclone/remote/amazon_cloud_drive.py
  src/middlewared/middlewared/rclone/remote/azureblob.py
  src/middlewared/middlewared/rclone/remote/b2.py
  src/middlewared/middlewared/rclone/remote/box.py
  src/middlewared/middlewared/rclone/remote/dropbox.py
  src/middlewared/middlewared/rclone/remote/ftp.py
  src/middlewared/middlewared/rclone/remote/google_cloud_storage.py
  src/middlewared/middlewared/rclone/remote/google_drive.py
  src/middlewared/middlewared/rclone/remote/http.py
  src/middlewared/middlewared/rclone/remote/hubic.py
  src/middlewared/middlewared/rclone/remote/mega.py
  src/middlewared/middlewared/rclone/remote/onedrive.py
  src/middlewared/middlewared/rclone/remote/pcloud.py
  src/middlewared/middlewared/rclone/remote/s3.py
  src/middlewared/middlewared/rclone/remote/sftp.py
  src/middlewared/middlewared/rclone/remote/webdav.py
  src/middlewared/middlewared/rclone/remote/yandex.py
  src/middlewared/middlewared/schema.py
Labels: review

#1395 fix(storage/locking_volumes): Stop iocage jails before doing so
  gui/storage/views.py
Labels: review

#1409 feat(plugin/jail): Rewrite jail.plugin_get_versions
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1418 fix(advanced/consolemsg): Show consolemsg correctly on update and load
  gui/freeadmin/static/lib/js/msg.js
  gui/system/forms.py
  gui/templates/freeadmin/index.html
Labels: review

#1451 feat(vm/create): Create zvol's instead of the UI
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1456 fix(sharing/iscsi): Don't check peer_secret if peer_user isn't supplied
  src/middlewared/middlewared/plugins/iscsi.py
Labels: review

#1490 tkt-36808: fix(vm/vnc): Fix VNC for touch events and mobile
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1506 regenerate /etc/resolv.conf when disabling DC
  src/freenas/etc/directoryservice/DomainController/ctl
Labels: review

#1503 feat(middlewared/network): implement interfaces.websocket_interface
  src/middlewared/middlewared/plugins/network.py
Labels: review

#1507 Write out files if they don't exist
  src/middlewared/middlewared/plugins/etc.py
Labels: review

#1509 Skipping test until it is fix.
  tests/api2/pool_import_disk.py
  tests/api2/pool_scrub.py
  tests/runtest.py
Labels: review

#1511 replace .skip by .mark.skip
  tests/api2/pool_scrub.py
Labels: review

#1500 fix(stable) remove enabled/disabled logic in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/afp/afp.sh
  src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
  src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: review

#1514 fix(stable) remote syslog for truenas HA
  src/freenas/etc/ix.rc.d/ix-syslogd
Labels: review

#1513 fix(master) remote syslog for truenas HA
  src/freenas/etc/ix.rc.d/ix-syslogd
Labels: review

#1515 add delete cifs sharing in all api v1 test that use cifs
  tests/api1/ad_bsd.py
  tests/api1/ad_osx.py
  tests/api1/ldap_bsd.py
  tests/api1/ldap_osx.py
  tests/api1/smb_bsd.py
  tests/api1/smb_osx.py
Labels: review

#1517 fix(stable) add M series hardware to doms.sh
  src/freenas/usr/local/libexec/freenas-debug/doms/doms.sh
Labels: review

#1520 Master kerberos auth
  gui/common/freenasdc.py
  gui/common/freenasldap.py
  gui/common/system.py
  src/freenas/etc/directoryservice/rc.LDAP
Labels: review

#1262 do not grant extra privileges to users
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1495 Place winbind after nis and ldap in nsswitch.conf
  src/middlewared/middlewared/etc_files/nsswitch.conf
Labels: review

#1340 Fix unneeded stops and restarts in AD monitoring
  gui/common/freenasldap.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_monitor.py
Labels: review

#1521 Fix traceback in Volume Status
  gui/templates/storage/volumestatus_datagrid.html
Labels: review

#1518 fix(master) add sas3flash -listall for M series
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
Labels: review

#1519 fix(stable) add sas3flash -listall for M series
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
Labels: review

#1523 Secret sauce for enabling multi channel in Samba
  src/freenas-sysctl/services.c
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1525 Hide User & Group base fields - They aren't supported right now
  gui/directoryservice/forms.py
Labels: review

#1526 Fix broken LDAP Kerberos
  src/freenas/etc/directoryservice/LDAP/ctl
  src/freenas/etc/directoryservice/rc.LDAP
Labels: review

#1522 fix(alert): Allow lists as alert arguments
  src/middlewared/middlewared/alert/base.py
Labels: review

#1512 feat(alert): Emit alerts from IPMI System Event Log
  gui/system/migrations/0025_keyvalue.py
  gui/system/models.py
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/ipmi_sel.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/keyvalue.py
  src/middlewared/middlewared/pytest/unit/alert/source/test_ipmi_sel.py
Labels: review

#1528 datastore.dump_json
  src/middlewared/middlewared/plugins/datastore.py
Labels: review

#1529 add webdav sharing url change
  tests/api2/webdav_bsd.py
  tests/api2/webdav_osx.py
Labels: review

#1532 Remove leftover NT4 node
  src/freenas-sysctl/directoryservice.c
Labels: review

#1533 sysctl configuration for cache & enum (off by default & hidden)
  src/freenas-sysctl/directoryservice.c
  src/freenas-sysctl/middlewared.c
  src/freenas-sysctl/utils.c
Labels: review

#1536 add missig import PUT in network.py
  tests/api2/network.py
Labels: review

#1537 Use proper sysctl trees
  src/freenas-sysctl/directoryservice.c
Labels: review

#1534 fix(master) remove 'net usersidlist' from freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: review

#1538 Make sure that `netbiosname_b` is mandatory field as well.
  gui/directoryservice/forms.py
Labels: review

#1531 fix(middlewared/rsync): adding rsync task with validate_rpath as false
  src/middlewared/middlewared/plugins/rsync.py
Labels: review

#1539 fix(stable) remove 'net usersidlist' from freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: review

#1542 Fix IPMI SEL alerts
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: review

#1543 Allow users to complete CSR
  gui/system/forms.py
  src/middlewared/middlewared/plugins/crypto.py
Labels: review

#1544 Wildcard IP's allowed for Portal creation
  src/middlewared/middlewared/plugins/iscsi.py
Labels: review

#1535 fix(plugins/jail): Bad caching on list_resource
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1540 Add NTP alert, in case peer is not reachable
  src/middlewared/middlewared/alert/source/ntp_status.py
Labels: review

#1546 Fix cloud sync defaults (follow-up to 36003)
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1549 fix(alert): Add UnavailableException to NTPStatusAlertSource
  src/middlewared/middlewared/alert/source/ntp_status.py
Labels: review

#1551 Use existing mechansisms for loader logo and brand
  src/freenas/boot/brand-FreeNAS.4th
  src/freenas/boot/loader.conf
  src/freenas/boot/loader.rc.local
  src/freenas/boot/logo-FreeNAS.4th
Labels: review

#1548 Bug fix for vCenter
  gui/vcp/forms.py
  src/middlewared/middlewared/plugins/vcenter.py
Labels: review

#1554 Legacy shell values updated
  gui/account/migrations/0008_migrate_legacy_values.py
Labels: review

#1556 Fix INFO alerts being shown as CRITICAL
  gui/templates/freeadmin/alert_status.html
Labels: review

#1555 Forbid duplicate e-mail addresses in SMART configuration
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/validators.py
Labels: review

#1550 Commas are not valid in an E-Mail address. Separate multiple E-Mail a…
  gui/services/forms.py
Labels: review

#1557 tkt-38595: Delete mp_get_permission, it is not used anywhere
  gui/middleware/notifier.py
Labels: backport-11.2, redmine, review

#1452 Rework the text suggested in PR 1343
  gui/services/migrations/0003_add_ntlmv1_auth.py
Labels: review

#1552 Make sure that `netbiosname_b` is mandatory field as well. As it got
  gui/directoryservice/forms.py
Labels: review

#1558 tkt-38699: Replace text logo with ascii art
  src/freenas/boot/brand-FreeNAS.4th
  src/freenas/boot/logo-FreeNAS.4th
Labels: review

#1560 Failing validation for rsync fix
  src/middlewared/middlewared/plugins/rsync.py
Labels: review

#1564 Ticket #33453 fix unnecessary AD restarts caused by service monitor
  gui/common/freenasldap.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_monitor.py
Labels: review

#1553 Remove Screen Saver Option
  docs/api/resources/system.rst
  gui/api/test_system.py
  gui/system/migrations/0025_remove_screensaver.py
  gui/system/models.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1559 tkt-38711: Do boot-time disk.multipath_sync after ZFS volume imports
  src/freenas/etc/ix.rc.d/ix-syncdisks
  src/freenas/etc/ix.rc.d/ix-syncmultipaths
Labels: backport-11.2, redmine, review

#1563 tkt-36293: fix(middlewared/vm): get ip from websocket or use provided host for vnc
  gui/vm/views.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1566 tkt-26434: fix(middlewared/vm): raise errors when VM fails to start
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1567 Fix a typo and casting issue
  src/middlewared/middlewared/alert/source/ntp_status.py
Labels: review

#1570 Remove warning that vfs_full_audit may cause transfer problems with the
  gui/sharing/admin.py
Labels: review

#1571 tkt-37590: fix(gui): typo
  gui/api/resources.py
Labels: review

#1573 Add supports for api v1 test on real hardware, VMware, and VirtualBox disk
  tests/runtest.py
Labels: review

#1574 tkt-37263: Don't propose installing to the installer disk
  src/freenas-installer/etc/install.sh
Labels: review

#1569 fix(master) fix verbiage for unauthorized email alerts
  src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
Labels: review

#1581 Wait for /etc/resolv.conf to be available and valid
  src/middlewared/middlewared/plugins/mdns.py
Labels: review

#1584 tkt-38898 (stable) fix verbiage for unauthorized email alerts
  src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
Labels: review

#1577 tkt-26361: Implement high-level function for sending e-mail
  gui/system/views.py
  nas_ports/freenas/py-middlewared/Makefile
  src/middlewared/middlewared/assets/templates/mail.html
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/unauthorized_reboot_alert.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/utils/__init__.py
Labels: review

#1579 tkt-29908: Cloud sync task hook
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/tasks/forms.py
  gui/tasks/migrations/0006_auto_20180719_1714.py
  gui/tasks/models.py
  gui/templates/tasks/cloudsync_add.html
  gui/templates/tasks/cloudsync_edit.html
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/pytest/unit/plugins/test_cloud_sync.py
Labels: review

#1585 tkt-38355: License acceptance for plugins fix
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1587 tkt-38155: fix(middlewared/jail): add default gateway interface to vnet jail bridge
  src/freenas/etc/rc.conf
  src/middlewared/middlewared/plugins/jail.py
  src/middlewared/middlewared/plugins/network.py
Labels: review

#1589 tkt-38575: Null values fix in NFS plugin
  src/middlewared/middlewared/plugins/nfs.py
Labels: review

#1590 tkt-36698: Null values fix for iSCSI plugin
  gui/services/forms.py
  src/middlewared/middlewared/plugins/iscsi.py
Labels: review

#1568 tkt-38893: Enable /var/log/console.log for easier tracking and debugging of cons…
  src/freenas/usr/local/etc/syslog-ng.conf.freenas
Labels: backport-11.2, redmine, review

#1594 tkt-39418: null=True should not imply default=None
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/service.py
Labels: review

#1588 tkt-37594: Volume upgrade moved to Middelwared
  gui/api/resources.py
  gui/middleware/notifier.py
  gui/storage/models.py
  gui/storage/views.py
  src/middlewared/middlewared/alert/source/volume_version.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1592 Update ZFS Upgrade Pool message to better point to the relevant docs
  src/middlewared/middlewared/alert/source/volume_version.py
Labels: review

#1487 tkt-36778: fix(oldgui): Allow saving cloud sync even if bucket listing failed
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
  gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
Labels: review

#1596 tkt-39598: fix(vm): make sure to UP bridge if it already exists
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1597 tkt#29628 fix function to store SID in DB
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: review

#1595 tkt-37598: Volume: Scrub moved to Middlewared
  gui/api/resources.py
  gui/middleware/notifier.py
  gui/storage/views.py
  gui/system/views.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1606 tkt-35062: fix(notifier/volume_detach): Stop jails related to the volume
  gui/middleware/notifier.py
  gui/storage/views.py
Labels: review

#1602 tkt-39967: Disallow empty cloud sync bucket
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
Labels: backport-11.2, redmine, review

#1611 tkt-39373: move save/delete logic from django models to middleware
  gui/account/models.py
  gui/middleware/form.py
  gui/services/models.py
  gui/sharing/models.py
  gui/storage/models.py
  gui/system/models.py
  gui/tasks/models.py
  src/middlewared/middlewared/plugins/afp.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/ntp.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/snapshot.py
  src/middlewared/middlewared/plugins/tunables.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: review
