Repository truenas/middleware, pull requests merged in 2018-06, with the labels that each got.

#1323 Write API functional tests for webdav_osx
  tests/api2/webdav_osx.py
Labels: review

#1321 Write API functional tests for webdav_bsd
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/webdav.py
  tests/api2/webdav_bsd.py
Labels: review

#1327 fix(afp): Path key may not exist
  src/middlewared/middlewared/plugins/afp.py
Labels: review

#1326 Minor fixes for iSCSI plugin
  src/middlewared/middlewared/plugins/iscsi.py
Labels: review

#1325 API v2 Tests for iSCSI
  tests/api2/iscsi.py
Labels: review

#1328 Minor changes for TFTP plugin
  src/middlewared/middlewared/plugins/tftp.py
  src/middlewared/middlewared/validators.py
Labels: review

#1332 fix(update): Provide progress report for update.download job
  src/middlewared/middlewared/plugins/update.py
Labels: review

#1333 fix(update): Human-friendly sizes in update download progress
  src/middlewared/middlewared/plugins/update.py
Labels: review

#1334 Transient jobs are ones that use job infrastructure (locking, pipes)
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/service.py
Labels: review

#1329 TFTP tests API v2
  tests/api2/tftp.py
Labels: review

#1201 Support all cloud sync services that rclone supports
  gui/api/resources.py
  gui/choices.py
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
  gui/freeadmin/static/lib/js/freeadmin/templates/cloudsync.html
  gui/system/forms.py
  gui/system/migrations/0022_cloud_sync.py
  gui/system/models.py
  gui/tasks/forms.py
  gui/tasks/models.py
  gui/tasks/widgets.py
  nas_ports/freenas/py-middlewared/Makefile
  src/freenas/etc/ix.rc.d/ix-crontab
  src/middlewared/middlewared/plugins/backup.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/rclone/__init__.py
  src/middlewared/middlewared/rclone/base.py
  src/middlewared/middlewared/rclone/remote/__init__.py
  src/middlewared/middlewared/rclone/remote/amazon_cloud_drive.py
  src/middlewared/middlewared/rclone/remote/azureblob.py
  src/middlewared/middlewared/rclone/remote/b2.py
  src/middlewared/middlewared/rclone/remote/box.py
  src/middlewared/middlewared/rclone/remote/dropbox.py
  src/middlewared/middlewared/rclone/remote/ftp.py
  src/middlewared/middlewared/rclone/remote/google_cloud_storage.py
  src/middlewared/middlewared/rclone/remote/google_drive.py
  src/middlewared/middlewared/rclone/remote/http.py
  src/middlewared/middlewared/rclone/remote/hubic.py
  src/middlewared/middlewared/rclone/remote/mega.py
  src/middlewared/middlewared/rclone/remote/onedrive.py
  src/middlewared/middlewared/rclone/remote/pcloud.py
  src/middlewared/middlewared/rclone/remote/s3.py
  src/middlewared/middlewared/rclone/remote/sftp.py
  src/middlewared/middlewared/rclone/remote/webdav.py
  src/middlewared/middlewared/rclone/remote/yandex.py
Labels: review

#1335 Ticket: #34477
  src/middlewared/middlewared/plugins/crypto.py
Labels: review

#1339 Bug fix
  src/middlewared/middlewared/plugins/crypto.py
Labels: review

#1348 fix(nfs): Support IPv6 networks for NFS shares
  src/middlewared/middlewared/plugins/nfs.py
Labels: review

#1350 fix(ipmi): setting VLAN
  src/middlewared/middlewared/plugins/ipmi.py
Labels: review

#1351 [stable] fix(ipmi): setting VLAN
  src/middlewared/middlewared/plugins/ipmi.py
Labels: review

#1345 fix(plugins/jail): Catch any exceptions during updating a property
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1349 Root email field populated in Wizard form
  gui/system/forms.py
Labels: review

#1346 Minor edits in IPMI plugin
  src/middlewared/middlewared/plugins/ipmi.py
Labels: review

#1347 Api v2 tests for IPMI plugin
  tests/api2/ipmi.py
Labels: review

#1331 Fix zfs after reinstall
  jenkins/Jenkinsfile-PR
Labels: review

#1342 Bug Fix
  gui/storage/views.py
Labels: review

#1341 Functionality to reset SED password in GUI added
  gui/storage/forms.py
  gui/system/forms.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1353 fix(middlewared): `ui_protocol` should be uppercase
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1352 fix(rc): fstab is required even if empty
  src/freenas/etc/fstab
Labels: review

#1355 feat(middlewared): rename pool.snapshot to pool.snapshottask
  gui/storage/forms.py
  src/middlewared/middlewared/plugins/snapshot.py
Labels: review

#1315 feat(backup): Allow specifying custom S3 endpoint
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/system/forms.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/backup.py
Labels: review

#1318 fix(smart): Temporarily enable monitoring for all NVMe devices if at …
  src/freenas/etc/ix.rc.d/ix-smartd
Labels: review

#1357 fix(oldguit): Show smart_email as space-separated instead of comma-se…
  gui/services/forms.py
Labels: review

#1359 fix(service): Fix "Set of coroutines/Futures is empty" when querying …
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1358 Fix 34684
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1361 fix(plugin/smb): Path key may not exist
  src/middlewared/middlewared/plugins/smb.py
Labels: review

#1360 fix(plugins/jail): Fix default jail filtering
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1337 Fix 17923 stable
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1356 Minor changes in Jail plugin
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1324 get samba_server status when checking if AD started
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_monitor.py
Labels: review

#1363 Encrypt cloud credentials
  gui/freeadmin/models/__init__.py
  gui/freeadmin/models/fields.py
  gui/system/forms.py
  gui/system/migrations/0016_encrypt_cloud_credentials.py
  gui/system/migrations/0021_merge_20180612_2332.py
  gui/system/models.py
Labels: review

#1362 Merge migrations after merging cloud credentials to stable
  gui/system/migrations/0016_encrypt_cloud_credentials.py
  gui/system/migrations/0021_merge_20180612_2332.py
  gui/system/migrations/0021_merge_20180612_2359.py
  gui/system/migrations/0022_cert_serial.py
Labels: review

#1366 Fix PEP8
  gui/freeadmin/models/__init__.py
  gui/freeadmin/models/fields.py
Labels: review

#1364 fix(cloudsync): Make encryption_salt non-required field
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1367 fix(middlewared): deadlock when using call_sync
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/worker.py
Labels: review

#1368 fix(middlewared): handle interface attach in middlewared
  src/freenas/etc/devd/ifnet_attach.conf
  src/middlewared/middlewared/plugins/network.py
Labels: review

#1198 Ticket: #32685
  src/freenas/etc/find_alias_for_smtplib.py
  src/freenas/etc/ix.rc.d/ix-aliases
Labels: review

#1365 SSH not reloading when start on boot is disabled for SSH
  src/middlewared/middlewared/service.py
Labels: review

#1153 WebAuthn support
  gui/account/models.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/auth.py
Labels: WIP, review

#1372 Revert "WebAuthn support"
  gui/account/models.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/auth.py
Labels: review

#1376 fix(smb): renaming and tests
  gui/sharing/forms.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/smb_and_cifs.py
Labels: review

#1375 move clean up to the correct node
  jenkins/Jenkinsfile-PR
Labels: review

#1374 feat(middlewared/restful): do not allow extra attributes
  src/middlewared/middlewared/restful.py
Labels: review

#1380 Fix migrations bug introduced in aa87d9e89a51414ef43b37cac593edb02294a0b8
  gui/system/migrations/0022_cert_serial.py
  gui/system/migrations/0023_merge_20180612_2359.py
Labels: review

#1379 Improve validation for serial ports
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1383 fix(oldgui): Fix url field being missing if provider is WebDAV
  gui/freeadmin/static/lib/js/freeadmin.js
Labels: review

#1384 feat(cloud_sync): Allow passing auxiliary arguments to rclone
  gui/tasks/migrations/0004_cloudsync_args.py
  gui/tasks/models.py
  src/middlewared/middlewared/plugins/backup.py
Labels: review

#1381 fix(api): secret confirmation not required
  gui/services/forms.py
Labels: review

#1378 feat(mw/smb): document args and simplify sharing.smb.get_storage_tasks
  gui/sharing/forms.py
  src/middlewared/middlewared/plugins/smb.py
Labels: review

#1388 fix(cloud_sync): Properly report invalid credentials
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1389 feat(api): register URLs with and without slash, avoiding a redirect
  src/middlewared/middlewared/restful.py
Labels: review

#1390 fix(nfs): add -sec=sys if we have kerberos keytabs
  src/middlewared/middlewared/etc_files/nfsd.py
Labels: review

#1391 feat(mw|gui): reload iscsi when zvol size changes
  gui/storage/forms.py
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1393 fix(jail/exec): Attribute name changed upstream, additional improvements
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1394 fix(apidocs): show lists in swagger ui (openapi)
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/schema.py
Labels: review

#1401 fix(gui): catch up sharing.cifs -> sharing.smb renaming
  gui/choices.py
Labels: review

#1400 fix(stable) echo the device so smart.nawk finds da#
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
Labels: review

#1392 fix(master) echo the device so smart.nawk finds da#
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
Labels: review

#1398 fix(nfs): Fix invalid syntax for multiple networks
  src/middlewared/middlewared/etc_files/nfsd.py
Labels: review

#1399 fix(backup): fix deleting cloud credentials through compability layer
  src/middlewared/middlewared/plugins/backup.py
Labels: review

#1397 Documentation for smarttest api1.0 updated
  docs/api/resources/tasks.rst
Labels: review

#1396 Force size option added for zvol creation in Middlewared
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1354 Remove vaaiserver from FreeNAS repo as well for 11.2:
  src/freenas/etc/rc.conf.local
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1344 feat(plugins/jail, plugins/cache): Return plugin versions, cache timeout
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/jail.py
Labels: review

#1402 Rsync bug fixed
  gui/tasks/forms.py
Labels: review

#1405 Snapshot extend method bug fix
  src/middlewared/middlewared/plugins/snapshot.py
Labels: review

#1387 feat(alert): Configurable per-dataset quota alerts using alert plugin
  gui/storage/forms.py
  gui/storage/migrations/0010_auto_20180618_0340.py
  gui/storage/models.py
  src/middlewared/middlewared/alert/source/quota.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/schema.py
Labels: 0 - Backlog, review

#1406 Fix coroutines using libzfs
  src/middlewared/middlewared/plugins/zfs.py
Labels: review

#1404 fix(middlewared): watch parent process on workers
  src/middlewared/middlewared/worker.py
Labels: review

#1410 API v2 tests for S3
  tests/api2/s3.py
Labels: review

#1413 Explicitly check for None values in IPMI plugin when DHCP is off
  src/middlewared/middlewared/plugins/ipmi.py
Labels: review

#1416 Bug fix for traceback when updating zvol size
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1386 Jails API v2 tests
  tests/api2/jails.py
Labels: review

#1422 pool.snapshot usages renamed to pool.snapshottask
  src/middlewared/middlewared/plugins/replication.py
Labels: review

#1382 fix(oldgui): Display paused scrub state as Paused
  gui/middleware/notifier.py
  gui/middleware/zfs.py
  gui/storage/views.py
  gui/templates/storage/scrub_confirm.html
  gui/templates/storage/volumestatus_datagrid.html
  gui/templates/system/alertservice_edit.html
  gui/templates/system/bootenv_datagrid.html
Labels: review

#1423 fix(service): Fix race condition where StartNotify(verb="restart") re…
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1421 pool.import_disk tests
  tests/api2/fixtures/msdosfs-nonascii.gz
  tests/api2/fixtures/msdosfs.gz
  tests/api2/fixtures/ntfs.gz
  tests/api2/pool_import_disk.py
Labels: review

#1419 Fix 28156
  src/freenas/etc/rc.conf.local
  src/middlewared/middlewared/plugins/s3.py
Labels: review

#1424 Revert "Join latest job to cloud sync tasks"
  gui/api/resources.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1425 Revert "fix(oldgui): Display paused scrub state as Paused"
  gui/middleware/notifier.py
  gui/middleware/zfs.py
  gui/storage/views.py
  gui/templates/storage/scrub_confirm.html
  gui/templates/storage/volumestatus_datagrid.html
  gui/templates/system/alertservice_edit.html
  gui/templates/system/bootenv_datagrid.html
Labels: review

#1428 fix(service): Fix race condition where StartNotify(verb="restart") re…
  src/middlewared/middlewared/plugins/service.py
Labels: review

#1431 Functionality to reset SED Password added
  gui/storage/forms.py
  gui/system/forms.py
Labels: review

#1435 Fix tests failing due to wrong dataset name
  tests/api2/cloud_sync.py
  tests/api2/pool_import_disk.py
Labels: review

#1438 Pool name changed for Jails Tests
  tests/api2/jails.py
Labels: review

#1403 - If we can't reserve memory from ZFS ARC for a guest VM,
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1444 Revert "- If we can't reserve memory from ZFS ARC for a guest VM,"
  src/middlewared/middlewared/plugins/vm.py
Labels: review

#1414 Explicitly make serial console preferred when it is enabled.
  src/freenas/etc/ix.rc.d/ix-loader
Labels: review

#1430 Check GRUB presence via kenv instead of fstab.
  src/freenas/etc/ix.rc.d/ix-bsdloader
Labels: review

#1442 fix(cloud_sync): Default value for args
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1439 Storage:Volumes:Zvol to Middlewared
  gui/freeadmin/forms.py
  gui/storage/forms.py
  gui/storage/views.py
  src/middlewared/middlewared/plugins/pool.py
Labels: review

#1443 Fix updating cloud credentials in new UI
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: review

#1446 fix(s3): Restrict characters that can be used as access_key or secret…
  src/middlewared/middlewared/plugins/s3.py
Labels: review

#1447 fix(middleware): Be more strict with CRUDPlugin query filters
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/utils/__init__.py
Labels: review

#1450 Resolve hostname validator fix
  src/middlewared/middlewared/async_validators.py
Labels: review

#1433 Import CSR's and Certs for existing CSR's
  docs/api/resources/system.rst
  gui/api/resources.py
  gui/system/forms.py
  gui/system/urls.py
  gui/system/views.py
  gui/templates/system/certificate/CSR_import.html
  gui/templates/system/certificate_datagrid.html
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/system.py
Labels: review

#1434 CSR identifier made editable in GUI
  gui/system/forms.py
Labels: review

#1457 fix(installer): Allow upgrades on system where grub is the only /etc/…
  src/freenas-installer/etc/install.sh
Labels: review

#1463 Accept ECC keys for Nginx
  src/freenas/etc/ix.rc.d/ix-nginx
Labels: review

#1455 Standalone tool to fix AFP files with EA corruption
  nas_ports/freenas/freenas-files/Makefile
  src/fix_afp_ea/Makefile
  src/fix_afp_ea/fix_afp_ea.c
Labels: review

#1461 Volumes: Dataset to Middlewared
  gui/choices.py
  gui/freeadmin/forms.py
  gui/storage/forms.py
  gui/storage/views.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/validators.py
Labels: review
