Repository truenas/middleware, pull requests merged in 2018-11, with the labels that each got.

#2010 tkt-54315: Remove the -J flag from freenas-debug, and merge it's functionality
  src/freenas/usr/local/bin/freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/jails/jails.sh
  src/freenas/usr/local/libexec/freenas-debug/jails_ng/jails_ng.sh
Labels: backport-11.2

#2009 tkt-54738: feat(middlewared/auth): document auth.generate_token params
  src/middlewared/middlewared/plugins/auth.py
Labels: redmine

#2013 tkt-54789: fix(middlewared): run on_close even on exceptions
  src/middlewared/middlewared/main.py
Labels: backport-11.2, redmine

#2018 QA-Test tkt-55674 Adding a test to verify boot/scrub job
  tests/api2/boot.py
Labels: api tests, review

#1477 ACME native integration in FreeNAS
  docs/api/resources/system.rst
  gui/api/resources.py
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/middleware/form.py
  gui/middleware/util.py
  gui/system/admin.py
  gui/system/forms.py
  gui/system/hook.py
  gui/system/migrations/0033_acme_models.py
  gui/system/models.py
  gui/system/nav.py
  gui/system/urls.py
  gui/system/utils.py
  gui/system/views.py
  gui/templates/system/acmednsauthenticator_add.html
  gui/templates/system/acmednsauthenticator_edit.html
  gui/templates/system/certificate/certificate_create_ACME.html
  gui/templates/system/certificate/certificate_progress.html
  gui/templates/system/cloudcredentials_add.html
  gui/templates/system/cloudcredentials_edit.html
  src/middlewared/middlewared/alert/source/certificates.py
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/validators.py
Labels: review

#2035 tkt-55899: Ensure that cloud sync is ran against dataset
  src/middlewared/middlewared/plugins/backup.py
Labels: backport-11.2, backport-11.3

#2036 tkt-56079: Ensure that cloud sync is ran against dataset (by themylogin)
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-11.2

#2055 tkt-54924: feat(gui): documentation is now online
  gui/documentation/__init__.py
  gui/documentation/urls.py
  gui/documentation/views.py
  gui/freeadmin/navtree.py
  gui/freeadmin/site.py
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/Menu.js
  gui/templates/documentation/index.html
  gui/templates/freeadmin/index.html
  gui/templates/menubar.html
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
Labels: backport-11.2

#2057 tkt-56508: Update trueview_stats.sh
  src/freenas/usr/local/bin/trueview_stats.sh
Labels: backport-11.2, redmine

#2060 QA-Test tkt-56544 Change s3 API v2 test to create and use is own dataset
  tests/api2/s3.py
Labels: api tests, review

#2062 tkt-56589: Fix cronjobs not being reflected in crontab
  src/freenas/etc/ix.rc.d/ix-crontab
Labels: backport-11.1, backport-11.2

#2072 tkt-56628: fix(vlan): make sure we have a parent interface with `up`
  gui/network/forms.py
  src/freenas/etc/netcli
Labels: backport-11.1, backport-11.2

#2054 tkt-56466: Netcli runs on virtual terminal 0 only
  src/freenas/etc/ix.rc.d/ix-ttys
Labels: 3 - Review

#2084 tkt-15451: Generate Apache config files with etc plugin
  src/freenas/usr/local/libexec/nas/generate_webdav_conf.py
  src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf
  src/middlewared/middlewared/etc_files/local/apache24/httpd.conf
  src/middlewared/middlewared/etc_files/local/apache24/webdav_config.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: 3 - Review

#2088 Bug fix for cloned zvols
  docs/api/resources/storage.rst
  gui/api/resources.py
Labels: 3 - Review, backport-11.2, backport-11.3

#2087 tkt-56781: fix(jail/do_update): Throw validation error if plugin and rename are set
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2090 tkt-57528: Bug fix for cloned zvols
  docs/api/resources/storage.rst
  gui/api/resources.py
Labels: 3 - Review

#2093 tkt-57699: Downloading config bug fix
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/templates/system/manualupdate_wizard_0.html
  gui/templates/system/manualupdate_wizard_1.html
Labels: 3 - Review

#2051 tkt-27734: Configurable Metrics for Netdata Service
  gui/services/migrations/0023_configurable_netdata_metrics.py
  gui/services/models.py
  src/middlewared/middlewared/etc_files/local/netdata/alarms.py
  src/middlewared/middlewared/etc_files/local/netdata/netdata.conf
  src/middlewared/middlewared/etc_files/local/netdata/stream.conf
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/netdata.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/validators.py
Labels: 3 - Review

#2104 tkt-58113: fix(jail/activate): Correctly return True/False
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2109 tkt-58581: fix(jail/exec): Use Str instead of RuntimeError instance for message
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2107 tkt-58218: Clean Middlewared log
  src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf
  src/middlewared/middlewared/plugins/webdav.py
Labels: 3 - Review

#2112 tkt-58662: fix(netcli): interfaces lookup model name
  src/freenas/etc/netcli
Labels: backport-11.3

#2092 tkt-47675: SMART Temp alerts for specific disks
  gui/storage/migrations/0011_disk_temperatures.py
  gui/storage/models.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/service.py
Labels: 3 - Review

#2115 tkt-58860: fix(middlewared/vm): make sure device VM exists
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-11.2

#2117 tkt-58968: fix(rc): do not try to load gmirror (builtin module)
  src/freenas/etc/rc.conf
Labels: backport-11.2

#2120 tkt-59175: fix(middlewared/network): network.general.summary after interfaces API changes
  src/middlewared/middlewared/plugins/network.py
Labels: redmine

#2121 tkt-39787: fix(scrub): allow freenas-boot scrub to run on passive/standby
  src/freenas/usr/local/libexec/nas/scrub
Labels: backport-11.2

#2123 tkt-27886: fix(vm): include VLAN parent as possible choice
  gui/vm/forms.py
Labels: backport-11.2

#2131 tkt-59463: rm(middlewared/cluster): plugin was never finished
  src/middlewared/middlewared/plugins/cluster.py
Labels: redmine

#2134 tkt-28778: fix(gui): regenerate VM NIC choices
  gui/vm/forms.py
Labels: backport-11.2

#2138 tkt-35263: fix(middlewared/device): parse devd messages using "=" as separator
  src/middlewared/middlewared/plugins/device.py
Labels: backport-11.2

#2101 tkt-57105: Add -d removable for all S.M.A.R.T. devices
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Labels: backport-11.3

#2141 tkt-59616: Fix pool.import_disk rsync stderr being lost
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-11.3, redmine

#2146 tkt-59877: fix(middlewared/ssh): validate ssh bindiface attribute
  src/middlewared/middlewared/plugins/ssh.py
Labels: redmine

#2148 tkt-55692: Bug fix for iscsi extents
  src/middlewared/middlewared/plugins/iscsi.py
Labels: 3 - Review

#2154 tkt-60138: Remove vCenter from System
  gui/freeadmin/static/css/custom.css
  gui/freeadmin/static/images/ui/menu/vsphere.png
  gui/freeadmin/static/images/ui/tree/vsphere.png
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/Menu.js
  gui/templates/freeadmin/index.html
  gui/templates/vcp/aux_settings.html
  gui/templates/vcp/index.html
  gui/vcp/Extensionconfig.ini.dist
  gui/vcp/__init__.py
  gui/vcp/admin.py
  gui/vcp/forms.py
  gui/vcp/hook.py
  gui/vcp/migrations/0001_initial.py
  gui/vcp/migrations/__init__.py
  gui/vcp/models.py
  gui/vcp/nav.py
  gui/vcp/plugin.py
  gui/vcp/urls.py
  gui/vcp/utils.py
  gui/vcp/vcp_locales/task_locale_en.properties
  gui/vcp/views.py
Labels: 3 - Review, backport-11.2, backport-11.3

#2163 tkt-59697: fix(motd): bump year in copyright
  src/freenas/etc/motd.template
Labels: backport-11.2

#2157 tkt-54717: feat(jail/fetch): Set downloading progress
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2
