Repository truenas/middleware, pull requests merged in 2018-12, with the labels that each got.

#2194 QA-Test tkt-62097 Adding 'vnet_default_interface=auto' to props of test_06_create_jail
  tests/api2/jail.py
Labels: api tests, review

#2085 tkt-56043: Asigra from 11.1 + Improvements
  gui/account/migrations/0008_add_pgsql_user.py
  gui/account/migrations/0009_merge_20181109_1114.py
  gui/freeadmin/static/css/custom.css
  gui/freeadmin/static/images/ui/tree/asigra.png
  gui/freeadmin/static/lib/js/freeadmin/Services.js
  gui/services/forms.py
  gui/services/migrations/0018_add_asigra_service.py
  gui/services/migrations/0019_add_asigra_model.py
  gui/services/migrations/0021_merge_20181109_1113.py
  gui/services/models.py
  gui/services/views.py
  gui/templates/services/asigra_edit.html
  src/freenas/etc/ix.rc.d/ix-asigra
  src/freenas/etc/ix.rc.d/ix-nginx
  src/freenas/etc/rc.conf.local
  src/middlewared/middlewared/etc_files/dssys.cfg
  src/middlewared/middlewared/etc_files/libmap.conf
  src/middlewared/middlewared/etc_files/local/pam.d/dssystem
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service.py
Labels: backport-11.3

#2142 tkt-59625: Fix using synchronous middleware client in asynchronous middleware code
  src/middlewared/middlewared/plugins/replication.py
Labels: backport-11.3, backported, redmine

#2176 tkt-61128: fix(gui): properly show network errors and save w/o hostname virtual
  gui/network/forms.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.3, backported, redmine

#2151 tkt-59634: Bug fix for iscsi share creation
  gui/system/forms.py
Labels: 3 - Review

#2089 tkt-57519: Bug fix for cloned zvols
  docs/api/resources/storage.rst
  gui/api/resources.py
Labels: 3 - Review

#2161 tkt-60624: Remove vCenter from System (by sonicaj)
  gui/freeadmin/static/css/custom.css
  gui/freeadmin/static/images/ui/menu/vsphere.png
  gui/freeadmin/static/images/ui/tree/vsphere.png
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/Menu.js
  gui/templates/freeadmin/index.html
  gui/templates/vcp/aux_settings.html
  gui/templates/vcp/index.html
  gui/vcp/Extensionconfig.ini.dist
  gui/vcp/__init__.py
  gui/vcp/admin.py
  gui/vcp/forms.py
  gui/vcp/hook.py
  gui/vcp/migrations/0001_initial.py
  gui/vcp/migrations/0002_auto_20180523_1943.py
  gui/vcp/migrations/__init__.py
  gui/vcp/models.py
  gui/vcp/nav.py
  gui/vcp/urls.py
  gui/vcp/utils.py
  gui/vcp/vcp_locales/task_locale_en.properties
  gui/vcp/views.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/notifier.py
  src/middlewared/middlewared/plugins/vcenter.py
Labels: 3 - Review

#2162 tkt-60633: Remove vCenter from System (by sonicaj)
  gui/freeadmin/static/css/custom.css
  gui/freeadmin/static/images/ui/menu/vsphere.png
  gui/freeadmin/static/images/ui/tree/vsphere.png
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/Menu.js
  gui/templates/freeadmin/index.html
  gui/templates/vcp/aux_settings.html
  gui/templates/vcp/index.html
  gui/vcp/Extensionconfig.ini.dist
  gui/vcp/__init__.py
  gui/vcp/admin.py
  gui/vcp/forms.py
  gui/vcp/hook.py
  gui/vcp/migrations/0001_initial.py
  gui/vcp/migrations/0002_auto_20180523_1943.py
  gui/vcp/migrations/__init__.py
  gui/vcp/models.py
  gui/vcp/nav.py
  gui/vcp/urls.py
  gui/vcp/utils.py
  gui/vcp/vcp_locales/task_locale_en.properties
  gui/vcp/views.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/notifier.py
  src/middlewared/middlewared/plugins/vcenter.py
Labels: 3 - Review

#2189 tkt-61884: fix(jail/fstab): Join the exceptions that iocage will return
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2202 QA-Test tkt-62208 remove da* in runtest.py to fix pool storage problem for API v1
  tests/runtest.py
Labels: review

#2193 tkt-61659: fix(jail/rc_action): RESTART now works as intended
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2212 QA-Test tkt-62595 replace timeout 10min to 15min on test 15
  tests/api2/jail.py
Labels: review

#2219 tkt-62901: Bug fix for nginx conf
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
Labels: 3 - Review

#2220 tkt-62910: Bug fix for nginx conf
  src/freenas/etc/ix.rc.d/ix-nginx
Labels: 3 - Review, backport-11.1

#2222 tkt-59697: Update motd
  src/freenas/etc/motd.template
Labels: 3 - Review

#2224 QA tkt-63123 replace pytest.mark.skipif condition
  tests/api2/smart.py
Labels: review

#2225 QA-Test tkt-63126 adding API v1 test to check the existence of all disk
  tests/api1/storage.py
Labels: review

#2226 tkt-62703: fix(middlewared/zfs): do not raise exception if snapshot does not exist
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-11.2

#2229 tkt-45398: Add alert if syslog-ng is not running
  src/middlewared/middlewared/alert/source/syslog_ng.py
Labels: backport-11.3

#2230 tkt-63216: Fix installer saying "This computer has less than the recommended GB of RAM"
  src/freenas-installer/etc/install.sh
Labels: backport-11.2, redmine

#2233 Fix MSDOSFS import
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-11.2

#2238 tkt-60135: Fix AWS S3 Cloud Sync hostname resolving to s3.None.amazonaws.com
  src/middlewared/middlewared/rclone/remote/s3.py
Labels: backport-11.2

#2240 tkt-34915: Allow cloud sync S3 endpoints that do not support regions and use v2 signatures
  src/middlewared/middlewared/rclone/remote/s3.py
Labels: backport-11.2

#2239 tkt-63459: Check for None for r[n]in filters
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-11.2

#2244 tkt-62766: fix(jail/query): Catch subprocess exception
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2243 QA-Test tkt-63405 Adding API v1 storage verification of pool, dataset, and zvol
  tests/api1/storage.py
Labels: review

#2247 QA tkt-63495 replacing all 'tank' string by pool name varible in all test usning dataset
  tests/api1/ad_bsd.py
  tests/api1/ad_osx.py
  tests/api1/afp_osx.py
  tests/api1/iscsi.py
  tests/api1/jails.py
  tests/api1/ldap_bsd.py
  tests/api1/ldap_osx.py
  tests/api1/nfs.py
  tests/api1/nis_bsd.py
  tests/api1/smb_bsd.py
  tests/api1/smb_osx.py
  tests/api1/tftp.py
  tests/api1/user.py
  tests/api1/webdav_bsd.py
  tests/api1/webdav_osx.py
Labels: review

#2252 tkt-63648: Fix handling of LDAPErr messages in directory service wizard
  gui/system/forms.py
Labels: backport-11.2

#2257 Fix parse_ipmitool_output
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: backport-11.2

#2255 tkt-63414: fix trusted domain users/groups in webUI
  gui/common/freenasldap.py
  gui/freeadmin/forms.py
Labels: backport-11.1, backport-11.2

#2254 tkt-62574: Show Certificate validity period accurately
  gui/system/models.py
  src/middlewared/middlewared/plugins/crypto.py
Labels: 3 - Review

#2260 tkt-60759: fix(middlewared/zfs): do not get all datasets on zfs.pool.query
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-11.2

#2271 tkt-64284: fix(middlewared/pool): handle pool not found traceback
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-11.2

#2273 tkt-64593: feat(middlewared/restful): output message and traceback on any error
  src/middlewared/middlewared/restful.py
Labels: redmine

#2274 tkt-64635: fix(middlewared/vm): process is already being kill after
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-11.2

#2276 tkt-64053: fix(gui/api): clean up main ipv4 field if DHCP is checked
  gui/network/forms.py
Labels: backport-11.2

#2270 tkt-62892: Disallow keys of length less then 1024
  src/middlewared/middlewared/plugins/crypto.py
Labels: 3 - Review

#2265 tkt-62655: Parse certificate attributes
  gui/api/resources.py
  gui/common/freenasldap.py
  gui/common/ssl.py
  gui/directoryservice/forms.py
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/system/forms.py
  gui/system/migrations/0036_remove_parseable_cert_attrs.py
  gui/system/models.py
  gui/system/views.py
  src/freenas/etc/ix.rc.d/ix-proftpd
  src/freenas/usr/local/etc/rc.d/django
  src/middlewared/middlewared/alert/source/certificates.py
  src/middlewared/middlewared/alert/source/httpd_ssl.py
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/ftp.py
  src/middlewared/middlewared/plugins/system.py
Labels: 3 - Review

#2290 tkt-62433: Allow slow but stubborn middleware startup on low-performance boot devices
  nas_ports/freenas/py-middlewared/files/middlewared.in
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-11.2

#2300 tkt-65565: Warning for manual setup of Volume creation
  gui/templates/storage/zfswizard.html
Labels: 3 - Review, backport-11.2, backport-11.3

#2304 tkt-65544: Bug fix for s3
  src/freenas/etc/rc.conf.local
Labels: 3 - Review, backport-11.1, backport-11.3

#2320 tkt-66331: Bug fix for pwenc
  gui/middleware/notifier.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: redmine

#2325 tkt-64482: fix(middlewared/zfs): split by newline only
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-11.3

#2327 tkt-66646: Properly encode/decode passwords
  gui/middleware/notifier.py
Labels: redmine

#2329 QA-Test tkt-66675 Adding status_code and text to all disk API v2 tests
  tests/api2/disk.py
Labels: review

#2331 tkt-66691: fix(debug): use midclt to get alerts
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: backport-11.2, redmine
