Repository truenas/middleware, pull requests merged in 2019-06, with the labels that each got.

#3129 NAS-101954 / 11.3 / add swap usage to top output in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: backport-11.2

#3125 NAS-101944 / 11.2 / New VMware snapshot flags
  gui/storage/forms.py
  gui/tools/autosnap.py
Labels: backport-11.3

#3159 NAS-102043 / 11.2 / Fix Traceback creating big pool
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3166 NAS-102035 / 11.2 / Fix HipChat Legacy UI
  src/middlewared/middlewared/alert/service/hipchat.py
Labels: backport-11.3

#3167 NAS-102035 / 11.3 / Fix HipChat Legacy UI (by themylogin)
  src/middlewared/middlewared/alert/service/hipchat.py
Labels: skip jira status

#3172 NAS-101811 / 11.3 / Proper "Failed to generate debug file:" error reporting
  src/middlewared/middlewared/plugins/system.py
Labels: skip jira status

#3174 NAS-100083 / 12 / Reset update train on config upload
  src/freenas/etc/ix.rc.d/ix-update
Labels: backport-11.3, backported

#3204 NAS-101675 / 11.2 / Generate an alert when creating a new ticket for TrueNAS proactive al…
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3250 NAS-102225 / 11.3 / only run this section on freenas and truenas licensed for jails
  src/freenas/usr/local/libexec/freenas-debug/jails/jails.sh
Labels: skip jira status

#3262 NAS-102234 / 11.3 / Cloud sync providers not working (by william-gr)
  src/middlewared/middlewared/rclone/remote/amazon_cloud_drive.py
Labels: skip jira status

#3273 NAS-102281 / 11.3 / Expose destroying jail force flag
  src/middlewared/middlewared/plugins/jail.py
Labels: jira

#3274 NAS-102280 / 11.3 / Donot run network related periodic tasks on boot
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/jail.py
Labels: jira

#3269 NAS-102231 / 11.2 / Only refresh cloud credentials tokens
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/rclone/base.py
  src/middlewared/middlewared/rclone/remote/google_drive.py
  src/middlewared/middlewared/rclone/remote/onedrive.py
  src/middlewared/middlewared/rclone/remote/pcloud.py
  src/middlewared/middlewared/rclone/remote/yandex.py
Labels: backport-11.3, backported
