Repository truenas/middleware, pull requests merged in 2019-03, with the labels that each got.

#2694 tkt-78132: Fix idmap_ldap parameters
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.1

#2696 tkt-78168: fix(middlewared/update): set user train on update.update
  src/middlewared/middlewared/plugins/update.py
Labels: backport-11.2

#2699 tkt-78232: Remove all usages of ix-resolv
  src/freenas/etc/directoryservice/DomainController/ctl
  src/middlewared/middlewared/plugins/service.py
Labels: 3 - Review, redmine

#2706 tkt-73380: Update ups service to listen to ipv6 addresses
  src/middlewared/middlewared/etc_files/local/nut/upsd.conf
Labels: 3 - Review

#2708 tkt-78609: [etc] Remove unused freenas.conf
  src/freenas/etc/freenas.conf
Labels: backport-11.2

#2692 tkt-76440: Migrate CA's to Certificate in Directory Services
  gui/common/freenasldap.py
  gui/directoryservice/forms.py
  gui/directoryservice/migrations/0006_certificate_model.py
  gui/directoryservice/models.py
  src/freenas/usr/local/libexec/nas/generate_sssd_conf.py
  src/middlewared/middlewared/etc_files/local/nslcd.conf
  src/middlewared/middlewared/etc_files/local/nss_ldap.conf
  src/middlewared/middlewared/etc_files/local/openldap/ldap.conf
Labels: 3 - Review

#2709 tkt-77412: Fix prepending / for non-bucket cloud sync remotes
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-11.3, backported

#2690 tkt-77106: fix(smart): Fix SMART service startup
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Labels: backport-11.3

#2716 tkt-78286: fix(middlewared/zfs): mount dataset after snapshot clone
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-11.2

#2719 tkt-78825: fix(middlewared): use login(1) for webshell
  src/middlewared/middlewared/main.py
Labels: backport-11.2

#2724 tkt-79419: Correct kern.corefile setting
  src/freenas/etc/sysctl.conf
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: 3 - Review, backport-11.1, backport-11.2, redmine

#2728 QE tkt-79464 Update freenas/11.2-stable jail/stop parameter
  tests/api2/jails.py
Labels: review

#2732 tkt-76864: fix(jail/fstab): Remove replacement of spaces and split on tabs
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2734 tkt-74631: FN 12 Installer
  src/freenas-installer/etc/installer12.sh
Labels: 3 - Review

#2742 tkt-80337: fix regression in unified smb configuration
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.2

#2751 tkt-80085: fix(middleawre/iscsi): do not allow duplicate tags for iSCCI Auth
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-11.2

#2770 Volume check in migration
  gui/vm/migrations/0009_auto_20190315_1058.py
Labels: 3 - Review

#2776 tkt-82641: Be a bit more safer on our rm(1) usages
  gui/middleware/notifier.py
  src/freenas/etc/ix.rc.d/ix-ldap
  src/freenas/etc/rc.d/ix-update-scripts
  src/freenas/usr/local/bin/freenas-debug
  src/freenas/usr/local/bin/ixdiagnose
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
  src/middlewared/middlewared/plugins/reporting.py
Labels: backport-11.2, backported, redmine

#2778 tkt-81399: Bug fixes in Rsync Plugin
  gui/services/forms.py
  src/middlewared/middlewared/etc_files/local/rsyncd.conf
  src/middlewared/middlewared/plugins/rsync.py
Labels: 3 - Review, backport-11.2

#2780 Correctly escape path on validation as well for rsync
  src/middlewared/middlewared/plugins/rsync.py
Labels: 3 - Review

#2693 tkt-72957: Improve datastore listing in vmware
  gui/storage/views.py
  src/middlewared/middlewared/plugins/vmware.py
  tests/api2/vmware.py
Labels: 3 - Review, backport-11.1, backport-11.2, backported

#2784 Update vmware tests
  src/middlewared/middlewared/pytest/functional/test_0095_vmware.py
  tests/api2/vmware.py
Labels: 3 - Review

#2791 tkt-83067: Fix smartd not running alert
  src/middlewared/middlewared/alert/source/smartd.py
Labels: backport-11.3

#2795 tkt-83491: Correctly display post install messages
  src/middlewared/middlewared/plugins/jail.py
Labels: 3 - Review, backport-11.3, backported

#2801 tkt-77916: Use nfsd command-line option instead of /etc/nfsd.virtualhost
  src/middlewared/middlewared/etc_files/nfsd.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.2

#2803 Donot encrypt empty dictionary
  gui/freeadmin/models/fields.py
Labels: 3 - Review

#2806 tkt-83700: Expose Supported Dynamic DNS Providers
  gui/choices.py
  gui/services/migrations/0001_initial.py
  gui/services/models.py
  src/middlewared/middlewared/plugins/dyndns.py
Labels: 3 - Review, backport-11.2

#2779 tkt-82713: Bug fixes in Rsync Plugin (by sonicaj)
  gui/services/forms.py
  src/middlewared/middlewared/plugins/rsync.py
Labels: 3 - Review

#2785 tkt-83075: Correct encoding logic for certificates
  gui/common/ssl.py
Labels: 3 - Review, backport-11.1

#2787 tkt-83235: Configure Encrypted Pools Correctly
  gui/api/resources.py
  gui/storage/forms.py
  gui/storage/views.py
  gui/templates/freeadmin/generic_model_dialog.html
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: 3 - Review

#2792 tkt-69562: Fix "unscheduled system reboot" alert after update
  src/freenas/etc/ix.rc.d/ix-update
Labels: backport-11.3, backported

#2814 tkt-83147: feat(collectd): try to use `cam` to get temperature for SCSI disks
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
Labels: backport-11.2
