Repository truenas/middleware, pull requests merged in 2019-12, with the labels that each got.

#3883 NAS-104191 / 12 / Properly delete iscsi targets/extents
  src/middlewared/middlewared/plugins/iscsi.py
Labels: jira

#3882 NAS-104190 / 12 / Remove vm devices before deleting vm
  src/middlewared/middlewared/plugins/vm.py
Labels: jira

#3881 NAS-104189 / 12 / Fixes for bootenv plugin
  src/middlewared/middlewared/plugins/bootenv.py
Labels: jira

#3857 NAS-104153 / 11.2 / Added support for the /dev/twsX (3ware 9750) controller
  src/middlewared/middlewared/common/smart/smartctl.py
Labels: backport-11.3, backported

#3880 NAS-104188 / 12 / Correct path for ups driver choices
  src/middlewared/middlewared/plugins/ups.py
Labels: jira

#3890 NAS-104216 / 11.2 / ensure 'progressfile' isn't empty
  src/middlewared/middlewared/plugins/replication.py
Labels: backport-11.3

#3902 NAS-104251 / 12 / Perform cleanup when the installer loops
  src/freenas-installer/etc/install.sh
Labels: backport-11.3

#3891 NAS-104132 / 12 / Make disk.sync* work on linux
  src/middlewared/debian/control
  src/middlewared/middlewared/plugins/device.py
  src/middlewared/middlewared/plugins/device_/__init__.py
  src/middlewared/middlewared/plugins/device_/device_info_base.py
  src/middlewared/middlewared/plugins/device_/device_info_freebsd.py
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/disk_/identify_base.py
  src/middlewared/middlewared/plugins/disk_/identify_freebsd.py
  src/middlewared/middlewared/plugins/disk_/identify_linux.py
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: pending QA

#3905 NAS-104259 / 11.3 / Provide replication progress in job so that standard UI component can…
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: jira

#3904 NAS-104260 / 11.3 / Legacy periodic snapshot naming schema did not have %S
  gui/storage/migrations/0012_new_periodic_snapshot_task.py
  src/middlewared/middlewared/plugins/snapshot.py
Labels: jira

#3896 NAS-104222 / 11.3 / Legacy replication progress
  src/middlewared/middlewared/plugins/replication.py
Labels: jira

#3901 NAS-104256 / 11.3 / Prevent breaking replication task
  src/middlewared/middlewared/plugins/snapshot.py
Labels: jira

#3903 NAS-104257 / 11.3 / Fix re-replicating everything under different path when migrating fro…
  gui/api/resources.py
  gui/storage/migrations/0013_new_replication_task.py
  src/middlewared/middlewared/plugins/replication.py
Labels: jira

#3916 NAS-104284 / 11.3 / Fix prepending "This is a MIME formatted message." to HTML e-mails se…
  gui/common/system.py
  src/freenas/etc/find_alias_for_smtplib.py
  src/middlewared/middlewared/plugins/mail.py
Labels: jira

#3921 NAS-104298 / 11.3 / Fix TypeError: object of type 'Header' has no len() when sending e-ma…
  src/middlewared/middlewared/plugins/mail.py
Labels: jira

#3917 NAS-104269 / 11.2 / raise custom exception and log it
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3926 NAS-104318 / 12 / Remove system dataset from pool.dataset.query
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/vmware.py
Labels: jira

#3888 NAS-104204 / 12 / Add support more more quota types
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira

#3938 NAS-104380 / 11.3 / Allow setting nat/bpf props without order for jail.update
  src/middlewared/middlewared/plugins/jail.py
Labels: jira

#3937 NAS-104353 / 11.3 / Fix cloud sync with snapdir=visible
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-11.2

#3941 NAS-104405 / 11.3 / Make sure usage stats are gathered irrespective of jail errors
  src/middlewared/middlewared/plugins/usage.py
Labels: jira

#3943 NAS-104421 / 11.3 / Use realpath for path validation in middleware
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira

#3945 NAS-104348 / 11.3 / ZfsDeadmanAlertClass
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12, backported

#3951 NAS-104438 / 11.3 / Pass new ldap credentials to ldap.validate_credentials
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira

#3955 NAS-104479 / 11.2 / Add ability to gather locking an memory pool stats from freenas cache
  gui/common/freenascache.py
  gui/tools/cachetool.py
Labels: jira

#3957 NAS-104488 / 11.3 / Fix "Not authenticated" when disconnecting immediately after scheduli…
  src/middlewared/middlewared/main.py
Labels: jira

#3967 NAS-104491 / 11.3 / Do not treat failure to properly configure for kerberized NFS as fatal
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#3980 NAS-104492 / 11.3 / S.M.A.R.T. is always enabled on NVMe devices
  src/middlewared/middlewared/etc_files/smartd.py
Labels: WIP
