Repository truenas/middleware, pull requests merged in 2019-10, with the labels that each got.

#3622 NAS-103311 / 11.3 / Do not initialize iocage until plugin is installed
  src/middlewared/middlewared/plugins/jail.py
Labels: jira

#3625 NAS-103319 / 11.3 / feat(middlewared/update): allow train redirection
  src/middlewared/middlewared/plugins/update.py
Labels: jira

#3628 NAS-103164 / 11.3 / Ensure we don't add duplicate log handlers
  src/middlewared/middlewared/plugins/vm.py
Labels: skip jira status

#3631 Bug fixes for iscsi plugin
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-11.2

#3559 NAS-103021 / 11.2 / Restart smartd on interval change
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/service.py
Labels: backport-11.3, backported

#3635 NAS-103367 / 11.3 / fix(api1.0): recordsize choice is 1M not 1024K
  docs/api/resources/storage.rst
Labels: skip jira status

#3650 NAS-103312 / 11.3 / Do not run annotate_devices_with_areca_enclosure simultaneously N times
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
  src/middlewared/middlewared/common/smart/areca.py
  src/middlewared/middlewared/common/smart/smartctl.py
Labels: skip jira status

#3651 NAS-103454 / 11.2 / fix netcli on TrueNAS HA systems
  src/freenas/etc/netcli
Labels: backport-11.3

#3669 NAS-103518 / 11.3 / Ensure validation errors are raised with api v1
  gui/api/utils.py
Labels: skip jira status

#3659 NAS-103496 / 11.2 / properly handle rc.conf.local on TrueNAS HA systems
  src/freenas/etc/rc.conf.local
Labels: backport-11.3

#3685 NAS-103500 / 11.2 / Do not hide disk update validation errors
  gui/api/resources.py
Labels: backport-11.3

#3712 NAS-103615 / 11.2 / add bindkey for searching recent commands in zsh
  src/freenas/root/.zshrc
Labels: backport-11.3

#3725 NAS-103643 / 11.2 / Fix alerts
  src/middlewared/middlewared/plugins/alert.py
  tests/results/.keepme
Labels: backport-11.3

#3724 NAS-103337 / 12 / Add ed25519 key support
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/rsync.py
Labels: skip jira status

#3727 NAS-103651 / 12 / Add defaults for VPN plugin models
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira

#3733 NAS-103613 / 11.2 / Remove legacy vmware snapshot alerts when updating/deleting vmware
  gui/tools/autosnap.py
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-11.3, backported

#3740 NAS-103678 / 11.2 / make sure to not run vmware-checkvm on truenas
  src/freenas/etc/rc.conf.local
Labels: backport-11.3

#3743 NAS-103708 / 11.3 / Return updated config on system dataset update
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#3746 NAS-103710 / 12 / Fix RESTful API broken
  src/middlewared/middlewared/service.py
Labels: jira
