Repository truenas/middleware, pull requests merged in 2019-02, with the labels that each got.

#2520 QE-Test tkt-73306 Update FreeNAS jail/stop API v2
  tests/api2/jail.py
Labels: api tests, review

#2519 tkt-70192: Move ix-aliases to etc
  src/freenas/etc/ix.rc.d/ix-aliases
  src/middlewared/middlewared/etc_files/aliases
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service.py
Labels: 3 - Review

#2523 tkt-73317: Restart collectd/rrdcached properly
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: 3 - Review, redmine

#2521 tkt-72459: fix(oldgui): Support boolean properties for cloud credentials
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
Labels: backport-11.3, backported

#2524 QE tkt-73558 update vnet_default_interface to auto in freenas/11.2-stable jail API v2 test
  tests/api2/jails.py
Labels: api tests, review

#2525 tkt-73587: Password fix for Dynamic DNS
  gui/services/forms.py
Labels: 3 - Review, backport-11.2, redmine

#2528 tkt-66961: fix(nfs/api1.0): imply v4_v3owner=false when v4=false
  gui/api/resources.py
Labels: backport-11.2, backported

#2532 tkt-73819: Fix OpenSSL path
  src/freenas/etc/rc.freenas
Labels: 3 - Review, redmine

#2533 Remove leftovers of OpenSSL configuration
  src/freenas/etc/rc.freenas
Labels: 3 - Review

#2534 tkt-65943: Allow non-word characters (like .) in pool/dataset/zvol names in API 1.0
  gui/api/resources.py
Labels: backport-11.2

#2538 tkt-70282: Convert ix-preinit to etc
  src/freenas/etc/ix.rc.d/ix-preinit
  src/middlewared/middlewared/plugins/init_shutdown_script.py
Labels: 3 - Review

#2541 tkt-70300: Convert ix-shutdown to Middlewared
  src/freenas/etc/ix.rc.d/ix-shutdown
Labels: 3 - Review

#2540 tkt-70291: Convert ix-postinit to Middlewared
  src/freenas/etc/rc.d/ix-postinit
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  src/middlewared/middlewared/service.py
Labels: 3 - Review

#2543 tkt-72131: Configure timezone correctly
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/system.py
Labels: 3 - Review

#2544 QE tkt-74109 adding sleep 1 to all API v1 & v2 test starting and stoping services
  tests/api1/ad_bsd.py
  tests/api1/ad_osx.py
  tests/api1/afp_osx.py
  tests/api1/ftp.py
  tests/api1/iscsi.py
  tests/api1/ldap_bsd.py
  tests/api1/ldap_osx.py
  tests/api1/lldp.py
  tests/api1/nfs.py
  tests/api1/rsync.py
  tests/api1/smb_bsd.py
  tests/api1/smb_osx.py
  tests/api1/snmp.py
  tests/api1/ssh.py
  tests/api1/tftp.py
  tests/api1/ups.py
  tests/api1/webdav_bsd.py
  tests/api1/webdav_osx.py
  tests/api2/afp.py
  tests/api2/dyndns.py
  tests/api2/iscsi.py
  tests/api2/jail.py
  tests/api2/lldp.py
  tests/api2/nfs.py
  tests/api2/rsync.py
  tests/api2/s3.py
  tests/api2/service.py
  tests/api2/smart.py
  tests/api2/smb.py
  tests/api2/ssh.py
  tests/api2/tftp.py
  tests/api2/webdav_bsd.py
  tests/api2/webdav_osx.py
Labels: api tests, review

#2537 tkt-70372: Convert ix_textdump
  src/freenas/etc/ix.rc.d/ix_textdump
  src/freenas/etc/rc.conf
  src/middlewared/middlewared/plugins/system.py
Labels: 3 - Review

#2547 tkt-74785: Fix setting root password using netcli
  src/freenas/etc/netcli
Labels: backport-11.1, backport-11.2

#2578 tkt-65013: Ignore SMART utf-8 decoding errors
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-11.3

#2526 tkt-73441: fix(bhyve): prevent setting vfs.zfs.arc_max to lower than vfs.zfs.arc…
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-11.3, backported

#2449 tkt-70770: Fix incorrectly ported LAGG alert
  src/middlewared/middlewared/alert/source/lagg.py
Labels: backport-11.3, backported

#2423 tkt-60822: TFTP listen host option
  gui/services/migrations/0021_tftp_host.py
  gui/services/models.py
  src/freenas/etc/rc.conf.local
  src/middlewared/middlewared/plugins/tftp.py
Labels: backport-11.2, backport-11.3, backported

#2572 Address fstab reviews
  src/middlewared/middlewared/etc_files/fstab_configure.py
Labels: 3 - Review

#2570 Bug fix for ntp.conf
  src/middlewared/middlewared/etc_files/ntp.conf
Labels: 3 - Review

#2571 Bug fix for alerts
  src/middlewared/middlewared/alert/source/multipaths.py
Labels: 3 - Review

#2573 tkt-70345: Remove sudoers base file
  src/freenas/usr/local/etc/sudoers
  src/middlewared/middlewared/etc_files/local/sudoers
Labels: 3 - Review

#2441 Improve iscsi validation
  src/middlewared/middlewared/plugins/iscsi.py
Labels: 3 - Review, backport-11.3, backported

#2467 Correctly set kern.corefile
  src/freenas/etc/sysctl.conf
Labels: 3 - Review

#2470 Correctly set kern.corefile
  src/freenas/etc/sysctl.conf
Labels: 3 - Review

#2583 tkt-70264: Fix linebreak for motd
  src/middlewared/middlewared/etc_files/motd
Labels: 3 - Review

#2546 [directoryservice] Fix shell errors
  src/freenas/etc/directoryservice/rc.ActiveDirectory
  src/freenas/etc/directoryservice/rc.DomainController
  src/freenas/etc/directoryservice/rc.LDAP
Labels: backport-11.1, backport-11.2

#2535 tkt-73657: Fix ordering for vfs_crossrename
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.3

#2495 tkt-35813: Bring in "unified" SMB HA mode.
  gui/directoryservice/forms.py
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.2, backport-11.3

#2592 tkt-74785: fix(netcli): restore ability to change root password without middlewa…
  src/freenas/etc/netcli
Labels: backport-11.1, backport-11.2

#2585 tkt-75532: Fix recursive dependency for aliases
  src/freenas/etc/find_alias_for_smtplib.py
  src/middlewared/middlewared/plugins/account.py
Labels: 3 - Review, backport-11.2

#2599 tkt-74785: fix(netcli): restore ability to change root password without middlewa…
  src/freenas/etc/netcli
Labels: backport-11.1, backport-11.2

#2602 tkt-75883: Fix "valid users" parameter for [homes] in Samba 4.9
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.3

#2558 tkt-75171: change netstat -i to netstat -in in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: backport-11.1, backport-11.2

#2559 tkt-75180: change arp -a to arp -an in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: backport-11.1, backport-11.2

#2560 tkt-75181: change middleware job timeout to 10mins for passive contro…
  gui/system/utils.py
Labels: backport-11.1

#2604 tkt-72571: Remove SAN from subject
  gui/system/models.py
  src/middlewared/middlewared/plugins/crypto.py
Labels: 3 - Review

#2609 tkt-76108: Simplify SAN code in middlewared
  src/middlewared/middlewared/plugins/crypto.py
Labels: 3 - Review, redmine

#2612 tkt-74569: fix(pool/export): Only stop jails if the pool is the same as activated
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-11.2

#2614 tkt-75829: Remove unsupported ciphers (they were not used anyway)
  gui/system/ixselftests/Tests/Replication.py
  gui/tools/autorepl.py
  src/freenas/usr/local/bin/replfix.py
Labels: backport-11.3

#2616 tkt-75937: Add product name and hostname to alerts body
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/service/aws_sns.py
  src/middlewared/middlewared/alert/service/hipchat.py
  src/middlewared/middlewared/alert/service/mail.py
  src/middlewared/middlewared/alert/service/mattermost.py
  src/middlewared/middlewared/alert/service/slack.py
  src/middlewared/middlewared/etc_files/local/proftpd.py
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.2

#2621 QE tkt-76297 Fix failed to download updates fot API v2 automation testing
  tests/api2/update.py
Labels: api tests, bug, review

#2586 tkt-73866: Update tooltip for password field
  gui/system/forms.py
Labels: 3 - Review

#2627 tkt-74551: Allow multiple SMB shares with same path
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-11.2

#2596 tkt-76018: Increase timeout for inittasks
  docs/api/resources/tasks.rst
  gui/tasks/migrations/0013_init_tasks_timeout.py
  gui/tasks/models.py
  src/freenas/etc/ix.rc.d/ix-preinit
  src/freenas/etc/ix.rc.d/ix-shutdown
  src/freenas/etc/rc.conf
  src/freenas/etc/rc.d/ix-postinit
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/system.py
Labels: 3 - Review, redmine

#2631 tkt-76242: let truenas ha code manage smartd service
  src/freenas/etc/rc.conf.local
Labels: backport-11.1, backport-11.2

#2620 tkt-66927: fix(collectd): Do not poll for temperature on drives with SMART disabled
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-11.2

#2635 tkt-76027: Update init/shutdown ix* scripts
  src/freenas/etc/ix.rc.d/ix-preinit
  src/freenas/etc/ix.rc.d/ix-shutdown
  src/freenas/etc/rc.d/ix-postinit
Labels: 3 - Review

#2636 tkt-76000: Fix regression with user/group validation in AD environments
  gui/common/freenasldap.py
Labels: backport-11.1, backport-11.3

#2641 tkt-76594: feat(middlewared/system): implement system.general.ui_certificate_choices
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.2

#2643 Update certificate extend method
  src/middlewared/middlewared/plugins/crypto.py
Labels: 3 - Review

#2649 tkt-76413: Move ix-ttys to etc
  src/freenas/etc/ix.rc.d/ix-ttys
  src/middlewared/middlewared/etc_files/ttys
  src/middlewared/middlewared/etc_files/ttys_config.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service.py
Labels: 3 - Review

#2653 tkt-77169: feat(etc): avoid using client to restart mdnsadvertise
  src/freenas/etc/ix.rc.d/ix_register
  src/middlewared/middlewared/plugins/service.py
Labels: redmine

#2650 tkt-74515: fix(vm): vnc web url when host is an ipv6 address
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-11.2

#2652 tkt-76431: ensure variables are stripped of leading/trailing whitespace
  gui/tools/autorepl.py
Labels: backport-11.1, backport-11.2

#2657 Bug fix for alerts
  src/middlewared/middlewared/alert/source/multipaths.py
Labels: 3 - Review

#2661 tkt-77323: Set proper primary UNIX account group ID in /etc/passwd
  src/middlewared/middlewared/etc_files/master.passwd
Labels: redmine

#2660 tkt-74172: Always use upsmon as primary indicator of UPS service status because …
  src/middlewared/middlewared/plugins/service.py
Labels: backport-11.2

#2664 tkt-77368: Bug fix for multipath
  gui/middleware/notifier.py
Labels: 3 - Review, redmine

#2673 tkt-77503: fix(jail/fetch): Workaround interactive plugin install on first init
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2676 tkt-77089: Init/shutdown script fixes
  src/freenas/etc/ix.rc.d/ix-preinit
  src/freenas/etc/ix.rc.d/ix-shutdown
  src/freenas/etc/rc.d/ix-postinit
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/system.py
Labels: 3 - Review

#2680 tkt-65943: fix(api): id should be allowed for volume
  gui/api/resources.py
Labels: backport-11.2

#2588 tkt-74848: [directoryservice] Fix shell errors
  src/freenas/etc/directoryservice/rc.ActiveDirectory
  src/freenas/etc/directoryservice/rc.DomainController
  src/freenas/etc/directoryservice/rc.LDAP
Labels: backport-11.1
