Repository truenas/middleware, pull requests merged in 2019-07, with the labels that each got.

#3261 NAS-102234 / 11.2 / Cloud sync providers not working
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/rclone/remote/amazon_cloud_drive.py
Labels: backport-11.3, backported

#3231 NAS-102203 / 11.3 / fix(restful): Catch IndexErrors
  src/middlewared/middlewared/plugins/datastore.py
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/service_exception.py
  src/middlewared/middlewared/utils/__init__.py
Labels: WIP

#3292 NAS-101010 / 11.3 / guihttpsredirect -> ui_httpsredirect
  src/middlewared/middlewared/plugins/system.py
Labels: skip jira status

#3302 NAS-102144 / 11.3 / fix(middlewared/zfs): empty snapshots should not break output
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-11.2, skip jira status

#3311 Fix NFS tests
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-11.2

#3313 NAS-102457 / 11.3 / Allow request body with GET/DELETE requests
  src/middlewared/middlewared/restful.py
Labels: jira

#3310 NAS-102451 / 11.2 / Fix Box cloud sync provider not refreshing token
  src/middlewared/middlewared/rclone/remote/box.py
Labels: backport-11.3, backported, jira

#3037 NAS-101727 / 11.2 / Fix JSON serialize errors being silently discarded (by themylogin)
  src/middlewared/middlewared/main.py
Labels: backport-11.3, backported

#3315 NAS-100271 / 11.2 / Remove CARP IPs from NICChoices even if failover is not licensed
  gui/choices.py
Labels: backport-11.3, backported

#3257 NAS-102226 / 11.2 / Explain DropBox path/restricted_content/ error
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-11.3, backported

#3305 NAS-102252 / 11.3 / Remove Asigra as a service
  gui/services/migrations/0035_remove_asigra.py
  src/middlewared/middlewared/etc_files/dssys.cfg
  src/middlewared/middlewared/etc_files/libmap.conf
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf
  src/middlewared/middlewared/etc_files/local/pam.d/dssystem
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: pending QA, skip jira status

#3353 NAS-102590 / 11.3 / Bug fix for csr
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/crypto.py
Labels: jira

#3361 NAS-102588 / 11.2 / Do not run "update is avaliable" alert on standby controller
  src/middlewared/middlewared/alert/source/update.py
Labels: backport-11.3, backported

#3364 NAS-102630 / 11.3 / Fix exporting non-decrypted pool
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#3370 NAS-102654 / 11.3 / Fix geli_testkey doing nothing
  src/middlewared/middlewared/plugins/disk.py
Labels: jira

#3376 NAS-102648 / 11.3 / fix(migration): add used lun ids to the list so we dont reuse it
  gui/services/migrations/0020_make_lunid_non_null.py
Labels: backport-11.2

#3381 NAS-102665 / 11.3 / fix(middlewared/alert): do not let alert jobs queue up
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.2, skip jira status

#3389 Do not run "Scrub is paused" alert on backup node
  src/middlewared/middlewared/alert/source/scrub_paused.py
Labels: backport-11.2

#3393 NAS-102692 / 11.3 / Ensure iocage is not setup on jail/plugin query
  src/middlewared/middlewared/plugins/jail.py
Labels: jira

#3384 NAS-102665 / 11.2 / fix(middlewared/alert): do not let alert jobs queue up (by william-gr)
  src/middlewared/middlewared/plugins/alert.py
Labels: skip jira status

#3400 NAS-102698 / 11.3 / Slack field "detailed" does not exist
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/system/forms.py
  src/middlewared/middlewared/alert/service/slack.py
Labels: backport-11.2

#3404 NAS-102579 / 11.3 / Fix mess in alert service schemas
  gui/system/forms.py
  src/middlewared/middlewared/alert/service/aws_sns.py
  src/middlewared/middlewared/alert/service/hipchat.py
  src/middlewared/middlewared/alert/service/influxdb_.py
  src/middlewared/middlewared/alert/service/mail.py
  src/middlewared/middlewared/alert/service/mattermost.py
  src/middlewared/middlewared/alert/service/opsgenie.py
  src/middlewared/middlewared/alert/service/pagerduty.py
  src/middlewared/middlewared/alert/service/slack.py
  src/middlewared/middlewared/alert/service/snmp_trap.py
  src/middlewared/middlewared/alert/service/victorops.py
Labels: backport-11.2
