Repository truenas/middleware, pull requests merged in 2019-05, with the labels that each got.

#2978 NAS-101608 / 11.3 / Properly restart UPS
  src/middlewared/middlewared/etc_files/local/nut/upsmon.conf
  src/middlewared/middlewared/plugins/service.py
Labels: jira

#2976 NAS-101604 / 11.3 / feat(jail/list_resource): Allow avoiding the cache on the remote plug…
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#2975 NAS-101496 / 11.2 / fix legacy replication after QA failure
  gui/tools/autorepl.py
Labels: backport-11.1

#2977 NAS-101566 / 11.2 / Failover alerts fixes
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#2988 NAS-101592 / 11.3 / Bug fixes for legacy wizards
  gui/system/forms.py
Labels: backport-11.2, skip jira status

#3000 NAS-100773 / 11.3 / fix(gui): create VLAN interface with `up`
  gui/network/forms.py
Labels: backport-11.2, skip jira status

#3006 NAS-101662 / 11.3 / Correct syslog level case
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: jira

#3022 NAS-101723 / 11.3 / fix(gui): deleting alert service
  gui/system/forms.py
Labels: backport-11.2, skip jira status

#3027 NAS-101728 / 11.3 / fix(middlewared/alert): fix formatting for threaded alert services
  src/middlewared/middlewared/alert/base.py
Labels: backport-11.2, skip jira status

#3031 NAS-101727 / 11.3 / Fix JSON serialize errors being silently discarded
  src/middlewared/middlewared/main.py
Labels: backport-11.1, backport-11.2

#3040 NAS-101531 / 11.3 / fix(jail/fstab): Add more validation
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#3039 NAS-101752 / 11.3 / Fix Traceback creating big pool
  gui/system/forms.py
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.2

#3038 NAS-101753 / 11.2 / Fix Traceback processing TN alerts
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3, backported

#3052 NAS-101757 / 11.3 / Fix cloud sync legacy UI javascript escaping bug
  gui/freeadmin/static/lib/js/freeadmin/CloudSync.js
  gui/tasks/widgets.py
Labels: backport-11.2

#3057 NAS-101789 / 11.2 / Disable netdata on passive controller
  src/freenas/etc/rc.conf.local
Labels: backport-11.3

#3056 NAS-101750 / 11.2 / Properly reraise Client init exception
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/worker.py
Labels: backport-11.3

#3064 NAS-101816 / 11.3 / Generate SSL certs after signing cert
  src/middlewared/middlewared/plugins/crypto.py
Labels: jira

#3067 NAS-101808 / 11.2 / fix(middlewared/sysdataset): set update=True
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-11.1

#3072 NAS-101821 / 11.2 / Do not report transport-related errors when running alerts on backup …
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3063 NAS-101798 / 11.2 / Use onerestart for smartd because on TN HA smart_daemon_enable is not set
  gui/storage/forms.py
  gui/tasks/models.py
Labels: backport-11.3

#3080 NAS-101753 / 11.2 / Fix sending hardware alerts to iX
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3086 NAS-101825 / 11.2 / Make Volume Rekey Alert worth reporting to iX as it was in 11.1
  src/middlewared/middlewared/alert/source/volume_rekey.py
Labels: backport-11.3

#3085 NAS-101863 / 11.2 / Set up NFSv4 properly
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/service.py
Labels: backport-11.3

#3071 NAS-101675 / 11.2 / Generate an alert when creating a new ticket for TrueNAS proactive al…
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3

#3093 NAS-101880 / 11.3 / Move replication logging to /var/log/zettarepl.log
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: jira

#2971 NAS-101588 / 11.2 / Respect alert service enabled field
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-11.3, backported

#3099 NAS-101244 / 11.2 / Point to System version documentation
  gui/freeadmin/site.py
  gui/templates/freeadmin/index.html
Labels: backport-11.1, backport-11.3

#3069 NAS-101826 / 11.2 / Do not crash autorepl.py on misconfigured SSH connection
  gui/tools/autorepl.py
Labels: backport-11.3

#3054 NAS-101778 / 11.2 / Allow getting disktemp for non-fatal smartctl exit statuses
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
Labels: backport-11.3, backported, jira

#3065 NAS-101818 / 11.2 / Stop granting privileges to local users in standalone servers
  src/freenas/usr/local/libexec/nas/generate_smb4_conf.py
Labels: backport-11.1

#3112 NAS-101926 / 11.3 / Bug fixes for rsync
  src/middlewared/middlewared/plugins/rsync.py
Labels: jira

#3113 NAS-101787 / 11.2 / Event loop blocked
  src/middlewared/middlewared/main.py
Labels: backport-11.3

#3102 NAS-101525 / 11.3 / Improve fstab validation
  src/middlewared/middlewared/plugins/jail.py
Labels: backport-11.2

#3121 NAS-101823 / 11.2 / Fix Alert Services tab glitch
  gui/system/forms.py
Labels: backport-11.3
