Repository truenas/middleware, pull requests merged in 2020-09, with the labels that each got.

#5584 NAS-107424 / 12.1 / Fix ssh releated tests for pytest dependency
  tests/api2/test_260_iscsi.py
  tests/api2/test_400_service.py
  tests/api2/test_490_system_general.py
  tests/api2/test_700_host_key.py
Labels: jira

#5585 NAS-107425 / 20.10 / Fix SMB share bind ip check
  src/middlewared/middlewared/etc_files/local/smb4.conf.mako
Labels: backport-12.0, jira

#5591 NAS-107438 / 11.3 / Reintroduce special behavior for HOMES path
  src/middlewared/middlewared/etc_files/local/smb4_share.conf
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, backport-20.10, jira

#5590 NAS-107432 / 12.1 / disable offload capabilitie in interface test for core only
  tests/api2/test_005_interface.py
Labels: backport-11.3, backport-12.0, jira

#5586 NAS-107427 / 12.0 / fix traceback when sync'ing zfs guids
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-20.10, jira

#5600 NAS-107441 / 20.10 / Adding scale in to test_700_host_key.py pytestmark skipif
  tests/api2/test_700_host_key.py
Labels: jira

#5602 NAS-107444 / 20.10 / NAS-107444 - Updates TC stats binary, which fixes some issues with NFS /
  nas_ports/freenas/tc-stats/Makefile
  nas_ports/freenas/tc-stats/distinfo
Labels: backport-12.0

#5598 NAS-107418 / 12.0 / proper validation on excluded disks in fenced
  src/fenced/fenced/fence.py
Labels: backport-20.10

#5592 NAS-107437 / 11.3 / Expand validation for user home directories
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0, backport-20.10, jira

#5607 NAS-107446 / 12.0 / Raise ExcludeDiskError properly in fenced
  src/fenced/fenced/fence.py
Labels: backport-20.10, jira

#5599 NAS-107440 / 12.1 / 20.10 / Changing network test 03 to more automated and to not rely on config
  tests/api2/test_003_network.py
Labels: backport-11.3, backport-12.0, jira

#5614 NAS-107415 / 20.10 / Improve VolumeVersionAlertSource
  src/middlewared/middlewared/alert/source/volume_version.py
Labels: backport-12.0

#5617 NAS-107466 / 20.10 / Allow exporting encryption key for single dataset
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0, jira

#5619 NAS-107467 / 20.10 / optimize system.info
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/plugins/ups.py
Labels: jira

#5620 NAS-107469 / 20.10 / Fix disk.sync_zfs_guid stack traces
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-12.0, jira

#5589 NAS-107431 / 20.10 / Ensure stub smb4.conf always exists
  src/freenas/usr/local/etc/smb4.conf
  src/middlewared/middlewared/plugins/etc.py
Labels: backport-12.0, jira

#5601 NAS-107445 / 12.0 / Remove unprotected setfacl / chmod call
  src/middlewared/middlewared/plugins/account.py
Labels: backport-20.10, jira

#5622 NAS-106110 / 20.10 / Donot raise UPS alert during self test
  src/middlewared/middlewared/plugins/ups.py
Labels: backport-11.3, backport-12.0

#5629 NAS-107488 / 20.10 / remove duplicate nfsstat calls in freenas-debug
  src/freenas/usr/local/libexec/freenas-debug/nfs_freebsd/nfs.sh
Labels: backport-12.1, jira

#5633 NAS-107493 / 20.10 / Do not try to automatically create swap on MINIs
  src/freenas-installer/etc/install.sh
Labels: backport-12.0

#5632 Accept TRUENAS-MINI as well as FREENAS-MINI for enclosure
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
Labels: backport-12.0

#5639 NAS-107479 / 11.3 / Account that, for some reason, some RAID cards that are flashed to IT…
  src/middlewared/middlewared/common/smart/smartctl.py
Labels: backport-12.0, backport-20.10

#5637 NAS-107503 / 20.10 / Allow keytab setup through NFS plugin
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/nfs_/krb5.py
Labels: backport-12.0, jira

#5636 NAS-107501 / 20.10 / Fix pdbedit parsing when SMB service aux param invalid
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: backport-11.3, backport-12.0, jira

#5643 NAS-107506 / 11.3 / correctly reload resolvconf when updating search domains
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0, backport-20.10

#5646 NAS-107504 / 11.3 / Fix update.destroy_upload_location
  src/middlewared/middlewared/plugins/update.py
Labels: backport-12.0, backport-20.10

#5651 NAS-107492 / 20.10 / Do not blacklist SGPIO for MINIs
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-12.0

#5654 NAS-107518 / 20.10 / Add service announcements to rc.conf.py
  src/middlewared/middlewared/etc_files/rc.conf.py
Labels: backport-12.0, jira

#5655 NAS-107519 / 20.10 / Prevent middleware from killing itself
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-12.0, jira

#5659 NAS-107505 / 12.0 / Unlock replication tasks on failover pool import
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-20.10

#5660 NAS-107519 / 12.0 / Prevent middleware from killing itself (by anodos325)
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-20.10

#5653 NAS-107517 / 20.10 / Setup default storage class for k8s
  src/middlewared/middlewared/etc_files/docker.py
  src/middlewared/middlewared/plugins/device_/gpu_linux.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/api_client.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/storage_classes.py
Labels: jira, pending QA

#5663 NAS-107521 / 20.10 / multiple fixes for network general validation
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#5667 NAS-107553 / 20.10 / Fix regression introduced for configuring interfaces
  src/middlewared/middlewared/plugins/interface/configure.py
Labels: jira

#5668 NAS-107561 / 20.10 / Do not use alias for interface namespace
  src/middlewared/middlewared/etc_files/pf.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira

#5669 NAS-107526 / 20.10 / Do not run camcontrol reprobe for NVMe
  src/middlewared/middlewared/plugins/pool_/expand.py
Labels: backport-12.0

#5673 NAS-107588 / 20.10 / Comment inexistent sysctls for resilver priority
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#5681 NAS-107348 / 12.0 / Cache pwenc secret
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: backport-20.10

#5684 NAS-107618 / 11.3 / freenas-debug: replace pdbedit with smb.passdb_list
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: backport-12.0, backport-20.10, jira

#5682 NAS-107516 / 11.3 / S3 max_upload_parts
  src/middlewared/middlewared/rclone/remote/s3.py
Labels: backport-12.0, backport-20.10

#5691 NAS-107610 / 11.3 / Fix HA network validation
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0, backport-20.10

#5688 NAS-107617 / 12.0 / Enforce 1GiB limit on cores dataset
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-20.10

#5698 NAS-107587 / 20.10 / Bug fix for SSH key pair validation
  src/middlewared/middlewared/plugins/keychain.py
Labels: backport-11.3, backport-12.0

#5702 NAS-107650 / 12.0 / Fix TypeError: 'NoneType' object is not subscriptable
  src/middlewared/middlewared/plugins/disk_/encryption_freebsd.py
  src/middlewared/middlewared/plugins/disk_/identify_freebsd.py
Labels: backport-20.10, jira

#5564 NAS-107382 / 20.10 / Add support for kubernetes
  debian/debian/postinst
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
  src/freenas/usr/local/libexec/freenas-debug/kubernetes_linux/kubernetes.sh
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
  src/middlewared/debian/control
  src/middlewared/middlewared/alembic/versions/12.1/2020-08-24_14-32_kubernetes_support.py
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/applications_linux.py
  src/middlewared/middlewared/etc_files/cni/kube-router.py
  src/middlewared/middlewared/etc_files/cni/multus.py
  src/middlewared/middlewared/etc_files/cni/net.d/kube-router.d/kubeconfig.mako
  src/middlewared/middlewared/etc_files/cni/net.d/multus.d/multus.kubeconfig.mako
  src/middlewared/middlewared/etc_files/docker.py
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
  src/middlewared/middlewared/etc_files/systemd/system/docker.service.d/http-proxy.conf.mako
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/plugins/docker_linux/__init__.py
  src/middlewared/middlewared/plugins/docker_linux/images.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/interface/info_base.py
  src/middlewared/middlewared/plugins/interface/info_freebsd.py
  src/middlewared/middlewared/plugins/interface/info_linux.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/routing.py
  src/middlewared/middlewared/plugins/kubernetes_linux/__init__.py
  src/middlewared/middlewared/plugins/kubernetes_linux/attachments.py
  src/middlewared/middlewared/plugins/kubernetes_linux/cni.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/__init__.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/api_client.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/nodes.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/service_accounts.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/utils.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
  src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/docker.py
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
  src/middlewared/middlewared/plugins/service_/services/kuberouter.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#5623 NAS-107471 / 20.10 / Add support for managing docker images
  src/middlewared/debian/control
  src/middlewared/middlewared/etc_files/docker.py
  src/middlewared/middlewared/plugins/device.py
  src/middlewared/middlewared/plugins/device_/device_info_base.py
  src/middlewared/middlewared/plugins/device_/device_info_freebsd.py
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
  src/middlewared/middlewared/plugins/docker_linux/images.py
  src/middlewared/middlewared/plugins/kubernetes_linux/daemonset.py
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/api_client.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/storage_classes.py
Labels: pending QA

#5678 NAS-107595 / 20.10 / Add interfaces to reporting.realtime subscription
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira

#5706 NAS-107666 / 20.10 / Retrieve internally logged zfs events with user initiated events in debug
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: backport-11.3, backport-12.0, jira

#5713 NAS-107684 / 20.10 / Remove random sleeps in k8s lifecycle management
  src/middlewared/middlewared/plugins/interface/netif_linux/netif.py
  src/middlewared/middlewared/plugins/interface/type_linux.py
  src/middlewared/middlewared/plugins/kubernetes_linux/cni.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
Labels: jira

#5716 NAS-107716 / 20.10 / Add truenas-samba
  debian/debian/control
  src/middlewared/debian/control
  src/middlewared/middlewared/etc_files/local/smb4.conf.mako
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#5721 NAS-107726 / 12.0 / Fix iscsi.auth.is_in_use_by_portals_targets
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-20.10, jira

#5722 NAS-107523 / 12.0 / Properly handle invalid datasets in zettarepl.list_datasets
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-20.10

#5723 NAS-107728 / 12.0 / Fix rcorder
  src/freenas/etc/ix.rc.d/ix-bsdloader
  src/freenas/etc/ix.rc.d/ix-update
Labels: backport-20.10, jira

#5735 NAS-107747 / 20.10 / open with write bit in scale ha failover plugin
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event_linux.py
Labels: jira

#5734 NAS-107743 / 12.0 / change activedirectory api tests to only change nameserver1
  tests/api2/activedirectory.py
  tests/api2/ad_idmap.py
  tests/api2/ad_kerberos.py
Labels: backport-11.3, backport-12.1, jira

#5733 NAS-107674 / 20.10 / Less garbage in logs when hardware faults lead to disk.temperatures timeout
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
  src/middlewared/middlewared/plugins/disk_/temperature.py
Labels: backport-11.3, backport-12.0
