Repository truenas/middleware, pull requests merged in 2020-07, with the labels that each got.

#5050 NAS-106330 / 12.1 / Specify separate endpoint for VM console
  src/middlewared/middlewared/main.py
Labels: backport-12.0

#5078 NAS-106640 / 12.1 / Do not update grub on first boot when system is ready
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#5083 NAS-106642 / 11.3 / Fix TN HA NFS config validation
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-12.0, backport-12.1, jira

#5089 NAS-106569 / 12.1 / SCALE static route
  src/middlewared/middlewared/plugins/interface/netif_linux/routing.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: backport-12.0

#5094 NAS-106636 / 11.3 / Allow importing 9.x configs
  src/middlewared/middlewared/plugins/config.py
Labels: backport-12.0, backport-12.1

#5084 NAS-106648 / 12.1 / Make registry configuration aware of locked datasets
  src/middlewared/middlewared/etc_files/local/smb4_share_load.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5076 NAS-106638 / 12.1 / Fix regression in winacl's chown()
  src/middlewared/middlewared/plugins/filesystem.py
  src/winacl/winacl.c
Labels: backport-12.0, jira

#5010 NAS-106520 / 12.1 / fix product_type on bhyve vms
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_enclosure_freebsd.py
Labels: pending QA

#5108 NAS-106688 / 12.1 / Fix validation check for user quotas
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0, jira

#5110 NAS-106686 / 12.1 / Fix middleware chroot behavior for permissions change
  src/middlewared/middlewared/plugins/filesystem.py
  src/winacl/winacl.c
Labels: backport-12.0

#5111 NAS-106692 / 12.1 / Fix VM console command
  src/middlewared/middlewared/main.py
Labels: backport-12.0, jira

#5114 NAS-106693 / 12.1 / Only map partitions which have valid partition uuid
  src/middlewared/middlewared/plugins/zfs_/disks_linux.py
Labels: jira

#5077 NAS-106639 / 12.1 / Fix traceback in ldap.conf generation script when AD enabled
  src/middlewared/middlewared/etc_files/local/openldap/ldap.conf
Labels: backport-12.0, jira

#5119 NAS-106697 / 12.1 / We'll have to replicate system dataset if we want full replication
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-12.0, jira

#5121 NAS-106004 / 11.3 / Fix order for ix-sed
  src/freenas/etc/ix.rc.d/ix-sed
Labels: backport-12.0, backport-12.1

#5124 NAS-106703 / 12.1 / Ensure that permissions for tmp are correct during smb.configure
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, jira

#5129 NAS-106705 / 11.3 / Reset SMB HA mode prior to starting AD join job
  src/middlewared/middlewared/etc_files/smb_configure.py
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-12.0, backport-12.1

#5132 NAS-106714 / 12.1 / correctly generate critical interfaces in failover.json
  src/middlewared/middlewared/etc_files/failover.py
Labels: backport-12.0

#5128 Update migrate113 port
  nas_ports/freenas/freenas-migrate113/Makefile
  nas_ports/freenas/freenas-migrate113/distinfo
Labels: backport-12.0

#5127 NAS-106707 / 12.1 / falover -> failover
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5136 NAS-106717 / 12.0 / Disable auto-rollback for vfs_tmprotect
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#5137 NAS-106721 / 12.1 / sync db after deletion of interface on HA systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5138 NAS-106651 / 12.1 / configure advskew for CARP on HA systems correctly
  src/middlewared/middlewared/plugins/interface/configure.py
Labels: backport-12.0

#5104 NAS-106683 / 12.1 / Use correct rsync path for SCALE
  src/middlewared/middlewared/plugins/rsync.py
Labels: jira

#5145 NAS-106723 / 12.1 / ensure CARP password exists when creating aliases
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#5143 NAS-106685 / 11.3 / Double-check the return value of disk.identifier_to_device in disk.sync_all
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0

#5148 NAS-106734 / 12.1 / fix API on SCALE for adding network
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#5147 NAS-106685 / 12.0 / Double-check the return value of disk.identifier_to_device in disk.sync_all (by themylogin)
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-12.1

#5142 NAS-106726 / 12.1 / Donot collect jails/plugins usage in SCALE
  src/middlewared/middlewared/plugins/usage.py
Labels: jira

#5161 NAS-106748 / 12.1 / Use path_is_encrypted endpoint for determining if a path uses locked dataset
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0

#5149 NAS-106735 / 12.1 / Add support for nested VM's in SCALE
  src/middlewared/middlewared/alembic/versions/12.1/2020-07-09_16-11_vm_cpu_controls.py
  src/middlewared/middlewared/plugins/vm/info_linux.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_linux.py
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#5166 NAS-106773 / 12.1 / Host guest configuration for KVM guests
  src/middlewared/middlewared/plugins/vm/devices/nic.py
Labels: jira

#5176 NAS-106783 / 12.1 / Change default hostname to truenas
  src/freenas/etc/rc.conf
Labels: backport-12.0, jira

#5182 NAS-106764 / 12.1 / Fix SNMP agent not starting on FreeBSD
  src/freenas/usr/local/etc/rc.d/snmp-agent
Labels: backport-12.0

#5179 NAS-106784 / 12.1 / Make SAN required for certificates
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-12.0

#5188 NAS-106794 / 12.1 / write_if_changed may block the event loop as it does sync file ops
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#5189 NAS-106796 / 12.1 / Unlock encrypted datasets when initialising KMIP keys
  src/middlewared/middlewared/plugins/kmip/__init__.py
  src/middlewared/middlewared/plugins/kmip/zfs_keys.py
Labels: backport-12.0, jira, pending QA

#5153 NAS-106732 / 12.1 / fix adding/deleting aliases on HA systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5184 NAS-106795 / 12.0 / Modify migration to simplified SMB configuration setup
  src/middlewared/middlewared/alembic/versions/12.0/2020-01-23_10-22_simplify_smb_shares.py
Labels: backport-12.1, jira

#5157 NAS-106713 / 12.0 / Prevent queued and then disabled cron tasks from executing. (by themylogin)
  src/middlewared/middlewared/etc_files/cron.d/middlewared
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-12.1

#5196 NAS-106754 / 12.1 / Generate encrypt key path when importing geli encrypted pools
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#5201 NAS-106807 / 12.1 / Cover rm -rfx usages in scale to use --one-file-system
  src/middlewared/middlewared/plugins/reporting/configure.py
  src/middlewared/middlewared/plugins/reporting/update.py
Labels: jira

#5202 NAS-106808 / 12.1 / Ensure monpwd/monuser fields are provided for UPS service
  src/middlewared/middlewared/plugins/ups.py
Labels: backport-11.3, backport-12.0, jira

#5200 NAS-106806 / 12.1 / treat CARP NONE state as INIT
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_virtual_ips_freebsd.py
Labels: backport-12.0

#5209 NAS-106812 / 12.1 / Make retrieving cert extensions non-fatal
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-11.3, backport-12.0

#5181 NAS-106719 / 12.1 / Terminate orphaned multiprocessing bits
  src/middlewared/middlewared/main.py
Labels: backport-12.0

#5208 NAS-106333 / 12.1 / make sync_internal_ip method work on SCALE
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_internal_interface_freebsd.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_internal_interface_linux.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/internal_interface_freebsd.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/internal_interface_linux.py
Labels: backport-12.0

#5216 NAS-106827 / 12.0 / Remove extra debug statements from directory service refresh
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.1, jira

#5218 NAS-106833 / 12.1 / Scale SMB - override build options for statedir and private dir
  src/middlewared/middlewared/etc_files/local/smb4.conf
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#5221 NAS-106840 / 12.1 / prevent invalid VHIDs
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.3, backport-12.0

#5220 NAS-106843 / 12.1 / FC ports in target mode by default
  src/freenas/boot/loader.conf
Labels: backport-12.0

#5229 NAS-106858 / 12.1 / Clarify bootloader options to be more verbose
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#5226 NAS-106798 / 12.1 / Allow lunid to be null on creation
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-11.3, backport-12.0

#5219 NAS-106828 / 12.1 / fix CARP on vlan creation
  src/middlewared/middlewared/plugins/interface/vlan.py
Labels: backport-11.3, backport-12.0

#5238 NAS-106871 / 12.0 / Fix migrations state
  src/middlewared/middlewared/alembic/versions/12.0/2020-07-21_13-53_fix_migrations_state.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.1, jira

#5244 NAS-106866 / 12.1 / Better errno for expected replication errors
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-11.3, backport-12.0

#5243 NAS-102808 / 12.1 / Abort cloudsync task on deletion
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-11.3, backport-12.0

#5241 NAS-106878 / 12.1 / exclude nvme boot drives from fenced on freeBSD
  src/fenced/fenced/exceptions.py
  src/fenced/fenced/fence.py
  src/fenced/fenced/main.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/fenced_force_freebsd.py
Labels: backport-12.0

#5255 NAS-106891 / 12.1 / fix LicenseStatus alert on SCALE
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
Labels: jira

#5258 NAS-106893 / 12.1 / run LicenseStatus on ENTERPRISE and SCALE_ENTERPRISE
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
Labels: jira

#5254 NAS-106889 / 12.0 / dont update encryption keys unless we have an encrypted zpool
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-12.1

#5261 NAS-106901 / 12.1 / Use tmpfs for /tmp
  src/freenas/etc/systemd/system/tmp.mount
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
Labels: jira

#5262 NAS-106902 / 12.1 / VM libvirt connection improvements
  src/middlewared/middlewared/plugins/vm/connection.py
  src/middlewared/middlewared/plugins/vm/events.py
  src/middlewared/middlewared/plugins/vm/lifecycle.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
  src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#5267 NAS-106887 / 12.1 / sysctl must run before ix-netif on HA
  src/freenas/etc/ix.rc.d/ix-netif
Labels: backport-12.0

#5266 NAS-106883 / 12.0 / Enable autotune on ENTERPRISE install / license entry
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.1

#5268 NAS-106912 / 12.1 / Make sure ix-shutdown is not stopped after middlewared
  debian/debian/ix-shutdown.service
Labels: jira

#5277 NAS-106923 / 12.1 / fix sync'ing of encryption keys (if any) on 12 HA
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/failover.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-12.0, pending QA

#5276 NAS-106921 / 11.3 / Expand ACL testing regimen
  tests/api2/acl.py
Labels: backport-12.0, backport-12.1, jira

#5282 NAS-106953 / 12.1 / Improve validation for SMB service and shares
  src/middlewared/middlewared/etc_files/local/smb4_share.conf
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5287 NAS-106963 / 12.1 / Address race in unlocking SMB shares
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0

#5291 NAS-106978 / 12.0 / Add regression tests for AD machine account keytab generation
  tests/api2/activedirectory.py
Labels: backport-11.3, backport-12.1, jira

#5297 NAS-106986 / 12.0 / Add regression tests for SMB registry configuration
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/smb_registry.py
Labels: backport-12.1, jira

#5299 NAS-106993 / 12.1 / Reassign sys.{stdout,stderr} after log rollover
  src/middlewared/middlewared/logger.py
Labels: backport-11.3, backport-12.0, jira

#5295 NAS-106960 / 12.0 / Do not restart ctld on BACKUP -> MASTER
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: WIP, backport-12.1

#5307 QE-372 / 11.3 / fix cloudsync API test 06
  tests/api2/cloudsync.py
  tests/runtest.py
Labels: backport-12.0, backported

#5311 NAS-106983 / 12.1 / Fix col IN(NULL) filter
  src/middlewared/middlewared/plugins/datastore/connection.py
  src/middlewared/middlewared/plugins/datastore/filter.py
  src/middlewared/middlewared/pytest/unit/helpers.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
Labels: backport-12.0

#5314 NAS-107012 / 12.1 / Omit debug botocore module log
  src/middlewared/middlewared/logger.py
Labels: backport-12.0, jira

#5315 NAS-107013 / 12.1 / Leftover debug message for acltype
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0, jira

#5298 NAS-106991 / 12.1 / Reduce SMB-related log entries
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5316 NAS-106946 / 12.1 / Multiple idmap generation and validation fixes
  src/middlewared/middlewared/etc_files/local/smb4.conf
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-12.0

#5322 NAS-107009 / 12.1 / Restore /etc/ix.rc.d/ix_sshd_save_keys
  debian/debian/ix-ssh-keys.service
  src/freenas/etc/ix.rc.d/ix_sshd_save_keys
Labels: backport-12.0

#5326 NAS-107019 / 11.3 / Fix issue with AD machine account keytab storage on HA platform
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#5325 Update idmap certificate tests for API change
  tests/api2/test_110_certificate.py
  tests/api2/test_230_idmap.py
Labels: backport-12.0

#5327 Make failover faster by not doing failover.status_refresh when it's not necessary
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-12.0

#5313 NAS-107011 / 12.0 / Add idmap regression tests for AD environments
  tests/api2/ad_idmap.py
Labels: backport-12.1, jira

#5332 Fix merging of aux param overrides of krb5.conf values
  src/middlewared/middlewared/etc_files/krb5.conf
  src/middlewared/middlewared/plugins/kerberos.py
Labels: backport-11.3, backport-12.0

#5333 NAS-107023 / 12.1 / Expand list of error strings that should trigger an AD rejoin
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-11.3, backport-12.0, jira
