Repository truenas/middleware, pull requests merged in 2020-12, with the labels that each got.

#6089 NAS-108498 / 20.12 / Use TrueNAS instead of FreeNAS in api docs
  src/middlewared/middlewared/apidocs/templates/index.html
  src/middlewared/middlewared/apidocs/templates/restful.html
  src/middlewared/middlewared/apidocs/templates/websocket.html
  src/middlewared/middlewared/apidocs/templates/websocket/jobs.md
  src/middlewared/middlewared/apidocs/templates/websocket/protocol.md
  src/middlewared/middlewared/restful.py
Labels: backport-12.0, jira

#6092 NAS-108497 / 12.0 / Delay GMail initialization
  src/middlewared/middlewared/plugins/mail_/gmail.py
Labels: backport-20.12

#6095 NAS-108511 / 20.12 / Update Text Strings
  src/middlewared/middlewared/alert/source/freenas_bmc.py
Labels: backport-12.0

#6097 NAS-108485 / 12.0 / Fix replication key-format
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-20.12

#6099 NAS-108524 / 12.0 / Bump up AIO values for Samba
  src/freenas/etc/sysctl.conf.local
Labels: jira

#6105 NAS-108527 / 12.0 / Changed sleep from 2 to 5 to prevent failure due to ldap latency in ldap API testing
  tests/api2/ldap.py
Labels: backport-20.12, jira

#5814 NAS-107925 / 20.12 / Prevent system dataset changes while AD is enabled
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-11.3, backport-12.0, jira

#6118 NAS-108564 / 20.12 / Fix user shell for scale in test 21 of test_345_acl_nfs4.py
  tests/api2/test_345_acl_nfs4.py
Labels: jira

#6059 NAS-108379 / 12.0 / Proper autotrim for inaccessible pool
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-20.12, backported, jira

#6074 NAS-108320 / 12.0 / Create hint.isp.{i}.role=2 tunables on non-iX hardware
  nas_ports/freenas/freenas-files/files/pkg-install.in
  src/middlewared/middlewared/plugins/sysctl/hint_isp_role_freebsd.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-20.12

#6100 NAS-108206 / 12.0 / netcli: only show login banner if we are a child of init
  src/freenas/etc/netcli
Labels: backport-20.12

#6101 NAS-108423 / 12.0 / Properly handle inaccessible pools and unused CPUs
  src/middlewared/middlewared/alert/source/volume_status.py
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: backport-20.12, backported

#6103 NAS-108520 / 12.0 / Do not release SQLite lock between `INSERT` and `SELECT last_insert_rowid()`
  src/middlewared/middlewared/plugins/datastore/connection.py
  src/middlewared/middlewared/plugins/datastore/write.py
Labels: backport-20.12, backported

#6108 NAS-107395 / 12.0 / Implement smart.test.disk_choices to remove NVMe disks
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-20.12

#6110 NAS-108371 / 12.0 / Avoid ZeroDivisionError when zettarepl is reporting incorrect bytes_total
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-20.12

#6130 NAS-108601 / 20.12 / minor tweaks to HA setup method and sync ssh state to standby on HA setup
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#6132 NAS-108611 / 12.0 / Move aio_fbsd to end of list of VFS modules
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#6135 NAS-108555 / 12.0 / Do not show alerts with frequency=NEVER
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-20.12

#6140 NAS-107421 / 12.0 / Always have empty /etc/zfs/exports
  src/freenas/etc/zfs/exports
Labels: backport-20.12

#6142 NAS-108619 / 20.12 / Bye Travis, Hi PEP8 Speaks
  .pep8speaks.yml
  .travis.yml
  .travis/flake8.sh
Labels: jira

#6147 NAS-108525 / 12.0 / Properly check if a jail exists
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-20.12

#6146 NAS-108636 / 20.12 / Add context to helm values
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
Labels: jira

#6159 NAS-108658 / 20.12 / Fix logging when failing to add SMB share
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#6157 NAS-108623 / 20.12 / FIx crash when trying to offline a faulted drive
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#6111 NAS-108551 / 20.12 / Changes for handling catalog items schema
  src/middlewared/middlewared/plugins/catalogs_linux/features.py
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
  src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
  src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
  src/middlewared/middlewared/plugins/docker_linux/images.py
  src/middlewared/middlewared/plugins/docker_linux/update_alerts.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/schema.py
Labels: jira

#6166 NAS-108678 / 12.0 / Fix possibility for middleware plugin to leak passwords to debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/vmware.py
  src/middlewared/middlewared/service.py
Labels: backport-20.12

#6168 NAS-108678 / 12.0 / Partially revert "Fix possibility for middleware plugin to leak passw…
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/vmware.py
  src/middlewared/middlewared/service.py
Labels: backport-20.12

#6171 NAS-108560 / 20.12 / Fix zfs-zed
  debian/debian/postinst
Labels: skip jira status

#6170 NAS-108659 / 12.0 / fix loader.conf.local being lost on upgrade
  nas_ports/freenas/freenas-files/files/pkg-install.in
  src/freenas/etc/ix.rc.d/ix-update
  src/middlewared/middlewared/etc_files/loader.py
Labels: backport-20.12

#6173 NAS-108609 / 12.0 / Do not use fake serial numbers for multipath
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-20.12

#6177 NAS-105062 / 12.0 / Allow empty specific attributes for NIC (by william-gr)
  src/middlewared/middlewared/plugins/network.py
Labels: skip jira status

#6179 NAS-108714 / 20.12 / installer: Clarify preferred media for install
  src/freenas-installer/etc/install.sh
Labels: backport-12.0, jira

#6183 NAS-108675 / 12.0 / Bug fix for plugin update
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-20.12

#6184 NAS-108724 / 21.02 / if serial input is enabled, read the input buffer to clear any garbage
  src/freenas/etc/grub.d/10_truenas_linux
Labels: jira

#6165 NAS-108624 / 21.02 / Handle race condition when retrieving data from netif
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#6163 NAS-108662 / 21.02 / Bug fix for ip_in_use endpoint
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#6162 NAS-108512 / 21.02 / Do not start a VM which has unavailable resources
  src/middlewared/middlewared/plugins/vm/devices/cdrom.py
  src/middlewared/middlewared/plugins/vm/devices/device.py
  src/middlewared/middlewared/plugins/vm/devices/nic.py
  src/middlewared/middlewared/plugins/vm/devices/pci.py
  src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
  src/middlewared/middlewared/plugins/vm/devices/vnc.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
Labels: backport-12.0, backported

#6174 NAS-108685 / 21.02 / Fix traceback trying to export an offline pool
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-12.0

#6160 NAS-108613 / 21.02 / Fix parsing smartctl time output
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-12.0

#6116 NAS-108537 / 21.02 / Revise collectd df plugin configuration
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
Labels: backport-12.0

#6115 NAS-107341 / 21.02 / Use collectd patches
  src/middlewared/middlewared/plugins/reporting/plugins.py
Labels: backport-12.0

#6181 NAS-108720 / 21.02 / Do not background Samba path creation during sysdataset setup
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-12.0, jira

#6188 NAS-108738 / 21.02 / Add method to retrieve vnet_default_interface choices
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-12.0, jira

#6194 NAS-108671 / 21.02 / ignore proxy when sending file to standby node across heartbeat
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/remote.py
Labels: backport-12.0

#6175 NAS-105062 / 21.02 / Allow empty specific attributes for NIC
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0, backported, skip jira status

#6198 NAS-108765 / 21.02 / CTDB_VOL_name.value -> CTDB_VOL_NAME.value
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#6201 NAS-108746 / 12.0 / Do not blame all debug faults on "81.00% (Dump ZFS Configuration)"
  src/freenas/usr/local/bin/ixdiagnose
Labels: backport-21.02, skip jira status

#6203 NAS-108780 / 21.02 / use libsgio to get rotation rate instead of subprocess
  src/middlewared/debian/control
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
Labels: jira

#6133 NAS-108479 / 20.12 / Expand verbosity of AD health error messages
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-12.0
