Repository truenas/middleware, pull requests merged in 2020-06, with the labels that each got.

#4866 NAS-106291 / 12.0 / Add winacl action to allow restoring ACL from another path
  src/winacl/Makefile
  src/winacl/winacl.c
Labels: backport-11.3, jira

#4880 NAS-106349 / 12.0 / Add initial POSIX1e ACL support to middleware
  debian/debian/control
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#4885 NAS-106306 / 12.0 / Make sure MTU is properly configured at boot for interfaces
  src/middlewared/middlewared/plugins/interface/bridge.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.3, pending QA

#4890 NAS-106316 / 12.0 / Make sure HOME env variable is set correctly when setting user context
  src/middlewared/middlewared/utils/osc/freebsd/user_context.py
Labels: backport-11.3

#4883 NAS-106150 / 12.0 / Bug fixes for swap devices configuration
  src/middlewared/middlewared/plugins/disk_/disk_events.py
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
  src/middlewared/middlewared/plugins/disk_/swap_remove.py
  src/middlewared/middlewared/plugins/disk_/wipe.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
  src/middlewared/middlewared/pytest/functional/test_0025_disk.py
  src/middlewared/middlewared/service.py
Labels: backport-11.3

#4405 NAS-105030 / 11.3 / Fix exporting pool with iSCSI shares
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-12.0

#4725 NAS-106016 / 11.3 / Add used/available properties in pool.dataset.query output
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#4774 NAS-106112 / 11.3 / Re-synchronize passdb after disabling LDAP service
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, jira

#4793 NAS-106139 / 11.3 / restrict ntpd traffic to configured servers
  src/middlewared/middlewared/etc_files/ntp.conf
Labels: backport-12.0

#4798 NAS-105468 / 11.3 / Remove replication dedup option
  gui/freeadmin/static/lib/js/freeadmin.js
  gui/storage/admin.py
  gui/storage/forms.py
  gui/storage/migrations/0024_auto_20200518_0616.py
  gui/storage/models.py
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/zettarepl.py
  tests/api2/replication.py
Labels: backport-12.0, backported

#4831 NAS-106195 / 11.3 / Do not include root_folder_id if team_drive is present
  src/middlewared/middlewared/rclone/remote/google_drive.py
Labels: backport-12.0

#4835 NAS-106199 / 11.3 / Use `service routing restart` instead of start
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/service.py
Labels: backport-12.0

#4845 NAS-105943 / 11.3 / disk.sync_all improvements
  src/freenas/etc/ix.rc.d/ix-syncdisks
  src/freenas/etc/rc.d/devd
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/device.py
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0

#4850 NAS-106239 / 11.3 / Do not remove automatically configured IPv6 default gateway
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#4892 NAS-106261 / 11.3 / Decrypt filenames in cloudsync.list_directory
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-12.0, backported

#4931 NAS-106448 / 12.0 / Reload systemd daemon after enabling/disabling services
  src/middlewared/middlewared/etc_files/systemd.py
Labels: jira

#4934 NAS-106454 / 11.3 / Fix savecore error logging
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0, jira

#4937 NAS-106459 / 12.0 / Enable crash/usage for all products
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.3, jira

#4941 NAS-106467 / 12.0 / Introduce preset file for TN package in SCALE
  debian/debian/ix-ssh-keys.service
  debian/debian/postinst
  src/freenas/debian/rules
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
  src/middlewared/middlewared/etc_files/systemd.py
Labels: jira

#4944 NAS-106477 / 12.0 / Use correct prefix in clearing pending sed keys for KMIP
  src/middlewared/middlewared/plugins/kmip/sed_keys.py
Labels: jira

#4946 NAS-106461 / 11.3 / Prevent duplicate IP addresses in NFS export from causing issues. Hel…
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-12.0

#4945 NAS-106456 / 12.0 / Escape spaces in S3 storage paths
  src/middlewared/middlewared/etc_files/rc.conf.py
Labels: backport-11.3

#4943 NAS-106474 / 12.0 / Make sure sysctl keys/values are in sync with reality for tunable plugin
  src/middlewared/middlewared/plugins/tunables.py
Labels: jira

#4959 NAS-106336 / 11.3 / loosen restrictions on network config for HA
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#4968 NAS-106501 / 12.0 / AD: catch and log JSON errors on winbind status pipe
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-11.3, jira

#4972 NAS-106505 / 12.0 / AD: split messages from wb_fifo on newline
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-11.3, jira

#4969 NAS-106511 / 12.0 / asyncio/thread pool/process pool juggling improvements
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/utils/service/__init__.py
  src/middlewared/middlewared/utils/service/call.py
  src/middlewared/middlewared/worker.py
Labels: jira

#4974 NAS-106512 / 12.0 / ACLs: fix acl_is_trivial on FreeBSD platform
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira

#4970 NAS-106503 / 12.0 / Add index to FreeNAS-MIB tables.
  src/freenas/usr/local/bin/snmp-agent.py
Labels: backport-11.3

#4980 NAS-106519 / 12.0 / Fix rrdtool path in stats plugin
  src/middlewared/middlewared/plugins/stats.py
Labels: jira

#4994 NAS-104342 / 12.1 / SCALE sensor plugin
  src/freenas/usr/local/lib/middlewared_truenas/plugins/sensor.py
Labels: backport-12.0

#4989 Fix smartd alert on SCALE
  src/middlewared/middlewared/alert/source/smartd.py
  src/middlewared/middlewared/plugins/system_/__init__.py
  src/middlewared/middlewared/plugins/system_/system_freebsd.py
  src/middlewared/middlewared/plugins/system_/system_linux.py
Labels: backport-12.0

#4977 NAS-106482 / 12.1 / nvme reservation support for fenced
  src/fenced/fenced/disks.py
  src/fenced/fenced/exceptions.py
  src/fenced/fenced/fence.py
  src/fenced/fenced/logging.py
  src/fenced/fenced/main.py
Labels: backport-12.0

#4991 NAS-106538 / 12.1 / Expose method to retrieve list of all systemd units
  src/middlewared/middlewared/etc_files/systemd.py
  src/middlewared/middlewared/plugins/config.py
  src/middlewared/middlewared/plugins/service_/systemd_linux.py
Labels: jira

#5002 NAS-106571 / 12.1 / Make sure we move uploaded config to tn db location in scale
  src/freenas/usr/local/sbin/ix-update
Labels: jira

#4986 NAS-106530 / 12.1 / Donot create swap partition for TN enterprise on pool creation
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.3, backport-12.0, jira

#5006 NAS-106575 / 12.1 / Fix 12 config upload
  src/middlewared/middlewared/plugins/config.py
Labels: backport-12.0, jira

#5005 NAS-106574 / 12.1 / Remove exra wait argument from dhclient start
  src/middlewared/middlewared/plugins/interface/configure.py
Labels: backport-12.0, jira

#5016 Do not permit users to set root as a guest account
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-11.3, backport-12.0

#5018 NAS-106585 / 12.1 / use curly brace in f-string enclosure alert
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/enclosure_status.py
Labels: backport-12.0

#5015 NAS-106577 / 11.3 / Re-initialize secrets.tdb in LDAP environments on SMB setup
  src/middlewared/middlewared/etc_files/smb_configure.py
Labels: backport-12.0, backport-12.1

#5013 NAS-106578 / 12.0 / regenerate /tmp/failover.json on pool create or export
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.1

#5022 NAS-106586 / 12.1 / Refresh failover status before starting services after becoming master
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-12.0

#5026 NAS-106558 / 12.1 / fix ALUA on TN HA
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Labels: backport-12.0

#5025 Remove legacy SMB-related items from failover events
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-12.0

#5017 NAS-106582 / 12.1 / allow updating via webUI from master to internal
  src/middlewared/middlewared/plugins/update_/utils.py
Labels: backport-12.0

#5032 NAS-106587 / 12.1 / fix keyerror traceback when disabling wsd
  src/middlewared/middlewared/plugins/service_/services/wsd.py
Labels: backport-12.0

#5033 NAS-106589 / 12.1 / fix(midclt): properly handle job call to show progress and not rewind
  src/middlewared/middlewared/client/utils.py
Labels: backport-12.0, jira

#5037 NAS-106592 / 12.1 / fix disabled_reasons method on TN HA
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5040 NAS-106589 / 12.1 / Fix midclt job with null message
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/client/utils.py
Labels: backport-12.0

#5043 NAS-106599 / 12.1 / Add timeout for ix-etc service
  debian/debian/ix-etc.service
Labels: jira

#5047 NAS-106611 / 12.1 / Don't log libvirt connection failure if there are no vm's
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-12.0, jira

#5052 NAS-106620 / 12.1 / Prevent users from setting user / group quota on id 0
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0, jira

#4993 NAS-106181 / 12.1 / avahi: set "allow-interfaces" to an empty list
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf
Labels: backport-12.0

#5044 NAS-106598 / 12.1 / Correctly generate iSCSI portal ip alert
  src/middlewared/middlewared/alert/source/iscsi_portal_ips.py
Labels: backport-12.0

#5038 NAS-106293 / 12.1 / Add more stats to usage plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-12.0

#5058 NAS-106541 / 11.3 / Ignore rclone output decode errors
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-12.0, backport-12.1

#5049 NAS-106455 / 12.1 / Default to adding client auth to openvpn ca certs
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/vpn.py
Labels: backport-12.0, pending QA

#5055 NAS-106497 / 11.3 / Replication: Does not require unrelated exclude
  src/middlewared/middlewared/plugins/replication.py
  tests/api2/replication.py
Labels: backport-12.0, backport-12.1

#5066 NAS-106554 / 12.1 / Remove duplicate fibrechannel entry in license features
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.3, backport-12.0

#5045 NAS-106601: Don't alert on non-fatal rsync return codes
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-11.3, backport-12.0

#5051 NAS-106613 / 12.1 / Always add server auth extension to default certificate created
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-11.3, backport-12.0, jira
