Repository truenas/middleware, pull requests merged in 2020-08, with the labels that each got.

#5280 NAS-106941 / 12.1 / Fix unlock parent check
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#5331 NAS-104877 / 12.0 / Add regression tests for AD kerberos
  tests/api2/ad_kerberos.py
Labels: backport-11.3, backport-12.1

#5339 NAS-106998 / 12.0 / Fix enclosures on unknown systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-12.1

#5336 NAS-107037 / 11.3 / Have ftp reload method reload proftpd rather than restart it
  src/middlewared/middlewared/plugins/service.py
Labels: backport-12.0, backport-12.1, jira

#5340 NAS-107022 / 12.1 / save failover logs in /root/syslog like 11.3
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/middlewared/middlewared/etc_files/syslogd.py
  src/middlewared/middlewared/logger.py
Labels: backport-12.0

#5348 NAS-106974 / 12.0 / Fix avahi configuration bugs on HA platform
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf
Labels: backport-12.1

#5352 NAS-107031 / 12.1 / Start openvpn server/client services on boot if enabled
  src/middlewared/middlewared/plugins/vpn.py
Labels: backport-12.0

#5360 NAS-107050 / 12.1 / Make sure to auto start jails marked to start at boot on dataset unlock
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-12.0

#5363 NAS-107076 / 12.0 / Expand regression tests for user api
  tests/api2/user.py
Labels: backport-11.3, backport-12.1, jira

#5362 NAS-107074 / 12.1 / Permissions are incorrect on home directory move
  src/middlewared/middlewared/plugins/account.py
Labels: backport-11.3, backport-12.0, jira

#5370 NAS-106777 / 12.1 / install.sh: Fix fresh installs to a BE
  src/freenas-installer/etc/install.sh
Labels: backport-12.0

#5155 NAS-106713 / 11.3 / Prevent queued and then disabled cron tasks from executing.
  src/middlewared/middlewared/etc_files/crontab
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-12.0, backported

#5242 NAS-106864 / 11.3 / NVMe SED support
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0, backport-12.1, backported

#5281 NAS-106948 / 11.3 / Correct typo in vfs_recycle options
  src/middlewared/middlewared/etc_files/local/smb4_share.conf
Labels: backport-12.0, backport-12.1, backported

#5355 NAS-107069 / 11.3 / Symlink /usr/share/skel to /etc/skel in FreeBSD
  src/middlewared/middlewared/etc_files/pam.d/pam.skel_freebsd
Labels: backport-12.0, backport-12.1, backported, jira

#5371 NAS-107032 / 11.3 / Set --b2-upload-cutoff to at least --b2-chunk-size
  src/middlewared/middlewared/rclone/remote/b2.py
Labels: backport-12.0, backport-12.1

#5374 NAS-106966 / 11.3 / Properly format collectd warning alerts
  src/middlewared/middlewared/alert/source/collectd.py
Labels: backport-12.0, backport-12.1, backported

#5377 NAS-107077 / 12.1 / speed up failover when remote node panics
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5366 install.sh: Fix silencing of cleanup errors
  src/freenas-installer/etc/install.sh
Labels: backport-12.0

#5385 NAS-107082 / 12.1 / Make v4_krb_enabled a bool
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-11.3, backport-12.0

#5390 NAS-107100 / 12.1 / Do not run check_available in a tight loop in case an exception happens
  src/middlewared/middlewared/plugins/system.py
Labels: backport-11.3, backport-12.0, jira

#5387 NAS-107099 / 12.1 / Do not display previous replication task status after deleting it and…
  src/middlewared/middlewared/plugins/zettarepl.py
  src/middlewared/middlewared/plugins/zettarepl_/state.py
Labels: backport-11.3, backport-12.0, jira

#5395 NAS-107088 / 12.1 / correctly sync db to standby
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#5399 NAS-107124 / 12.0 / Fix /etc/skel symlink
  src/middlewared/middlewared/etc_files/pam.d/pam.skel_freebsd
Labels: backport-12.1, jira

#5402 NAS-107123 / 12.1 / Add catia mappings for special Apple characters
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5396 NAS-107107 / 12.0 / Clear any potential stale state after leaving AD domain
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-12.1, jira

#5103 NAS-107085 / 12.1 / Disable fruit:locking on time machine shares
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5398 NAS-107115 / 12.0 / Newly created builtin users should not default to 'smb'
  src/middlewared/middlewared/alembic/versions/12.0/2020-08-07_12-39_fix_smb_builtins.py
  src/middlewared/middlewared/plugins/account_/sync_builtin.py
Labels: backport-12.1, jira

#5405 NAS-107130 / 12.0 / Add test to verify builtin users are not smb users
  tests/api2/user.py
Labels: backport-12.1, jira

#5308 NAS-106999 / 12.1 / Human-readable error for deleting used cloud credential
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_130_cloudsync.py
Labels: backport-12.0, jira

#5401 NAS-107116 / 12.1 / allow editing empty interfaces on HA
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.3, backport-12.0, jira

#5422 NAS-107148 / 12.1 / Generate a random default serial extent
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-11.3, backport-12.0, jira

#5424 NAS-107102 / 12.1 / Add ha licensed stats to usage plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-12.0

#5409 NAS-107141 / 12.1 / remove excess logging info when syncing disks
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-12.0, jira

#5347 NAS-107025 / 12.0 / Add sysutils/intel-pcm
  nas_ports/freenas/py-middlewared/Makefile
Labels: backport-12.1

#5416 NAS-107142 / 12.0 / Add tests for SMB groupmaps
  tests/api2/group.py
Labels: backport-12.1, jira

#5425 NAS-107122 / 12.0 / Default to disabling TLS 1.0 and 1.1
  src/middlewared/middlewared/alembic/versions/12.0/2019-11-20_00-09_stg_guihttpsprotocols.py
Labels: backport-12.1

#5406 NAS-107140 / 12.0 / Expand api tests for user
  tests/api2/user.py
Labels: backport-12.1, jira

#5431 NAS-106875 / 12.1 / Add directory services stats to usage plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-12.0

#5438 NAS-107154 / 12.1 / Fix issue with smb share generation
  src/middlewared/middlewared/etc_files/local/smb4_share.conf
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, jira

#5415 NAS-106999 / 12.0 / Human-readable error for deleting used cloud credential (by themylogin)
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/cloudsync.py
Labels: backport-12.1

#5440 NAS-107156 / 12.0 / Expand testing for SMB homes shares
  tests/api2/smb_registry.py
Labels: backport-12.1, jira

#5373 NAS-107035 / 11.3 / Properly calculate swap partition size on 4k sector disks
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0

#5432 NAS-107152 / 12.1 / Retry gathering usage starts if we experience a failure
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-12.0

#5417 NAS-107143 / 12.1 / Ensure groupmap entries are properly added / deleted on group.update
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0, jira

#5447 NAS-107035 / 12.0 / Properly calculate swap partition size on 4k sector disks (by themylogin)
  src/middlewared/middlewared/plugins/disk_/format.py
Labels: backport-12.1

#5453 NAS-107166 / 11.3 / Move NFS kerberos SPN setup into separate function
  src/middlewared/middlewared/etc_files/nfsd.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-12.0, backport-12.1, jira

#5457 NAS-107169 / 11.3 / Add basic set of tests to verify nfs spn in AD environments
  tests/api2/ad_kerberos.py
Labels: backport-12.0, backport-12.1, jira

#5455 NAS-107165 / 12.1 / Bug fix for formatting disk for geli encrypted pool
  src/middlewared/middlewared/plugins/pool_/format_disks.py
Labels: backport-12.0

#5458 NAS-106988 / 12.0 / Fix parsing lsof output
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.1

#5469 NAS-107185 / 12.1 / After getting rid of legacy replication, we don't need to restart cron anymore
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/snapshot.py
Labels: backport-12.0, jira

#5468 NAS-107182 / 12.1 / Delete legacy replication VMware alerts
  src/middlewared/middlewared/alert/source/vmware_snapshot.py
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-12.0, jira

#5337 NAS-106994 / 12.0 / Allow user to explicitly set ipv4 for openvpn server/client protocol
  src/middlewared/middlewared/plugins/vpn.py
Labels: backport-12.1, backported

#5475 NAS-107215 / 11.3 / Add functional tests for ZFS ACLs
  tests/api2/acl.py
Labels: backport-12.0, backport-12.1, jira

#5479 NAS-107221 / 12.0 / Fix editing built-in users
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.1, jira

#5474 NAS-107214 / 12.1 / cache dmidecode results to reduce CPU time
  src/freenas/etc/netcli
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/sensors.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/detect_enclosure_freebsd.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/sensor.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/truenas.py
  src/middlewared/middlewared/alert/source/freenas_bmc.py
  src/middlewared/middlewared/etc_files/loader.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#5483 NAS-107227 / 11.3 / Add more ACL regression tests
  tests/api2/acl.py
Labels: backport-12.0, backport-12.1, jira

#5476 NAS-105654 / 11.3 / Add regression test for safe handling of private middleware plugin attributes
  tests/api2/activedirectory.py
  tests/api2/ad_kerberos.py
  tests/api2/auth.py
  tests/api2/dyndns.py
  tests/api2/ipmi.py
  tests/api2/snmp.py
  tests/api2/user.py
  tests/api2/vmware.py
  tests/runtest.py
Labels: backport-12.0, backport-12.1

#5490 NAS-107242 / 12.1 / Do not permit NetBIOS information changes while AD is enabled.
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-11.3, backport-12.0, jira

#5494 NAS-107252 / 11.3 / Allow chown back to uid / gid 0 in pool.dataset.permission
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0, backport-12.1, jira

#5498 NAS-107226 / 12.0 / Fix enclosures on unknown products
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/m50_plx.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
Labels: backport-12.1

#5497 NAS-107254 / 12.0 / Add basic tests for filesystem permissions API
  tests/api2/posix_mode.py
Labels: backport-11.3, backport-12.1, jira

#5502 NAS-107086 / 11.3 / Remove devd rc script, we fix this in freenas/os
  src/freenas/etc/rc.d/devd
Labels: backport-12.0, backport-12.1

#5505 NAS-107269 / 12.0 / remove DELETE duplicate in api2/cloudsync.py
  tests/api2/cloudsync.py
Labels: jira

#5509 NAS-107060 / 12.1 / Report read/write bytes for NFS server
  src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
Labels: backport-12.0

#5512 NAS-107060 / 12.1 / Separate chart for NFS bytes
  src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
Labels: backport-12.0

#5508 NAS-107256 / 12.1 / Be prepared to receive tons of zfs deadman messages
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: backport-12.0

#5518 NAS-107310 / 12.0 / Set correct ACL on home dataset
  tests/api2/user.py
Labels: backport-12.1, jira

#5528 NAS-107343 / 12.1 / Fix alternate data streams support
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: backport-12.0, jira

#5531 NAS-107349 / 12.0 / Fix migrating to BSD bootloader
  src/freenas/etc/ix.rc.d/ix-bsdloader
Labels: backport-12.1, jira

#5526 NAS-107351 / 12.1 / datasets *or zvols* in several places, and a little comment on overlapping tasks
  src/middlewared/middlewared/plugins/snapshot.py
Labels: backport-12.0, jira

#5530 NAS-107213 / 12.1 / Fix validation for netbios names that are NULL
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0

#5539 NAS-107332 / 20.10 / Disable 2FA when resetting password from TN console
  src/freenas/etc/netcli
Labels: backport-12.0

#5543 NAS-107367 / 20.10 / Correctly handle ACME certs using SAN
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-11.3, backport-12.0, jira

#5538 NAS-107365 / 20.10 / Fix disk process_datastore_event
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-12.0, jira

#5536 NAS-107370 / 20.10 / Make sure hook is being called for a specific pool
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: backport-12.0, jira

#5551 NAS-107104 / 20.10 / Properly renew ACME certs
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-11.3, backport-12.0

#5548 NAS-107346 / 20.10 / Skip getting jid for each jail as iocage will provide it
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-12.0

#5549 NAS-107374 / 12.0 / Add auxiliary parameter blacklist for SMB.
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-20.10, jira

#5557 NAS-107376 / 20.10 / Correctly pass the table name when resetting password from netcli
  src/freenas/etc/netcli
Labels: backport-12.0, jira

#5559 NAS-107371 / 12.0 / Take into account that disk.query can contain invalid disks during eclosure sync
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/m50_plx.py
Labels: backport-20.10

#5561 NAS-106173 / 12.0 / adding code to wait on middleware to be online in api2/host_key.py
  tests/api2/host_key.py
  tests/runtest.py
Labels: backport-20.10

#5565 NAS-107315 / 20.10 / fix rsync mem leak when snapdir = visible
  src/middlewared/middlewared/utils/osc/freebsd/user_context.py
Labels: backport-11.3, backport-12.0

#5570 NAS-107389 / 20.10 / adding missing parametrize to activedirectory test 16 and 20
  tests/api2/test_030_activedirectory.py
Labels: jira

#5571 NAS-107390 / 12.0 / Fix mDNS advertisement for afpovertcp
  src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
Labels: backport-20.10, jira

#5573 NAS-107392 / 12.1 / rename host_key test as test_700_host_key.py to run it at the end
  tests/api2/test_700_host_key.py
Labels: jira

#5574 NAS-107394 / 12.0 / adding host_key in ev to run at the end
  tests/runtest.py
Labels: jira

#5577 NAS-107409 / 20.10 / ensure nfs shares are within zpool mountpoint
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-11.3, backport-12.0

#5576 NAS-107402 / 20.10 / Fix parameter migration for "hide dot files"
  src/middlewared/middlewared/alembic/versions/12.0/2020-01-23_10-22_simplify_smb_shares.py
Labels: backport-12.0

#5575 NAS-107407 / 20.10 / Set lower bound on automatically assigned uids
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0
