Repository truenas/middleware, pull requests merged in 2020-05, with the labels that each got.

#4700 NAS-105700 / 11.3 / Properly handle bridge MTU
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#4697 NAS-105956 / 11.3 / Give proper meaning for nfs.v4_krb
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/nfs.py
Labels: backport-12.0

#4699 NAS-105980 / 11.3 / Fix KeyError in LDAP plugin
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-12.0, jira

#4704 NAS-105965 / 12.0 / fix rollback operation on TN HA
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-11.3

#4710 NAS-105940 / 12.0 / NAS-105940: Fix problem related with write tunables in rc.conf
  src/middlewared/middlewared/etc_files/rc.conf.py
Labels: backport-11.3

#4715 Fix quota test
  tests/api2/pool_dataset_quota_alert.py
Labels: backport-12.0

#4723 Fix replication test
  tests/api2/replication.py
Labels: backport-11.3

#4735 NAS-105679 / 12.0 / fix(ixdiagnose): disable trace
  src/freenas/usr/local/bin/ixdiagnose
Labels: backport-11.3

#4739 NAS-106027 / 12.0 / turn off syslog-ng stats msgs for TN HA
  src/freenas/usr/local/etc/syslog-ng.conf.freenas
Labels: backport-11.3

#4728 NAS-106023 / 12.0 / Use CLDAP for determining domain and site information
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#4742 NAS-106039 / 12.0 / Fix giant SSH login failure alert
  src/middlewared/middlewared/alert/source/ssh_login_failures.py
Labels: backport-11.3, jira

#4750 NAS-106049 / 11.3 / Fix errors tracebacks during system dataset migration
  src/middlewared/middlewared/etc_files/smb_configure.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, jira

#4767 NAS-106084 / 12.0 / filter smbd messages from HA syslog connection
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: backport-11.3

#4769 NAS-106084 / 12.0 / fix curly-brace syntax in f-string
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: backport-11.3

#4772 ensure log dir exists on TN HA systems
  src/fenced/fenced/logging.py
Labels: backport-11.3

#4773 NAS-106109 / 12.0 / Encrypt smbhash by default
  src/middlewared/middlewared/alembic/versions/12.0/2020-05-13_12-08_encrypt-smbhash.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: jira

#4775 NAS-106102 / 12.0 / Make sure virtualisation is supported on AMD platforms
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-11.3

#4785 NAS-106132 / 12.0 / Fix log rotation for netatalk
  src/freenas/etc/newsyslog.conf.template
Labels: backport-11.3, jira

#4790 NAS-106113 / 12.0 / Fix ZpoolCapacityAlertSource levels
  src/middlewared/middlewared/alert/source/zpool_capacity.py
Labels: backport-11.3

#4788 NAS-105985 / 12.0 / suppress repetitive log msgs that occur more than once in 60 secs
  src/freenas/usr/local/etc/syslog-ng.conf.freenas
Labels: backport-11.3

#4794 NAS-106143 / 12.0 / Generate debug for SCST in SCALE
  debian/debian/control
  src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
  src/freenas/usr/local/libexec/freenas-debug/iscsi_freebsd/iscsi.sh
Labels: jira

#4789 NAS-106062 / 12.0 / fix syslog-ng binding to all ints on TN HA
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: backport-11.3

#4792 NAS-106141 / 12.0 / Platform dependent NTP plugin
  src/middlewared/middlewared/etc_files/localtime_config.py
  src/middlewared/middlewared/etc_files/ntp.conf
  src/middlewared/middlewared/migration/0003_iscsi_vendor.py
  src/middlewared/middlewared/migration/0004_ntp_default_servers_linux.py
  src/middlewared/middlewared/plugins/ntp.py
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#4836 NAS-106149 / 12.0 / Fix ValueError: invalid literal for int() with base 10: 'unknown'
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: backport-11.3

#4839 NAS-106237 / 11.3 / Avoid race between zpool import completion and share config generation
  src/middlewared/middlewared/plugins/afp.py
  src/middlewared/middlewared/plugins/ftp.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: backport-12.0

#4848 NAS-106197 / 11.3 / Alert collisions are inevitable on TN HA; ignore them
  gui/system/migrations/0047_remove_alert_unique_constraint.py
  gui/system/models.py
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-12.0
