Repository truenas/middleware, pull requests merged in 2021-06, with the labels that each got.

#6934 NAS-110844 / 21.08 / Allow retrieving snapshot(s) of dataset(s) from pool.dataset
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira

#6943 NAS-110833 / 21.08 / Bug fix for checking if a cert is revoked
  src/middlewared/middlewared/alert/source/certificates.py
Labels: backport-21.06-BETA.1

#6946 NAS-110894 / 21.08 / Reinitialize udev monitor on udev polling error
  src/middlewared/middlewared/plugins/device_/udev_events_linux.py
Labels: backport-21.06-BETA.1, jira

#6945 NAS-110887 / 21.08 / enable STP by default when creating bridges on SCALE
  src/middlewared/middlewared/plugins/interface/netif_linux/bridge.py
Labels: backport-21.06-BETA.1

#6940 NAS-110877 / 21.08 / Create storage class before doing helm action
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: backport-21.06-BETA.1, jira

#6951 NAS-110909 / 21.08 / Fix enclosures on SCALE
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-21.06-BETA.1

#6924 NAS-110783 / 12.0 / only unlock SED disks on active controller
  src/freenas/etc/ix.rc.d/ix-sed
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-21.08, pending QA

#6896 NAS-110712 / 12.0 / add --trace-malloc arg to middlewared
  src/middlewared/middlewared/main.py
Labels: backport-21.08, backported

#6863 NAS-110773 / 12.0 / Fix kerberos error
  src/middlewared/middlewared/plugins/kerberos.py
Labels: backport-21.08, jira

#6965 NAS-110754 / 21.08 / Properly validate rsync extra arguments
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-12.0

#6963 NAS-110932 / 21.08 / Do not attempt to query chart releases if no pool is set
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6962 NAS-110931 / 21.08 / Raise multus log level
  src/middlewared/middlewared/etc_files/cni/multus.py
Labels: jira

#6953 NAS-110783 / 21.08 / only unlock SED disks on active controller (by yocalebo)
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/failover_/event_linux.py
Labels: backport-21.06-BETA.1

#6970 NAS-110949 / 21.08 / Improve retrieving installed application(s) performance
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6971 NAS-110671 / 12.0 / prevent unlimited WAITING cron jobs
  src/middlewared/middlewared/plugins/cron.py
Labels: backport-21.06-BETA.1, backport-21.08

#6957 NAS-110929 / 21.08 / Allow retrieving catalog data partially
  src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6972 NAS-110950 / 21.08 / remove unused files referencing lxml
  src/middlewared/middlewared/alert/source/fc_hba_not_present.py
  src/middlewared/middlewared/plugins/disk_/identify_freebsd.py
  src/middlewared/middlewared/plugins/iscsi_/global_freebsd.py
  src/middlewared/middlewared/plugins/multipath.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_freebsd.py
Labels: backport-21.06-BETA.1

#6986 NAS-110958 / 21.08 / Start libvirt before probing for cpu model choices
  src/middlewared/middlewared/plugins/vm/info_linux.py
Labels: backport-21.06-BETA.1, jira

#6989 NAS-110969 / 21.08 / Increase verbosity of range-related idmap verrors
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-12.0, backport-21.06-BETA.1, jira

#6991 NAS-110963 / 21.08 / Fix test failures for User account and SMB datasets
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-21.06-BETA.1

#6990 NAS-110972 / 21.08 / Add latest_human_version key in catalog items
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#7000 NAS-110979 / 21.08 / fix 'NoneType' object has no attribute 'call_sync'
  src/middlewared/middlewared/plugins/vm/vm_supervisor.py
Labels: backport-21.06-BETA.1

#7001 NAS-110980 / 21.08 / Make catalog.create endpoint a job
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#6983 NAS-110955 / 21.08 / Add regression tests for AFP/SMB migration param
  tests/api2/test_425_smb_protocol.py
Labels: backport-21.06-BETA.1, jira

#7018 NAS-111010 / 21.08 / Correctly validate root uid when retrieving user object
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#7023 NAS-111012 / 21.08 / Perform chown() when setting POSIX1E ACL non-recursively
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: backport-21.06-BETA.1, jira

#7026 NAS-111017 / 21.08 / Allow acltype to change through middleware
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-21.06-BETA.1, jira

#7028 NAS-111022 / 21.08 / Add validation related to legacy AFP shares
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-21.06-BETA.1, jira

#7032 NAS-111038 / 21.08 / Fix parsing error for POSIX1E getfacl output
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: backport-21.06-BETA.1, jira

#7034 NAS-111039 / 21.08 / Remove strict check for path existence in AFP validation
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-21.06-BETA.1, jira

#7038 NAS-111050 / 21.08 / Fix parsing error for getfacl return with comment in ACE
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: backport-21.06-BETA.1

#7039 NAS-111051 / 21.08 / Retrieve created at property for datasets/volumes
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7042 NAS-111065 / 21.08 / Use correct API endpoint for disabling ACL on update
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-21.06-BETA.1, jira

#7049 NAS-111069 / 12.0 / Add default value for extra list attribute
  src/middlewared/middlewared/plugins/rsync.py
Labels: jira

#7053 NAS-111073 / 21.08 / Fix MIT kerberos keytab handling
  src/middlewared/middlewared/etc_files/krb5.keytab.py
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#7057 NAS-111081 / 21.08 / Fix setting default SMB ACL on dataset creation
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-21.06-BETA.1, jira

#7061 NAS-111096 / 21.08 / Synchronously sync catalog on creation
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#7060 NAS-111087 / 21.08 / Do not read/validate all catalog item versions
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#7051 NAS-111071 / 21.08 / Document return type(s) of vpn plugin
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira

#7050 NAS-111070 / 21.08 / Document return type(s) of webdav plugin
  src/middlewared/middlewared/plugins/webdav.py
Labels: jira

#7071 NAS-111046 / 21.08 / update recommended zvol blocksize depending on zpool geometry
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#7078 NAS-111174 / 21.08 / Fix api tests for catalog
  tests/api2/test_108_catalog.py
Labels: jira

#7081 NAS-111146 / 21.08 / add interfaces marked critical for failover in network debug
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: backport-12.0

#7085 NAS-111201 / 21.08 / Treat openebs/zfs-driver image as system internal image
  src/middlewared/middlewared/plugins/docker_linux/images.py
Labels: jira

#7069 NAS-111132 / 21.08 / Fix r10 enclosures
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7091 NAS-111217 / 21.08 / Disable containerd in systemd preset file
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
Labels: jira

#7084 NAS-111192 / 21.08 / Remove cached content of a catalog after deleting it
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
  src/middlewared/middlewared/plugins/catalogs_linux/utils.py
Labels: jira

#7093 NAS-111223 / 21.08 / Fix R40 to comply with enclosure management nep specified single mapped enclosure to UI.
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7055 NAS-111080 / 21.08 / Fix Enclosure Mapping for early version Mini X 3.0 Systems
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7096 NAS-111240 / 21.08 / Add `who` string to ACL output
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#7100 NAS-111248 / 21.08 / Convert JSON validation errors ValidationErrors
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira

#7101 NAS-111254 / 21.08 / Remove API test for MULTIPROTOCOL_AFP
  tests/api2/test_435_smb_registry.py
Labels: jira

#7094 NAS-111226 / 21.08 / Mark login password as private
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#7090 NAS-111215 / 21.08 / Bug fix for validating acltype when parent ds does not exist
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7087 NAS-111210 / 21.08 / Improvements to revoking a certificate/ca
  src/middlewared/middlewared/plugins/crypto.py
Labels: jira
