Repository truenas/middleware, pull requests merged in 2021-03, with the labels that each got.

#6514 NAS-109643 / 12.0 / Adjust default NFSv4 ACL for new datasets
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-21.04, jira

#6517 NAS-109639 / 21.04 / Use default sudo
  src/middlewared/middlewared/plugins/account_/sync_builtin.py
Labels: backport-12.0

#6511 NAS-108202 / 21.04 / Configure ocsp stapling in nginx
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: pending QA

#6519 NAS-109648 / 21.04 / Retrieve chart release history on chart.release.query event
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
Labels: jira

#6527 NAS-109210 / 21.04 / Fix HA upgrade progress
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#6523 NAS-109668 / 21.04 / Fix resolving patch for certificate service
  src/middlewared/middlewared/plugins/crypto.py
Labels: jira

#6530 NAS-109671 / 21.04 / Fix creating users
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0

#6534 NAS-109656 / 12.0 / Do not crash debug if /var/db/system/cores does not exist
  src/freenas/usr/local/bin/ixdiagnose
Labels: backport-21.04, skip jira status

#6536 NAS-109684 / 12.0 / Enable SA-based xattrs on all new datasets
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6539 NAS-109510 / 21.04 / Do not crash on poor unicode in ixdiagnose
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0, skip jira status

#6549 NAS-109650 / 12.0 / Properly handle invalid unicode in filesystem.file_tail_follow
  src/middlewared/middlewared/plugins/filesystem.py
Labels: backport-21.04

#6521 NAS-109700 / 21.04 / Support mailcfg[fromname]
  src/freenas/etc/find_alias_for_smtplib.py
Labels: backport-12.0, jira

#6444 NAS-109458 / 21.04 / try smartctl SAS to SATA translation in debug
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
Labels: backport-12.0

#6553 NAS-109702 / 21.04 / Retrieve build time without authentication
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0, jira

#6555 NAS-109704 / 12.0 / Prevent users from changing kerberos realm while AD enabled.
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-21.04, jira

#6560 NAS-109718 / 21.04 / Add throttle for build_time endpoint
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#6564 NAS-109724 / 12.0 / allow failover.status endpoint in rest API
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-21.04

#6569 NAS-109656 / 12.0 / Allow multiple SSH connection host keys
  src/middlewared/middlewared/plugins/keychain.py
Labels: backport-21.04

#6562 NAS-109341 / 12.0 / Do not start VM if grub config cannot be found
  src/middlewared/middlewared/plugins/vm.py
Labels: backport-21.04

#6573 NAS-109732 / 12.0 / Clear various AD-related caches when service explicitly stopped
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-21.04, jira

#6581 NAS-109687 / 21.04 / add R20 enclosure string to enclosure plugin
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-12.0

#6578 NAS-109696 / 12.0 / Better cloud sync progress reporting: per-file progress, checks progress
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-21.04

#6580 NAS-109734 / 12.0 / Fix RcloneVerboseLogCutter
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-21.04, jira

#6543 NAS-109694 / 12.0 / Initial protocol testing for SMB using pylibsmb
  tests/api2/smb.py
  tests/api2/smb_protocol.py
  tests/protocols.py
Labels: backport-21.04, jira

#6587 NAS-108599 / 12.0 / Restart mDNS after jail start
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-21.04

#6588 NAS-109741 / 12.0 / Allow better progress report for core.bulk
  src/middlewared/middlewared/service.py
Labels: backport-21.04, jira

#6589 NAS-109743 / 12.0 / Explicitly set tdbsam as passdb backend when stopping ldap
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-21.04, jira

#6596 NAS-109749 / 21.04 / Fix SMB share ids in smb_registry tests
  tests/api2/test_435_smb_registry.py
Labels: jira

#6345 NAS-109196 / 12.0 / Issue alert for incorrect NVDIMM firmware version on M-Series
  src/freenas/usr/local/lib/middlewared_truenas/plugins/truenas.py
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
  src/middlewared/middlewared/alert/source/m_series_nvdimm_firmware_freebsd.py
  src/middlewared/middlewared/alert/source/m_series_old_bios_version_freebsd.py
  src/middlewared/middlewared/plugins/enterprise/__init__.py
  src/middlewared/middlewared/plugins/enterprise/m_series_nvdimm_freebsd.py
Labels: backport-21.04

#6604 NAS-109769 / 12.0 / dont log exception when pickle.load()'ing an empty file
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-21.04

#6605 NAS-109777 / 21.04 / Retrieve app_readme at item level for UI
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6613 NAS-109764 / 21.04 / raise EOPNOTSUPP when exporting last zpool on HA system
  src/middlewared/middlewared/plugins/pool.py
Labels: skip jira status

#6616 NAS-109808 / 12.0 / Fix typo in nis.get_cache
  src/middlewared/middlewared/plugins/nis.py
Labels: backport-21.04, jira

#6602 NAS-109767 / 12.0 / fix ENOMETHOD on kmip.update_memory_keys on HA upgrades
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: jira

#6622 NAS-109644 / 21.04 / Do not crash whole network on invalid bridge/LAG/VLAN configuration
  src/middlewared/middlewared/plugins/interface/vlan.py
  src/middlewared/middlewared/plugins/network.py
Labels: skip jira status

#6615 NAS-109805 / 12.0 / Add regression tests for domain sid modifications
  tests/api2/smb.py
Labels: backport-21.04, jira

#6610 NAS-109790 / 12.0 / Add initial tests for alternate datastream support
  tests/api2/smb_protocol.py
Labels: backport-21.04, jira

#6625 NAS-109727 / 21.04 / Handle abnormal zettarepl process termination properly
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: skip jira status

#6628 NAS-109827 / 21.04 / Retrieve k8s backup name after completing backup
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: jira

#6631 NAS-109388 / 21.04 / Report boot pool for disks
  src/middlewared/middlewared/plugins/disk.py
Labels: backport-12.0

#6627 NAS-109824 / 21.04 / Ensure aclmode set to DISCARD if not using NFSv4 ACLs on SCALE
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6645 NAS-109865 / 12.0 / Add dependencies to SMB SID tests
  tests/api2/smb.py
Labels: backport-21.04, jira

#6649 NAS-109727 / 21.04 / Set replication state error on abnormal zettarepl process termination
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: skip jira status

#6641 NAS-109858 / 21.04 / Recursively destroy backup snapshot
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: jira

#6644 NAS-109861 / 21.04 / Selectively add locked key
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6655 NAS-109898 / 21.04 / PoolDatasetService.do_create: skip children lookups on parent datasets
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6669 NAS-109919 / 21.04 / Bug fix for validation acme authenticator schemas
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/route53.py
Labels: jira

#6643 NAS-109921 / 21.04 / Correctly display CertBot validation errors
  src/middlewared/middlewared/plugins/acme_protocol_/issue_cert.py
Labels: jira

#6670 NAS-109884 / 21.04 / Add video device by default for guests
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_linux.py
Labels: pending QA

#6672 NAS-109926 / 21.04 / Increase permitted SMB stream size
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#6646 NAS-109863 / 21.04 / Improve chart release rollback logic
  src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py
Labels: jira

#6684 NAS-109944 / 21.04 / Allow specifying default identifier field for tables
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/service.py
Labels: jira

#6671 NAS-109907 / 21.04 / Add listen directive for wireguard ip for TC
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
Labels: backport-12.0

#6677 NAS-109927 / 21.04 / Do not have catalog query fail
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#6680 NAS-109932 / 21.04 / Properly show error messages for invalid client cert
  src/middlewared/middlewared/plugins/vpn.py
Labels: backport-12.0, jira

#6693 NAS-109959 / 21.04 / Fix AD cache fill with alternate character sets
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-12.0, jira

#6700 NAS-109968 / 21.04 / Allow retrieving parsed image tags for container images
  src/middlewared/middlewared/plugins/docker_linux/images.py
  src/middlewared/middlewared/plugins/docker_linux/update_alerts.py
Labels: jira

#6702 NAS-109801 / 12.0 / Fix that ldap_binddn was errorneously encrypted instead of ldap_bindpw…
  src/middlewared/middlewared/alembic/versions/12.0/2021-03-31_09-08_fix_ldap_pwenc.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-21.04

#6710 NAS-109981 / 21.04 / Fix using sql filters in rest api
  src/middlewared/middlewared/restful.py
Labels: jira
