Repository truenas/middleware, pull requests merged in 2021-08, with the labels that each got.

#7238 NAS-111597 / 21.08 / Retrieve more useful information for app upgrade summary
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: jira

#7245 NAS-111631 / 21.08 / fuse mount gluster volumes with acl support
  src/middlewared/middlewared/plugins/gluster_linux/fuse.py
Labels: jira

#7248 NAS-111633 / 21.08 / Bug fix for creating a zvol
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7250 NAS-111655 / 21.08 / Fix check for passdb backend type
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: jira

#7240 NAS-111594 / 13.0 / improve the process for formatting disks
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-21.08

#7251 NAS-111593 / 21.08 / CLI commands examples
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/service.py
Labels: skip jira status

#7254 NAS-111667 / 13.0 / fix minor typo in wipe.py
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: jira

#7257 NAS-111670 / 21.08 / Fix DS_TYPE_LDAP idmap generation
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#7258 NAS-111671 / 21.08 / Fix foreign groupmap alias removal
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira

#7260 NAS-111674 / 21.08 / only eventsd.delete if glustereventsd is running
  src/middlewared/middlewared/plugins/gluster_linux/eventsd.py
Labels: jira

#7261 NAS-111683 / 21.08 / Fix smb plugin issues causing test_435_smb_registry failures
  src/middlewared/middlewared/plugins/service_/services/cifs.py
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  tests/api2/test_435_smb_registry.py
Labels: jira

#7264 NAS-111689 / 21.08 / Fixes for test_425_smb_protocol
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  tests/api2/test_425_smb_protocol.py
Labels: jira

#7263 NAS-111682 / 12.0 / Improve smartd restart performance
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/disk_/disk_info_base.py
  src/middlewared/middlewared/plugins/disk_/disk_info_freebsd.py
  src/middlewared/middlewared/plugins/disk_/disk_info_linux.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.08

#7262 NAS-111685 / 12.0 / make get_ses_enclosures scale on large systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/ses_enclosure.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/ses_enclosure_freebsd.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/ses_enclosure_linux.py
Labels: jira

#7265 NAS-111690 / 12.0 / call enclosure.query once in disk.sync_all
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#7268 NAS-111697 / 21.08 / Fix idmap create / delete methods
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#7266 NAS-111693 / 12.0 / fix enclosure.sync_zpool
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: jira

#7269 NAS-111696 / 12.0 / dont call system.info in enclosure plugin
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: jira

#7273 NAS-111706 / 21.08 / Fixes for base SMB regression tests
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  tests/api2/test_420_smb.py
Labels: jira

#7278 NAS-111710 / 21.08 / Fix groupmap tests
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  tests/api2/test_210_group.py
Labels: jira

#7279 NAS-111714 / 21.08 / Enable SMB2/3 aapl extensions prior to AFP compat tests
  tests/api2/test_425_smb_protocol.py
Labels: jira

#7281 NAS-111715 / 21.08 / Add global parameter handling for guest access
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: jira

#7288 NAS-111741 / 21.08 / Stop containerd explicitly after stopping docker
  src/middlewared/middlewared/plugins/service_/services/docker.py
Labels: jira

#7290 NAS-111758 / 21.08 / fix IndexError in network.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-12.0

#7282 NAS-111720 / 12.0 / fix numerous issues with disk.sync_all
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
  src/middlewared/middlewared/plugins/disk_/identify_base.py
  src/middlewared/middlewared/plugins/disk_/identify_freebsd.py
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#7287 NAS-111744 / 21.08 / Fix SSHd IPV6 link local ListenAddress
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
Labels: jira, backport-12.0

#7295 NAS-111762 / 21.08 / Remove Samba passdb binding from middleware
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/connection.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
Labels: jira

#7239 NAS-111603 / 21.08 / Fix quota alert for dataset owner
  src/middlewared/middlewared/alert/source/quota.py
Labels: jira

#7296 NAS-111763 / 21.08 / Fix homedir copy on SCALE
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#7297 NAS-111764 / 12.0 / move disk.sync_all and enclosure.sync_zpool on HA
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: jira

#7299 NAS-111766 / 12.0 / fix slot number calculation for expansion shelves
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: jira

#7304 NAS-111785 / 21.08 / Fix tdb directory setup
  src/middlewared/middlewared/plugins/tdb/base.py
Labels: jira

#7302 NAS-111772 / 21.08 / Fix multiple issues with krb nfs4 config in SCALE
  src/middlewared/middlewared/etc_files/ganesha/ganesha.conf.mako
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/nfs_/krb5.py
  tests/api2/test_032_ad_kerberos.py
Labels: jira

#7306 NAS-111788 / 12.0 / fix typo
  src/middlewared/middlewared/plugins/disk_/identify_freebsd.py
Labels: jira

#7310 NAS-111790 / 12.0 / dont restart services twice on failover
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-21.08

#7309 NAS-111789 / 21.08 / Perform direct smb config write when updating with AD domain name
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#7312 NAS-111792 / 21.08 / Allow setting permissions on /root/.ssh
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira

#7316 NAS-111796 / 21.08 / Fix lazy initialization of directory services cache
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/cache.py
Labels: jira

#7317 NAS-111806 / 21.08 / Add tests for directory services user/group cache
  tests/api2/test_040_ad_user_group_cache.py
Labels: jira

#7318 NAS-111813 / 21.08 / Remove check for privatedir path in passdb_list
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: jira

#7313 NAS-111794 / 21.08 / Move static nsswitch.conf to base install
  src/freenas/debian/preinst
  src/freenas/debian/rules
  src/freenas/etc/nsswitch.conf
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#7320 NAS-111816 / 21.08 / Improve acltype retrieval based on path
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira

#7321 NAS-111819 / 12.0 / Fix taking vmware-aware manual snapshots
  src/middlewared/middlewared/plugins/vmware.py
Labels: jira, backport-21.08

#7332 NAS-111843 / 21.08 / Fix typo in _strip_acl_posix1e call
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira

#7333 NAS-111847 / 21.08 / Enforce global configuration reload on share guest access change
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7335 NAS-111849 / 21.08 / Fix typo in smb.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7325 NAS-111837 / 21.08 / Make sure we start nfs when user requests it
  src/middlewared/middlewared/etc_files/ganesha/ganesha.conf.mako
Labels: jira

#7323 NAS-111695 / 21.08 / Make sure we freeup unused pages in sqlite
  src/middlewared/middlewared/plugins/datastore/connection.py
Labels: backport-12.0

#7334 NAS-111848 / 21.08 / Improve share enumeration test
  tests/api2/test_420_smb.py
Labels: jira

#7319 NAS-111814 / 21.10 / Do not report coredumps generated by apps in containers
  src/middlewared/middlewared/alert/source/cores.py
Labels: jira

#7341 NAS-111876 / 21.10 / Avoid pool.dataset call in SMB share generation
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
Labels: jira

#7344 NAS-111883 / 21.10 / Explicitly disable clustering in smb.conf
  src/middlewared/middlewared/etc_files/local/smb4.conf.mako
Labels: jira

#7351 NAS-111902 / 21.10 / Remove dependency on samba3 loadparm context
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7355 NAS-111917 / 21.10 / Avoid generating invalid krb5.conf
  src/middlewared/middlewared/etc_files/krb5.conf.mako
Labels: jira

#7359 NAS-111920 / 21.10 / Run corefile alert every 6 hours instead of every 5 minutes
  src/middlewared/middlewared/alert/source/cores.py
Labels: jira

#7353 NAS-111910 / 21.10 / Remove invalid auxiliary parameter from test payload
  tests/api2/test_435_smb_registry.py
Labels: jira

#7342 NAS-111881 / 21.10 / catch NoSuchDevice in ethtool
  src/middlewared/middlewared/plugins/interface/netif_linux/ethernet_settings.py
Labels: jira

#7360 NAS-111925 / 21.10 / Fix regression in kerberos config generation
  src/middlewared/middlewared/etc_files/krb5.conf.mako
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#7358 NAS-111676 / 12.0 / Do not allow deleting a target if it's in use by fcport service
  src/middlewared/middlewared/plugins/iscsi.py
Labels: pending QA

#7361 NAS-111927 / 21.10 / Update preferred trains default value for catalog
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#7356 NAS-111276 / 12.0 / VMware VM UUIDs are not unique and we should use FindAllByUuid
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-21.10

#7363 NAS-111934 / 21.10 / Move loglevel mapping conversion to compress method
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7364 NAS-111935 / 21.10 / Do not retrieve old catalog.items jobs when querying up catalogs
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#7365 NAS-111938 / 21.10 / Create idmap service to wrap around winbind
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/cifs.py
  src/middlewared/middlewared/plugins/service_/services/idmap.py
Labels: jira

#7370 NAS-111885 / 21.10 / Update check_user method to allow checking passwords of other users
  src/middlewared/middlewared/plugins/auth.py
Labels: backport-12.0

#7375 NAS-111947 / 21.10 / Remove additional unused mDNS service types
  src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
Labels: jira

#7377 NAS-111954 / 21.10 / Fix GMail thread safety
  src/middlewared/middlewared/plugins/mail_/gmail.py
Labels: jira, backport-12.0

#7367 NAS-111779 / 21.10 / improve IoThreadPoolExecutor
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/utils/io_thread_pool_executor.py
Labels: backport-12.0, backport-21.08-BETA.1

#7384 NAS-111958 / 21.10 / Properly retrieve snapshots in bootenv plugin
  src/middlewared/middlewared/plugins/bootenv.py
Labels: jira, backport-21.08-BETA.1

#7391 NAS-111970 / 21.10 / Remove unnecessary validation for SMB password
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#7394 NAS-111990 / 21.10 / Wait for permissions job to finish during dataset creation
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7395 NAS-111992 / 21.10 / Log parameter lookup failures due to missing config file
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7396 NAS-111993 / 21.10 / Shift wsdd setup to post_init
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#7398 NAS-111995 / 21.10 / Fix out of order operations in applying smb config
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7400 NAS-111997 / 21.10 / Properly retrieve registry config and ACLs in SMB debug
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira, backport-21.08-BETA.1

#7404 NAS-112001 / 21.10 / Deprecate heimdal portion of kerberos plugin
  src/middlewared/middlewared/etc_files/krb5.conf.mako
  src/middlewared/middlewared/etc_files/krb5.keytab.py
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#7432 NAS-112081 / 21.10 / Ignore deletion of hidden daatset clones such as `%recv` dataset crea…
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: backport-21.08-BETA.1

#7441 NAS-112090 / 21.10 / Add dump endpoint for or-operator schema
  src/middlewared/middlewared/schema.py
Labels: jira

#7440 NAS-112089 / 21.10 / Add returns to filesystem acl
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7416 NAS-112034 / 21.10 / Add smb data to account plugin
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/admin_group.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira

#7437 NAS-111634 / 12.0 / Correctly generate configuration for remote syslog with TLS
  src/middlewared/middlewared/alembic/versions/12.0/2021-09-30_18-42_syslog_ca.py
  src/middlewared/middlewared/etc_files/syslogd.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.10

#7435 NAS-112084 / 12.0 / Add accepts to do_ldap_query
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/schema.py
Labels: jira, backport-13.0
