Repository truenas/middleware, pull requests merged in 2021-11, with the labels that each got.

#7803 NAS-113157 / 12.0 / Fix ordering of crossrename and recycle.
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#7798 NAS-113134 / 22.02-RC.2 / Allow call("pool.query", [], {"extra": {"is_upgraded": true}}) to avo…
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7815 NAS-113160 / 22.02-RC.2 / fix KeyError when moving user homedir
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0

#7812 NAS-113180 / 22.02-RC.2 / Blacklist `interfaces` global parameter in SMB config
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7828 NAS-113237 / 22.02-RC.2 / add more unit tests for dmi parsing
  src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py
Labels: jira

#7810 NAS-113175 / 22.02-RC.2 / Remove chart context added when doing validation
  src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
Labels: jira

#7837 NAS-113268 / 22.02-RC.2 / Mark macvtapX as an internal interface
  src/middlewared/middlewared/plugins/interface/internal_ifaces.py
Labels: jira

#7831 NAS-113252 / 22.02-RC.2 / Show correct choices for ups ports
  src/middlewared/middlewared/plugins/ups.py
Labels: jira

#7838 NAS-113272 / 22.02-RC.2 / Do not repeatedly log same error
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
Labels: jira

#7840 NAS-113280 / 22.02-RC.2 / `{"ha_sync": False}` option for queries that should not be synchroniz…
  src/middlewared/middlewared/plugins/datastore/connection.py
  src/middlewared/middlewared/plugins/datastore/write.py
  src/middlewared/middlewared/plugins/failover_/journal.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
Labels: jira, backport-13.0

#7847 NAS-113287 / 22.02-RC.2 / Fix `Attribute` constructor arguments typos and fix the bug that made…
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/vm/vms.py
  src/middlewared/middlewared/schema.py
Labels: jira, backport-13.0

#7842 NAS-113034 / 22.02-RC.2 / prevent some db queries on passive
  src/middlewared/middlewared/plugins/keyvalue.py
  src/middlewared/middlewared/plugins/migration.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-13.0

#7843 NAS-113281 / 22.02-RC.2 / only run ssh.save_keys when necessary
  src/middlewared/middlewared/plugins/ssh.py
Labels: backport-13.0

#7846 NAS-113288 / 22.02-RC.2 / Fix a couple of incorrect schemas
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#7856 NAS-113312 / 22.02-RC.2 / fix smb cluster api tests
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira

#7855 NAS-113310 / 12.0 / Work around flaky NIS domains
  src/middlewared/middlewared/alert/source/nis.py
  src/middlewared/middlewared/etc_files/nsswitch.conf
  src/middlewared/middlewared/plugins/nis.py
Labels: jira, backport-13.0

#7858 NAS-113316 / 22.02-RC.2 / fix event that is sent when gluster vol is deleted
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#7863 NAS-113327 / 22.02-RC.2 / fix cluster smb api tests (round 2)
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira

#7868 NAS-113352 / 12.0 / Make sure SED disks are unlocked on HA systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: jira

#7871 NAS-113365 / 22.02-RC.2 / Update payload for catalog.items job in api tests
  tests/api2/test_108_catalog.py
Labels: jira

#7874 NAS-113367 / 12.0 / Allow larger reporting databases
  src/middlewared/middlewared/alert/source/reporting_db.py
Labels: backport-22.02-RC.2

#7880 NAS-113400 / 22.02-RC.2 / timeout ix-zfs.service after 15mins at boot time
  debian/debian/ix-zfs.service
Labels: jira

#7882 NAS-113413 / 12.0 / add R50B model to license alert
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
Labels: jira

#7883 NAS-113417 / 22.02-RC.1-2 / fix event that is sent when gluster vol is deleted (#7858)
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#7888 NAS-113427 / 22.02-RC.2 / missing f-string formatter in cluster.localevents
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
Labels: jira

#7884 NAS-113420 / 22.02-RC.2 / simplify SCALE HA duplicate failover event logging
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira

#7895 NAS-113391 / 12.0 / Fix nsswitch generation
  src/middlewared/middlewared/etc_files/nsswitch.conf
Labels: backport-13.0

#7899 NAS-113460 / 12.0 / Shift order nsswitch generation in LDAP plugin
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-13.0

#7904 NAS-113466 / 12.0 / Manage LDAP service state during service start
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-13.0

#7906 NAS-113468 / 22.02-RC.2 / Only run nscd when LDAP is enabled
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: jira

#7908 NAS-113473 / 22.02-RC.2 / Add acls to debug
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: jira

#7913 NAS-113487 / 22.02-RC.2 / Have humanized app version for history of chart releases
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#7918 NAS-113561 / 22.02-RC.2 / fix fstype parsing in filesystem.statfs
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira
