Repository truenas/middleware, pull requests merged in 2021-12, with the labels that each got.

#7919 NAS-113574 / 22.02-RC.2 / Skip statfs check on SMB path if it does not exist
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7920 NAS-113576 / 22.02-RC.2 / use PAM in sshd_config when AD is configured to allow PAM
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
Labels: jira

#7931 NAS-113608 / 22.02-RC.2 / Fix job progress statement for ctdb plugin
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
Labels: jira

#7925 NAS-113592 / 22.02-RC.2 / Generate new user `uid` before chowning his home directory to that uid
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#7936 NAS-113631 / 22.02-RC.2 / Fix bug in initializing hwm in winbindd_idmap.tdb
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira

#7937 NAS-113632 / 22.02-RC.2 / Ensure rid value consistency between user/group name changes
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: jira

#7940 NAS-113664 / 22.02 / Add required parameters for fsrvp in SCALE
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: jira

#7948 NAS-113692 / 22.02 / Fix FTP test asset
  src/middlewared/middlewared/test/integration/assets/ftp.py
Labels: backport-22.02-RC.2

#7962 NAS-113744 / 13.0 / prevent endless loop in hook_setup_ha on CORE
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#7965 NAS-113753 / 22.02 / Fix nested `Dict` validation error attribute name
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/pytest/unit/test_validators.py
  src/middlewared/middlewared/schema.py
Labels: jira

#7945 NAS-113687 / 22.02 / Document Boot CD and Python packages
  docs/Makefile
  docs/source/middleware/jobs.rst
  docs/source/middleware/plugins/index.rst
  docs/source/os/boot-cd.rst
  docs/source/os/index.rst
  docs/source/os/python.rst
  docs/source/testing/integration-tests/mock.rst
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/test/integration/utils/pool.py
  src/middlewared/middlewared/test/integration/utils/ssh.py
Labels: jira

#7967 NAS-113726 / 22.02 / Generate different UUID for each test alert
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-13.0

#7966 NAS-113754 / 22.02 / Remove unnecessary usage of parametrize in filesystem api test
  tests/api2/test_190_filesystem.py
Labels: jira

#7969 NAS-113758 / 22.02 / Bug fix for encryption summary of dataset
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02-RC.2

#7972 NAS-110853 / 22.02 / Download single dataset encryption key as a json file
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-13.0

#7974 NAS-113698 / 22.02 / Changed range_low to 1000000001 in test_035_ad_idmap.py
  tests/api2/test_035_ad_idmap.py
Labels: backport-22.02-RC.2

#7971 NAS-113041 / 13.0 / FTP TimeoutNoTransfer
  src/middlewared/middlewared/alembic.ini
  src/middlewared/middlewared/alembic/versions/13.0/2021-12-10_13-36_ftp_timeout_notransfer.py
  src/middlewared/middlewared/etc_files/local/proftpd.conf
  src/middlewared/middlewared/plugins/ftp.py
Labels: backport-22.02

#7981 NAS-113791 / 22.02 / Allow empty fromemail
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/validators.py
Labels: jira, backport-22.02-RC.2

#7984 NAS-113797 / 22.02 / prevent duplicate vlan entries in db
  src/middlewared/middlewared/plugins/interface/interface_types.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
Labels: backport-22.02-RC.2

#7985 NAS-113797 / 22.02-RC.2 / prevent duplicate vlan entries in db (by yocalebo)
  src/middlewared/middlewared/plugins/interface/interface_types.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
Labels: backport-13.0

#7989 NAS-104989 / 22.02 / Return IP network if schema wants an IP network
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
Labels: backport-13.0

#7993 NAS-113816 / 22.02 / Fix wsdd configuration generation
  src/middlewared/middlewared/etc_files/local/wsdd.conf.mako
Labels: jira

#7997 NAS-113698 / 22.02 / Added some sleeps in ad_idmap test 8
  tests/api2/test_035_ad_idmap.py
Labels: backport-22.02-RC.2

#7999 NAS-113835 / 22.02-RC.2 / Use html2text for PagerDuty
  src/middlewared/middlewared/alert/service/pagerduty.py
Labels: backport-22.02, backport-13.0

#8005 NAS-113852 / 13.0 / catch up dmi parsing in 13
  src/middlewared/middlewared/plugins/system_/dmi.py
  src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py
Labels: jira

#8013 NAS-113868 / 13.0 / Fix SyntaxError: 'await' outside async function
  src/middlewared/middlewared/plugins/hardware.py
Labels: jira

#8007 NAS-113856 / 22.02 / SQLAlchemy 1.4 does not use `default=` when adding a column through alembic
  docs/source/database/migrations.rst
  src/middlewared/middlewared/alembic/versions/12.0/2020-02-24_17-48_webdav_enable.py
  src/middlewared/middlewared/alembic/versions/12.0/2020-03-10_09-03_replication_readonly.py
  src/middlewared/middlewared/alembic/versions/12.0/2021-02-23_11-54_sudo_nopasswd_commands.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-03-31_21-15_gpu_isolation.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-06-10_11-30_configure_gpus_k8s.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-08-02_13-13_vm_video_device.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-08-19_09-30_ca_trusted_store.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-11-09_22-08_add_servicelb_toggle.py
Labels: jira, backported, backport-13.0

#8015 NAS-113857 / 22.02 / return SCALE_ENTERPRISE on r-series hardware
  src/middlewared/middlewared/plugins/system.py
Labels: backport-22.02-RC.2

#8017 DOCS-2981 / Added longer sleeps to ad_idmap test 8
  tests/api2/test_025_chart_release.py
  tests/api2/test_035_ad_idmap.py
  tests/functions.py
Labels: backport-22.02-RC.2

#8034 NAS-113494 / 22.02 / speed up disk wiping
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-13.0

#8036 NAS-113791 / 22.02 / dont forcefully run fenced on single controllers
  src/middlewared/middlewared/plugins/failover_/fenced.py
Labels: backport-13.0

#8038 NAS-106633 / 13.0 / Fix: cron restart does not work
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: backport-12.0

#8040 NAS-113958 / 13.0 / fix issues in disk_info_freebsd.py
  src/middlewared/middlewared/plugins/disk_/disk_info_freebsd.py
Labels: backport-12.0

#8042 NAS-113951 / 22.02 / Better asserts in test_filesystem__file_tail_follow__grouping
  tests/api2/test_filesystem__file_tail_follow.py
Labels: skip jira status

#8031 NAS-113776 / 12.0 / Fix TLS certificate issue on Minio web console
  src/middlewared/middlewared/alembic/versions/12.0/2021-12-22_12-59_add_server_tls_uri_to_s3_config.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/s3.py
Labels: skip jira status

#8052 NAS-114027 / 13.0 / Fix TLS certificate issue on Minio web console (cherry-picked from 12.0-stable)
  src/middlewared/middlewared/alembic/versions/12.0/2021-12-22_12-59_add_server_tls_uri_to_s3_config.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/s3.py
Labels: jira

#8063 NAS-113631 / 12.0 / Fix bug in initializing hwm in winbindd_idmap.tdb
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: backport-13.0

#8062 NAS-114020 / 13.0 / Fix MinioFSAttachmentDelegate.query (by themylogin)
  src/middlewared/middlewared/plugins/s3_/attachments.py
Labels: backport-12.0

#8071 NAS-113409 / 12.0 / Fix `iscsi.global.sessions`
  src/middlewared/middlewared/plugins/iscsi_/global_freebsd.py
Labels: backport-13.0

#8069 NAS-114029 / 22.02 / Print full name of the plugin being initialized
  src/middlewared/middlewared/main.py
Labels: jira, backport-13.0

#7978 NAS-113789 / 22.02 / Allow enabling multichannel SMB through API validation
  src/middlewared/middlewared/plugins/smb.py
Labels: jira
