Repository truenas/middleware, pull requests merged in 2021-07, with the labels that each got.

#7099 NAS-111175 / 21.08 / add xmit_hash_policy and lacpdu_rate for lagg interfaces
  src/middlewared/middlewared/alembic/versions/21.MM/2021-06-29_add_xmit_hash_policy_and_lacpdu_rate.py
  src/middlewared/middlewared/plugins/interface/lag.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/lagg.py
  src/middlewared/middlewared/plugins/network.py
Labels: pending QA

#7102 NAS-111259 / 21.08 / Fix R20/R20A to comply to enclosure management NEP
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7106 NAS-111273 / 21.08 / Fix R50 to comply with enclosure NEP
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/concatenate.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7109 NAS-111296 / 21.08 / Update certificate/ca return type entry
  src/middlewared/middlewared/plugins/crypto.py
Labels: jira

#7120 NAS-111339 / 21.08 / Add iptables rules with counters to debug
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: jira

#7123 NAS-111343 / 21.08 / Additional Enclosure Fixes
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7130 NAS-111350 / 21.08 / only log pyroute2.NDB errors
  src/middlewared/middlewared/logger.py
Labels: jira

#7131 NAS-111360 / 21.08 / Add ipsets to debug
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: jira

#7126 NAS-111344 / 21.08 / Log error(s) if we fail to add/remove iptable rules for k8s
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#7136 NAS-111368 / 21.08 / Bug fix for syslog log level
  src/middlewared/middlewared/plugins/ups.py
Labels: jira

#7133 NAS-111335 / 12.0 / Fix Syntax error: "}" unexpected (expecting "fi"
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
Labels: backport-21.08

#7134 NAS-111188 / 12.0 / support.new_ticket should fully consume system.debug file to prevent …
  src/middlewared/middlewared/plugins/support.py
Labels: backport-21.08

#6955 NAS-111042 / 12.0 / pool.dataset: optimized create/update operations
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#7144 NAS-111390 / 21.08 / Enclosure Management fix for R20A.
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7151 NAS-111399 / 21.08 / fix NDB() instantiation
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
Labels: jira

#7154 NAS-111406 / 21.08 / Fix for mini-3.0-xl+ 2.5 inch drive bays being swapped.
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-12.0, jira

#7156 NAS-108723 / 21.08 / Implement NVMe resize in disk_resize for FreeBSD.
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-12.0, backport-13.0, jira

#7008 NAS-110987 / 21.08 / Dataset checksum
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#7152 NAS-111402 / 21.08 / Fix api tests for ups plugin
  tests/api2/test_530_ups.py
Labels: jira

#7165 NAS-111415 / 21.08 / Update chart.release.scale api tests
  tests/api2/test_305_container.py
  tests/api2/test_306_chart_release.py
Labels: jira

#7167 NAS-108723 / 21.08 / Correct NVMe capacity check in disk_resize.
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-12.0, backport-13.0

#7171 NAS-111424 / 21.08 / Bug fix for retrieving catalog item versions in api tests
  tests/api2/test_306_chart_release.py
Labels: jira

#7174 NAS-111430 / 21.08 / Allow disabling post-error cleanup for debugging purposes
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/plugins/update_/download_freebsd.py
  src/middlewared/middlewared/plugins/update_/install.py
  src/middlewared/middlewared/plugins/update_/install_freebsd.py
  src/middlewared/middlewared/plugins/update_/install_linux.py
  src/middlewared/middlewared/plugins/update_/pending_freebsd.py
  src/middlewared/middlewared/plugins/update_/trains_freebsd.py
  src/middlewared/middlewared/plugins/update_/upload_location_freebsd.py
  src/middlewared/middlewared/plugins/update_/utils_freebsd.py
Labels: jira

#7172 NAS-111427 / 21.08 / Bug fix for catalog item migration handling
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: jira

#7180 NAS-111422 / 12.0 / fix issues in enclosure.sync_zpool
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-21.08

#7182 NAS-111462 / 12.0 / fix license detection on r-series devices
  src/freenas/usr/local/lib/middlewared_truenas/plugins/truenas.py
Labels: backport-21.08

#7190 NAS-111482 / 21.08 / Add configuration entries for SMB multichannel
  src/middlewared/middlewared/alembic/versions/21.MM/2021-07-20_15-49_add_multichannel_support.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#7203 NAS-111505 / 21.08 / Add support for fuse-mounted paths to filesystem plugin
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira

#7205 NAS-111511 / 21.08 / automatic configuration of ctdb clustering daemon
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/plugins/gluster_linux/peer.py
  src/middlewared/middlewared/webhooks/cluster_events.py
Labels: jira

#7210 NAS-111531 / 21.08 / make sure xmit hash and lacpdu rate are reported in iface_extend
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#7211 NAS-111532 / 21.08 / fix xmit-hash and lacpdu rate on iface update
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#7193 NAS-111487 / 12.0 / Do not crash pool.dataset.kill_processes if a process has terminated on its own (by themylogin)
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/service.py
Labels: jira

#7214 NAS-111538 / 21.08 / raise CallError on cluster api events
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
Labels: jira

#7220 NAS-111556 / 21.08 / Bug fix for iptables getting out of sync
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#7224 NAS-111568 / 21.08 / Bug fix for collectd configuration generation
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
Labels: jira

#7235 DOCS-2422 / 12.0 / Changing the timeout for plex job api test to 20 minutes
  tests/api2/plugin.py
Labels: backport-13.0

#7229 NAS-111578 / 21.08 / Clear cached chart releases when stopping k8s
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
Labels: jira
