Repository truenas/middleware, pull requests merged in 2021-05, with the labels that each got.

#6833 NAS-110334 / 21.06 / Store middleware job logs in the system dataset
  src/freenas/usr/local/bin/ixdiagnose
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/service.py
Labels: backport-12.0

#6800 NAS-110174 / 12.0 / WBC_ERR_WINBIND_NOT_AVAILABLE is not an SSH login failure
  src/middlewared/middlewared/alert/source/ssh_login_failures.py
  src/middlewared/middlewared/pytest/unit/alert/source/test_ssh_login_failures.py
Labels: backport-21.06

#6824 NAS-110401 / 12.0 / Fix regression in service restart after pool decryption
  src/middlewared/middlewared/plugins/pool_/encryption_freebsd.py
Labels: jira

#6657 NAS-109545 / 12.0 / Prevent nested loop queries in iscsi.target
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-21.06, backported

#6836 NAS-110510 / 21.06 / Only delete jobs log dir if it exists
  src/middlewared/middlewared/job.py
Labels: jira

#6837 NAS-110511 / 21.06 / Bug fixes for setting system birthday
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#6838 NAS-110513 / 21.06 / Indicate we failed to retrieve catalog items in catalog.query response
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#6860 NAS-110362 / 21.06 / Fix syntax error in SSSD-compatibility idmap config
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-12.0

#6857 NAS-110566 / 21.06 / Remove unused quotes for chart release update alerts
  src/middlewared/middlewared/alert/source/applications_linux.py
  src/middlewared/middlewared/alert/source/catalogs.py
Labels: jira

#6858 NAS-110509 / 21.06 / Do not report successful S.M.A.R.T. test starts on SCSI/SAS drives as…
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-12.0

#6869 NAS-110496 / 12.0 / Explicitly set system dataset to readonly=off
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-21.06

#6871 NAS-110576 / 12.0 / R20A enclosure support
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-21.06

#6873 NAS-110602 / 12.0 / Fix concatenating enclosures
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/concatenate.py
Labels: backport-21.06

#6884 NAS-110618 / 21.06 / Start SSH service on SSH pairing
  src/middlewared/middlewared/plugins/keychain.py
Labels: backport-12.0, jira

#6886 NAS-110575 / 12.0 / Stop TrueCommand connection on BACKUP node
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/truecommand/__init__.py
Labels: backport-21.06, backported

#6889 NAS-110667 / 21.06 / Add testparm output to debug
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: backport-12.0, jira

#6892 NAS-110689 / 21.06 / Only consider interfaces in database for dhcp/ipv6 autoconfiguration
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#6895 NAS-110701 / 21.06 / Remove copy-paste error from old AD LDAP code.
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-12.0, jira

#6899 NAS-110715 / 21.06 / Do not normalize docker tag when updating app
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: jira

#6917 NAS-110779 / 21.06 / Consistently retrieve boot time
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0

#6835 NAS-110502 / 21.06 / Implement nfs4acl management features
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#6932 NAS-110822 / 21.06 / Correctly compare nfs4 key when creating dataset
  src/middlewared/middlewared/plugins/pool.py
Labels: jira
