Repository truenas/middleware, pull requests merged in 2021-02, with the labels that each got.

#6347 NAS-109140 / 12.0 / fix RuntimeWarning on python3.8
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.02

#6348 NAS-109230 / 21.02 / zettarepl.datasets_have_encryption
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-12.0, jira

#6356 NAS-109242 / 21.02 / Fix List() schema with multiple dict "items"
  src/middlewared/middlewared/schema.py
Labels: jira

#6365 NAS-109251 / 12.0 / Fix coroutine never awaited
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-21.02, jira

#6366 NAS-109066 / 12.0 / Fix "This rsync lacks old-style --compress due to its external zlib. …
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-21.02

#6363 NAS-109250 / 12.0 / Fix enclosure.sync_zpool KeyError
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-21.02, jira

#6372 NAS-109264 / 21.02 / Do not show "Controller A" for non-HA systems
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-12.0

#6346 NAS-109228 / 21.02 / Allow running a migration for chart release upgrades
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: jira

#6376 NAS-109279 / 21.02 / Allow consumer to specify which properties to retrieve for datasets
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6377 NAS-109285 / 21.02 / Send a changed event after chart release upgrade completes
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: jira

#6385 NAS-109298 / 12.0 / fix send_event usage for system ready
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-21.02

#6381 NAS-109291 / 21.02 / Add validation for catalog label
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#6382 NAS-109292 / 21.02 / Bug fix for chart release name regex
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6357 NAS-108932 / 12.0 / GMail fixes
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/mail_/gmail.py
Labels: backport-21.02

#6136 NAS-106689 / 12.0 / Ensure HBA update is to latest approved hba version and not just that…
  src/freenas/usr/local/sbin/firmware_update.py
Labels: backport-21.02

#6278 NAS-108956 / 12.0 / Always terminate rsync if pool import disk fails
  src/middlewared/middlewared/plugins/pool_/import_disk.py
Labels: backport-21.02

#6320 NAS-109101 / 12.0 / Support NFS41 VMware datastore
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-21.02

#6360 NAS-109032 / 12.0 / Account for cores dataset snapshots when evaluating its size and dest…
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-21.02

#6361 NAS-109034 / 12.0 / Postpone sending init-time oneshot alerts until the system is ready
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-21.02

#6364 NAS-109078 / 12.0 / Explain system.info license addhw
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/utils/license.py
Labels: backport-21.02

#6362 NAS-109031 / 12.0 / from middlewared.utils.network import INTERNET_TIMEOUT
  src/middlewared/middlewared/alert/service/mattermost.py
  src/middlewared/middlewared/alert/service/opsgenie.py
  src/middlewared/middlewared/alert/service/pagerduty.py
  src/middlewared/middlewared/alert/service/slack.py
  src/middlewared/middlewared/alert/service/victorops.py
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/update_/trains.py
  src/middlewared/middlewared/utils/network.py
Labels: backport-21.02, backported

#6280 NAS-108154 / 12.0 / max_parallel_replication_tasks
  .gitignore
  src/middlewared/middlewared/alembic/versions/12.0/2020-12-10_20-38_replication_config.py
  src/middlewared/middlewared/plugins/replication_/config.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-21.02

#6421 NAS-109411 / 21.04 / Add encryption summary for pools in debug
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: jira

#6389 NAS-109310 / 21.04 / new firmware for E16 expansion shelf
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure.py
Labels: backport-12.0

#6423 NAS-109418 / 21.04 / Properly set error code if dataset is busy on deletion
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira

#6414 NAS-109344 / 21.04 / Keep track of catalog repo/branches for installed chart releases
  src/middlewared/middlewared/plugins/usage.py
Labels: jira

#6397 NAS-109328 / 21.04 / Register events of services as private which are private themselves
  src/middlewared/middlewared/service.py
Labels: jira

#6396 NAS-109327 / 21.04 / Remove temporary wrapper to start kubernetes service
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#6416 NAS-109350 / 21.04 / Make UPSRemainingBatteryPlugin report minutes
  src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
Labels: backport-12.0

#6429 NAS-109408 / 21.04 / Fix firmware path
  nas_ports/freenas/firmware/Makefile
  nas_ports/freenas/firmware/distinfo
Labels: backport-12.0, backport-21.02

#6335 NAS-109177 / 12.0 / Clean up LDAP error messages and fix call to set ldap passwd
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-21.04, jira

#6432 NAS-109440 / 21.04 / Fix migration revision id
  src/middlewared/middlewared/alembic/versions/12.1/2021-02-10_13-53_.py
Labels: jira

#6433 NAS-109441 / 21.04 / Properly send events for event sources when arguments are specified
  src/middlewared/middlewared/common/event_source/manager.py
  src/middlewared/middlewared/main.py
Labels: jira

#6405 NAS-108421 / 21.04 / Report proper memory classes in reporting.realtime
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: backport-12.0

#6442 NAS-109403 / 21.04 / Use IEC units for replication progress
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-12.0

#6440 NAS-109459 / 12.0 / Try enabling capabilities at once for interfaces
  src/middlewared/middlewared/plugins/interface/capabilities_freebsd.py
Labels: jira

#6438 NAS-109474 / 12.0 / Reconfigure zettarepl_file logger on system dataset reconfiguration
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/service.py
Labels: backport-21.04, jira

#6451 NAS-109434 / 21.04 / Avoid AD connectivity check in update() method
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-12.0

#6452 NAS-109452 / 21.04 / Bring back disk removal event
  src/middlewared/middlewared/plugins/datastore/event.py
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-12.0

#6390 NAS-109321 / 21.04 / Add basic pseudo service for directory services cache
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: jira

#6448 NAS-109371 / 21.04 / Recursively delete snapshots of vm zvols when deleting vms
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: backport-12.0

#6447 NAS-109435 / 21.04 / Restart UI after some X seconds
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0

#6459 NAS-109526 / 21.04 / Use get_instance endpoint when using middleware call
  src/middlewared/middlewared/etc_files/local/minio/certificates.py
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/jail_freebsd.py
  src/middlewared/middlewared/plugins/kmip/update.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#6460 NAS-109523 / 21.04 / Remove minio certs directory when certificates are not configured
  src/middlewared/middlewared/etc_files/local/minio/certificates.py
Labels: backport-12.0

#6463 NAS-109528 / 21.04 / ignore `docs` folder for train validation
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6465 NAS-109534 / 21.04 / Fix service query
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-12.0, jira

#6436 NAS-109454 / 12.0 / Don't generate corefile alerts on enterprise product
  src/freenas/usr/local/bin/ixdiagnose
  src/middlewared/middlewared/alert/source/cores.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.04, jira

#6466 NAS-109533 / 21.04 / Use colon to concatenate repository and tag for ix-chart
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6475 NAS-109549 / 21.04 / Add human version for catalog items
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6476 Remove core files after setting up system dataset
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.04

#6478 NAS-109555 / 21.04 / Add endpoint to retrieve valid system dataset pool choices
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#6479 NAS-109560 / 21.04 / Retrieve timestamps for each pod log entry
  src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
Labels: jira

#6426 NAS-109430 / 12.0 / Improve error handling for directory services
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-21.04, jira

#6473 NAS-107219 / 12.0 / Allow passwordless sudo
  src/middlewared/middlewared/alembic/versions/12.0/2021-02-23_11-54_sudo_nopasswd_commands.py
  src/middlewared/middlewared/etc_files/local/sudoers
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/nis.py
Labels: backport-21.04

#6487 NAS-109581 / 12.0 / Filter existing alerts by product_type
  src/middlewared/middlewared/alert/source/cores.py
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-21.04

#6486 NAS-109585 / 12.0 / Give proper replication and periodic snapshot task debug
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: backport-21.04, jira

#6482 NAS-109020 / 12.0 / Fix various pwenc related issues
  src/middlewared/middlewared/etc_files/local/ssh/config.py
  src/middlewared/middlewared/plugins/crypto.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: backport-21.04

#6494 NAS-109597 / 21.04 / fix FailoverService HA_MODE/LICENSE attributes
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py
Labels: backport-12.0

#6498 NAS-109602 / 12.0 / fix AttributeError in event_loop_execution in vm plugin
  src/middlewared/middlewared/plugins/vm_/events.py
Labels: backport-21.04

#6496 NAS-109599 / 12.0 / fix KeyError in jails
  src/middlewared/middlewared/plugins/jail_freebsd.py
Labels: backport-21.04

#6445 NAS-109273 / 21.04 / Do not remove encryption keys if pool is not found
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-12.0

#6497 NAS-109545 / 21.04 / middlewared/iscsi: skip reload after extent creation
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-12.0, backported, skip jira status

#6506 NAS-109545 / 12.0 / middlewared/iscsi: skip reload after extent creation (by rkojedzinszky)
  src/middlewared/middlewared/plugins/iscsi.py
Labels: skip jira status

#6502 NAS-109605 / 21.04 / Validate certificate while creating/updating idmap
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#6507 NAS-109610 / 12.0 / ignore proxy settings when downloading debug from standby
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.04
