Repository truenas/middleware, pull requests merged in 2021-01, with the labels that each got.

#6209 NAS-108666 / 21.02 / prevent netcli from hanging on sockstat calls by redoing get_ui_urls
  src/freenas/etc/netcli
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0

#6221 NAS-108904 / 21.02 / Fix FreeNASBMCAlertClass
  src/middlewared/middlewared/alert/source/freenas_bmc.py
Labels: backport-12.0, jira

#6223 NAS-108905 / 21.02 / Require private key to be present when importing CSR
  src/middlewared/middlewared/plugins/crypto.py
Labels: backport-12.0, jira

#6225 NAS-108625 / 21.02 / Fix FTP onlyanonymous/anonpath logic
  src/middlewared/middlewared/plugins/ftp.py
Labels: backport-12.0

#6227 NAS-108796 / 21.02 / Do not receive sharenfs and sharesmb properties when replicating
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-12.0

#6204 NAS-108762 / 12.0 / Create VLAN network interface database record from netcli
  src/freenas/etc/netcli
Labels: backport-21.02

#6219 NAS-108900 / 12.0 / Add exception handling for setting NTP in AD plugin
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-21.02, jira

#6210 NAS-108837 / 21.02 / fix _register_virthostname in ad plugin
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-12.0

#6199 NAS-108912 / 12.0 / Add basic SMB protocol testing functions
  tests/protocols.py
Labels: backport-21.02, jira

#6236 NAS-108657 / 21.02 / Change replication task schedule logic
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-12.0

#6240 NAS-108794 / 21.02 / prevent lagg members as parent interface choices for vlan interfaces
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#6244 NAS-108444 / 21.02 / prevent vlan interfaces as being choices for creating lagg/bond
  src/middlewared/middlewared/plugins/network.py
Labels: backport-12.0

#6246 NAS-108923 / 21.02 / Get more information for deployed resources in k8s cluster in debug
  src/freenas/usr/local/libexec/freenas-debug/kubernetes_linux/kubernetes.sh
Labels: jira

#6248 NAS-108928 / 12.0 / Fix logging in synchronize_registry
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#6254 NAS-108945 / 21.02 / only run get_remote_os_version() on HA systems
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/remote.py
Labels: backport-12.0

#6256 NAS-108946 / 21.02 / Do not process old k8s events
  src/middlewared/middlewared/plugins/kubernetes_linux/events.py
Labels: jira

#6257 NAS-108948 / 21.02 / Do not convert app-readme to html
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6249 NAS-108889 / 12.0 / Split middleware and winbind netlogon traffic between DCs
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-21.02

#6261 NAS-108953 / 21.02 / Correctly return empty response if there are no k8s backups
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: jira

#6262 NAS-108955 / 21.02 / Retrieve kubernetes event objects associated with a chart release
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/kubernetes_linux/events.py
Labels: jira

#6264 NAS-108960 / 12.0 / Fix replication test
  tests/api2/replication.py
Labels: backport-21.02, jira

#6145 NAS-108661 / 21.02 / Query Docs
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
Labels: jira

#6266 NAS-108969 / 21.02 / Fix event handler exception not being logged
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/etc.py
Labels: backport-12.0, jira

#6270 NAS-108976 / 21.02 / Properly handle service restart
  src/middlewared/middlewared/plugins/service.py
Labels: jira

#6273 DOCS-1600 / 12.0 / Changed the plugin API test sourcing of index_url*
  tests/api2/plugin.py
Labels: backport-12.1

#6275 NAS-108985 / 12.0 / Only output last 1000 lines of zpool history ioctls
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/system.py
Labels: backport-21.02

#6283 NAS-108997 / 21.02 / Bug fix for starting middleware with python3.9
  src/middlewared/middlewared/main.py
Labels: jira

#6285 NAS-108999 / 21.02 / Use cgroups v1 for k8s
  src/freenas/usr/local/bin/truenas-grub.py
Labels: jira

#6271 NAS-108979 / 21.02 / Properly setup k3s agent
  src/middlewared/middlewared/etc_files/rancher/node/node_passwd.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py
  src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
Labels: jira

#6288 NAS-109015 / 21.02 / Specially handle TN system related datasets
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/ix_volumes.py
  src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: jira

#6287 NAS-109008 / 21.02 / Reserve library name in catalogs
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6274 NAS-108988 / 21.02 / Bring back toggle_attachments in pool.dataset.unlock
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#6301 NAS-109045 / 21.02 / Serialize passdb modifications
  src/middlewared/middlewared/plugins/account.py
Labels: backport-12.0

#6300 NAS-109080 / 21.02 / Retrieve chart release schema for installed chart releases
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: jira

#6294 NAS-109067 / 21.02 / Update image cache after pulling docker image
  src/middlewared/middlewared/plugins/docker_linux/images.py
  src/middlewared/middlewared/plugins/docker_linux/update_alerts.py
Labels: jira

#6291 NAS-109064 / 21.02 / Allow to not retrieve children of a dataset
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira

#6305 NAS-109088 / 21.02 / Make GPU label more descriptive
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#6304 NAS-109037 / 21.02 / set comconsole,efi on UEFI booted mseries systems
  src/freenas-installer/etc/install.sh
  src/middlewared/middlewared/etc_files/loader.py
Labels: backport-12.0

#6299 NAS-109047 / 21.02 / use iptables to allow/disallow network traffic on failover event for SCALE HA
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event_linux.py
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/iptables_linux.py
Labels: pending QA

#6313 NAS-109050 / 21.02 / Fix the year in motd
  src/middlewared/middlewared/etc_files/motd.mako
  src/middlewared/middlewared/plugins/system.py
Labels: backport-12.0

#6315 NAS-109136 / 21.02 / Isolate kubernetes cluster
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
Labels: jira

#6321 NAS-109030 / 12.0 / services_iscsitargetauthcredential peeruser and peersecret are not nullable
  src/middlewared/middlewared/plugins/iscsi.py
Labels: backport-21.02

#6325 NAS-109141 / 12.0 / Properly pass LDAP errors into validation errors
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-21.02

#6330 NAS-109164 / 21.02 / dont traceback in ctdb.general.healthy
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira

#6331 NAS-109170 / 21.02 / start/stop ctdbd service with glusterd
  src/middlewared/middlewared/plugins/service_/services/glusterd.py
Labels: jira

#6332 NAS-109173 / 21.02 / middleware job - re-raise existing CallError
  src/middlewared/middlewared/job.py
Labels: backport-12.0, jira

#6334 NAS-109176 / 21.02 / add ctdb shared vol validation to gluster.volume CRUD API
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira
