Repository truenas/middleware, pull requests merged in 2021-10, with the labels that each got.

#7613 NAS-112632 / 21.10 / Start / stop idmap service when clearing idmap cache
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#7623 NAS-112357 / 21.10 / Do not include disks that do not spport S.M.A.R.T. in smart.test.disk…
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-12.0

#7621 NAS-112669 / 21.10 / Fix SMB config generation issues when clustered
  src/middlewared/middlewared/etc_files/local/smb4.conf.mako
  src/middlewared/middlewared/plugins/service_/services/ctdb.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/registry_share.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/plugins/tdb/base.py
Labels: jira

#7611 NAS-112627 / 12.0 / make DiskStats not suck
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/plugins/reporting/iostat.py
Labels: backport-21.10

#7790 NAS-112666 / 22.02-RC.2 / Do not sleep in the ZFS process pool while performing a scrub
  src/middlewared/middlewared/apidocs/templates/websocket/events.md
  src/middlewared/middlewared/plugins/boot.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-13.0

#7795 NAS-113133 / 22.02-RC.2 / Allow updating anything to MASTER release
  src/middlewared/middlewared/plugins/update_/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_utils.py
Labels: jira

#7752 Bug fix and add more security headers
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-12.0
