Repository truenas/middleware, pull requests merged in 2022-01, with the labels that each got.

#8086 NAS-114130 / 22.02 / Correctly recognize wg/macvtap interfaces as cloned interfaces
  src/middlewared/middlewared/plugins/interface/internal_ifaces.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
Labels: jira

#8082 NAS-114116 / 13.0 / Make minio console port configurable
  src/middlewared/middlewared/alembic/versions/12.0/2022-01-03_11-46_add_s3_console_bindport.py
  src/middlewared/middlewared/etc_files/rc.conf.py
  src/middlewared/middlewared/plugins/s3.py
Labels: jira, backport-12.0

#8089 NAS-114135 / 22.02 / Correctly raise assertion error in api tests
  tests/api2/test_025_chart_release.py
Labels: jira

#8092 NAS-114122 / 22.02 / Set urllib3 logging level to warning
  src/middlewared/middlewared/logger.py
Labels: skip jira status

#8093 NAS-114159 / 22.02 / Fix building docs
  docs/install.sh
Labels: jira

#8094 NAS-114164 / 12.0 / Disable SMB1 Unix Extensions by default
  src/middlewared/middlewared/etc_files/local/smb4.conf
Labels: jira

#8096 NAS-114170 / 22.02 / Properly check catalog dataset is locked
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira

#8099 NAS-113967 / 13.0 / Fix `Unable to downgrade from TrueNAS-12.0-U7 to TrueNAS-12.0-U7`
  src/middlewared/middlewared/plugins/update_/install_freebsd.py
  src/middlewared/middlewared/plugins/update_/install_linux.py
Labels: backport-22.02

#8101 NAS-113727 / 13.0 / Fix a deadlock situation when creating many snapshots simultaneously
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/utils/service/call.py
  src/middlewared/middlewared/worker.py
Labels: backport-12.0

#8107 NAS-114188 / 13.0 / Use correct parameter for base user quota
  tests/api2/test_425_smb_protocol.py
Labels: jira

#8108 NAS-114189 / 22.02 / Fix a few schema errors discovered when performing integration tests …
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#8106 NAS-114187 / 22.02 / Add allow interfaces directive to avahi config
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf.mako
Labels: jira

#8116 NAS-114226 / 22.02 / Do not enable waagent automatically
  src/middlewared/middlewared/plugins/system.py
Labels: jira

#8118 NAS-114230 / 13.0 / fix typo in hardware.py
  src/middlewared/middlewared/plugins/hardware.py
Labels: jira

#8121 NAS-112667 / 13.0 / Set default max_parallel_replication_tasks to 5
  src/middlewared/middlewared/plugins/replication_/config.py
Labels: skip jira status, backport-22.02

#8123 NAS-114248 / 22.02 / Selectively handle auth header in docker client
  src/middlewared/middlewared/plugins/docker_linux/client.py
Labels: jira

#8100 NAS-114177 / 12.0 / fix disk.sync with multipath disks
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-22.02, backport-13.0

#8120 NAS-114239 / 12.0 / Add alert for CVE-2021-20316-related misconfiguration
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#8112 NAS-114223 / 22.02 / Do not take snapshot of docker dataset when making a backup of apps
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: jira

#8129 NAS-114279 / 22.02 / Reduce pyroute logs footprint in middleware logs
  src/middlewared/middlewared/logger.py
Labels: jira

#8134 NAS-114302 / 22.02 / Only log once that no enclosures were found
  src/middlewared/middlewared/plugins/enclosure.py
Labels: jira

#8135 NAS-113212 / 22.02 / Set sysctl panic tunables
  src/freenas/etc/sysctl.d/10-truenas.conf
Labels: jira

#8144 NAS-114353 / 22.02 / Do not run `disk.sync_all` on zvol creation/deletion
  src/middlewared/middlewared/plugins/disk_/disk_events.py
Labels: jira

#8146 NAS-114359 / 22.02 / Provide `exclude_mountpoint_property` for `replication.run_onetime` f…
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/zettarepl.py
  src/middlewared/middlewared/test/integration/assets/pool.py
  src/middlewared/middlewared/test/integration/utils/ssh.py
  tests/api2/test_cloudsync.py
  tests/api2/test_replication.py
  tests/api2/test_s3.py
Labels: jira

#8147 NAS-114360 / 22.02 / Correctly retrieve bus attribute for disk
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
Labels: jira

#8139 NAS-114333 / 13.0 / Expand `__[POSTCOMPILE_encrypted_provider_1` into valid SQL syntax
  src/middlewared/middlewared/plugins/datastore/connection.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
Labels: jira

#8140 NAS-113609 / 13.0 / Check for SATA DOM wear only on M- and Z-series, and only on `ada` boot pool devices
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/sata_dom_wear.py
Labels: backport-22.02

#8154 NAS-114381 / 22.02 / Increase acme.client logging level
  src/middlewared/middlewared/logger.py
Labels: jira

#8157 NAS-114398 / 13.0 / Properly use call_sync in synchronous method
  src/middlewared/middlewared/plugins/disk_/disk_info_freebsd.py
Labels: jira

#8141 NAS-114076 / 22.02 / Counterpart for truenas/py-libzfs#158
  src/middlewared/middlewared/plugins/pool.py
Labels: skip jira status, backport-13.0

#8162 NAS-114417 / 22.02 / Do not modify original create properties dict
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#8168 NAS-114427 / 13.0 / Load ctl.ko at boot
  src/freenas/etc/rc.conf
Labels: jira

#8169 NAS-114431 / 22.02 / VM performance improvements
  src/middlewared/middlewared/plugins/vm/events.py
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#8143 NAS-114176 / 22.02 / Do not crash cloud sync from snapshot when a zvol is present
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/test/integration/assets/pool.py
  tests/api2/test_cloudsync.py
Labels: backport-13.0

#8160 NAS-114149 / 22.02 / One sentence to document how CD image launches installer
  docs/source/os/boot-cd.rst
Labels: skip jira status

#8181 NAS-113781 / 22.02 / fix iftop spinning CPU at 100%
  src/freenas/usr/local/bin/snmp-agent.py
  src/freenas/usr/local/share/pysnmp/mibs/FREENAS-MIB.py
  src/freenas/usr/local/share/snmp/mibs/FREENAS-MIB.txt
  src/middlewared/debian/control
  src/middlewared/middlewared/alembic/versions/22.02/2022-01-25_18-25_remove_snmp_iftop_column.py
  src/middlewared/middlewared/plugins/snmp.py
Labels: backport-13.0

#8176 NAS-114501 / 22.02 / services/nfs - convert to kernel NFS server
  debian/debian/control
  src/freenas/usr/local/lib/collectd_pyplugins/nfsstat.py
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
  src/middlewared/middlewared/etc_files/default/nfs-common.mako
  src/middlewared/middlewared/etc_files/default/nfs-kernel-server.mako
  src/middlewared/middlewared/etc_files/default/rpcbind.mako
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/etc_files/ganesha/ganesha.conf.mako
  src/middlewared/middlewared/etc_files/idmapd.conf.mako
  src/middlewared/middlewared/etc_files/pam.d/common-password.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/nfs_/krb5.py
  src/middlewared/middlewared/plugins/nfs_/status.py
  src/middlewared/middlewared/plugins/service_/services/nfs.py
  tests/api2/test_032_ad_kerberos.py
Labels: jira
