Repository truenas/middleware, pull requests merged in 2022-06, with the labels that each got.

#9066 NAS-116500 / 22.12 / Remove widelinks from list of sample aux params for CI
  tests/api2/test_435_smb_registry.py
Labels: jira, backport-13.0, backport-22.02.2

#9065 NAS-116496 / 22.12 / Raise validation error on permissions changes to .zfs
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
Labels: jira, backport-22.02.2

#9074 NAS-116520 / 22.12 / Allow setting gid 0 on new groups
  src/middlewared/middlewared/plugins/account.py
Labels: jira, backport-13.0, backport-22.02.2

#9078 NAS-116522 / 22.12 / remove sockstat dependency
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
  src/middlewared/debian/control
Labels: jira, backport-22.02.2

#9080 NAS-116029 / 22.12 / Improve error handling in smb.sharesec and SID parsing
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/plugins/smb_/util_sd.py
Labels: backport-13.0, backport-22.02.2

#9089 NAS-116532 / 22.12 / Remove FreeBSD debug scripts
  src/freenas/usr/local/libexec/freenas-debug/doms_freebsd/doms.sh
  src/freenas/usr/local/libexec/freenas-debug/geom_freebsd/geom.sh
  src/freenas/usr/local/libexec/freenas-debug/ipmi_freebsd/ipmi.sh
  src/freenas/usr/local/libexec/freenas-debug/jails_freebsd/jails.sh
  src/freenas/usr/local/libexec/freenas-debug/kubernetes/kubernetes.sh
  src/freenas/usr/local/libexec/freenas-debug/ldap_freebsd/ldap.sh
  src/freenas/usr/local/libexec/freenas-debug/loader_freebsd/loader.sh
Labels: jira, backport-22.02.2

#9087 NAS-116531 / 22.12 / Fix AD debug script
  src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
Labels: jira, backport-22.02.2

#9086 NAS-115102 / 22.12 / Always restart SMB service on LDAP update
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-22.02.2

#9035 NAS-116203 / 22.02.2 / Improve zpool capacity alert, make it proactive, allow disabling proactive support for specific alert classes
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/boot_pool.py
  src/middlewared/middlewared/alert/source/nis_freebsd.py
  src/middlewared/middlewared/alert/source/smart.py
  src/middlewared/middlewared/alert/source/usb_storage.py
  src/middlewared/middlewared/alert/source/volume_rekey_freebsd.py
  src/middlewared/middlewared/alert/source/volume_status.py
  src/middlewared/middlewared/alert/source/zpool_capacity.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/alert.py
  tests/api2/test_060_alertclasses.py
  tests/api2/test_alert_classes.py
  tests/api2/test_zpool_capacity_alert.py
Labels: backport-22.12

#9095 NAS-116534 / 22.12 / bump event-timeout to 300 seconds
  src/freenas/etc/systemd/systemd-udevd.service.d/override.conf
Labels: backport-22.02.2

#9096 NAS-116535 / 22.12 / bump kernel.watchdog_thresh to 60 (2mins)
  src/freenas/etc/sysctl.d/10-truenas.conf
Labels: backport-22.02.2

#9105 NAS-116545 / 22.12 / Add key to SMB share presets to indicate cluster-safety
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.2

#9106 NAS-116546 / 22.12 / SCST rotational config option is 0 or 1
  src/middlewared/middlewared/etc_files/scst.conf.mako
Labels: jira, backport-22.02.2

#9109 NAS-116518 / 22.12 / fix SCST crash when migrating from CORE ctld
  src/middlewared/middlewared/etc_files/scst.conf.mako
Labels: backport-22.02.2

#9051 NAS-116470 / 22.12 / Ensure disk_choices methods don't show in-use zvols
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/vm/vm_devices.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
Labels: jira, backport-22.02.2

#9111 NAS-115435 / 22.12 / Fix GSSAPI config in LDAP config
  src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
  src/middlewared/middlewared/etc_files/local/nslcd.conf.mako
  src/middlewared/middlewared/etc_files/local/openldap/ldap.conf.mako
  src/middlewared/middlewared/plugins/ldap.py
Labels: backport-22.02.2

#9071 NAS-116484 / 22.02.2 / optimize disk.sync_all on SCALE
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/device_/device_info_base.py
  src/middlewared/middlewared/plugins/disk_/sync.py
  src/middlewared/middlewared/pytest/unit/plugins/disk/test_dev_to_ident.py
  src/middlewared/middlewared/pytest/unit/plugins/disk/test_ident_to_dev.py
Labels: backport-22.12

#9116 NAS-116220 / 13.0 / Fir crash on validation of inherited `special_small_block_size` and `…
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-22.12, backport-22.02.2

#9125 NAS-116568 / 22.02.2 / fix typo causing exorbitant memory usage
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: jira, backport-22.12

#9128 Fix iSCSI disk tests
  src/middlewared/middlewared/plugins/zfs.py
  tests/api2/test_iscsi.py
Labels: backport-22.02.2

#9130 NAS-116569 / 22.12 / Fix typo in SMB presets
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.2

#9123 NAS-116567 / 22.12 / Fix `rmtree_one_filesystem` error reporting
  src/middlewared/middlewared/utils/shutil.py
Labels: jira, backport-22.02.2

#9129 NAS-116566 / 22.02.2 / fix encrypted_provider and remove glob to optimize
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: backport-22.12

#9135 NAS-106532 / 22.02.2 / M50/M60 PLX Enclosures on SCALE
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/m50_plx.py
  src/middlewared/middlewared/plugins/enclosure_/m_series_nvme.py
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
  src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_m_series_nvme.py
  src/middlewared/middlewared/pytest/unit/requirements.txt
Labels: backport-22.12

#9143 NAS-116600 / 22.02.2 / Fix mseries nvme mapping
  src/middlewared/middlewared/plugins/enclosure_/m_series_nvme.py
Labels: jira, backport-22.12

#9142 NAS-116596 / 22.02.2 / fix AttributeError in disabled_reasons
  src/middlewared/middlewared/plugins/failover.py
Labels: jira

#9146 NAS-116602 / 22.12 / catch proper pyudev exception
  src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py
Labels: jira, backport-22.02.2

#9136 NAS-116584 / 22.12 / Add initial bunch of returns decorators to DS-related plugins
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/schema.py
Labels: jira, backport-22.02.2

#9150 Fix path validation for non-existent paths
  src/middlewared/middlewared/async_validators.py
Labels: backport-22.02.2

#9151 NAS-116613 / 22.12 / Fix async path validator
  src/middlewared/middlewared/async_validators.py
Labels: jira, backport-22.02.2

#9156 NAS-116626 / 13.0 / fix AttributeError crash in disk.sync_all
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#9157 NAS-116608 / 22.02.2 / fix enclosure mapping on MINI XL+ on SCALE
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-22.12

#9159 NAS-116630 / 22.12 / fix BHYVE disk serial detection on SCALE
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: jira, backport-22.02.2

#9100 NAS-116631 / 22.02.2 / `wait_to_hang_and_dump_core` script
  src/middlewared/middlewared/scripts/wait_to_hang_and_dump_core.py
  src/middlewared/setup.py
Labels: jira, backport-22.12

#9166 NAS-116304 / 22.02.2 / add r50 rear nvme drive mapping and simplify code
  src/middlewared/middlewared/plugins/enclosure_/map.py
  src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py
Labels: backport-22.12

#9173 NAS-116650 / 22.02.2 / fix NO_VIP check when bond iface is empty
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12

#9170 NAS-116646 / 22.02.2 / ctdb teardown method to resync interfaces
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira

#9176 NAS-116652 / 22.02.2 / fix SCALE HA detection on BHYVE VMs
  src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
Labels: jira, backport-22.12

#9162 NAS-116269 / 22.12 / validate user/group entries can execute on path in setacl
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  src/middlewared/middlewared/plugins/filesystem_/perm_check.py
  tests/api2/test_190_filesystem.py
Labels: backport-22.02.2

#9180 NAS-116657 / 22.02.2 / Fix `EventSource` error handling
  src/middlewared/middlewared/event.py
Labels: jira, backport-22.12

#9183 NAS-116659 / 22.02.2 / Fix iSCSI disk tests
  src/middlewared/middlewared/plugins/zfs.py
  tests/api2/test_iscsi.py
Labels: jira

#9187 NAS-116660 / 22.12 / Ensure that SMB service stays running after AD stop
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira, backport-22.02.2

#9190 NAS-115425 / 22.12 / Fix SMB service start on reboot for clustered truenas
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-22.02.2

#9193 NAS-116671 / 22.12 / optimize ctdb.general.healthy
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
Labels: jira, backport-22.02.2

#9195 NAS-116677 / 22.12 / Fix KeyError while collecting coredump info
  src/middlewared/middlewared/plugins/system/coredump.py
Labels: jira, backport-22.02.3

#9208 NAS-116704 / 22.12 / Fix debug size
  src/freenas/usr/local/bin/ixdiagnose
Labels: jira, backport-22.02.3

#9215 NAS-116712 / 22.12 / Fix `ArrayDevSlot.device_slot_set` off-by-one
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-22.02.2

#9216 NAS-116726 / 22.12 / Fix disks serial numbers
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: backport-22.02.2

#9219 NAS-116723 / 22.12 / Disk/partition sizes are always expressed in blocks of 512 bytes
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/disk_info.py
Labels: backport-22.02.2

#9227 NAS-116597 / 22.12 / Be more explicit about which ACE we're checking
  tests/api2/test_427_smb_acl.py
Labels: backport-13.0, backport-22.02.3

#9230 NAS-116749 / 22.12 / Expose used stats through pool.dataset
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02.3

#9233 NAS-116725 / 22.02.3 / Show only block NVMe devices in R50 enclosures
  src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py
Labels: backport-22.12, backport-22.02.2

#9236 NAS-116751 / 22.12 / Expose pool-wide space counters
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02.3

#9231 NAS-116691 / 22.02.3 / Fix `KeyError('validate_rpath')` on rsync task toggle
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-22.02.3

#9200 NAS-116683 / 22.12 / Add new helper function to convert mountinfo to dict
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/s3_/attachments.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
  src/middlewared/middlewared/utils/osc/linux/__init__.py
  src/middlewared/middlewared/utils/osc/linux/mount.py
  tests/api2/test_340_pool_dataset.py
Labels: jira, backport-22.02.3

#9243 NAS-116767 / 22.12 / Add test coverage for SMB ACL "map modify" behavior
  tests/api2/test_427_smb_acl.py
Labels: jira, backport-13.0, backport-22.02.3

#9053 NAS-116477 / 22.12 / Add tests for validating file permissions check works as intended
  tests/api2/test_can_access_as_user.py
Labels: jira

#9248 NAS-116680 / 22.12 / Fix validation error for naming schema
  src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
  src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_release_validation_schema.py
Labels: backport-22.02.3

#9253 NAS-116812 / 22.12 / minor improvement to interface.sync
  src/middlewared/middlewared/plugins/failover_/internal_interface.py
  src/middlewared/middlewared/plugins/interface/internal_ifaces.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#9250 NAS-113663 / 22.12 / Make sure we open disk with exclusive flag set when wiping
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-22.02.3

#9252 NAS-116810 / 22.12 / Place mako module directory under /run
  src/middlewared/middlewared/utils/mako.py
Labels: jira, backport-22.02.3

#9262 NAS-116835 / 22.12 / add ipv6 flags to interfaces
  src/middlewared/middlewared/plugins/interface/netif_linux/bits.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
Labels: jira, backport-22.02.3

#9264 NAS-115994 / 22.02.3 / Fix idmap tdb gid parsing (by anodos325)
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  tests/api2/test_427_smb_acl.py
Labels: backport-13.0

#9257 NAS-116816 / 22.12 / use statx to retrieve btime for files in filesystem.stat output
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/stat_x.py
Labels: jira, backport-22.02.3

#9274 NAS-116865 / 22.12 / Also install `pytest-timeout` in `install-dev-tools`
  src/freenas/usr/bin/install-dev-tools
Labels: jira, backport-22.02.3

#9281 NAS-116867 / 22.12 / Add filesystem plugin method to get mount_info
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira, backport-22.02.3

#9283 NAS-116869 / 22.12 / simplify and speed up interface.query (round 1)
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/netif.py
Labels: jira

#9286 NAS-116878 / 22.12 / fix AttributeError crash in reporting
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira

#9287 NAS-116881 / 22.12 / stop doing file I/O on main event loop
  src/middlewared/middlewared/plugins/interface/dhclient.py
Labels: jira, backport-22.02.3

#9289 NAS-116882 / 22.12 / Fix FS attachment for NFS shares
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira

#9276 NAS-116850 / 22.02.3 / Do not try to send `sync_zfs_guid` disk change events for expired disks
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-13.0, backport-22.12

#9302 NAS-116904 / 22.12 / rate limit disk.temperatures endpoint
  src/middlewared/middlewared/plugins/disk_/temperature.py
Labels: jira, backport-13.0, backport-22.02.3

#9300 NAS-116900 / 22.12 / Verify that child mounts under SMB path are consistent
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.3

#9306 NAS-116931 / 22.12 / remove duplicate code in interface do_create
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#9309 NAS-116939 / 22.12 / fix regression in bond creation
  src/middlewared/middlewared/plugins/interface/netif_linux/lagg.py
Labels: jira

#9308 NAS-116936 / 22.12 / Remove unnecessary debug statements
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.3

#9312 NAS-116949 / 22.12 / add {add_/delete_}ports methods and use them
  src/middlewared/middlewared/plugins/interface/lag.py
  src/middlewared/middlewared/plugins/interface/netif_linux/lagg.py
Labels: jira

#9315 NAS-116967 / 13.0 / add enterprise upgrade safeguard
  src/middlewared/middlewared/plugins/update_/install_freebsd.py
Labels: jira

#9311 NAS-116907 / 22.12 / Fix off-by-one and statically map Well-Known SIDs
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: backport-22.02.3

#9321 NAS-116982 / 22.12 / Properly handle DNSException from dnsclient
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
Labels: jira, backport-22.02.3

#9325 NAS-116986 / 13.0 / Update m_series_nvdimm_firmware_freebsd.py
  src/middlewared/middlewared/alert/source/m_series_nvdimm_firmware_freebsd.py
Labels: jira

#9327 NAS-116989 / 22.12 / Fix `ix-wait-on-disks.service` not being installed
  debian/debian/rules
Labels: jira

#9326 NAS-116988 / 22.12 / Fix `"device": "pmem0p2", "disk": "pmem0p"` in pool topology
  src/middlewared/middlewared/plugins/boot_/boot_loader.py
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/disk_info.py
Labels: jira, backport-22.02.3
