Repository truenas/middleware, pull requests merged in 2022-11, with the labels that each got.

#10053 NAS-118848 / 22.12 / go away exim4
  debian/debian/postinst
Labels: jira

#10052 NAS-118846 / 22.12 / Improve diasbled reasons
  src/freenas/usr/local/sbin/hactl
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira

#10059 NAS-118866 / 22.12 / Handle edge case of retrieving active apps
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#10069 NAS-118909 / 22.12 / Fix `disk.get_unused` checking for duplicate serials only among unuse…
  src/middlewared/middlewared/plugins/disk_/availability.py
Labels: jira

#10070 NAS-118910 / 22.12 / add private GlusterBricksService
  src/middlewared/middlewared/plugins/gluster_linux/bricks.py
Labels: jira

#10075 NAS-118885 / 22.12 / Run through full directory services initialization on failover
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12-RC.1

#10072 NAS-118931 / 22.12 / update and privatize GlusterRebalance service
  src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
Labels: jira

#10078 NAS-118765 / 22.12 / Add handling for MatchNotFound to share_info parsing
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: backport-22.12-RC.1

#10082 NAS-118954 / 22.12 / interfae -> interface typo fix
  src/freenas/usr/local/sbin/hactl
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira

#10086 NAS-118970 / 22.12 / remove duplicate and dead code
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#10081 NAS-118953 / 22.12 / Properly remove mirror with degraded disks
  src/middlewared/middlewared/plugins/disk_/swap_mirror.py
Labels: jira

#10087 NAS-118971 / 22.12 / add CtdbRootDirService class
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
Labels: jira

#10092 NAS-118990 / 22.12 / add format_bricks helper function
  src/middlewared/middlewared/plugins/gluster_linux/bricks.py
  src/middlewared/middlewared/plugins/gluster_linux/utils.py
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#10093 NAS-118994 / 22.12 / Make python-glfs a middleware build dependency
  src/middlewared/debian/control
Labels: jira

#10083 NAS-118957 / 22.12 / Prevent users from sharing root of gluster volume
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#10091 NAS-118988 / 22.12 / Stop any md mirror which might be present on disk
  src/middlewared/middlewared/plugins/disk_/disk_events.py
Labels: jira

#10094 NAS-119017 / 22.12 / Add glusterfs filesystem plugin
  src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
Labels: jira

#10108 NAS-119057 / 22.12 / fix KeyError in zfs_/disks.py
  src/middlewared/middlewared/plugins/zfs_/disks.py
Labels: jira

#10110 NAS-119061 / 22.12 / fix TypeError in self.logger.debug call
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#10088 NAS-118973 / 22.12 / Split up API test protocols into separate files
  tests/api2/test_420_smb.py
  tests/protocols/__init__.py
  tests/protocols/nfs_proto.py
  tests/protocols/smb_proto.py
Labels: jira

#10118 NAS-119105 / 22.12 / Do not repeatedly request for logs when following
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/watch.py
  src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
Labels: jira

#10121 NAS-119120 / 22.12 / fix nvdimm alert on SCALE HA
  src/middlewared/middlewared/alert/source/nvdimm.py
Labels: jira

#10122 NAS-119126 / 22.12 / Revert the vrrp.thread changes
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/vrrp.py
  tests/api2/test_014_failover_related.py
Labels: jira

#10123 NAS-119132 / 22.12 / Allow 3rd party catalogs to benefit from catalog sync performance improvements
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#10126 NAS-119157 / 22.12 / Fix catalog creation
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: jira

#10128 NAS-119161 / 22.12 / Skip invalid lines in samba auth audit log
  src/middlewared/middlewared/plugins/smb_/status.py
Labels: jira

#10132 NAS-119171 / 22.12 / Use `STORJ_IX_BUCKET` everywhere
  tests/api2/test_cloudsync_storj.py
Labels: jira

#10102 NAS-119044 / 22.12 / Add endpoint to check service configuration prior to start
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/services/base_interface.py
  src/middlewared/middlewared/plugins/service_/services/cifs.py
  src/middlewared/middlewared/plugins/service_/services/nfs.py
Labels: jira

#10125 NAS-119136 / 22.12 / Add glusterfs.filesystem tests
  cluster-tests/tests/filesystem/test_002_glusterfs_filesystem_plugin.py
  src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
Labels: jira

#10130 NAS-119163 / 13.0 / Move CNID databases to system dataset by default
  src/middlewared/middlewared/etc_files/afpd.py
Labels: jira

#10135 NAS-119184 / 23.10 / Workaround https://github.com/vmware/pyvmomi/issues/993
  tests/requirements.txt
Labels: backport-22.12, backport-22.12.1

#10134 NAS-119182 / 23.10 / Regenerate /etc/group after deleting group for orphan privilege gid
  tests/api2/test_account_privilege.py
Labels: backport-22.12, backport-22.12.1

#10138 NAS-118929 / 23.10 / Allow binding authorization token to its origin
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/utils/origin.py
  tests/api2/test_account_privilege_authentication.py
  tests/api2/test_auth_token.py
  tests/api2/test_rest_api_authentication.py
Labels: backport-22.12, backport-22.12.1

#10137 NAS-118945 / 23.10 / Add job IDs to `core.bulk` API response
  src/middlewared/middlewared/service.py
  tests/api2/test_core_bulk.py
Labels: backport-22.12.1

#10152 NAS-119215 / 23.10 / fix attach_interface
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-22.12.1
