Repository truenas/middleware, pull requests merged in 2022-05, with the labels that each got.

#8832 NAS-115930 / 22.12 / Autoconnect VNC display device when it's opened
  src/middlewared/middlewared/plugins/vm/devices/display.py
Labels: jira

#8867 NAS-115927 / 22.12 / fix regression in interface.update
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.02.2

#8883 NAS-116072 / 22.12 / `middlewared.utils.functools.cache`
  src/middlewared/middlewared/utils/functools.py
Labels: jira, backport-13.0, backport-22.02.2

#8886 NAS-116074 / 22.12 / Maintain equal `--ignore` option for both flake8 invocations
  .github/workflows/lint.yml
Labels: jira, backport-22.02.2

#8889 NAS-116089 / 13.0 / import by name on failover event
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: jira

#8891 NAS-116099 / 22.12 / Fix `pool.dataset.processes` returning bogus paths for locked datasets
  src/middlewared/middlewared/plugins/pool.py
  tests/api2/test_pool_dataset_processes.py
Labels: jira, backport-22.02.2

#8890 NAS-116097 / 22.12 / Bettet diagnostics for system dataset umount failures
  src/middlewared/middlewared/plugins/pool_/track_processes.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-22.02.2

#8902 NAS-116125 / 22.12 / Remove syslog options from system.general like we promised
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: jira

#8910 NAS-116128 / 22.12 / Include rpc-statd and rpc-gssd status in debug output
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
Labels: jira, backport-22.02.2

#8864 NAS-115980 / 22.12 / add ctdb.shared.volume.teardown method
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira, backport-22.02.2

#8876 NAS-116033 / 22.02.2 / Fix unlocking readonly datasets
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#8878 NAS-116049 / 13.0 / add release-date to dmi cache
  src/middlewared/middlewared/plugins/system_/dmi.py
  src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py
Labels: DO NOT MERGE, backport-22.12, backport-22.02.2

#8879 NAS-116053 / 13.0 / cache truenas.get_chassis_hardware
  src/freenas/usr/local/lib/middlewared_truenas/plugins/truenas.py
Labels: DO NOT MERGE, backport-22.12, backport-22.02.2

#8880 NAS-116048 / 13.0 / clean up setup_m_series_nvdimm method
  src/middlewared/middlewared/plugins/enterprise/m_series_nvdimm_freebsd.py
Labels: DO NOT MERGE, backport-22.12, backport-22.02.2

#8881 NAS-116063 / 13.0 / optimize system_is_enterprise_ix_hardware calls in smartctl
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/disk_/smartctl.py
  src/middlewared/middlewared/plugins/smart.py
Labels: DO NOT MERGE, backport-22.12, backport-22.02.2

#8882 NAS-116066 / 13.0 / fix IoThreadPoolExecutor
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/utils/io_thread_pool_executor.py
Labels: jira, DO NOT MERGE

#8884 NAS-116072 / 13.0 / `middlewared.utils.functools.cache` (by themylogin)
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/utils/functools.py
  src/middlewared/middlewared/utils/lang.py
Labels: DO NOT MERGE

#8888 NAS-116075 / 13.0 / fix old bios alert on m-series
  src/middlewared/middlewared/plugins/enterprise/m_series_nvdimm_freebsd.py
Labels: DO NOT MERGE

#8893 NAS-116102 / 13.0 / remove bsd.geom from remove_disk_from_graid
  src/middlewared/middlewared/plugins/disk_/remove_disk_freebsd.py
Labels: DO NOT MERGE

#8894 NAS-116103 / 13.0 / call geom.scan in overprovisioning code
  src/middlewared/middlewared/plugins/disk_/overprovision_freebsd.py
Labels: DO NOT MERGE

#8877 NAS-116013 / 13.0 / catch up network.globalconfiguration on 13 to match SCALE
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/hostname.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/service_/services/routing.py
  src/middlewared/middlewared/plugins/service_/services/wsd.py
Labels: DO NOT MERGE

#8908 NAS-116126 / 13.0 / optimize reporting db alert
  src/middlewared/middlewared/alert/source/reporting_db.py
Labels: DO NOT MERGE

#8917 NAS-116049 / 22.02.2 / add release-date to dmi cache (by yocalebo)
  src/middlewared/middlewared/plugins/system_/dmi.py
  src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py
Labels: backport-22.12

#8899 NAS-116118 / 22.12 / include pool name and GUID in lsblk output
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: jira, backport-22.02.2

#8919 NAS-116053 / 22.02.2 / cache truenas.get_chassis_hardware (by yocalebo)
  src/middlewared/middlewared/plugins/truenas.py
Labels: backport-22.12

#8928 NAS-116157 / 13.0 / Fix system_/dmi.py comparing a list to an int
  src/middlewared/middlewared/plugins/system_/dmi.py
Labels: jira, backport-22.12, backport-22.02.2

#8778 NAS-115771 / 13.0 / Add oneshot alert for deprecated services that are running
  src/middlewared/middlewared/alert/source/deprecated_service.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/services/afp.py
  src/middlewared/middlewared/plugins/service_/services/base.py
Labels: jira

#8933 NAS-116161 / 13.0 / add interface.internal_interfaces method
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#8934 NAS-115771 / 22.12 / Add oneshot alert for deprecated services that are running
  src/middlewared/middlewared/alert/source/deprecated_service.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/services/base_interface.py
Labels: backport-22.02.2

#8935 NAS-116121 / 22.12 / Fix updating default storage class
  src/middlewared/middlewared/plugins/kubernetes_linux/storage_classes.py
Labels: backport-22.02.2

#8940 NAS-116169 / 13.0 / Fix TypeError when mapping element types
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
Labels: jira

#8863 NAS-115976 / 22.12 / Add tests for renames over SMB protocol
  tests/api2/test_425_smb_protocol.py
  tests/protocols.py
Labels: jira, backport-13.0, backport-22.02.2

#8942 NAS-116174 / 22.12 / Show most important alerts first
  src/middlewared/middlewared/plugins/alert.py
Labels: jira

#8938 NAS-116094 / 22.12 / Fix reporting for UPS plugin
  src/middlewared/middlewared/plugins/reporting/plugins.py
Labels: backport-22.02.2

#8912 NAS-116135 / 22.12 / fix changing hostname on standby node on HA
  src/middlewared/middlewared/plugins/network_/global.py
Labels: jira, backport-22.02.2

#8948 NAS-115802 / 22.12 / Make sure system reflects newer cert before redeploying cert attachments
  src/middlewared/middlewared/plugins/crypto_/renew_certs.py
Labels: backport-22.02.2

#8956 NAS-116232 / 13.0 / fix geom cache crash on cd devs
  src/middlewared/middlewared/plugins/geom_/cache.py
Labels: jira

#8924 NAS-116063 / 22.12 / optimize system.is_enterprise_ix_hardware calls in smartctl (by yocalebo)
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/disk_/smartctl.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
Labels: backport-22.02.2

#8957 NAS-116233 / 22.12 / Fix alternate code path for SMB connection rename in tests
  tests/protocols.py
Labels: jira, backport-13.0, backport-22.02.2

#8966 NAS-116252 / 22.12 / Blacklist wide links related parameters
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-13.0, backport-22.02.2

#8967 Remove crossrename from vfs objects when recycle enabled
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  tests/api2/test_420_smb.py
Labels: backport-13.0, backport-22.02.2

#8970 NAS-116253 / 22.02.2 / Remove crossrename from vfs objects when recycle enabled (#8967)
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  tests/api2/test_420_smb.py
Labels: jira, backport-13.0

#8965 NAS-116242 / 22.12 / Add initial Windows SD conversion regression tests
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/util_sd.py
  tests/api2/test_427_smb_acl.py
Labels: jira, backport-13.0, backport-22.02.2

#8973 NAS-116264 / 22.12 / fix NO_VIP check on SCALE HA
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira, backport-22.02.2

#8972 NAS-115860 / 22.12 / fix importing zpools on SCALE
  .github/workflows/lint.yml
  debian/debian/ix-zfs.service
  src/middlewared/middlewared/scripts/zpoolhelper.py
  src/middlewared/setup.py
Labels: backport-22.02.2

#8978 NAS-116273 / 22.12 / remove nonexistent entry point for middlewared
  src/middlewared/setup.py
Labels: jira, backport-22.02.2

#8981 NAS-116275 / 13.0 / Remove osc plugin from boot_/format.py
  src/middlewared/middlewared/plugins/boot_/format.py
Labels: jira

#8984 NAS-116283 / 22.12 / fix pool.is_upgraded_by_name
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira, backport-13.0, backport-22.02.2

#8986 NAS-115578 / 22.12 / Force systemd to not terminate vms forcefully
  src/middlewared/debian/middlewared.service
Labels: backport-22.02.2

#8992 NAS-116163 / 22.12 / ensure unique /etc/machine-id on upgrade from CORE
  src/middlewared/middlewared/plugins/update_/freebsd_to_scale_linux.py
Labels: backport-22.02.2

#8999 NAS-116310 / 22.12 / Remove automatic quota on TM preset
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-13.0, backport-22.02.2

#9006 NAS-116329 / 22.12 / properly configure nvdimm/dual-nvdimm on m-series
  src/freenas/usr/lib/modprobe.d/truenas.conf
  src/middlewared/middlewared/etc_files/dual-nvdimm.mako
  src/middlewared/middlewared/etc_files/nvdimm.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: backport-22.02.2

#9009 NAS-116350 / 22.02.2 / `pool.is_upgraded` minor performance improvements and tests
  src/middlewared/middlewared/alert/source/volume_version.py
  src/middlewared/middlewared/plugins/zfs.py
  tests/api2/test_pool_is_upgraded.py
Labels: jira, backport-22.12

#9005 NAS-116326 / 22.12 / Significantly increase maxPods per node
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
Labels: jira

#9011 NAS-116231 / 22.12 / Add support for AMD gpus in kubernetes
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
  src/middlewared/middlewared/utils/gpu.py
Labels: backport-22.02.2

#9013 NAS-116361 / 13.0 / minor improvement in disk.sync_all
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#9008 NAS-116349 / 22.02.2 / Do not send events for transient jobs
  src/middlewared/middlewared/job.py
Labels: jira, backport-22.12

#8951 NAS-116213 / 22.12 / Do not allow modifying devices in vm create/update
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#9021 NAS-116370 / 22.12 / Fix vm.clone to use vm.device api for devices
  src/middlewared/middlewared/plugins/vm/clone.py
Labels: jira

#9024 NAS-116351 / 22.02.2 / Set `"snapdir": "hidden"` for system dataset
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-22.12

#9027 NAS-116234 / 22.02.2 / Properly raise exception if specified user does not exist (by sonicaj)
  src/middlewared/middlewared/plugins/filesystem_/perm_check.py
  src/middlewared/middlewared/utils/osc/linux/user_context.py
Labels: skip jira status

#9037 NAS-116454 / 22.12 / Add mount flags to filesystem.statfs() output
  src/middlewared/middlewared/plugins/filesystem.py
  tests/api2/test_190_filesystem.py
  tests/utils.py
Labels: jira, backport-22.02.2

#9038 NAS-116388 / 22.12 / Allow custom reporting realtime interval
  src/middlewared/middlewared/event.py
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: backport-22.02.2

#9042 NAS-116387 / 22.12 / Remove unused trueview.stats event source
  src/middlewared/middlewared/plugins/trueview.py
Labels: backport-22.02.2

#9031 NAS-116425 / 22.02.2 / Do not crash `zettarepl_schedule` if `begin` or `end` are not specified
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: jira, backport-22.12

#9030 NAS-116424 / 22.02.2 / Clean up created replication tasks after replication test
  tests/api2/test_370_replication.py
Labels: jira, backport-22.02.2

#9029 NAS-116248 / 22.02.2 / Fix restoring cloud sync tasks with `name_regex`
  src/middlewared/middlewared/plugins/replication_/crud.py
  tests/api2/test_370_replication.py
Labels: backport-22.12

#9016 NAS-115975 / 22.02.2 / Allow specifying SSL version for KMIP Server
  src/middlewared/middlewared/alembic/versions/22.02/2022-05-23_18_22_kmip_ssl_version.py
  src/middlewared/middlewared/plugins/kmip/connection.py
  src/middlewared/middlewared/plugins/kmip/update.py
  src/middlewared/middlewared/plugins/kmip/utils.py
Labels: backport-22.12

#9044 Fix filesystem API test
  tests/api2/test_190_filesystem.py
Labels: backport-22.02.2

#8998 NAS-116303 / 22.12 / add r50b rear nvme drive bay mapping
  src/middlewared/middlewared/plugins/enclosure_/map.py
  src/middlewared/middlewared/plugins/enclosure_/r50_nvme.py
Labels: backport-22.02.2

#9033 NAS-116433 / 22.02.2 / device.get_disks() optimizations
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
  src/middlewared/middlewared/plugins/disk_/disk_events.py
  src/middlewared/middlewared/plugins/disk_/enums.py
  src/middlewared/middlewared/plugins/enclosure.py
Labels: jira, backport-22.12

#9056 NAS-116480 / 22.02.2 / Fix migrations
  src/middlewared/middlewared/alembic/versions/22.02/2022-05-23_18_22_kmip_ssl_version.py
  src/middlewared/middlewared/alembic/versions/22.02/2022-05-31_11-50_kmip_ssl_version_not_null.py
Labels: jira, backported, backport-22.12

#9058 NAS-116486 / 22.12 / Simplify process of adding NFS SPNs
  src/middlewared/middlewared/plugins/activedirectory_/krb5.py
Labels: jira, backport-13.0, backport-22.02.2

#9061 NAS-116490 / 22.12 / Raise validation errors on ZFS ctldir and snapdir
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
Labels: jira, backport-13.0, backport-22.02.2
