Repository truenas/middleware, pull requests merged in 2022-10, with the labels that each got.

#9935 NAS-118429 / 22.12 / properly wait on job in dir services
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: jira

#9933 NAS-118424 / 22.12 / Improve test_420_smb - use python SMB client
  tests/api2/test_420_smb.py
Labels: jira

#9931 NAS-118416 / 22.12 / impose limit on max length of pool name
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#9937 NAS-118444 / 22.12 / add MISMATCH_VERSIONS to failover.disabled.reasons
  src/freenas/usr/local/sbin/hactl
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira

#9938 NAS-118450 / 22.12 / optimize zfs.{pool/dataset}.query
  src/middlewared/middlewared/plugins/zfs.py
Labels: pending QA, jira

#9939 NAS-118459 / 22.12 / Fix and enhance recycle test
  tests/api2/test_420_smb.py
Labels: jira

#9948 NAS-118477 / 22.12 / Cleanup all the cluster things
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
Labels: jira

#9949 NAS-118478 / 22.12 / fix cluster smb config test
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira

#9947 NAS-118476 / 22.12 / Override avahi hostname with hostname_virtual in HA
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf.mako
Labels: jira

#9943 NAS-118463 / 22.12 / VMware snapshot tests
  src/middlewared/middlewared/test/integration/assets/nfs.py
  src/middlewared/middlewared/test/integration/assets/snapshot_task.py
  src/middlewared/middlewared/test/integration/assets/vmware.py
  src/middlewared/middlewared/test/integration/utils/string.py
  tests/api2/test_snapshot_task.py
  tests/api2/test_vmware.py
  tests/requirements.txt
Labels: jira

#9951 NAS-118496 / 22.12 / Fix docs build
  docs/source/build/custom.rst
Labels: jira

#9961 NAS-118177 / 22.12 / Expose non-iX storj buckets as disabled
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/rclone/remote/storjix.py
Labels: backport-13.0

#9966 NAS-118562 / 13.0 / ensure nameservers are propagated to standby
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.12

#9971 NAS-118564 / 22.12 / fix iommu number detection
  src/middlewared/middlewared/plugins/vm/pci.py
Labels: jira

#9969 NAS-118563 / 13.0 / fix race with db insert/service.restart on HA
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.12

#9976 NAS-118572 / 13.0 / Fix NIS user/group cache
  src/middlewared/middlewared/plugins/nis.py
Labels: jira

#9974 NAS-118568 / 22.12 / Avoid spamming log files with docker mounts
  src/freenas/etc/logrotate.d/syslog-ng-truenas
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: jira

#9979 NAS-118576 / 22.12 / Correctly whitelist openvpn.client/server namespace when validating port
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira

#9977 NAS-117406 / 22.12 / Do not rename network interfaces based on their stored MAC address on…
  src/middlewared/middlewared/plugins/interface/link_address.py
Labels: skip jira status

#9985 NAS-118586 / 22.12 / Fix VMware snapshot delete test
  src/middlewared/middlewared/plugins/vmware_/snapshot_delete.py
Labels: jira

#9982 NAS-118578 / 13.0 / Add NIS regression tests
  src/middlewared/middlewared/plugins/nis.py
  tests/api2/test_043_nis.py
Labels: jira

#9986 NAS-118594 / 22.12 / Avoid unnecessary avahi reload_config() calls
  src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
Labels: jira

#9988 NAS-118599 / 22.12 / Do not expose MIXED case sensitivity as user choice
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#9983 NAS-118580 / 22.12 / Remove k8s cronjobs when scaling down apps
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
Labels: jira

#10000 NAS-118627 / 22.12 / Employ new method of testing if storj bucket is related to iX as conf…
  src/middlewared/middlewared/rclone/remote/storjix.py
Labels: jira, backported, backport-13.0

#10007 NAS-118641 / 22.12 / Do not repeatedly apply k8s infra migrations
  src/middlewared/middlewared/plugins/kubernetes_linux/infra_migrations.py
Labels: jira

#10008 NAS-118643 / 22.12 / Add method to retrieve usb controller type choices
  src/middlewared/middlewared/plugins/vm/usb.py
Labels: jira

#10015 NAS-118705 / 22.12 / No need to validate force flag when starting k8s service
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: jira

#10013 NAS-118704 / 22.12 / Disable NVMe multipath
  src/freenas/usr/local/bin/truenas-grub.py
Labels: jira

#10016 NAS-118706 / 22.12 / Do not try to update encryption property on ix-applications dataset
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: jira

#10020 NAS-118722 / 22.12 / fix inotify resource exhaustion on m50
  src/freenas/etc/sysctl.d/10-truenas.conf
Labels: jira

#10010 NAS-118649 / 22.12 / Do not start TC on standby node on SCALE
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
Labels: jira

#10023 NAS-118729 / 22.12 / fix middleware startup
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
Labels: jira

#10030 NAS-118751 / 22.12 / fix md integration tests on HA
  tests/api2/test_unsupported_md_devices.py
Labels: jira

#10031 NAS-118758 / 22.12 / remove enum values no longer in use
  src/freenas/usr/local/sbin/hactl
Labels: jira

#10037 NAS-118769 / 22.12 / preserve nameserver order in resolv.conf
  src/middlewared/middlewared/plugins/network_/dns.py
Labels: jira

#9471 NAS-117392 / 22.12 / Add clustered time health check
  src/middlewared/middlewared/alert/source/ctdb.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/ntp.py
Labels: jira

#10038 NAS-118772 / 22.12 / Fix ctdb assertions due to open handles
  src/middlewared/middlewared/plugins/service_/services/ctdb.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
Labels: jira

#10040 NAS-118780 / 22.12 / fix AttributeError in service.py
  src/middlewared/middlewared/service.py
Labels: jira

#10041 NAS-118781 / 22.12 / Create recovery lock if it doesn't exist
  src/freenas/usr/local/sbin/ctdb_glfs_lock
Labels: jira

#10045 NAS-118808 / 22.12 / Fix port delegate test
  tests/api2/test_port_delegates.py
Labels: jira

#10046 NAS-118814 / 22.12 / Fix disk.sync_all when booting
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira, backport-13.0

#10044 NAS-118807 / 22.12 / Prevent multiple users from having same homedir
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: jira
