Repository truenas/middleware, pull requests merged in 2022-07, with the labels that each got.

#9336 NAS-117001 / 22.12 / Add initial support for mDNS in cluster
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf.mako
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
Labels: jira, backport-22.02.3

#9338 NAS-117009 / 22.12 / Only enable wsdd on recovery master when clustered
  src/middlewared/middlewared/etc_files/local/wsdd.conf.mako
Labels: jira, backport-22.02.3

#9342 NAS-116953 / 22.02.3 / fix reporting.realtime memory leak
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/plugins/reporting/ifstat.py
Labels: backport-22.12

#9296 NAS-116895 / 22.12 / Do not show ix-applications children on any pool
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#9347 NAS-117044 / 22.12 / Do not expose user certificate's keys in debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: jira, backport-22.02.3

#9249 NAS-116332 / 22.12 / Don't allow putting files on locked paths
  src/middlewared/middlewared/plugins/filesystem.py
  tests/api2/test_filesystem__put.py
  tests/functions.py
Labels: backport-22.02.3

#9349 NAS-117049 / 22.12 / improve getting zfs arcstats
  src/middlewared/middlewared/plugins/reporting/arcstat.py
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira, backport-22.02.3

#9343 NAS-117014 / 22.12 / Replace subprocess calls for clustered tdb backend
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/connection.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
Labels: jira, backport-22.02.3

#9363 NAS-117081 / 22.12 / Fix regression in clustered timeinfo
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
Labels: jira, backport-22.02.3

#9368 NAS-117093 / 22.12 / Fix docs build
  docs/source/conf.py
  src/middlewared/middlewared/test/integration/utils/pool.py
Labels: jira

#9374 NAS-117113 / 22.02.3 / Report S.M.A.R.T. test in progress if there is a `Self test in progre…
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/pytest/unit/plugins/test_smart.py
Labels: jira, backport-22.12

#9381 NAS-117141 / 22.02.3 / Fix `reporting.setup`
  src/middlewared/middlewared/plugins/reporting/configure.py
Labels: jira, backport-22.12

#9385 NAS-117155 / 22.12 / Fix bug in `ensure_builtins` option for ACL templates
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira, backport-22.02.3

#9388 NAS-117097 / 22.12 / Fix cluster test for revisted ctdb status return
  cluster-tests/init_gluster.py
Labels: backport-22.02.3

#9391 NAS-117163 / 13.0 / add "Not Installed, Swapped" element status for X
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/element_types.py
Labels: jira

#9393 NAS-117174 / 22.12 / remove freeBSD specific script
  src/freenas/usr/local/bin/chelsio_adapter_config
Labels: backport-22.02.3

#9400 NAS-117196 / 22.12 / Properly await updating ui allowlist
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: jira

#9352 NAS-117058 / 22.12 / Include "df -T" for SMB share paths in debug output
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
Labels: jira, backport-22.02.3

#9406 NAS-117197 / 22.12 / Duplicate samba behavior when generating krb5.conf from AD info
  src/middlewared/middlewared/etc_files/krb5.conf.mako
  src/middlewared/middlewared/plugins/activedirectory_/krb5.py
Labels: backport-22.02.3

#9395 NAS-117181 / 22.12 / Allow setting UID 0 for new users
  src/middlewared/middlewared/plugins/account.py
Labels: jira, backport-22.02.3

#9359 NAS-117066 / 22.12 / Add pwenc service for cluster
  cluster-tests/tests/clustercache/__init__.py
  cluster-tests/tests/clustercache/test_001_base_clustercache_tests.py
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/pwenc.py
  src/middlewared/middlewared/utils/path.py
Labels: jira

#9411 NAS-117209 / 22.12 / Convert smb.status to sync method
  src/middlewared/middlewared/plugins/smb_/status.py
Labels: backport-13.0, backport-22.02.3

#9416 NAS-116776 / 22.02.3 / Fix `2021-01-20_10-19_autoincrement.py` when `id` column is not first…
  src/middlewared/middlewared/alembic/versions/22.02/2021-01-20_10-19_autoincrement.py
Labels: backport-22.12

#9419 NAS-117188 / 22.02.3 / `assert_creates_job` integration test helper to ensure that method be…
  src/middlewared/middlewared/test/integration/utils/__init__.py
  src/middlewared/middlewared/test/integration/utils/job.py
  tests/api2/test_439_snapshottask_retention.py
Labels: backport-22.12

#9424 NAS-117234 / 22.12 / Use mktemp for creating temporary directory
  tests/api2/test_run_as_user_impl.py
Labels: jira

#9389 NAS-117159 / 22.12 / save/rollback default gateway on interface changes
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#9251 NAS-116808 / 22.12 / Improve IPMI password validation
  src/middlewared/middlewared/plugins/ipmi.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/validators.py
Labels: jira, backport-13.0, backport-22.02.3

#9430 NAS-117248 / 22.12 / Fix parsing replication/rsync/cloud sync task ID from the job args in…
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/plugins/zettarepl_/state.py
Labels: backport-22.02.3

#9437 NAS-117264 / 22.02.3 / Updater size estimates seem quite off
  src/middlewared/middlewared/plugins/update_/install.py
Labels: jira, backport-22.12

#9439 NAS-117267 / 22.02.3 / Fix multiple issues with failover.disabled_reasons
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12

#9448 NAS-116911 / 22.12 / Allow LDAP netgroups support
  src/freenas/etc/nsswitch.conf
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-22.02.3

#9446 NAS-117276 / 22.12 / migrate shells from core to scale properly
  src/middlewared/middlewared/migration/0002_shell_linux.py
Labels: jira, backport-22.02.3

#9451 NAS-117217 / 22.02.3 / fix migration failure upgrading from core to scale
  src/middlewared/middlewared/alembic/versions/22.02/2021-01-20_10-19_autoincrement.py
Labels: backport-22.12

#9454 NAS-117282 / 22.12 / Remove redundant HA NIC capability checks in VMs
  src/middlewared/middlewared/plugins/vm/failover_check_base.py
  src/middlewared/middlewared/plugins/vm/failover_checks_linux.py
  src/middlewared/middlewared/plugins/vm/vm_devices.py
Labels: jira

#9455 NAS-117283 / 22.12 / Fix resolve_builtins for case where id is None
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: backport-22.02.3

#9452 NAS-117245 / 22.12 / Improve `get_remote_addr_port` performance
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/utils/nginx.py
  tests/api2/test_ip_auth.py
Labels: backport-22.02.3

#9458 NAS-117293 / 22.12 / Deprecate legacy behavior to allow empty homes path
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.3

#9418 NAS-117231 / 22.12 / Add CTDB event integration
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/ctdb.py
  src/middlewared/middlewared/etc_files/local/wsdd.conf.mako
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event_scripts.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/scripts/ctdb_events.py
Labels: jira, backport-22.02.3

#9464 NAS-117303 / 22.12 / use ejson in kubernetes backup plugin
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: jira

#9459 NAS-117206 / 22.12 / Fix test_032_ad_kerberos for krb5.conf changes
  tests/api2/test_032_ad_kerberos.py
Labels: backport-22.02.3

#9465 NAS-117305 / 22.12 / fill in app information in pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira

#9467 NAS-117306 / 22.12 / Fix ctdb jobs on pnn 0
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
Labels: jira, backport-22.02.3

#9460 NAS-111488 / 22.12 / Linux disk resize
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-22.02.3

#9470 Minor improvements to pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira

#9474 NAS-117313 / 22.12 / Fix out of order check for system.ready in ad.started method
  src/middlewared/middlewared/plugins/activedirectory_/health.py
Labels: backport-22.02.3

#9476 NAS-117328 / 22.12 / Fixes an empty line in SMB share presets
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.4

#9481 NAS-117353 / 22.12 / Fix Failover_disks alert typo
  src/middlewared/middlewared/alert/source/failover_disks.py
Labels: jira, backport-22.02.4

#9487 NAS-117362 / 22.12 / improve ntp alert verbiage
  src/middlewared/middlewared/alert/source/ntp.py
Labels: jira, backport-22.02.4

#9491 NAS-117367 / 22.12 / Ensure that required paths are auto-created for clustered pwenc
  src/middlewared/middlewared/plugins/pwenc.py
  src/middlewared/middlewared/utils/path.py
Labels: jira

#9493 NAS-117377 / 22.12 / Fix clustered filesystem test
  cluster-tests/tests/filesystem/test_001_base_filesystem_tests.py
Labels: backport-22.02.4

#9496 NAS-117378 / 22.12 / Bump up timeout values for permissions tests on cluster
  cluster-tests/config.py
  cluster-tests/tests/filesystem/test_001_base_filesystem_tests.py
Labels: jira, backport-22.02.4

#9498 NAS-117391 / 22.12 / Remove redundant dataset.query
  src/middlewared/middlewared/plugins/iscsi_/extents.py
Labels: jira, backport-22.02.4

#9501 NAS-117394 / 22.02.4 / fix typo in failover.disabled_reasons
  src/middlewared/middlewared/plugins/failover.py
Labels: backport-22.02.3

#9499 NAS-117074 / 22.12 / Fix kubernetes token issue
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
Labels: backport-22.02.4

#9509 NAS-117358 / 22.02.4 / Reset anonymous FTP configuration in FTP test assets
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/test/integration/assets/ftp.py
Labels: backport-22.02.3

#9514 NAS-117420 / 22.12 / Initialize cluster so that all nodes have all public IPs
  cluster-tests/init_gluster.py
Labels: jira, backport-22.02.4

#9506 NAS-117400 / 22.12 / Fix activedirectory join in cluster
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
  src/middlewared/middlewared/plugins/tdb/schema.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  src/middlewared/middlewared/service.py
Labels: jira, backport-22.02.4

#9523 NAS-117424 / 22.12 / freenas-debug: Restore ZFS kstat capture
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: jira, backport-22.02.4

#9490 NAS-117330 / 22.12 / Disable fruit nfs_aces by default
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: backport-22.02.4

#9529 NAS-117435 / 22.12 / move thick_provision key to dataset level
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira

#9517 NAS-117000 / 22.02.4 / set upper bound on number of cluster nodes
  src/middlewared/middlewared/plugins/gluster_linux/peer.py
  src/middlewared/middlewared/plugins/gluster_linux/utils.py
Labels: backport-22.12

#9531 NAS-117436 / 13.0 / stop running file IO in main event loop
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: jira, backport-22.12, backport-22.02.4

#9525 NAS-117437 / 22.12 / Remove microsoft account option
  src/middlewared/middlewared/alembic/versions/22.12/2022-07-29_14-47_remove_ms_accounts.py
  src/middlewared/middlewared/etc_files/local/smb4_share.conf.mako
  src/middlewared/middlewared/etc_files/local/smbusername.map.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/cifs.py
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
  tests/api2/test_425_smb_protocol.py
Labels: jira

#9537 NAS-117441 / 22.12 / Added better support for python virtual environment
  tests/README.md
  tests/protocols.py
  tests/requirements.txt
  tests/runtest.py
Labels: jira, backport-13.0, backport-22.02.3, backport-22.02.4

#9399 NAS-113922 / 22.12 / cluster volume integration tests
  cluster-tests/tests/gluster/__init__.py
  cluster-tests/tests/gluster/test_volume.py
Labels: backport-22.02.4

#9542 NAS-117442 / 22.12 / fix test_cluster_path_snapshot test
  cluster-tests/tests/cloudsync/test_cloudsync.py
Labels: jira, backport-22.02.4

#9544 NAS-117443 / 22.12 / Fix clustered SMB service management events
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
  cluster-tests/tests/smb/test_001_sharing_smb.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py
  src/middlewared/middlewared/scripts/ctdb_events.py
Labels: jira, backport-22.02.4
