Repository truenas/middleware, pull requests merged in 2022-09, with the labels that each got.

#9760 NAS-117991 / 22.12 / Use zfs.pool.query_imported_fast in failover.status
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
  src/middlewared/middlewared/plugins/failover_/failover_status.py
Labels: jira

#9763 NAS-117987 / 22.12 / add more integration tests
  tests/api2/test_013_test_corssl.py
Labels: backport-22.12-BETA.1

#9765 NAS-118014 / 22.12 / fix failover.get_ips
  src/middlewared/middlewared/plugins/failover.py
  tests/api2/test_014_failover_related.py
Labels: jira, backport-22.02.4

#9762 NAS-118013 / 22.12 / Improve `core.bulk` documentation
  src/middlewared/middlewared/service.py
Labels: jira, backport-22.02.4

#9766 NAS-118015 / 22.12 / prevent blocking event loop when checking updates
  src/middlewared/middlewared/plugins/update_/trains.py
  src/middlewared/middlewared/plugins/update_/trains_linux.py
  src/middlewared/middlewared/plugins/update_/utils.py
Labels: jira

#9768 NAS-118019 / 22.12 / Prohibit trailing spaces in ZFS dataset names
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02.4

#9778 NAS-118059 / 22.12 / fix blank graphs when UPSBase plugin crashes
  src/middlewared/middlewared/plugins/reporting/plugins.py
Labels: jira, backport-22.02.4

#9747 NAS-117911 / 22.12 / Ensure SMB share ACL is preserved during various share ops
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  tests/api2/test_430_smb_sharesec.py
Labels: backport-22.02.4

#9680 NAS-117274 / 13.0 / Adjust test_427 for slight FreeBSD ACL variation
  tests/api2/test_427_smb_acl.py
Labels: DO NOT MERGE

#9783 NAS-118064 / 22.12 / cache failover.hardware.detect
  src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
Labels: jira, backport-22.02.4

#9789 NAS-118075 / 22.12 / fix ssl integration test (typo)
  tests/api2/test_013_corssl.py
Labels: jira

#9791 NAS-118078 / 22.12 / fix test_is_outdated_alert
  tests/api2/test_pool_is_upgraded.py
Labels: jira

#9792 NAS-118074 / 22.12 / stop blocking event loop in auth plugin hook
  src/middlewared/middlewared/plugins/auth.py
Labels: backport-22.02.4

#9793 NAS-118083 / 22.12 / fix AttributeError crash in ha_permission hook
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.02.4

#9801 NAS-118091 / 22.02.4 / Forbid using download token for websocket authentication
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/api2/test_auth_token.py
Labels: jira, backport-22.12

#9803 NAS-118093 / 22.02.4 / Dont block event look in check_permission hook
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#9799 NAS-118092 / 22.02.4 / Properly terminate Web Shell and it's children
  src/middlewared/middlewared/main.py
Labels: jira, backport-22.12

#9798 NAS-117895 / 22.12 / dont crash in iscsi alert
  src/middlewared/middlewared/alert/source/iscsi.py
Labels: backport-22.02.4

#9809 NAS-118097 / 22.12 / Allow non-coroutine to be passed to `register_hook` and executed corr…
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/service_/on_config_upload.py
Labels: jira

#9800 NAS-118102 / 22.02.4 / Support `--log-cli-level` for `runtest.py`
  tests/runtest.py
Labels: jira

#9810 NAS-118098 / 22.12 / improve failover.disabled.reasons
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira

#9811 NAS-118103 / 22.12 / add connect_timeout to remote client
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira

#9812 NAS-118106 / 22.12 / fix starting of collectd service since upstream decided to break stuff
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
  src/middlewared/middlewared/plugins/reporting/plugins.py
Labels: backport-22.02.4, backport-22.12-BETA.1

#9817 NAS-118110 / 22.12 / move fenced process to root cgroup
  src/middlewared/middlewared/plugins/failover_/fenced.py
Labels: jira, backport-22.02.4

#9819 NAS-118117 / 22.12 / move gluster fuse mounts to root cgroups
  cluster-tests/config.py
  cluster-tests/init_gluster.py
  cluster-tests/tests/gluster/test_volume.py
  src/middlewared/middlewared/plugins/gluster_linux/fuse.py
Labels: jira, backport-22.02.4

#9790 NAS-118076 / 22.12 / Switch to using vfs_ixnas for default ACL module
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
Labels: jira

#9823 NAS-118131 / 22.12 / fix ctdb shared volume teardown integration test
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
Labels: jira, backport-22.02.4

#9816 NAS-118111 / 22.12 / Fix undefined name in vm/devices.cdrom.py
  src/middlewared/middlewared/plugins/vm/devices/cdrom.py
Labels: jira, backport-22.12-BETA.1

#9827 NAS-118135 / 22.12 / fix crash in nginx.get_remote_addr_port
  src/middlewared/middlewared/utils/nginx.py
Labels: jira, backport-22.02.4

#9830 NAS-118136 / 22.12 / fix crash(es) in webui_auth::addr_in_allowlist
  src/middlewared/middlewared/webui_auth.py
Labels: jira

#9829 NAS-117230 / 22.02.4 / Do not accumulate `self._finished.wait()` tasks when doing `job.wrap`
  src/middlewared/middlewared/job.py
Labels: skip jira status, backport-13.0

#9833 NAS-118138 / 22.12 / Fix unused disks issue
  src/middlewared/middlewared/plugins/disk_/availability.py
Labels: jira

#9834 NAS-117952 / 22.12 / Add initial containers in pod logs choices
  src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
Labels: backport-22.02.4

#9838 NAS-118140 / 22.02.4 / Do not use `undefined` from `middlewared.utils` in integration tests
  src/middlewared/middlewared/client/utils.py
  src/middlewared/middlewared/test/integration/utils/client.py
Labels: jira

#9837 NAS-118139 / 22.12 / Catalogs need to be synced after restoring k8s backup
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: jira

#9808 NAS-118094 / 22.12 / Use libwbclient bindings
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/idmap_/utils.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: jira

#9842 NAS-118152 / 22.12 / set CPU governor to performance mode always
  src/middlewared/middlewared/plugins/tunables.py
Labels: jira

#9840 NAS-118149 / 22.02.4 / Removed log_py_exceptions from middlewared.test.integration.utils.client
  src/middlewared/middlewared/test/integration/utils/client.py
Labels: jira

#9843 NAS-118164 / 22.12 / fix AttributeError crash in update.get_trains
  src/middlewared/middlewared/plugins/update_/trains.py
  tests/api2/test_013_corssl.py
Labels: jira

#9850 NAS-118178 / 22.02.4 / fix typo in failover_/event.py
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12

#9855 NAS-118150 / 22.02.4 / properly catch libzfs EZFS_NOENT errno on failover
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12

#9847 NAS-117410 / 22.12 / Do not store rsync command output in RAM
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/utils/osc/linux/user_context.py
Labels: backported, backport-22.02.4

#9846 NAS-118168 / 22.12 / Do not require `remotehost` when rsync task is configured using an SS…
  src/middlewared/middlewared/plugins/rsync.py
  tests/api2/test_rsync_ssh_authentication.py
Labels: jira

#9869 NAS-118222 / 22.12 / Fix keyerror in ACL template domain info lookup
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira

#9874 NAS-118249 / 22.12 / dont call pool.query in vmware plugin
  src/middlewared/middlewared/plugins/vmware.py
Labels: jira

#9871 NAS-118241 / 22.12 / Fix boot device replace
  src/middlewared/middlewared/plugins/boot.py
Labels: jira

#9876 NAS-117917 / 22.12 / `getty@tty1.service.d` improvements
  src/freenas/etc/systemd/system/getty@tty1.service.d/override.conf
Labels: skip jira status, backport-22.02.4

#8694 NAS-115586 / 22.12 / Enable `pool.replace_disk` tests
  tests/api2/test_pool_replace_disk.py
Labels: jira

#9880 NAS-118257 / 22.12 / fix mapping rear NVMe on M50/60 HA systems
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
Labels: jira

#9881 NAS-118261 / 22.12 / Fix `test__get_smartd_config`
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
Labels: jira

#9882 NAS-118271 / 22.12 / fix failover.become_passive
  src/middlewared/middlewared/plugins/failover.py
Labels: backport-22.02.4

#9887 NAS-118216 / 22.12 / Clean up system and hardware section in debug and add enclosures
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: backport-13.0, backport-22.02.4

#9890 NAS-118283 / 22.12 / fix failover.disabled.reasons
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira, backport-22.02.4

#9893 NAS-118200 / 22.12 / fix incorrect ticket URL
  src/middlewared/middlewared/alert/source/cores.py
Labels: backport-22.02.4

#9896 NAS-118288 / 22.02.4 / fix behavioral change in api_key.create
  src/middlewared/middlewared/plugins/api_key.py
Labels: jira

#9899 NAS-118289 / 22.12 / fix copy and paste typo....
  tests/api2/test_008_hactl.py
Labels: jira

#9903 NAS-118297 / 22.12 / Fix keyerror during idmap_create
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#9900 NAS-118294 / 22.12 / move test_008_hactl to test_14_failover_related
  tests/api2/test_008_hactl.py
  tests/api2/test_014_failover_related.py
Labels: jira

#9901 NAS-118295 / 22.12 / dont run boot_attach tests on HA VMs
  tests/api2/test_boot_attach_replace_detach.py
Labels: jira

#9062 NAS-116495 / 22.12 / convert most of sysdataset plugin to sync
  src/middlewared/middlewared/etc_files/default/rrdcached.mako
  src/middlewared/middlewared/etc_files/default/syslog-ng.mako
  src/middlewared/middlewared/etc_files/glusterd.conf.mako
  src/middlewared/middlewared/etc_files/nscd.conf.mako
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#9905 NAS-118304 / 22.12 / Avoid blocking calls in smb plugin
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#9910 NAS-118329 / 22.12 / fix validation error
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#9912 NAS-118331 / 22.12 / fix interface unit tests
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
Labels: jira

#9911 NAS-118330 / 22.12 / fix m-series nvme unit test
  src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_m_series_nvme.py
Labels: jira

#9857 NAS-118197 / 22.12 / Fix k3s logs/exec issue
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
  tests/api2/test_027_kubernetes_logs.py
Labels: jira

#9914 NAS-118338 / 22.12 / Avoid logging on FileNotFoundError for sysdataset
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira

#9916 NAS-118351 / 22.12 / Disable middleware debug mode being the default
  src/middlewared/debian/middlewared.service
  src/middlewared/middlewared/main.py
Labels: jira

#9196 NAS-116678 / 22.12 / Refuse to download update if insufficient space avail
  src/middlewared/middlewared/plugins/update_/download.py
  src/middlewared/middlewared/plugins/update_/trains.py
Labels: jira

#9921 NAS-118362 / 22.12 / dramatically optimize retrieving drive temps
  src/freenas/usr/local/lib/collectd_pyplugins/disktemp.py
  src/middlewared/middlewared/plugins/disk_/temperature.py
Labels: jira

#9926 NAS-118373 / 22.12 / Fix a few HA issues on SCALE
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
  src/middlewared/middlewared/plugins/failover_/journal.py
Labels: jira

#9924 NAS-118372 / 22.12 / Add some more delay to fix k8s logs/exec tests
  tests/api2/test_027_kubernetes_logs.py
Labels: jira

#9928 NAS-118384 / 22.12 / dont block event loop in ws_can_access
  src/middlewared/middlewared/main.py
Labels: jira
