Repository truenas/middleware, pull requests merged in 2022-03, with the labels that each got.

#8388 NAS-115066 / 22.12 / Add truecommand connection information to debug
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: backport-22.02

#8395 NAS-114974 / 22.12 / Allow hooks to raise exceptions
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/sysdataset.py
  tests/api2/test_pool_export.py
Labels: backport-13.0, backport-22.02

#8396 NAS-114987 / 22.12 / Fix `Disks have duplicate serial numbers: ... (sda, sda).`
  src/middlewared/middlewared/plugins/disk_/availability.py
  src/middlewared/middlewared/pytest/unit/plugins/disk/test_availability.py
Labels: backport-13.0, backport-22.02

#8390 NAS-115098 / 22.12 / Add ability to specify render_context for etc files
  src/middlewared/middlewared/etc_files/default/nfs-common.mako
  src/middlewared/middlewared/etc_files/default/nfs-kernel-server.mako
  src/middlewared/middlewared/etc_files/default/rpcbind.mako
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/etc_files/idmapd.conf.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-22.02

#8404 NAS-115113 / 22.12 / Fix validation for raw uids / gids in pool.dataset.set_quota
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-13.0, backport-22.02.1

#8386 NAS-115027 / 22.12 / Optimize reloads of user service
  src/middlewared/middlewared/etc_files/group.mako
  src/middlewared/middlewared/etc_files/local/smbusername.map.mako
  src/middlewared/middlewared/etc_files/local/sudoers.mako
  src/middlewared/middlewared/etc_files/mail/aliases.mako
  src/middlewared/middlewared/etc_files/master.passwd.mako
  src/middlewared/middlewared/etc_files/pwd_db.py
  src/middlewared/middlewared/etc_files/shadow.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  tests/api2/test_011_user.py
Labels: backport-22.02.1

#8410 NAS-115060 / 22.12 / Make sure key exists before accessing it
  src/middlewared/middlewared/plugins/interface/netif_linux/routing.py
Labels: backport-22.02.1

#8360 NAS-115010 / 22.12 / Disable docker-compose cli usage
  debian/debian/postinst
Labels: backport-22.02.1

#8416 NAS-115125 / 22.12 / fix interface.query aliases key
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#8387 NAS-115083 / 22.12 / Add link state of interfaces for reporting realtime event source
  src/middlewared/middlewared/plugins/interface/netif_linux/netif.py
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira, backport-22.02.1

#8412 NAS-115041 / 22.02.1 / Proper way of mapping ZFS pool vdevs to disks
  src/middlewared/middlewared/plugins/zfs_/disks.py
Labels: backport-22.12

#8329 NAS-114781 / 22.02 / Very simple and fully test-covered `reporting.configure`
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
  src/middlewared/middlewared/plugins/reporting/configure.py
  src/middlewared/middlewared/utils/shutil.py
  tests/api2/test_replication.py
  tests/api2/test_reporting__configure.py
Labels: backport-22.12

#8413 NAS-115119 / 22.12 / Convert SSH etc group to use common render_ctx
  src/middlewared/middlewared/etc_files/local/ssh/config.py
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
  src/middlewared/middlewared/etc_files/local/users.oath.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-22.02.1

#8414 NAS-115121 / 22.12 / Convert PAM etc group to use a render_ctx
  src/middlewared/middlewared/etc_files/pam.d/README.mako
  src/middlewared/middlewared/etc_files/pam.d/atrun.mako
  src/middlewared/middlewared/etc_files/pam.d/common-account.mako
  src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
  src/middlewared/middlewared/etc_files/pam.d/common-password.mako
  src/middlewared/middlewared/etc_files/pam.d/common-session-noninteractive.mako
  src/middlewared/middlewared/etc_files/pam.d/common-session.mako
  src/middlewared/middlewared/etc_files/pam.d/cron.mako
  src/middlewared/middlewared/etc_files/pam.d/ftp.mako
  src/middlewared/middlewared/etc_files/pam.d/ftpd.mako
  src/middlewared/middlewared/etc_files/pam.d/imap.mako
  src/middlewared/middlewared/etc_files/pam.d/kde.mako
  src/middlewared/middlewared/etc_files/pam.d/login.mako
  src/middlewared/middlewared/etc_files/pam.d/other.mako
  src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
  src/middlewared/middlewared/etc_files/pam.d/pam.skel_freebsd.mako
  src/middlewared/middlewared/etc_files/pam.d/passwd.mako
  src/middlewared/middlewared/etc_files/pam.d/pop3.mako
  src/middlewared/middlewared/etc_files/pam.d/rsh.mako
  src/middlewared/middlewared/etc_files/pam.d/samba.mako
  src/middlewared/middlewared/etc_files/pam.d/sshd.mako
  src/middlewared/middlewared/etc_files/pam.d/su.mako
  src/middlewared/middlewared/etc_files/pam.d/sudo.mako
  src/middlewared/middlewared/etc_files/pam.d/system.mako
  src/middlewared/middlewared/etc_files/pam.d/telnetd.mako
  src/middlewared/middlewared/etc_files/pam.d/xdm.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-22.02.1

#8408 NAS-114938 / 22.02.1 / Allow specifying uuid for vms
  src/middlewared/middlewared/alembic/versions/22.02/2022-02-15_20-08_remove_hardware_offload.py
  src/middlewared/middlewared/alembic/versions/22.02/2022-03-03_10-01_vm_uuid.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
  src/middlewared/middlewared/plugins/vm/vms.py
  src/middlewared/middlewared/validators.py
Labels: WIP, backported, backport-22.12

#8423 NAS-115126 / 22.12 / Avoid pwd and grp lookups in etc file generation
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-22.02.1

#8429 NAS-115049 / 22.12 / Remove typo from nfs-common config generation
  src/middlewared/middlewared/etc_files/default/nfs-common.mako
  src/middlewared/middlewared/etc_files/nfsd.py
Labels: jira, backport-22.02.1

#8428 NAS-115128 / 22.12 / Remove FreeBSD checks from etc plugin in SCALE
  src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf.mako
  src/middlewared/middlewared/etc_files/local/apache24/webdav_config.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-22.02.1

#8434 NAS-115077 / 22.02.1 / Mark cloudsync.sync_onetime as abortable=True (by themylogin)
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_cloudsync.py
Labels: skip jira status

#8437 NAS-114977 / 22.02.1 / Better error for invalid uploaded config file
  src/middlewared/middlewared/plugins/config.py
Labels: backport-22.02.1

#8425 NAS-115111 / 22.12 / Only validate the subquestion if value is provided
  src/middlewared/middlewared/plugins/chart_releases_linux/validation.py
Labels: backport-22.02.1

#8440 NAS-115135 / 22.12 / Improve webdav validation and disable deprecated TLS versions
  src/middlewared/middlewared/etc_files/local/apache24/httpd.conf.mako
  src/middlewared/middlewared/etc_files/local/apache24/webdav_config.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/webdav.py
Labels: jira, backport-13.0, backport-22.02.1

#8444 NAS-115140 / 22.12 / Convert webdav etc group to use render_ctx
  src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf.mako
  src/middlewared/middlewared/etc_files/local/apache24/webdav_config.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-13.0, backport-22.02.1

#8445 NAS-115130 / 22.12 / More logging to debug rare `disk.sync_zfs_guid` issue
  src/freenas/usr/local/libexec/freenas-debug/zfs/join_ses.nawk
  src/freenas/usr/local/libexec/freenas-debug/zfs/normalize_pool.nawk
  src/freenas/usr/local/libexec/freenas-debug/zfs/normalize_ses.nawk
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-22.02.1

#8448 NAS-115061 / 22.12 / Bug fix for retrieving routes of all tables
  src/middlewared/middlewared/plugins/interface/netif_linux/routing.py
Labels: backport-22.02.1

#8452 NAS-115166 / 22.02.1 / Fix iSCSI extents with whitespace in zvol names
  src/middlewared/middlewared/alembic/versions/22.02/2022-03-07_11-21_normalize_iscsitargetextent_type_and_rpm.py
  src/middlewared/middlewared/plugins/iscsi.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
  tests/api2/test_iscsi.py
Labels: jira, backport-22.12

#8463 NAS-115196 / 22.12 / Use opener in ssh etc file generation
  src/middlewared/middlewared/etc_files/local/ssh/config.py
Labels: jira, backport-22.02.1

#8461 NAS-115195 / 22.02.1 / Fix updating `22.02.0` to `CUSTOM`
  src/middlewared/middlewared/plugins/update_/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_utils.py
Labels: jira, backport-22.12

#8466 NAS-115198 / 22.12 / Reuse fd in etc file generation and run unlink in thread
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/utils/io.py
Labels: jira, backport-22.02.1

#8334 NAS-114967 / 13.0 / add send_event key to datastore plugin
  src/middlewared/middlewared/plugins/datastore/write.py
  src/middlewared/middlewared/plugins/disk_/sync.py
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-22.12

#8476 NAS-115203 / 22.12 / Improve permissions handling in temporary keytab files
  src/middlewared/middlewared/etc_files/krb5.keytab.py
Labels: jira, backport-13.0, backport-22.02.1

#8479 NAS-115205 / 13.0 / fix number_of_disks logging logic
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#8475 NAS-114967 / 22.12 / add send_event key to datastore plugin (by yocalebo)
  src/middlewared/middlewared/plugins/datastore/write.py
  src/middlewared/middlewared/plugins/disk_/sync.py
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-22.02.1

#8480 NAS-115211 / 22.12 / Remove legacy LDAP truenas_cacerts.pem file
  src/middlewared/middlewared/etc_files/generate_ssl_certs.py
  src/middlewared/middlewared/etc_files/local/nslcd.conf.mako
  src/middlewared/middlewared/etc_files/local/openldap/ldap.conf.mako
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-22.02.1

#8487 NAS-115215 / 22.12 / Remove pwd and grp lookups from minio etc file
  src/middlewared/middlewared/etc_files/local/minio/configure.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira, backport-13.0, backport-22.02.1

#8331 NAS-114978 / 22.12 / Default to enabling SA-based xattrs
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-13.0, backport-22.02.1

#8491 NAS-115218 / 22.12 / Avoid writing pool secrets to temp file and use fchmod where possible
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: jira, backport-22.02.1

#8498 NAS-115227 / 22.12 / fix cluster api tests
  cluster-tests/init_cluster.py
Labels: jira

#8496 NAS-115101 / 22.12 / Enable nscd for hosts
  src/middlewared/middlewared/etc_files/nscd.conf.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/network_/global.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/nscd.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: backport-22.02.1

#8503 NAS-115232 / 22.12 / Improve net global
  src/middlewared/middlewared/etc_files/hostname.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/network_/global.py
Labels: jira

#8506 NAS-115234 / 13.0 / import zpools by guid on failover event
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: jira

#8511 NAS-115177 / 22.12 / Fix broken SSH on fresh installs
  src/middlewared/middlewared/etc_files/local/ssh/config.py
Labels: backport-13.0, backport-22.02.1

#8468 NAS-115171 / 22.12 / Correctly specify type of raw/disk device in libvirt xml
  src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
Labels: backport-22.02.1

#8518 NAS-115244 / 22.12 / minor optimization in network common_validation
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.02.1

#8524 NAS-115249 / 22.12 / Fix regression in clusterjobs
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
Labels: jira, backport-22.02.1

#8526 NAS-115251 / 22.12 / add junit_family=xunit2
  cluster-tests/run-cluster-tests.py
Labels: jira

#8528 NAS-115253 / 22.12 / Allow specifying protocol when retrieving uri for display devices
  src/middlewared/middlewared/plugins/vm/devices/display.py
  src/middlewared/middlewared/plugins/vm/vm_display_info.py
Labels: jira

#8534 NAS-115268 / 22.12 / Fix id used for user-related config file regression tests
  tests/api2/test_011_user.py
Labels: jira, backport-22.02.1

#8532 NAS-115246 / 22.02.1 / Set default kbdmap
  src/middlewared/middlewared/alembic/versions/22.02/2022-03-12_12-50_set_default_kbdmap.py
  src/middlewared/middlewared/etc_files/vconsole.conf.mako
  src/middlewared/middlewared/plugins/system.py
Labels: backport-22.12

#8533 NAS-115258 / 22.02.1 / Make `network_alias` `alias_address` and `alias_interface_id` NOT NULL
  src/middlewared/middlewared/alembic/versions/22.02/2022-03-12_13-03_network_alias_not_null.py
Labels: jira, backport-22.12

#8543 NAS-115273 / 22.12 / Employ `flake8-import-order` to ensure correct import orders accordin…
  .github/workflows/lint.yml
Labels: jira, backport-13.0, backport-22.02.1

#8546 NAS-115277 / 22.02.1 / Fix `replication.list_datasets` crashing when `SSH+NETCAT` transport is used
  src/middlewared/middlewared/plugins/zettarepl.py
  tests/api2/test_replication_utils.py
Labels: jira, backport-13.0, backport-22.12

#8547 NAS-115290 / 13.0 / Bug fix for attaching disk
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
Labels: jira

#8535 NAS-115185 / 22.12 / Get correct stats path for ups service when configured in slave mode
  src/middlewared/middlewared/plugins/reporting/plugins.py
Labels: backport-22.02.1

#8553 NAS-115294 / 22.12 / lldp was removed so remove from api tests
  tests/api2/test_400_service.py
Labels: jira, backport-22.02.1

#8554 NAS-115295 / 22.12 / add system.product_type API test
  tests/api2/test_470_system.py
Labels: jira, backport-22.02.1

#8555 NAS-115298 / 22.12 / stop test_022_catalog completely on HA
  tests/api2/test_022_catalog.py
Labels: jira, backport-22.02.1

#8561 NAS-115302 / 22.12 / fix regression in dns.sync
  src/middlewared/middlewared/plugins/network_/dns.py
Labels: jira, backport-22.02.1

#8551 NAS-115231 / 22.12 / fix regression in zfs.pool.get_disks
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs_/disks.py
  tests/api2/test_009_pool.py
  tests/api2/test_090_boot.py
  tests/runtest.py
Labels: backport-22.02.1

#8566 DOCS-3392 / 22.12 / Fixed missing request in boot test 03 and 04
  tests/api2/test_090_boot.py
Labels: backport-22.02.1

#8569 NAS-115345 / 22.12 / fix failover.call_remote
  src/middlewared/middlewared/client/__init__.py
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: backport-13.0, backport-22.02.1

#8573 NAS-115348 / 22.12 / improve loggin in device_info_linux.py
  src/middlewared/middlewared/plugins/device_/device_info_linux.py
Labels: backport-22.02.1

#8580 NAS-115356 / 22.12 / Disable root squashing in export config on demand
  src/middlewared/middlewared/etc_files/exports.mako
Labels: jira, backport-22.02.1

#8508 NAS-115237 / 22.12 / Add better handling for NFS hosts that don't resolve
  src/middlewared/middlewared/alert/source/nfs_host.py
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira, backport-22.02.1

#8579 NAS-115355 / 22.12 / fix test_400_service.py
  tests/api2/test_400_enable_disable_services.py
  tests/api2/test_400_service.py
Labels: jira, backport-22.02.1

#8584 NAS-115363 / 22.12 / add @filterable to get_swap_mirrors
  .github/workflows/lint.yml
  src/middlewared/middlewared/plugins/disk_/swap_mirror.py
Labels: jira, backport-22.02.1

#8586 NAS-115367 / 22.12 / fix test_400_enable_disable_services on HA
  tests/api2/test_400_enable_disable_services.py
Labels: jira, backport-22.02.1

#8591 NAS-115374 / 22.12 / Do not report coredumps generated in containers
  src/middlewared/middlewared/alert/source/cores.py
Labels: backport-22.02.1

#8594 NAS-115378 / 22.12 / Ensure that rpc-statd service is enabled / started when NFS is started
  src/middlewared/middlewared/etc_files/default/nfs-common.mako
  src/middlewared/middlewared/plugins/service_/services/nfs.py
Labels: jira, backport-22.02.1

#8589 NAS-115370 / 22.12 / Allow SYS security for NFSv3
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira, backport-22.02.1

#8588 NAS-115369 / 22.12 / Fix test_003_network.py on HA
  tests/api2/test_003_network.py
Labels: jira, backport-22.02.1

#8604 NAS-115399 / 22.12 / Test NFS bindip separately from NFS server
  tests/api2/test_300_nfs.py
Labels: jira, backport-22.02.1

#8608 NAS-115405 / 22.12 / `from middlewared.test.integration.assets.pool import pool` to test p…
  src/middlewared/middlewared/test/integration/assets/pool.py
  tests/api2/test_007_pool_dataset_encryption.py
  tests/api2/test_009_pool.py
Labels: jira, backport-22.02.1

#8610 NAS-115411 / 22.12 / Fix test failure
  tests/api2/test_007_pool_dataset_encryption.py
  tests/api2/test_009_pool.py
Labels: jira, backport-22.02.1

#8613 NAS-115412 / 22.12 / improve disk.get_dev_size
  src/middlewared/middlewared/plugins/disk_/disk_info.py
  tests/api2/test_disk_get_dev_size.py
Labels: jira, backport-22.02.1

#8615 NAS-115414 / 22.12 / better test_disk_get_dev_size tests
  tests/api2/test_disk_get_dev_size.py
Labels: jira, backport-22.02.1

#8617 NAS-115422 / 13.0 / fix typo in disk_/sync.py causing KeyError
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#8620 NAS-115434 / 22.12 / fix test_disk_get_dev_size api test
  tests/api2/test_disk_get_dev_size.py
Labels: jira, backport-22.02.1

#8607 NAS-115383 / 22.12 / Prevent contents of /etc/exports.d from altering NFS config
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/zfs.py
  tests/api2/test_009_pool.py
Labels: backport-22.02.1

#8625 NAS-115430 / 22.12 / Fix inability to disable microsoft accounts
  src/middlewared/middlewared/plugins/account.py
Labels: backport-13.0, backport-22.02.1

#8628 NAS-115442 / 22.12 / Fix error in generating exports on firstboot
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#8631 NAS-115448 / 22.12 / Expand maproot tests
  tests/api2/test_300_nfs.py
Labels: jira, backport-22.02.1

#8612 NAS-113655 / 22.12 / Properly use zpool cachefile on HA
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/event_exceptions.py
  src/middlewared/middlewared/plugins/failover_/zpool_cachefile.py
Labels: backport-13.0, backport-22.02.1

#8635 NAS-115450 / 22.12 / Remove anonuid / anongid if user sets uid 0 / gid 0 as maproot
  src/middlewared/middlewared/etc_files/exports.mako
  tests/api2/test_300_nfs.py
Labels: jira, backport-22.02.1

#8639 NAS-115456 / 22.12 / Fix logic for ms-account validation
  src/middlewared/middlewared/plugins/account.py
Labels: jira, backport-22.02.1

#8644 NAS-115472 / 22.12 / fix test_disk_get_dev_size
  tests/api2/test_disk_get_dev_size.py
Labels: backport-22.02.1

#8624 NAS-115438 / 22.12 / Convert nfs_paths to nfs_path and remove alldirs
  src/middlewared/middlewared/alembic/versions/22.12/2022-03-23_16-23_fix-nfs-paths.py
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py
  tests/api2/test_300_nfs.py
Labels: jira

#8642 NAS-115469 / 22.12 / Optimize acl_is_trivial
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
Labels: jira, backport-22.02.1

#8646 NAS-115486 / 22.12 / Fix api docs not respecting port properly when redirecting
  src/middlewared/middlewared/apidocs/templates/index.html
Labels: jira

#8643 NAS-115471 / 22.12 / Remove LEGACY HA mode for SMB on SCALE
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.1

#8652 NAS-115496 / 22.12 / Add check that systemdataset pool is valid
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-22.02.1

#8654 NAS-115498 / 22.12 / Fix typo in filesystem.listdir and add optimization
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira, backport-22.02.1

#8663 NAS-115521 / 22.12 / return stp info in interface.query
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-22.02.1

#8666 NAS-115524 / 13.0 / fix disk.list_partitions and disk.gptid_from_part
  src/middlewared/middlewared/plugins/disk_/disk_info_freebsd.py
Labels: jira

#8668 NAS-115528 / 22.12 / Fix test for toggling sharenfs
  tests/api2/test_009_pool.py
Labels: backport-22.02.1

#8655 NAS-115479 / 22.12 / Retrieve images being consumed by ix-chart
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-22.02.1

#8673 NAS-115520 / 22.12 / Add filesystem.mkdir call to fix test failure
  tests/api2/test_300_nfs.py
Labels: backport-22.02.1

#8677 NAS-115529 / 22.12 / Ensure that ACL is always stripped prior to moving home folder
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: backport-22.02.1

#8679 NAS-115561 / 22.12 / Provide `sensors -j` output in debug
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
Labels: jira, backport-22.02.1

#8689 NAS-115580 / 13.0 / Fix AD join failure messages
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#8690 NAS-115574 / 22.02.1 / Fix starting jobs with lock from a thread without an event loop on python < 3.10
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/test/mock.py
  tests/api2/test_job_lock.py
Labels: backport-22.12
