Repository truenas/middleware, pull requests merged in 2022-08, with the labels that each got.

#9547 NAS-117463 / 13.0 / Fixed missing comma in pytest command list
  tests/runtest.py
Labels: jira

#9549 NAS-116513 / 22.12 / generate serial number for pmem devices
  src/freenas/debian/rules
  src/freenas/etc/udev/rules.d/61-pmem.rules
Labels: backport-22.02.4

#9553 NAS-117472 / 22.12 / minor grammar fix
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira, backport-22.02.4

#9555 NAS-116380 / 22.12 / ensure unique ns/gws in network.general.summary
  src/middlewared/middlewared/plugins/network_/general.py
Labels: backport-22.02.4

#9557 NAS-117478 / 22.12 / Revert change to SMB etc generation
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#9564 NAS-117485 / 22.12 / Fix rare `OrderedDict mutated during iteration`
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/service.py
Labels: backport-22.02.4

#9566 NAS-117449 / 22.12 / Sane timeout for cloud credentials verify
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-22.02.4

#9569 NAS-117483 / 22.12 / Fix cluster test
  cluster-tests/tests/cloudsync/test_cloudsync.py
Labels: backport-22.02.4

#9568 NAS-117495 / 22.12 / fix and improve middlewared Makefile
  src/middlewared/Makefile
Labels: jira, backport-22.02.4

#9572 NAS-117500 / 22.12 / call install-dev-tools before setup_test.py
  src/middlewared/Makefile
Labels: jira, backport-22.02.4

#9574 NAS-117501 / 22.12 / disk_resize: Don't trigger udev events for NVMe
  src/freenas/usr/local/sbin/disk_resize
Labels: jira, backport-22.02.4

#9548 NAS-117467 / 22.12 / Reuse tdb / ctdb handles
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
Labels: jira, backport-22.02.4

#9582 NAS-117524 / 22.12 / huge optimization to query_for_quota_alert
  src/middlewared/middlewared/plugins/zfs.py
Labels: jira, backport-22.02.4

#9584 NAS-117525 / 22.02.4 / Remove silent from starting service in custer test
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira

#9587 NAS-117528 / 22.12 / properly show ctdb public ip interface candidates
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py
Labels: backport-22.02.3, backport-22.02.4

#9593 NAS-117551 / 22.12 / Fix `ftp_server_with_user_account` asset
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/test/integration/assets/ftp.py
Labels: jira, backport-22.02.4

#9559 NAS-117479 / 22.12 / Skipping RAW device to be created
  src/middlewared/middlewared/plugins/vm/clone.py
Labels: jira, backport-22.02.4

#9590 NAS-117307 / 22.12 / Update ixvolumes during pool migration
  src/middlewared/middlewared/plugins/chart_releases_linux/redeploy.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: backport-22.02.4

#9598 NAS-117556 / 22.12 / fix IndexError in failover.vip.get_states
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: jira, backport-22.02.4

#9601 NAS-117562 / 22.12 / Add more dataset details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
Labels: jira

#9606 NAS-117587 / 22.12 / Fix regression in getgrnam for gid 0
  src/middlewared/middlewared/etc_files/group.mako
Labels: jira, backport-22.02.4

#9604 NAS-117584 / 22.12 / fix Makefile MWPATH
  src/middlewared/Makefile
Labels: jira, backport-22.02.4

#9603 NAS-117575 / 22.12 / Add more properties to dataset details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira

#9609 NAS-117600 / 13.0 / add back recoverable APEI alert
  src/middlewared/middlewared/plugins/hardware_/mca_and_apei_events.py
  src/middlewared/middlewared/pytest/unit/plugins/hardware/test_mca_and_apei_events.py
Labels: jira

#9615 NAS-117617 / 22.12 / Allow setting snapdev field for filesystems
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#9614 NAS-117601 / 22.12 / optmize system.general.get_ui_urls
  src/middlewared/middlewared/plugins/system_general/ui.py
Labels: backport-22.02.4

#9616 NAS-117604 / 22.12 / Fix initialization event for ctdbd
  src/middlewared/middlewared/scripts/ctdb_events.py
Labels: pending QA, backport-22.02.4

#9599 NAS-117557 / 22.12 / Improvements to ctdb.public.ips APIs
  cluster-tests/tests/interfaces/__init__.py
  cluster-tests/tests/interfaces/test_001_base_interface_tests.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py
Labels: jira, backport-22.02.4

#9624 NAS-117627 / 22.12 / fix zfs.dataset.query_for_quota_alert
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-22.02.4

#9626 NAS-117118 / 22.12 / Properly expose `Invalid update image file` error
  src/middlewared/middlewared/plugins/update_/utils_linux.py
Labels: backport-22.02.4

#9628 NAS-117636 / 22.02.4 / Fix account test assets
  src/middlewared/middlewared/test/integration/assets/account.py
Labels: jira

#9629 NAS-117635 / 22.12 / remove unused startup_seq file
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/main.py
Labels: jira

#9631 NAS-117661 / 22.12 / Minor bug fix for vm plugin
  src/middlewared/middlewared/plugins/vm/lifecycle.py
Labels: jira, backport-22.02.4

#9633 NAS-117673 / 22.12 / enforce minimum zfs passphrase length
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02.4

#9621 NAS-117622 / 22.12 / Add SMB client failover test for cluster
  cluster-tests/config.py
  cluster-tests/helpers.py
  cluster-tests/protocols.py
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
Labels: jira, backport-22.02.4

#9641 NAS-117681 / 22.12 / Remove overlay_dirs
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/migration.py
  src/middlewared/middlewared/utils/plugins.py
  src/middlewared/middlewared/worker.py
Labels: jira

#9441 NAS-117382 / 22.12 / Handle case of non-existent path during smbconf generation
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
Labels: jira, backport-22.02.4

#9637 NAS-117675 / 22.12 / Add basic tests for ctdb managed services
  cluster-tests/config.py
  cluster-tests/tests/smb/test_001_sharing_smb.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_services.py
Labels: jira, backport-22.02.4

#9644 NAS-117658 / 22.12 / fix KeyError for min_memory key
  src/middlewared/middlewared/plugins/vm/vm_memory_info.py
Labels: backport-22.02.4

#9648 NAS-117692 / 22.12 / Explicitly reference min_memory
  src/middlewared/middlewared/plugins/vm/vm_memory_info.py
Labels: jira

#9647 NAS-117691 / 22.02.4 / Minimum memory field is not applicable for angelfish based vms
  src/middlewared/middlewared/plugins/vm/vm_memory_info.py
Labels: jira

#9646 NAS-115869 / 22.12 / fix ntp on scale when dhcp is involved
  src/freenas/debian/preinst
  src/freenas/usr/lib/ntp/ntp-systemd-wrapper
Labels: backport-22.02.4

#9649 NAS-117695 / 22.02.4 / use asterisk to explicitly indicate full API access
  src/middlewared/middlewared/alembic/versions/22.02/2022-08-16_12-23_root_api_key.py
  src/middlewared/middlewared/plugins/api_key.py
  tests/api2/test_012_api_key.py
Labels: jira, backport-22.12

#9654 NAS-117711 / 13.0 / Increase vfs.zfs.zfetch.max_distance to 64MB.
  src/autotune/files/autotune.py
Labels: jira

#9639 NAS-117684 / 22.12 / Separately test basic NFS ops for version 3 and version 4
  tests/api2/test_300_nfs.py
  tests/protocols.py
Labels: jira, backport-22.02.4

#9656 NAS-117716 / 22.12 / Storj tests
  src/middlewared/middlewared/rclone/remote/storjix.py
  tests/api2/test_cloudsync_storj.py
Labels: jira

#9661 NAS-117728 / 22.12 / Shift timeouts to a single dict for cluster tests
  cluster-tests/config.py
  cluster-tests/helpers.py
  cluster-tests/tests/filesystem/test_001_base_filesystem_tests.py
  cluster-tests/tests/gluster/test_volume.py
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira, backport-22.02.4

#9669 NAS-117735 / 22.12 / Only break out of fuse mount loop early on success
  cluster-tests/tests/gluster/test_volume.py
Labels: jira, backport-22.02.4

#9671 NAS-117620 / 22.12 / fix SCALE HA upgrades
  src/freenas/usr/local/bin/truenas-nvdimm.py
  src/middlewared/middlewared/etc_files/nvdimm.mako
  src/middlewared/middlewared/etc_files/truenas_nvdimm.py
  src/middlewared/middlewared/plugins/etc.py
Labels: backport-22.02.4

#9658 NAS-117144 / 22.12 / Fix api docs not respecting port properly when redirecting
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-22.02.4

#9662 NAS-117699 / 22.12 / Add test for NFS server-side-copy
  tests/api2/test_300_nfs.py
  tests/protocols.py
Labels: backport-22.02.4

#9675 NAS-117761 / 22.12 / fix typo of nft fw rules for SCALE HA
  src/middlewared/middlewared/plugins/failover_/nftables.py
Labels: jira

#9678 NAS-117801 / 22.12 / Add some explicit tests for firstboot
  tests/api2/test_001_ssh.py
  tests/api2/test_cloudsync_storj.py
Labels: jira, backport-22.02.4

#9681 NAS-117655 / 22.12 / Directly query ldap config while validating AD config
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-22.02.4

#9679 NAS-117777 / 22.12 / Create SMB directories before reconfiguring logging
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-22.02.4

#9610 NAS-117602 / 22.12 / Privilege Management API
  src/middlewared/middlewared/alembic/versions/22.12/2022-08-17_13-37_privilege.py
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/builtin_administrator.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/api_key.py
  src/middlewared/middlewared/plugins/system_general/update.py
  src/middlewared/middlewared/test/integration/assets/account.py
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/api2/test_account_privilege.py
Labels: jira

#9688 NAS-115992 / 22.12 / Add plumbing for NFSv4 domain override to idmap config
  src/middlewared/middlewared/etc_files/idmapd.conf.mako
Labels: backport-22.02.4

#9686 NAS-117825 / 22.12 / Remove python nslcd client
  src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-22.02.4

#9692 NAS-117725 / 22.12 / Fix ctdb.shared.volume.teardown and add integration tests
  cluster-tests/config.py
  cluster-tests/run-cluster-tests.py
  cluster-tests/tests/cleanup/__init__.py
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/service_/services/glusterd.py
Labels: backport-22.02.4

#9697 NAS-117842 / 22.12 / fix creating/updating bonds
  src/middlewared/middlewared/plugins/interface/lag.py
Labels: jira

#9677 NAS-117806 / 22.12 / update network configuration domain to match AD one
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#9552 NAS-117471 / 22.12 / Improve AD health checks
  src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
  src/middlewared/middlewared/plugins/activedirectory_/health.py
Labels: pending QA, jira, backport-22.02.4

#8505 NAS-115235 / 22.12 / Restrict job log dir to root
  src/middlewared/middlewared/job.py
Labels: jira, backport-13.0

#9703 NAS-117858 / 22.12 / Relax validation for FreeBSD VFS modules
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
Labels: backport-22.02.4

#9707 NAS-117860 / 22.12 / Ensure that we always have a valid krb5.conf during AD start
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#9701 NAS-117802 / 22.12 / Update usage endpoint to use truenas domain
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-22.02.4

#9712 NAS-117865 / 22.12 / Fix timeout during idmap updates
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira, backport-22.02.4

#9710 NAS-117864 / 22.12 / Fix edge case for k8s node ca
  src/middlewared/middlewared/plugins/kubernetes_linux/nodes.py
Labels: jira

#9714 NAS-117868 / 22.12 / Do not run post stop actions if VM is suspended
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor_base.py
Labels: jira

#9716 NAS-117877 / 22.12 / Improve KDC detection during domain join
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira, backport-22.02.4

#9719 NAS-117889 / 22.12 / fix KeyError in pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira

#9595 NAS-117553 / 22.12 / Require at least one public IP address before joining cluster to AD
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#9718 NAS-117885 / 22.12 / Shift winbindd_cache.tdb path in middleware
  src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira, backport-22.02.4

#9722 NAS-116098 / 22.12 / stop / restart nmbd on sysdataset move
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-22.02.4

#9729 NAS-117921 / 22.12 / add `reinstall_container` make argument
  src/middlewared/Makefile
Labels: jira, backport-22.02.4

#9731 NAS-117843 / 22.12 / Allow specifying global middleware client timeout
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/client/utils.py
Labels: skip jira status

#9734 NAS-117926 / 22.12 / fix test_mountinfo unit test
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
Labels: jira

#9727 NAS-117674 / 22.12 / Use ExecStartPre in ix-zfs
  debian/debian/ix-zfs.service
Labels: backport-22.02.4

#9738 NAS-117933 / 22.12 / remove migrate call in make reinstall_container
  src/middlewared/Makefile
Labels: jira

#9742 NAS-117931 / 22.12 / HTTP Basic Auth is unavailable when OTP is enabled
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/restful.py
  tests/api2/test_auth_otp.py
Labels: backport-22.02.4, backport-22.12-BETA.1

#9748 NAS-117950 / 22.12 / mask ndctl-monitor.service
  debian/debian/postinst
Labels: jira

#9725 NAS-115737 / 22.02.4 / Fix spaces in zvols for extents
  src/middlewared/middlewared/alembic/versions/22.02/2022-08-24_12-58_update_iscsi_zvol_path.py
Labels: backport-22.12

#9735 NAS-117927 / 22.12 / Remove dead smartctl code and fix functional tests
  src/middlewared/middlewared/common/smart/areca.py
  src/middlewared/middlewared/common/smart/smartctl.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/smartctl.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
Labels: jira

#9746 NAS-117736 / 22.12 / Handle edge case for docker created time
  src/middlewared/middlewared/plugins/docker_linux/images.py
Labels: backport-22.02.4

#9741 NAS-117944 / 22.12 / Allow passing OTP token to `keychaincredential.remote_ssh_semiautomat…
  src/middlewared/middlewared/plugins/keychain.py
Labels: jira

#9757 NAS-117963 / 22.12 / Remove kernel share modes from Samba configuration
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
Labels: WIP
