Repository truenas/middleware, pull requests merged in 2022-04, with the labels that each got.

#8695 NAS-115587 / 22.12 / Remove geli logic on scale
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/pool_/format_disks.py
Labels: jira

#8577 NAS-115279 / 22.02.1 / Normalize REST resources for jobs that use pipes:
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/system.py
  src/middlewared/middlewared/plugins/test/rest.py
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/api2/test_rest_api_download.py
  tests/api2/test_rest_api_upload.py
Labels: backported, backport-22.12

#8686 NAS-115432 / 22.02.1 / net.inet.tcp.recvbuf_inc was removed in 13 (by yocalebo)
  src/middlewared/middlewared/alembic/versions/13.0/2022-03-23_11-40_remove_recvbuf_inc_tunable.py
  src/middlewared/middlewared/alembic/versions/22.02/2022-04-01_16_09_merge.py
Labels: backported, backport-22.12

#8701 NAS-115527 / 22.02.1 / Test public method (`timezone_choices`) instead of `get_timezone_choi…
  tests/api2/test_490_system_general.py
Labels: backport-22.12

#8704 NAS-115604 / 22.12 / Bug fix for configuring truecommand
  src/middlewared/middlewared/plugins/truecommand/update.py
Labels: backport-13.0, backport-22.02.1

#8707 NAS-115609 / 22.12 / fix typo in db migration
  src/middlewared/middlewared/alembic/versions/22.12/2022-04-01_16-26_merge.py
Labels: jira

#8667 NAS-115327 / 22.12 / Fix openapi json manifest
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/restful.py
  tests/api2/test_openapi.py
  tests/functions.py
Labels: backport-22.02.1

#8711 NAS-115552 / 22.12 / Improve validation when signing csr
  src/middlewared/middlewared/plugins/crypto_/sign_csr.py
Labels: backported, backport-22.02.1

#8714 NAS-104368 / 22.12 / Load and configure ntb_split kernel module.
  src/freenas/usr/lib/modprobe.d/truenas.conf
  src/freenas/usr/lib/modules-load.d/truenas.conf
Labels: backport-22.02.1

#8723 NAS-115671 / 22.12 / Properly disable haproxy service by default
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
Labels: jira

#8721 NAS-115642 / 22.12 / generate dual-nvdimm config on gen3 mseries hardware
  debian/debian/ix-etc.service
  debian/debian/ix-netif.service
  src/middlewared/middlewared/etc_files/dual-nvdimm.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: backport-22.02.1

#8727 NAS-115678 / 22.12 / fix NameError crash in exports.mako
  src/middlewared/middlewared/etc_files/exports.mako
Labels: jira, backport-22.02.1

#8722 NAS-115439 / 22.12 / Making sure helm apps are redeployed when some cert is renewed
  src/middlewared/middlewared/plugins/chart_releases_linux/cert_attachments.py
  src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: backport-22.02.1

#8732 NAS-115667 / 22.12 / Fix job lock test
  tests/api2/test_job_lock.py
Labels: backport-22.02.1

#8733 NAS-115616 / 22.12 / Do not account `iowait` as CPU busy time
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_get_cpu_usages.py
Labels: backport-22.02.1

#8735 Fix `system.info` schema
  src/middlewared/middlewared/plugins/system/dmi.py
  src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py
Labels: backport-22.02.1

#8724 NAS-115674 / 22.12 / Provide cluster cidr information in chart release context
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/redeploy.py
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
Labels: jira

#8699 NAS-115601 / 22.02.1 / Fix FileExistsError: [Errno 17] File exists: '/var/db/collectd/rrd/localhost' -> '/var/db/collectd/rrd/test91.test91.nb.ixsystems.com'
  src/middlewared/middlewared/plugins/reporting/configure.py
Labels: jira, backport-22.12

#8739 NAS-115639 / 22.12 / properly display zfs dataset recordsize choices
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py
  src/middlewared/middlewared/pytest/unit/plugins/pool/__init__.py
  src/middlewared/middlewared/pytest/unit/plugins/pool/test_recordsize_choices.py
Labels: backport-22.02.1

#8751 NAS-113532 / 22.12 / Specify `search_paths` for all `zfs.find_import` calls
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-22.02.1

#8756 NAS-115720 / 22.12 / Azure Custom Endpoint
  src/middlewared/middlewared/rclone/remote/azureblob.py
Labels: backport-13.0, backport-22.02.1

#8755 NAS-115707 / 22.12 / add ctdb.public.ips.interface_choices method
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py
Labels: backport-22.02.1

#8761 NAS-115752 / 22.12 / set netbios name in cluster api tests
  cluster-tests/config.py
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
Labels: jira

#8764 NAS-115749 / 22.02.1 / System dataset migration fixes
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/plugins/sysdataset.py
  tests/api2/test_system_dataset.py
Labels: backport-22.12

#8718 NAS-115646 / 22.12 / Optimize and fix tunable plugin for SCALE
  src/middlewared/middlewared/alembic/versions/22.12/2022-04-05_00-25_add_tun_orig_value.py
  src/middlewared/middlewared/etc_files/sysctl.py
  src/middlewared/middlewared/etc_files/sysctl_config.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/service_/services/sysctl.py
  src/middlewared/middlewared/plugins/tunables.py
  tests/api2/test_520_tunable.py
Labels: jira

#8771 DOCS-3530 / 22.12 / Fixed api2.test_system_dataset.test_system_dataset_migrate error
  tests/api2/test_system_dataset.py
Labels: backport-22.12

#8773 NAS-115766 / 22.02.1 / Fix NUT user group for 22.02.1
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#8529 NAS-115176 / 22.12 / snmp-agent integration test
  src/freenas/usr/local/bin/snmp-agent.py
  tests/api2/test_snmp_agent.py
Labels: backport-22.02.1

#8785 NAS-115783 / 22.12 / fix dhclient.conf generation
  src/middlewared/middlewared/etc_files/dhclient.conf.mako
Labels: backport-22.02.1

#8792 NAS-115837 / 22.12 / Fix crash on motd generation
  src/middlewared/middlewared/etc_files/motd.mako
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/system_advanced/config.py
Labels: jira

#8793 NAS-115836 / 22.12 / Retrieve SNMP MIB to test runner
  tests/api2/test_snmp_agent.py
Labels: jira

#8790 NAS-115793 / 22.12 / Allow netbiosname changes through AD plugin when clustered
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira, backport-22.02.1

#8796 NAS-115845 / 22.02.1 / Prevent integration tests to interfere with each other
  tests/api2/test_439_snapshottask_retention.py
Labels: jira, backport-22.12

#8805 NAS-115792 / 22.12 / NAS-115864 / 22.12 / generate new hostname properly
  src/middlewared/middlewared/plugins/network_/global.py
  tests/api2/test_network_configuration.py
Labels: backport-22.02.1

#8812 NAS-115882 / 22.12 / Do not try to create duplicate `minio`, `apps` and `webdav` groups (t…
  src/middlewared/middlewared/assets/account/builtin/freebsd/group
  src/middlewared/middlewared/assets/account/builtin/freebsd/passwd
  src/middlewared/middlewared/assets/account/builtin/linux/group
  src/middlewared/middlewared/assets/account/builtin/linux/passwd
  src/middlewared/middlewared/plugins/account_/sync_builtin.py
Labels: backport-22.02.1

#8795 NAS-115426 / 22.12 / Pass virtual hostname through netbiosname validation
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-13.0, backport-22.02.1

#8823 NAS-115913 / 22.12 / Secure temporary dir with `generate_ssh_key_pair`
  src/middlewared/middlewared/plugins/keychain.py
Labels: jira, backport-13.0, backport-22.02.1

#8822 NAS-115915 / 22.12 / Reduce the vulnerability to timing attacks
  src/middlewared/middlewared/plugins/auth.py
Labels: jira, backport-13.0, backport-22.02.1

#8834 NAS-115935 / 22.12 / Fix unit tests
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/pytest/unit/common/smart/test_smartctl.py
  src/middlewared/middlewared/pytest/unit/etc_files/test_smartd.py
  src/middlewared/middlewared/pytest/unit/helpers.py
  src/middlewared/middlewared/pytest/unit/middleware.py
  src/middlewared/middlewared/pytest/unit/plugins/failover/test_journal.py
  src/middlewared/middlewared/pytest/unit/plugins/network/test_convert_aliases_to_datastore.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_iostat.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
  src/middlewared/middlewared/pytest/unit/test_main.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/test/integration/utils/client.py
  src/middlewared/middlewared/utils/plugins.py
  tests/api2/test_schema_private.py
Labels: jira

#8788 NAS-115334 / 22.12 / Gather CPU temperatures for all CPUs
  src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_cpu_temperatures_amd.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_cpu_temperatures_generic.py
Labels: backport-22.02.2

#8802 NAS-115854 / 22.12 / Can't change SMB admin group due to typo
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.02.1

#8820 NAS-115850 / 22.12 / remove loginshell mapping from nslcd config
  src/middlewared/middlewared/etc_files/local/nslcd.conf.mako
Labels: backport-22.02.2

#8780 NAS-115947 / 13.0 / Ignore I101 in flake8 linter
  .github/workflows/lint.yml
Labels: jira

#7004 NAS-115948 / 22.12 / pare down acltype options to ones that ZFS returns
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#8849 NAS-115541 / 22.12 / Correctly handle network interface `description` and make sure it is …
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.02.1, backport-22.02.2

#8857 NAS-115866 / 22.12 / Changed rollback_snapshot to False in chart release test 40
  tests/api2/test_025_chart_release.py
Labels: backport-22.02.1, backport-22.02.2

#8865 NAS-115983 / 22.12 / missing f in f-string
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.02.2
