Repository truenas/middleware, pull requests merged in 2022-12, with the labels that each got.

#10157 NAS-119213 / 23.10 / Globally disable the vfs_fruit zero_file_id parameter
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: backport-22.12, backport-22.12.1

#10156 NAS-119226 / 23.10 / set_quota: Fix 0 to remove quota
  src/middlewared/middlewared/plugins/pool.py
Labels: jira, backport-22.12.1

#10155 NAS-119219 / 23.10 / Make validate_path_field properly location-aware
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/utils/path.py
Labels: backport-22.12, backport-22.12.1

#10124 NAS-119110 / 23.10 / Properly log scrub of pool in middleware logs
  src/middlewared/middlewared/plugins/pool.py
Labels: backport-22.12.1

#10172 NAS-119238 / 23.10 / Ensure app config always has release_name available
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/redeploy.py
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
Labels: jira, backport-22.12.1

#10183 NAS-119266 / 23.10 / Track tasks properly
  src/middlewared/middlewared/common/event_source/manager.py
  src/middlewared/middlewared/event.py
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/chart_releases_linux/host_path_attachments.py
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume_lifecycle.py
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/disk_/disk_events.py
  src/middlewared/middlewared/plugins/disk_/power_management_linux.py
  src/middlewared/middlewared/plugins/disk_/smartctl.py
  src/middlewared/middlewared/plugins/disk_/swap_remove.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/jobs_copy.py
  src/middlewared/middlewared/plugins/interface/listen.py
  src/middlewared/middlewared/plugins/iscsi_/host_injection.py
  src/middlewared/middlewared/plugins/kubernetes_linux/events.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/pool.py
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
  src/middlewared/middlewared/plugins/reporting/graphite.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/services/kubernetes.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/service_/services/ups.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/system/lifecycle.py
  src/middlewared/middlewared/plugins/system_advanced/config.py
  src/middlewared/middlewared/plugins/system_general/ui.py
  src/middlewared/middlewared/plugins/system_general/update.py
  src/middlewared/middlewared/plugins/truecommand/__init__.py
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/plugins/vm/attachments.py
  src/middlewared/middlewared/plugins/vm/lifecycle.py
  src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
  src/middlewared/middlewared/plugins/webdav.py
  src/middlewared/middlewared/plugins/zettarepl_/snapshot_removal_date.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
  src/middlewared/middlewared/service.py
Labels: jira, backport-22.12.1

#10174 NAS-119055 / 23.10 / Add kubernetes passthrough mode
  src/middlewared/middlewared/alembic/versions/22.12/2022-12-02_17-20_kubernetes_passthrough_mode.py
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
  src/middlewared/middlewared/pytest/unit/plugins/test_kubernetes.py
  tests/api2/test_kubernetes_passthrough_test.py
Labels: WIP, backport-22.12.1

#10191 NAS-119142 / 23.10 / Properly get serial number of virtio disk
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: backport-22.12.1

#10187 NAS-119278 / 23.10 / Document how to avoid "Host Key Verification Failed" error
  docs/source/dev-workspace/index.rst
  docs/source/dev-workspace/ssh-host-keys.rst
  docs/source/index.rst
  docs/source/testing/integration-tests/index.rst
Labels: jira

#10198 NAS-119292 / 23.10 / Safely access key when retrieving pods
  src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
Labels: jira, backport-22.12, backport-22.12.1

#10204 NAS-119294 / 23.10 / initramfs: Copy CorSSL HMAC files to initramfs
  src/freenas/usr/share/initramfs-tools/hooks/truenas
Labels: backport-22.12.1

#10206 NAS-119298 / 23.10 / retry pool import on invalid cachefile
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-22.12, backport-22.12.1

#10207 NAS-119300 / 23.10 / Drop winbind request timeout when not joined to AD
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: jira, backport-22.12, backport-22.12.1

#10210 NAS-119302 / 23.10 / `disk.sync_all_zfs_guid` for use in `vrrp_master`
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12.1

#10213 NAS-119267 / 23.10 / Change ordering and arguments of pam modules
  src/middlewared/middlewared/etc_files/pam.d/common-account.mako
  src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
  src/middlewared/middlewared/etc_files/pam.d/common-password.mako
  src/middlewared/middlewared/etc_files/pam.d/common-session.mako
  src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
Labels: backport-22.12.1

#10161 NAS-119007 / 23.10 / Present zvol snapshot count in dataset details
  src/middlewared/middlewared/alert/source/snapshot_count.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
  src/middlewared/middlewared/plugins/pool_/snapshot_count.py
  src/middlewared/middlewared/plugins/zfs.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
  tests/api2/test_snapshot_count_alert.py
Labels: backport-22.12.1

#10221 NAS-119353 / 23.10 / Add 1 second sleep to snapshots count alert test
  tests/api2/test_snapshot_count_alert.py
Labels: jira, backport-22.12.1

#10214 NAS-119241 / 23.10 / Add snapshot query tests.
  tests/api2/assets/REST/__init__.py
  tests/api2/assets/REST/pool.py
  tests/api2/assets/REST/snapshot.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_438_snapshots.py
Labels: backport-22.12.1

#10225 NAS-119357 / 23.10 / Fix regression when setting different quota types on same id(s)
  src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py
  src/middlewared/middlewared/plugins/zfs.py
  tests/api2/test_340_pool_dataset.py
  tests/api2/test_pool_dataset_set_quota.py
Labels: jira, backport-22.12.1

#10233 NAS-119386 / 13.0 / Fix and improve devd_listen
  src/middlewared/middlewared/plugins/device_/devd_events.py
Labels: jira

#10224 NAS-119356 / 23.10 / Avoid python DeprecationWarning wrt import of Callable.
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/plugins/chart_releases_linux/normalize_schema.py
Labels: jira

#10236 NAS-119399 / 23.10 / Fix "KeyError: 'remove_certificates' not found" exception.
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira, backport-22.12.1

#10240 NAS-119403 / 23.10 / fix alembic migration syntax error
  src/middlewared/middlewared/alembic/versions/22.12/2022-03-01_14-40_simplify_network_interfaces.py
Labels: backport-22.12.1

#10243 NAS-119410 / 23.10 / Fix locked status in pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira, backport-22.12.1

#10248 NAS-119374 / 22.12.1 / Allow sudo-enabled users to run virsh/kubectl in web shell with root privileges
  src/middlewared/middlewared/main.py
Labels: backport-23.10

#10250 NAS-119409 / 23.10 / mask mdadm and mdmonitor services
  debian/debian/postinst
Labels: backport-22.12.1

#10188 NAS-119208 / 23.10 / Try to extract /data/update.failed file from all the existing BEs
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
  src/middlewared/middlewared/plugins/system/debug_update_failed.py
  src/middlewared/middlewared/plugins/zfs.py
Labels: backport-22.12.1

#10254 NAS-119437 / 23.10 / Introduce `ErrnoMixin.ENOTAUTHENTICATED` as a code that WebUI will us…
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/main.py
Labels: backport-22.12.1

#10252 NAS-119251 / 23.10 / * Do not set ZFS guid for expired disks with the same name
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
  src/middlewared/middlewared/test/integration/utils/mock_db.py
  tests/api2/test_disk_zfs_guid.py
Labels: backport-22.12.1

#10219 NAS-119351 / 23.10 / Sanitse app errors from manual helm template catches
  src/middlewared/middlewared/plugins/chart_releases_linux/helm.py
Labels: jira

#10260 NAS-119460 / 23.10 / Fix restoring apps properly
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: jira

#10261 NAS-119398 / 23.10 / Fix backup/restore of k8s
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: backport-22.12.1

#10226 NAS-119360 / 23.10 / Remove old k3s/kubelet snapshots
  src/middlewared/middlewared/plugins/kubernetes_linux/migrations/0002_k3s_snapshots.py
Labels: jira

#10264 NAS-119469 / 23.10 / Do not write to `/var/log/jobs` in main loop
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: jira, backport-22.12.1

#10265 NAS-119402 / 22.12.1 / Fix migrations state
  src/middlewared/middlewared/alembic/versions/22.12/2022-12-19_08-31_fix_migrations_state.py
Labels: backport-23.10

#10259 NAS-119459 / 23.10 / Do not scale up workloads twice
  src/middlewared/middlewared/plugins/chart_releases_linux/rollback.py
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
  src/middlewared/middlewared/plugins/kubernetes_linux/restore.py
Labels: jira, backport-22.12.1

#10262 NAS-119366 / 23.10 / Fix nginx reverse proxy issue for haproxy
  src/middlewared/middlewared/plugins/vm/vm_display_info.py
Labels: backport-22.12.1

#10271 NAS-119478 / 23.10 / Fix docs build
  docs/install.sh
Labels: jira

#10228 NAS-119434 / 23.10 / Resolve symlinks when checking paths
  src/middlewared/middlewared/common/attachment/__init__.py
  src/middlewared/middlewared/plugins/chart_releases_linux/host_path_attachments.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  src/middlewared/middlewared/plugins/iscsi_/fs_attachment_delegate.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/s3_/attachments.py
  src/middlewared/middlewared/plugins/snapshot.py
  src/middlewared/middlewared/plugins/vm/attachments.py
  src/middlewared/middlewared/utils/path.py
Labels: jira, backport-22.12.1

#10274 NAS-119427 / 23.10 / fix snmp-agent.py
  src/freenas/usr/local/bin/snmp-agent.py
  src/freenas/usr/local/share/pysnmp/mibs/FREENAS-MIB.py
  src/freenas/usr/local/share/snmp/mibs/FREENAS-MIB.txt
Labels: backport-22.12.1

#10279 NAS-119540 / 23.10 / Remove ActiveDirectory monitor
  src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
  src/middlewared/middlewared/alert/source/active_directory.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/monitor.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.12.1

#10280 NAS-119546 / 23.10 / Ensure that SYSDATASET_PATH exists
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-22.12.1

#10283 NAS-119553 / 23.10 / Mark more sessions as internal
  src/middlewared/middlewared/auth.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12.1

#10289 NAS-119555 / 23.10 / Fix incorrect alerts keys usage
  src/middlewared/middlewared/alert/source/applications.py
  src/middlewared/middlewared/alert/source/catalogs.py
  src/middlewared/middlewared/alert/source/deprecated_service.py
  src/middlewared/middlewared/alert/source/jails.py
  src/middlewared/middlewared/alert/source/sharing_tasks.py
Labels: jira

#10288 NAS-119489 / 23.10 / Delete `PoolUpgraded` alert on pool upgrade
  src/middlewared/middlewared/alert/source/pools.py
  src/middlewared/middlewared/plugins/pool_/pool_operations.py
  tests/api2/test_pool_is_upgraded_alert_removal.py
Labels: backport-22.12.1

#10293 NAS-119511 / 23.10 / Fix failure backing up apps
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: backport-22.12.1

#10296 NAS-119511 / 23.10 / Fix filtering of secrets
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
Labels: backport-22.12.1

#10292 NAS-119558 / 23.10 / Refactor AD usage in test_030 and test_007
  tests/api2/assets/REST/directory_services.py
  tests/api2/test_007_systemdataset.py
  tests/api2/test_030_activedirectory.py
  tests/protocols/smb_proto.py
Labels: jira, backport-22.12.1

#10287 NAS-118588 / 23.10 / Fix kerberos ticket renewals
  src/middlewared/middlewared/etc_files/crontab.mako
  src/middlewared/middlewared/plugins/kerberos.py
Labels: backport-22.12.1

#10066 NAS-114479 / 23.10 / Shrink swap when formatting a disk in `pool.replace` to fit a data pa…
  src/middlewared/middlewared/plugins/disk_/format.py
  src/middlewared/middlewared/plugins/pool_/format_disks.py
  src/middlewared/middlewared/plugins/pool_/info.py
  src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
  src/middlewared/middlewared/test/integration/assets/pool.py
  tests/api2/test_pool_replace_disk.py
Labels: backported, backport-22.12.1

#10307 NAS-119623 / 23.10 / Do not silently `pass` zettarepl startup error
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: jira, backport-22.12.1

#10304 NAS-119619 / 23.10 / Fix scaling apps after restore
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
Labels: jira, backport-22.12.1

#10312 NAS-119396 / 23.10 / Update AMD device plugin image tag
  src/middlewared/middlewared/plugins/container_runtime_interface/images.py
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
Labels: backport-22.12.1

#10318 NAS-119637 / 23.10 / fix CI
  src/freenas/usr/bin/install-dev-tools
  src/middlewared/Makefile
Labels: jira

#10317 NAS-119633 / 23.10 / UI allowlist
  src/middlewared/middlewared/auth.py
  src/middlewared/middlewared/client/client.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12.1

#10306 NAS-119621 / 23.10 / dont spam logs
  src/middlewared/middlewared/alert/source/nvdimm.py
Labels: backport-22.12.1

#10322 NAS-119585 / 23.10 / remove dead code
  src/freenas/etc/netcli
Labels: backport-22.12.1

#10324 NAS-119423 / 23.10 / Strip trailing '/32' when writing /etc/initiators.allow
  src/middlewared/middlewared/etc_files/initiators.allow.mako
  src/middlewared/middlewared/test/integration/assets/iscsi.py
  tests/api2/test_iscsi_auth_network.py
Labels: backport-22.12.1

#10321 NAS-119608 / 23.10 / Do not crash migration when multiple bindings for the same IP are pre…
  src/middlewared/middlewared/alembic/versions/22.12/2022-07-27_01-00_portal_ips.py
Labels: backport-22.12.1

#10303 NAS-119618 / 22.12.1 / Use `$` for `admin` user zsh prompt
  src/freenas/root/.zshrc
Labels: jira, backport-23.10

#10331 NAS-119650 / 23.10 / change default homedir permissions on user create
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: backport-22.12.1

#10327 NAS-119649 / 23.10 / fix and improve user.shell_choices
  src/middlewared/middlewared/plugins/account.py
Labels: backported, backport-22.12.1

#10335 NAS-119667 / 22.12.1 / remove dangling references to netcli
  src/freenas/debian/rules
  src/freenas/etc/netcli.sh
  src/middlewared/middlewared/alembic/versions/22.12/2022-12-30_13-21_fix_netcli_refs.py
Labels: backport-23.10

#10334 NAS-119666 / 23.10 / Improve kerberos tests
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/schema.py
  tests/api2/assets/REST/directory_services.py
  tests/api2/test_032_ad_kerberos.py
  tests/protocols/__init__.py
Labels: jira, backport-22.12.1

#10336 NAS-119672 / 23.10 / Improve state handling in ad cache tests
  tests/api2/assets/REST/directory_services.py
  tests/api2/test_040_ad_user_group_cache.py
Labels: jira, backport-22.12.1

#10341 NAS-119676 / 23.10 / Shift two AD kerberos method to being private
  src/middlewared/middlewared/plugins/activedirectory_/krb5.py
Labels: jira, backport-22.12.1

#10342 NAS-119651 / 23.10 / add CLI as a shell to shell_choices
  src/middlewared/middlewared/plugins/account.py
Labels: backport-22.12.1

#10340 NAS-119673 / 23.10 / Improve state handling in AD idmap tests
  tests/api2/test_035_ad_idmap.py
Labels: jira, backport-22.12.1

#10346 NAS-119680 / 23.10 / Initialize use_default_domain to False on AD tests
  tests/api2/assets/REST/directory_services.py
Labels: jira, backport-22.12.1

#10348 NAS-119683 / 23.10 / Fix skipped idmap tests
  tests/api2/test_035_ad_idmap.py
Labels: jira, backport-22.12.1
