Repository truenas/middleware, pull requests merged in 2023-08, with the labels that each got.

#11764 NAS-123332 / 24.04 / fix crash in alert.license_status
  src/middlewared/middlewared/alert/source/license_status.py
Labels: backport-23.10

#11743 NAS-123337 / 24.04 / Add CI for clustered events
  cluster-tests/config.py
  cluster-tests/helpers.py
  cluster-tests/protocols.py
  cluster-tests/requirements.txt
  cluster-tests/run-cluster-tests.py
  cluster-tests/tests/ctdb/test_002_mutex_helper_tests.py
  cluster-tests/tests/ctdb/test_003_event_script.py
Labels: jira, backport-23.10

#11757 NAS-123305 / 24.04 / Add spare support in draid
  src/middlewared/middlewared/plugins/pool_/pool.py
  src/middlewared/middlewared/plugins/zfs_/pool.py
  src/middlewared/middlewared/plugins/zfs_/pool_utils.py
  tests/api2/test_draid.py
Labels: backport-23.10

#11767 NAS-123338 / 24.04 / change the release notes URL
  src/middlewared/middlewared/plugins/system/product.py
Labels: jira, backport-23.10

#11771 Increase allowed variance in FTP bandwidth test
  tests/api2/test_200_ftp.py
Labels: jira, backport-23.10

#11774 NAS-123353 / 24.04 / Remove redundant draid validation
  src/middlewared/middlewared/plugins/zfs_/pool.py
Labels: jira, backport-23.10

#11755 NAS-123000 / 24.04 / SATA: Wait for udev events to settle before setting max sector count
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-22.12.4, backport-23.10, backport-23.10-BETA.1

#11773 NAS-123268 / 24.04 / Use `output` SSH_TEST return value key for combined stdout and stderr
  src/middlewared/middlewared/test/integration/utils/ssh.py
  tests/api2/test_011_user.py
  tests/api2/test_014_failover_related.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_040_ad_user_group_cache.py
  tests/api2/test_130_cloudsync.py
  tests/api2/test_200_ftp.py
  tests/api2/test_210_group.py
  tests/api2/test_260_iscsi.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_275_ldap.py
  tests/api2/test_300_nfs.py
  tests/api2/test_340_pool_dataset.py
  tests/api2/test_347_posix_mode.py
  tests/api2/test_420_smb.py
  tests/api2/test_425_smb_protocol.py
  tests/api2/test_435_smb_registry.py
  tests/api2/test_450_staticroutes.py
  tests/api2/test_500_system_ntpservers.py
  tests/api2/test_api_key.py
  tests/api2/test_serial_consoles.py
  tests/functions.py
  tests/protocols/nfs_proto.py
Labels: backport-23.10

#11781 NAS-122711 / 24.04 / add ES102S enclosure support
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-23.10

#11784 NAS-123267 / 24.04 / Use the correct namespace id for disk resize
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-22.12.4, backport-23.10, backport-23.10-BETA.1

#11783 NAS-123309 / 24.04 / Safely retrieve data if netdata is not running
  src/middlewared/middlewared/plugins/reporting/netdata/__init__.py
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
  src/middlewared/middlewared/plugins/reporting/netdata/exceptions.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
  src/middlewared/middlewared/plugins/reporting/rest.py
Labels: backport-23.10, backport-23.10-BETA.1

#11792 NAS-123375 / 24.04 / fix KeyError crash in enclosure.query
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-23.10, backport-23.10-BETA.1

#11785 NAS-123392 / 24.04 / Simplify SMB share ACL handling
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  tests/api2/test_430_smb_sharesec.py
Labels: jira, backport-23.10

#11786 NAS-123015 / 24.04 / Do not allow starting k8s if system is not licensed
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: backport-23.10

#11797 NAS-123436 / 24.04 / Send `fields` for `zfs.snapshot.query` event
  src/middlewared/middlewared/plugins/zfs_/snapshot.py
  tests/api2/test_zfs_snapshot_events.py
Labels: jira, backport-23.10

#11798 NAS-123373 / 24.04 / Update VM NIC devices when migrating network interfaces
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
Labels: backport-23.10

#11799 NAS-123342 / 24.04 / Fix rsync tests
  tests/api2/test_rsync_ssh_authentication.py
Labels: backport-23.10, backport-23.10-BETA.1

#11801 NAS-123436 / 23.10 / Send `fields` for `zfs.snapshot.query` event (by themylogin)
  src/middlewared/middlewared/plugins/zfs_/snapshot.py
  tests/api2/test_zfs_snapshot_events.py
Labels: backport-23.10-BETA.1

#11807 NAS-123440 / 24.04 / Allow user to unset his 2fa secret
  src/middlewared/middlewared/plugins/account_/2fa.py
Labels: jira, backport-23.10

#11811 NAS-123451 / 24.04 / Add clustered sysdataset validation
  src/middlewared/middlewared/plugins/cluster_linux/management.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-23.10

#11776 NAS-123354 / 22.12.4 / Update cluster-tests for unified releng pipeline
  cluster-tests/requirements.txt
  cluster-tests/run-cluster-tests.py
Labels: jira

#11814 NAS-123363 / 24.04 / Fix disk temperature identifier bug
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Labels: backport-23.10

#11822 NAS-123074 / 24.04 / Add unit tests for realtime statistics
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
Labels: backport-23.10

#11824 NAS-123496 / 24.04 / fix regression in enclosure alert
  src/middlewared/middlewared/alert/source/enclosure_status.py
Labels: jira, backport-23.10

#11809 NAS-123443 / 24.04 / Handle netdata response in chunks
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
Labels: jira, backport-23.10

#11810 NAS-123216 / 24.04 / Do not crash on sysfs write failure
  src/middlewared/middlewared/plugins/tunables.py
Labels: backport-22.12.4, backport-23.10

#11831 NAS-123231 / 24.04 / Safely retrieve interfaces from iproute
  src/middlewared/middlewared/plugins/interface/netif_linux/routing.py
Labels: backport-23.10

#11835 NAS-123516 / 24.04 / fix smb.sharesec.entries
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: backport-23.10

#11839 NAS-123452 / 24.04 / Get rid of `NOTICE: s3: s3 provider "" not known - please set correctly`
  src/middlewared/middlewared/rclone/remote/s3.py
Labels: backport-23.10, backport-23.10-BETA.1

#11842 NAS-123463 / 24.04 / Do not wait indefinitely for a subscription request response
  src/middlewared/middlewared/client/client.py
Labels: backport-22.12.4, backport-23.10

#11836 NAS-123540 / 23.10 / Fix failover upgrade error
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira, backport-22.12.4, backport-24.04

#11848 NAS-123488 / 24.04 / Fix bug in interface stats
  src/middlewared/middlewared/plugins/reporting/realtime_reporting/ifstat.py
Labels: backport-23.10

#11853 NAS-123403 / 24.04 / Expanding iSCSI ZVol with a period in name doesn't notify connected client
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-23.10

#11856 NAS-123560 / 24.04 / Fix `get_cloudsync_tasks_count` and `get_rsync_tasks_count`
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: backport-23.10

#11815 NAS-123419 / 13.0 / Add overwrites for TrueCommand service start and get_state
  src/middlewared/middlewared/plugins/service_/services/base_freebsd.py
  src/middlewared/middlewared/plugins/service_/services/truecommand.py
  src/middlewared/middlewared/plugins/truecommand/portal.py
Labels: backported, backport-13.1

#11860 NAS-123572 / 24.04 / Update OTP test to try and disable 2FA
  tests/api2/test_auth_otp.py
Labels: jira, backport-13.0, backport-23.10, backport-13.1

#11865 NAS-123576 / 24.04 / Fix cpu temp plugin for those machine which don't have sensors
  src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
Labels: jira, backport-23.10

#11868 NAS-123570 / 24.04 / Extending a file-based iSCSI target has no effect
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-23.10

#11864 NAS-123574 / 24.04 / Fix TDB options mismatch for share_info.tdb
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: jira, backport-23.10

#11875 NAS-123452 / 24.04 / Fix empty provider message for STORJ
  src/middlewared/middlewared/rclone/remote/storjix.py
Labels: backport-23.10

#11878 NAS-123497 / 24.04 / Remove alerts from database when becoming failover master
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-23.10

#11876 NAS-123575 / 24.04 / Don't issue "New Feature Flags Are Available for Pool" alert for the boot-pool
  src/middlewared/middlewared/alert/source/pools.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
  tests/api2/test_pool_is_upgraded.py
Labels: backport-22.12.4, backport-23.10

#11873 NAS-123592 / 24.04 / Fix case when reporting identifier can be none
  src/middlewared/middlewared/plugins/reporting/graphs.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Labels: jira, backport-23.10

#11885 NAS-123608 / 24.04 / Give more time to rollback invalid UI configuration changes
  tests/api2/test_system_general_ui_rollback.py
Labels: backport-23.10

#11881 NAS-123601 / 24.04 / Fix snmp agent crashing on kstat.zfs.misc.arcstats.p
  src/freenas/usr/local/bin/snmp-agent.py
  src/freenas/usr/local/share/pysnmp/mibs/TRUENAS-MIB.py
  src/freenas/usr/local/share/snmp/mibs/TRUENAS-MIB.txt
Labels: backport-23.10

#11886 NAS-123606 / 24.04 / Mark `test_non_silent_service_start_failure` as flaky
  src/middlewared/middlewared/plugins/service_/services/base.py
  tests/api2/test_015_services.py
Labels: backport-23.10

#11871 NAS-123498 / 24.04 / Allow NFS server to start with empty or missing exports
  src/freenas/etc/systemd/system/nfs-server.service.d/override.conf
  src/middlewared/middlewared/alert/source/nfs_exportsd.py
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/service_/services/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-23.10

#11892 NAS-123535 / 24.04 / Gracefully handle client os error
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
Labels: backport-23.10

#11894 NAS-123605 / 24.04 / Update ftp IP connection test
  tests/api2/test_200_ftp.py
Labels: backport-23.10

#11898 NAS-123623 / 24.04 / acme: Fix instantiation of _CloudflareClient
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
Labels: jira, backport-23.10

#11896 NAS-123622 / 23.10 / Fix misused `id`
  src/middlewared/middlewared/plugins/pool_/unlock.py
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
Labels: jira, backport-22.12.4

#11812 NAS-123491 / 24.04 / Prevent pool export if hosting gluster volume
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira, backport-23.10

#11909 NAS-123659 / 24.04 / Fix listing interface IPv6 addresses
  src/middlewared/middlewared/plugins/interface/netif_linux/address/mixin.py
Labels: jira, backport-23.10

#11908 NAS-123635 / 24.04 / make `failover.upgrade_pending` use `can_update` utility function
  src/middlewared/middlewared/plugins/failover.py
Labels: backport-23.10

#11906 NAS-123374 / 24.04 / Fix `set_slot_status` not unmapping the physical enclosure bsg
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-23.10

#11914 NAS-123625 / 24.04 / Add changes to ensure UPS service works nicely in bookworm
  src/middlewared/middlewared/plugins/service_/services/ups.py
Labels: backport-23.10

#11849 NAS-121442 / 24.04 / Gather kubernetes statistics for UI
  src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py
  src/middlewared/middlewared/etc_files/netdata/python_conf.py
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/core_api.py
  src/middlewared/middlewared/plugins/kubernetes_linux/stats.py
  src/middlewared/middlewared/plugins/reporting/stats_utils.py
  src/middlewared/middlewared/plugins/reporting/utils.py
Labels: backport-23.10

#11919 NAS-123684 / 24.04 / Report abnormal installer process termination with code
  src/middlewared/middlewared/plugins/update_/install.py
Labels: jira, backport-22.12.4, backport-23.10

#11918 NAS-123674 / 24.04 / optimize addresses property in AddressMixin
  src/middlewared/middlewared/plugins/interface/netif_linux/address/mixin.py
Labels: jira

#11905 NAS-123515 / 24.04 / Destroy all tokens created or used in a session when it is forcibly t…
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/restful.py
  tests/api2/test_auth_token.py
Labels: backport-22.12.4, backport-23.10

#11924 NAS-122970 / 24.04 / Add default value for available gpus
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
Labels: backport-22.12.4, backport-23.10

#11925 NAS-123689 / 24.04 / Fix crash in querying ACL template
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira, backport-22.12.4, backport-23.10

#11931 NAS-123688 / 24.04 / Fix AttributeError crash in _doesVMDependOnDataStore
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-22.12.4, backport-23.10

#11928 NAS-123690 / 24.04 / Fix TypeError: on_zettarepl_state_changed() got an unexpected keyword…
  src/middlewared/middlewared/plugins/zettarepl_/state.py
Labels: jira

#11934 NAS-123692 / 24.04 / Add additional draid vdev stats when querying pool data
  src/middlewared/middlewared/plugins/pool_/pool.py
  src/middlewared/middlewared/plugins/pool_/topology.py
  src/middlewared/middlewared/plugins/pool_/utils.py
Labels: jira, backport-23.10

#11938 NAS-123589 / 24.04 / Do not have git spam middleware logs
  src/middlewared/middlewared/utils/git.py
Labels: backport-23.10

#11936 NAS-123612 / 24.04 / add fseries drive identification logic
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/fseries_drive_identify.py
Labels: backport-23.10

#11838 NAS-123632 / 24.04 / switch to `KubeletConfiguration` as flags are deprecated and add grace periods for node shutdown
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
Labels: jira

#11944 NAS-123661 / 24.04 / Fix `has_ipv6` not accounting for additional interface addresses
  src/middlewared/middlewared/plugins/interface/configure.py
Labels: backport-22.12.4, backport-23.10

#11947 NAS-123728 / 24.04 / Fix flake8
  src/middlewared/middlewared/plugins/interface/configure.py
Labels: jira

#11943 NAS-123326 / 24.04 / Improve retrieving historical stats performance
  src/middlewared/middlewared/plugins/reporting/graphs.py
  src/middlewared/middlewared/plugins/reporting/netdata/connector.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
  src/middlewared/middlewared/plugins/reporting/utils.py
Labels: backport-23.10

#11956 NAS-123571 / 24.04 / Add test for pool export behavior when clustered
  cluster-tests/tests/gluster/test_volume.py
Labels: backport-23.10

#11954 NAS-123286 / 23.10 / add ES60G2 enclosure detection
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/utils/license.py
Labels: backport-22.12.4, backport-24.04

#11955 NAS-123676 / 24.04 / Disable all forms of passthrough on ha machines
  src/middlewared/middlewared/plugins/system_advanced/gpu.py
  src/middlewared/middlewared/plugins/vm/devices/pci.py
  src/middlewared/middlewared/plugins/vm/devices/usb.py
  src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
Labels: backport-23.10

#11963 NAS-123700 / 24.04 / strip trailing newline/whitespace on sshpubkey
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_account_ssh_key.py
Labels: backport-23.10

#11966 NAS-123751 / 24.04 / fix update_sshpubkey
  src/middlewared/middlewared/plugins/account.py
Labels: backport-23.10

#11968 NAS-123753 / 24.04 / Wait for setperm when updating SSH pubkey
  src/middlewared/middlewared/plugins/account.py
Labels: backport-23.10

#11972 NAS-123654 / 24.04 / Use only one encrypted pool for system dataset on encrypted pool tests
  tests/api2/test_system_dataset.py
Labels: backport-23.10

#11974 NAS-123763 / 24.04 / fix edge-case crash in AddressMixin
  src/middlewared/middlewared/plugins/interface/netif_linux/address/mixin.py
Labels: backport-23.10

#11953 NAS-123042 / 24.04 / Relax restrictions on NFS subdir sharing
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/pytest/unit/plugins/test_nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-23.10

#11964 NAS-123755 / 24.04 / Collect disk temperature stats at 30 min intervals
  src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
  src/middlewared/middlewared/plugins/reporting/rest.py
  src/middlewared/middlewared/plugins/reporting/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
Labels: jira, backport-23.10

#11986 NAS-123607 / 24.04 / Fix kubernetes passthrough test
  tests/api2/test_25_kubernetes_passthrough_test.py
Labels: backport-23.10

#11991 NAS-123816 / 24.04 / Only run volume alert status alert once every hour
  src/middlewared/middlewared/alert/source/volume_status.py
Labels: jira, backport-23.10

#11993 NAS-123821 / 24.04 / Fix zpool status alerts
  src/middlewared/middlewared/alert/source/boot_pool.py
  src/middlewared/middlewared/alert/source/volume_status.py
  src/middlewared/middlewared/plugins/zfs_/pool.py
  src/middlewared/middlewared/utils/zfs.py
Labels: jira, backport-23.10

#11998 NAS-123825 / 24.04 / call query_imported_fast_impl in disabled_reasons
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira, backport-23.10

#12001 NAS-123830 / 24.04 / Add NotMatch validator and NFS share validation explanation
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/validators.py
Labels: jira, backport-23.10

#12002 NAS-123823 / 24.04 / Fix kubernetes backup name validation
  src/middlewared/middlewared/plugins/kubernetes_linux/backup.py
  tests/api2/test_026_kubernetes_backup_chart_releases.py
Labels: backport-23.10

#12007 NAS-123822 / 23.10 / Fix syslog-ng config generation (by anodos325)
  src/middlewared/middlewared/etc_files/syslogd.py
Labels: backport-23.10-RC.1

#12000 NAS-123614 / 24.04 / Have a retry mechanism in realtime event source
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: backport-23.10, backport-23.10-RC.1

#12006 NAS-123733 / 24.04 / Check for host keys in user home directory when setting up a rsync task
  src/middlewared/middlewared/plugins/rsync.py
  tests/api2/test_rsync_ssh_authentication.py
Labels: backport-23.10, backport-23.10-RC.1

#12014 NAS-123850 / 24.04 / remove ix-conf.service to fix /var/log
  debian/debian/ix-conf.service
  debian/debian/rules
  docs/source/os/boot-process.rst
  src/middlewared/debian/middlewared.service
Labels: jira, backport-23.10, backport-23.10-RC.1

#12019 NAS-123503 / 24.04 / Add alert misconfigured SMB paths
  src/middlewared/middlewared/alert/source/smb.py
Labels: backport-22.12.4, backport-23.10
