Repository truenas/middleware, pull requests merged in 2023-01, with the labels that each got.

#10275 NAS-119233 / 23.10 / Set valid keyboard layout if configured one is not supported
  src/middlewared/middlewared/migration/0008_default_keymap.py
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: backport-22.12.1

#10351 NAS-119702 / 23.10 / Add nameserver checks for activedirectory plugin
  src/middlewared/middlewared/alert/source/active_directory.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-22.12.1

#10353 NAS-119703 / 23.10 / Fix ix volume filtering in host path validation
  src/middlewared/middlewared/plugins/chart_releases_linux/host_path_attachments.py
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
Labels: jira, backport-22.12.1

#10354 NAS-119706 / 23.10 / Cleanly set and cleanup nameservers in test_007
  tests/api2/test_007_systemdataset.py
Labels: jira, backport-22.12.1

#10364 NAS-119758 / 23.10 / Add one second delay to test_21_Disconnect_iSCSI_target
  tests/api2/test_260_iscsi.py
Labels: jira

#10365 NAS-119762 / 23.10 / Fix display devices
  src/middlewared/middlewared/etc_files/haproxy/haproxy.cfg.mako
Labels: jira, backport-22.12.1

#10370 NAS-119330 / 23.10 / add readonly property to dataset_details.py
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
Labels: backport-22.12.1

#10373 NAS-119744 / 23.10 / add MINI-R platform to enclosure mgmt
  src/middlewared/middlewared/plugins/enclosure_/map.py
Labels: backport-13.0, backport-22.12.1

#10372 NAS-119782 / 23.10 / Shift bootready sentinel to middleware rundir
  src/middlewared/middlewared/plugins/system/__init__.py
  src/middlewared/middlewared/service.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira, backport-22.12.1

#10367 NAS-119763 / 23.10 / Expand tests for adding kerberos principal
  src/middlewared/middlewared/plugins/nfs_/krb5.py
  tests/api2/test_036_ad_ldap.py
Labels: jira, backport-22.12.1

#10380 NAS-119788 / 23.10 / Remove legacy optimization for AD cache
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
Labels: jira, backport-22.12.1

#10381 NAS-119789 / 23.10 / Shift more middleware-related sentinels to rundir
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/main.py
Labels: jira, backport-22.12.1

#10384 NAS-119795 / 23.10 / Fix progress reporting for NTFS disk import
  src/middlewared/middlewared/plugins/pool_/import_disk.py
Labels: jira, backport-22.12.1

#10387 NAS-119798 / 23.10 / fix random test failures wrt to service.start/stop
  tests/api2/test_015_services.py
  tests/api2/test_service.py
Labels: jira, backport-22.12.1

#10391 NAS-119801 / 23.10 / Add `--returncode` parameter to `runtest.py` so it returns a failure …
  tests/runtest.py
Labels: jira, backport-22.12.1

#10389 NAS-119799 / 23.10 / Fix overprovision logic overwriting `disks` variable contents
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: jira, backport-22.12.1

#10379 NAS-119733 / 23.10 / Save empty iSCSI target alias as NULL
  src/middlewared/middlewared/plugins/iscsi_/targets.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-22.12.1

#10397 NAS-119803 / 23.10 / verify timestamp changes when service fails
  tests/api2/test_015_services.py
Labels: jira, backport-22.12.1

#10399 NAS-119810 / 23.10 / fix ipmi sensor matching
  src/middlewared/middlewared/alert/source/ipmi_sel.py
  src/middlewared/middlewared/pytest/unit/alert/source/test_ipmi_sel.py
Labels: backport-13.0, backport-22.12.1

#10090 NAS-119814 / 23.10 / Add ("Power Supply", "Fully Redundant") to IPMI_EVENTS_BLACKLIST
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: jira, backport-13.0, backport-22.12.1

#10405 NAS-119817 / 23.10 / prevent changing unified_cgroup_hierarchy
  src/middlewared/middlewared/plugins/system_advanced/config.py
Labels: backport-22.12.1

#10302 NAS-119610 / 23.10 / Remove unnecessary method
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/test/integration/utils/ssh.py
  tests/api2/test_cloud_sync.py
  tests/api2/test_snmp_agent.py
Labels: jira, backport-22.12.1

#10412 NAS-119602 / 23.10 / fix enclosure.query
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-13.0, backport-22.12.1

#10409 NAS-119829 / 23.10 / Ensure that DNS is updated on domain join
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/network_/dns.py
  src/middlewared/middlewared/schema.py
  tests/api2/test_030_activedirectory.py
  tests/runtest.py
Labels: jira, backport-22.12.1

#10417 NAS-119727 / 23.10 / Do not fail local groupmap sync on broken domains
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: backport-22.12.1

#10420 NAS-119840 / 23.10 / Put additional interface info into wsdd config
  src/middlewared/middlewared/etc_files/local/wsdd.conf.mako
Labels: jira, backport-22.12.1

#10423 NAS-119842 / 23.10 / only run nvdimm alert on proper m-series
  src/middlewared/middlewared/alert/source/nvdimm.py
Labels: jira, backport-22.12.1

#10419 NAS-119839 / 23.10 / prevent console error log spam
  src/middlewared/middlewared/main.py
Labels: jira, backport-22.12.1

#10421 NAS-119841 / 23.10 / prevent breaking smartd service with extra options
  src/middlewared/middlewared/plugins/disk.py
Labels: jira, backport-22.12.1

#10429 NAS-119594 / 23.10 / Make ValidationError clearer for SMB share of apps DS
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-22.12.1

#10432 NAS-119707 / 23.10 / fix applying sysctl tunables on upgrade from 22.02
  src/middlewared/middlewared/alembic/versions/23.10/2023-01-13_17-44_fix_tunable_type.py
  src/middlewared/middlewared/plugins/tunables.py
Labels: backported, backport-22.12.1

#10434 NAS-119849 / 13.0 / fix memory allocation error on MASSIVE systems
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#10436 NAS-119851 / 23.10 / Fix migrations state
  docs/source/database/migrations.rst
  src/middlewared/middlewared/alembic/versions/22.12/2022-12-30_13-21_fix_netcli_refs.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-13_18-23_fix_tunable_type.py
  src/middlewared/middlewared/alembic/versions/23.10/2023-01-15_10-51_merge.py
Labels: jira

#10390 NAS-119800 / 23.10 / Handle gone processes in `pool.dataset_processes`
  src/middlewared/middlewared/plugins/pool_/dataset_processes.py
Labels: jira, backport-22.12.1

#10395 NAS-119455 / 23.10 / Fix swap creation
  src/middlewared/middlewared/plugins/disk_/swap_remove.py
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: backport-22.12.1

#10442 NAS-119485 / 22.12.1 / Allow specifying custom ovmf for VMs
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-16_ovmf_file.py
  src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: backport-23.10

#10447 NAS-119791 / 23.10 / Ensure that authorization tokens can only be used once
  src/middlewared/middlewared/plugins/auth.py
  tests/api2/test_auth_token.py
Labels: backport-22.12.1

#10450 NAS-119664 / 23.10 / Do not show WebUiRootLogin alert if root password is not disabled
  src/middlewared/middlewared/etc_files/web_ui_root_login_alert.py
Labels: backport-22.12.1

#10440 NAS-119854 / 23.10 / Validate disk device path
  src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
Labels: jira, backport-22.12.1

#10277 NAS-119507 / 23.10 / Don't delete builtin idmap table entries on constraint violation
  src/middlewared/middlewared/plugins/datastore/connection.py
Labels: backport-22.12.1

#10454 NAS-119873 / 23.10 / Fix image update header parsing
  src/middlewared/middlewared/plugins/container_runtime_interface/client.py
Labels: jira, backport-22.12.1

#10455 NAS-119876 / 23.10 / Add functional testing for NFS4 + KRB
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/kerberos.py
  tests/api2/test_036_ad_ldap.py
  tests/protocols/nfs_proto.py
Labels: jira, backport-22.12.1

#10452 NAS-119777 / 23.10 / Disable atime property on ix-applications dataset
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: backport-22.12.1

#10466 NAS-119892 / 23.10 / Fix typo in test_030_activedirectory
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-22.12.1

#10468 NAS-119893 / 23.10 / Fix AD start edge case for when keytab is entirely missing
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira, backport-22.12.1

#10369 NAS-119899 / 23.10 / Fix variant of the 256-bit NIST ECC curve
  src/middlewared/middlewared/plugins/crypto_/utils.py
Labels: jira

#10453 NAS-119630 / 23.10 / Allow users to download openvpn client configuration
  src/middlewared/middlewared/plugins/vpn.py
Labels: backport-22.12.1

#10472 NAS-119901 / 23.10 / fix failing unit test in test_vm.py
  src/middlewared/middlewared/pytest/unit/plugins/test_vm.py
Labels: jira, backport-22.12.1

#10476 NAS-119903 / 23.10 / Improve teardown after krb+nfs4 test module done
  tests/api2/test_036_ad_ldap.py
Labels: jira, backport-22.12.1

#10479 NAS-119904 / 23.10 / fix potentical crash in failover.events.event
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12.1

#10475 NAS-119902 / 23.10 / Remove some legacy handling from NFS and DS
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira, backport-22.12.1

#10435 NAS-119850 / 23.10 / Prevent users from foot-shooting with DENY entries in ACL
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
Labels: jira, backport-22.12.1

#10461 NAS-119882 / 22.12.1 / Re-add mistakenly deleted idmap table entry
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-17_15-29_fix-broken-idmap-table.py
Labels: jira, backport-23.10

#10486 NAS-119907 / 23.10 / Fix test_036_ad_ldap
  tests/api2/test_036_ad_ldap.py
Labels: jira, backport-22.12.1

#10490 NAS-119354 / 13.0 / Prevent breaking jobs manager if job log file was removed
  src/middlewared/middlewared/job.py
Labels: backport-22.12.1, backport-23.10

#10494 NAS-119919 / 23.10 / Fix regex for retrieving valid usb passthrough choices
  src/middlewared/middlewared/plugins/vm/usb.py
Labels: jira, backport-22.12.1

#10495 NAS-119920 / 23.10 / Fix sysdataset move
  src/middlewared/middlewared/etc_files/local/wsdd.conf.mako
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-22.12.1

#10496 NAS-119883 / 23.10 / Fix validating max length in string schema for apps
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
Labels: backport-22.12.1

#10501 NAS-119926 / 23.10 / Improve valid usb device regex
  src/middlewared/middlewared/plugins/vm/usb.py
Labels: jira, backport-22.12.1

#10503 NAS-119928 / 23.10 / Do not report GPUs if their count is 0 in k8s
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
Labels: jira, backport-22.12.1

#10509 NAS-119770 / 22.12.1 / Fix typo that leads to jobs being managed from outside the main event…
  src/middlewared/middlewared/main.py
Labels: backport-23.10

#10514 NAS-119933 / 23.10 / Enhance validation for licensed systems in apps
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: backport-22.12.1

#10518 NAS-119975 / 23.10 / Fix filtering service.query based on state
  src/middlewared/middlewared/plugins/service.py
Labels: jira, backport-22.12.1

#10522 NAS-119981 / 23.10 / Use optimization to avoid getting service state
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/iscsi_/host_injection.py
  src/middlewared/middlewared/plugins/pool_/unlock.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.1

#10525 NAS-119984 / 23.10 / Fix license logic check in catalogs
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira, backport-22.12.1

#10528 NAS-119384 / 23.10 / fix off-by-one on rear nvme mapping on R50BM
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
Labels: backport-22.12.1

#10520 NAS-119985 / 23.10 / Allow splitting up location of pam block info
  src/middlewared/middlewared/etc_files/pam.d/common-account.mako
  src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
  src/middlewared/middlewared/etc_files/pam.d/common-password.mako
  src/middlewared/middlewared/etc_files/pam.d/common-session-noninteractive.mako
  src/middlewared/middlewared/etc_files/pam.d/common-session.mako
  src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/ldap.py
  tests/api2/test_001_ssh.py
Labels: jira, backport-22.12.1

#10523 NAS-119983 / 23.10 / dont add pmem devices to smartd.conf
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/smart.py
Labels: jira, backport-22.12.1

#10534 NAS-119954 / 23.10 / KeyError crash in event_source/manager.py
  src/middlewared/middlewared/common/event_source/manager.py
Labels: backport-22.12.1

#10540 NAS-120000 / 23.10 / fix KeyError crash in kubernetes/update.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: jira, backport-22.12.1

#10544 NAS-120002 / 13.0 / fix await filter( typo
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#10549 NAS-120012 / 23.10 / Add basic time machine share preset
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.12.1

#10551 NAS-120015 / 23.10 / Fix KeyError when validating USB device
  src/middlewared/middlewared/plugins/vm/devices/usb.py
Labels: jira, backport-22.12.1

#10548 NAS-119959 / 23.10 / fix HA integration suite
  src/middlewared/middlewared/etc_files/default/smartmontools.mako
  src/middlewared/middlewared/etc_files/smartd.py
  tests/api2/test_001_ssh.py
Labels: backport-22.12.1

#10556 NAS-120022 / 23.10 / Fix single, HA and cluster CI
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira, backport-22.12.1

#10545 NAS-120020 / 23.10 / Apply some minor improvements to filter_list
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira, backport-22.12.1

#10561 NAS-120030 / 23.10 / Alter default for netbios-ns on fresh installs
  src/middlewared/middlewared/alembic/versions/12.0/2020-01-14_13-26_add_service_announcments.py
Labels: jira, backport-22.12.1

#10546 NAS-120003 / 23.10 / Add check for system.ready at beginning CI
  tests/api2/test_001_ssh.py
Labels: jira, DO NOT MERGE, backport-22.12.2

#10485 NAS-119605 / 22.12.2 / sudo rework + replication sudo
  src/freenas/usr/local/bin/truenas-set-authentication-method.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-18_09-31_replication_sudo.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-18_10-11_sudo_nopasswd_commands.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-18_17-09_sudo_refactoring.py
  src/middlewared/middlewared/etc_files/local/nut/upssched.conf.mako
  src/middlewared/middlewared/etc_files/local/sudoers.mako
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/sync_builtin.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/zettarepl.py
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/api2/test_011_user.py
  tests/api2/test_replication_sudo.py
Labels: backport-23.10

#10554 NAS-120018 / 23.10 / `iscsi.target.validate_name`
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: jira

#10567 NAS-120065 / 23.10 / Oneshot alerts are not created/deleted synchronously, give them some …
  tests/api2/test_pool_is_upgraded_alert_removal.py
Labels: backport-22.12.2, backport-22.12.1

#10555 NAS-119918 / 22.12.2 / `ssh_adminlogin`
  src/freenas/usr/local/bin/truenas-set-authentication-method.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-01-25_15-38_ssh_adminlogin.py
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
  src/middlewared/middlewared/plugins/ssh.py
Labels: backport-23.10, backport-22.12.1

#10574 NAS-120028 / 22.12.2 / Fix replacing a drive in a pool
  src/middlewared/middlewared/plugins/disk_/format.py
  tests/api2/test_pool_replace_disk.py
Labels: backport-23.10, backport-22.12.1

#10568 NAS-120063 / 23.10 / Fix sorting in disk_by_zfs_guid
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
Labels: backport-22.12.2, backport-22.12.1

#10577 NAS-120071 / 23.10 / Add order_by nulls_first, nulls_last
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10587 NAS-120068 / 23.10 / Set rdns off during kerberized NFS tests
  src/middlewared/middlewared/plugins/kerberos.py
  tests/api2/test_036_ad_ldap.py
Labels: backport-22.12.2, backport-22.12.1

#10585 NAS-120079 / 23.10 / Misc flake8 fixes
  src/middlewared/middlewared/alembic/versions/12.0/2020-01-28_00-31_add-smb-flag-to-accounts.py
  src/middlewared/middlewared/alembic/versions/12.0/2020-03-10_09-03_replication_readonly.py
  src/middlewared/middlewared/alembic/versions/12.0/2020-06-24_17-14_cleanup-ad-parameters.py
  src/middlewared/middlewared/alembic/versions/13.0/2022-02-11_19-54_increase_nfs_servers.py
  src/middlewared/middlewared/alembic/versions/22.12/2022-05-28_20-30_merge.py
  src/middlewared/middlewared/alert/service/snmp_trap.py
  src/middlewared/middlewared/etc_files/syslogd.py
  src/middlewared/middlewared/migration/0001_cloudsync_sftp_private_key_file.py
  src/middlewared/middlewared/plugins/boot.py
  src/middlewared/middlewared/plugins/kmip/sed_keys.py
  src/middlewared/middlewared/plugins/snapshot_/removal_date.py
  src/middlewared/middlewared/plugins/usage_/firstboot.py
  src/middlewared/middlewared/utils/cgroups.py
Labels: jira

#10565 NAS-120042 / 23.10 / Add test for ACL inheritance on new datasets via SMB
  tests/api2/test_030_activedirectory.py
  tests/api2/test_425_smb_protocol.py
Labels: backport-22.12.2, backport-22.12.1

#10592 NAS-120067 / 23.10 / fix test_00_firstboot_checks__stat
  tests/api2/test_001_ssh.py
Labels: backport-22.12.2, backport-22.12.1

#10596 NAS-120091 / 23.10 / fix ssh_credentials regression in replication
  src/middlewared/middlewared/plugins/replication.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10600 NAS-120033 / 22.12.2 / Update returns schema example for catalog items
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: backport-23.10

#10601 NAS-119201 / 23.10 / Expose waiting replication task reason
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: backport-13.0, backport-22.12.2

#10603 NAS-120104 / 23.10 / Fix random failure in container tests
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
  tests/api2/test_024_container.py
Labels: jira

#10610 NAS-120129 / 23.10 / Simplify nslcd state handling
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/nslcd.py
Labels: jira, backported, backport-22.12.2, backport-22.12.1

#10586 NAS-120036 / 23.10 / fix and improve enclosure disk slot mapping
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-22.12.2, backport-22.12.1

#10614 NAS-120081 / 22.12.1 / fix importing zpools on HA
  src/middlewared/middlewared/plugins/disk_/retaste.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/pool.py
Labels: backported, backport-22.12.2, backport-23.10

#10621 NAS-120153 / 13.0 / fix ValueError crash in enclosure plugin on 13
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
Labels: jira
