Repository truenas/middleware, pull requests merged in 2023-02, with the labels that each got.

#10604 NAS-120106 / 23.10 / Add some basic detection of misconfigured DNS
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-22.12.2

#10620 NAS-120162 / 23.10 / Simplified apps dataset preset
  src/middlewared/middlewared/plugins/filesystem_/perm_check.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_340_pool_dataset.py
Labels: jira, backport-22.12.2

#10623 NAS-120170 / 23.10 / skip test_06_krb5nfs_ops_with_ad on HA pipeline
  tests/api2/test_036_ad_ldap.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10627 NAS-120177 / 23.10 / ignore k3s.service core dumps
  src/middlewared/middlewared/alert/source/cores.py
Labels: jira

#10628 NAS-120171 / 23.10 / Apply SMB share preset prior to validation
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_435_smb_registry.py
Labels: backport-22.12.2, backport-22.12.1

#10634 NAS-120066 / 23.10 / fix websocket drop on scale HA failover event
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12.2, backport-22.12.1

#10631 NAS-120193 / 23.10 / Fix cleanup of DNS reverse zone
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/network_/dns.py
  tests/api2/assets/REST/directory_services.py
  tests/api2/test_030_activedirectory.py
Labels: backport-22.12.2, backport-22.12.1

#10645 NAS-120211 / 22.12.2 / Disk/partition sizes are always expressed in blocks of 512 bytes
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/disk_info.py
Labels: backport-23.10, backport-22.12.1

#10649 NAS-120228 / 23.10 / Clean up some remaining syslog items and fix sysds move
  src/middlewared/middlewared/etc_files/default/syslog-ng.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
  tests/api2/test_007_systemdataset.py
Labels: jira

#10632 NAS-120186 / 23.10 / Wait for app resources to be deleted by helm
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
  src/middlewared/middlewared/plugins/chart_releases_linux/scale_workload.py
Labels: jira

#10643 NAS-120200 / 23.10 / Fix random API test failure
  src/middlewared/middlewared/test/integration/assets/apps.py
  tests/api2/test_026_kubernetes_backup_chart_releases.py
Labels: jira

#10652 NAS-120147 / 22.12.2 / Restore AUTOINCREMENT property on primary keys of the tables that wer…
  src/middlewared/middlewared/alembic/env.py
  src/middlewared/middlewared/alembic/versions/22.02/2021-01-20_10-19_autoincrement.py
  src/middlewared/middlewared/alembic/versions/22.12/2023-02-07_10-33_autoincrement.py
Labels: backport-23.10, backport-22.12.1

#10656 NAS-119889 / 23.10 / bump udev receive queue buffer size to 256MB
  src/middlewared/middlewared/plugins/device_/udev_events.py
Labels: backport-22.12.2

#10651 NAS-120242 / 23.10 / Flush samba gencache after removing user or group
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira, backport-22.12.2

#10633 NAS-120190 / 23.10 / Add simplified API for granting ids access to path
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  tests/api2/test_340_pool_dataset.py
Labels: jira, backport-22.12.2

#10661 NAS-120246 / 23.10 / Edit iSCSI portal
  src/middlewared/middlewared/plugins/iscsi_/portal.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-22.12.2

#10664 NAS-120259 / 22.12.2 / `gpt_header_size` might vary between sector sizes; do not take it int…
  src/middlewared/middlewared/plugins/disk_/format.py
Labels: jira, backport-22.12.1

#10666 NAS-120234 / 23.10 / Add pci passthrough device description
  src/middlewared/middlewared/plugins/vm/pci.py
Labels: backport-22.12.2

#10665 NAS-120253 / 23.10 / Skip image update check for dangling images
  src/middlewared/middlewared/plugins/container_runtime_interface/update_alerts.py
Labels: backport-22.12.2

#10669 NAS-120261 / 23.10 / Fix tests
  tests/api2/test_008_pool.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10678 NAS-120226 / 23.10 / fix zpool import on failover events
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/zfs_/pool_actions.py
Labels: backport-22.12.2, backport-22.12.1

#10684 NAS-120291 / 23.10 / wait for disk events to settle on failover event
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/scripts/wait_on_disks.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10687 NAS-120092 / 23.10 / Fix editing S.M.A.R.T. tests
  src/middlewared/middlewared/plugins/smart.py
  tests/api2/test_smart_test_crud.py
Labels: backport-22.12.2, backport-22.12.1

#10662 NAS-120256 / 23.10 / clean up pool export
  src/middlewared/middlewared/plugins/pool_/export.py
Labels: jira, DO NOT MERGE, backport-22.12.2

#10695 NAS-120323 / 22.12.2 / fix truenas.get_chassis_hardware for legacy minis
  src/middlewared/middlewared/plugins/truenas.py
Labels: backport-23.10, backport-22.12.1

#10692 NAS-120315 / 23.10 / add serial_only kwarg to device.get_disks
  src/middlewared/middlewared/plugins/device_/device_info.py
Labels: jira, backport-22.12.2

#10700 NAS-120328 / 23.10 / fix typo gluster.peer.iniatialize_as_replacement
  src/middlewared/middlewared/plugins/gluster_linux/peer.py
Labels: jira, backport-22.12.2, backport-22.12.1

#10699 NAS-120324 / 23.10 / speed up failover.mismatch_disks
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12.2

#10704 NAS-120325 / 23.10 / add cpu_model to usage statistics
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-22.12.2

#10707 NAS-120345 / 23.10 / need to use IPs of cluster VMs
  cluster-tests/init_gluster.py
Labels: jira, backport-22.12.2

#10709 NAS-120346 / 23.10 / remove cloud sync cluster tests
  cluster-tests/tests/cloudsync/__init__.py
  cluster-tests/tests/cloudsync/test_cloudsync.py
Labels: jira, backport-22.12.2

#10706 NAS-120343 / 23.10 / Fix removing certificates for OpenVPN client
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira, backport-22.12.2

#10714 NAS-120145 / 23.10 / Expose `transient` flag in `core.get_jobs`
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/service.py
Labels: backport-22.12.2

#10715 NAS-120391 / 23.10 / Cleanup and improve SentryCrashReporting class
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/logging/__init__.py
  src/middlewared/middlewared/logging/sentry_crash_reporting.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: jira

#10720 NAS-120277 / 23.10 / Document return type in swagger API endpoints
  src/middlewared/middlewared/restful.py
Labels: backport-22.12.2

#10719 NAS-120398 / 23.10 / More cleanup to logger.py
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/logging/console_formatter.py
Labels: jira

#10726 NAS-120319 / 23.10 / Forbid using `ALL` with other commands for sudo commands list
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/keychain.py
Labels: backport-22.12.2

#10728 NAS-120428 / 13.0 / Ensure that DOSATTRIB xattr is disabled
  src/middlewared/middlewared/plugins/smb_/registry.py
Labels: jira

#10729 NAS-120430 / 23.10 / Fix ActiveDirectory DNS Health check Alert
  src/middlewared/middlewared/alert/source/active_directory.py
Labels: jira, backport-22.12.2

#10723 NAS-120417 / 23.10 / Add ability to specify whether to create homedir
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: jira, backport-22.12.2

#10733 NAS-120451 / 23.10 / fix TypeError crash
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12.2

#10730 NAS-120427 / 23.10 / Expand handling for CNAME records in dnsclient
  src/middlewared/middlewared/plugins/dns_client.py
Labels: backport-22.12.2

#10736 NAS-120465 / 23.10 / Fix sync_builtin.py
  src/middlewared/middlewared/plugins/account_/sync_builtin.py
Labels: jira

#10722 NAS-120416 / 23.10 / Handle case when no server is specified for openvpn server service
  src/middlewared/middlewared/plugins/vpn.py
Labels: jira

#10679 NAS-120280 / 23.10 / Add some validation for query-filters
  src/middlewared/middlewared/plugins/datastore/read.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/validators.py
Labels: jira, backport-22.12.2

#10745 NAS-120482 / 23.10 / Add last update field to schema
  src/middlewared/middlewared/plugins/catalogs_linux/item_version.py
  src/middlewared/middlewared/plugins/catalogs_linux/items.py
Labels: skip jira status

#10744 NAS-120243 / 23.10 / Properly validate BE name
  src/middlewared/middlewared/plugins/bootenv.py
Labels: backport-22.12.2

#10737 NAS-120478 / 23.10 / Make sure domain object is active before consumption
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py
Labels: jira, backport-22.12.2

#10743 NAS-120484 / 13.0 / Mark truecommand service as disabled on standby node
  src/middlewared/middlewared/plugins/truecommand/update.py
Labels: backport-22.12.2, backport-23.10

#10739 NAS-120424 / 22.12.2 / Add community train to preferred trains
  src/middlewared/middlewared/alembic/versions/22.12/2023-02-24_3-20_community_train.py
Labels: backport-23.10

#10742 NAS-120488 / 23.10 / fix API tests
  src/middlewared/middlewared/test/integration/assets/account.py
Labels: jira, backport-22.12.2

#10758 NAS-120527 / 23.10 / fix logical operator in portal port normalization
  src/middlewared/middlewared/plugins/chart_releases_linux/utils.py
Labels: jira

#10763 NAS-120498 / 23.10 / `ABORTED` status for S.M.A.R.T. tests
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-22.12.2

#10760 NAS-120528 / 23.10 / fix setting default gateway on 1st iface creation
  src/middlewared/middlewared/plugins/network.py
Labels: backport-22.12.2

#10765 NAS-120547 / 23.10 / Fix SMB share path validation for deeply nested directories
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_425_smb_protocol.py
Labels: jira, backport-22.12.2

#10771 NAS-120549 / 23.10 / disable invalid api tests until they can be reviewed
  tests/api2/test_022_catalog.py
  tests/api2/test_025_chart_release.py
Labels: jira

#10762 NAS-120534 / 23.10 / Fix removal of ctdb_shared_volume files during teardown
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
Labels: jira, backport-22.12.2

#10777 NAS-120561 / 23.10 / Reset cached SMB ha mode on cluster teardown
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira, backport-22.12.2

#10770 NAS-120563 / 23.10 / Ensure we append path separator in SMB validation
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.12.2
