Repository truenas/middleware, pull requests merged in 2023-09, with the labels that each got.

#12024 NAS-123756 / 13.0 / Generate WSDD config on SMB service restart
  src/middlewared/middlewared/plugins/service_/services/cifs.py
Labels: backport-13.1

#12031 NAS-123890 / 24.04 / Fix event name when creating/updating dataset
  src/middlewared/middlewared/plugins/pool_/dataset.py
Labels: jira, backport-23.10, backport-23.10-RC.1

#12030 NAS-123865 / 23.10 / fix init_shutdown_script.py and remove dead code
  src/middlewared/middlewared/alembic/versions/23.10/2023-09-01_11-11_remove_script_text.py
  src/middlewared/middlewared/plugins/init_shutdown_script.py
Labels: backport-24.04

#12034 NAS-123773 / 23.10 / Remove system dataset syslog
  src/middlewared/middlewared/alembic/versions/23.10/2023-09-02_09-06_remove_systemdataset_syslog.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: backport-24.04

#12039 NAS-123926 / 24.04 / Fix `filesystem.get`/`put`
  src/middlewared/middlewared/plugins/filesystem.py
Labels: backport-23.10, backport-23.10-RC.1

#12042 NAS-123942 / 24.04 / Remove older implementation of ixdiagnose
  src/freenas/usr/local/bin/freenas-debug
  src/freenas/usr/local/bin/ixdiagnose
  src/freenas/usr/local/libexec/freenas-debug/active_directory/active_directory.sh
  src/freenas/usr/local/libexec/freenas-debug/db_dump/db_dump.sh
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
  src/freenas/usr/local/libexec/freenas-debug/include.sh
  src/freenas/usr/local/libexec/freenas-debug/iscsi/iscsi.sh
  src/freenas/usr/local/libexec/freenas-debug/kubernetes/kubernetes.sh
  src/freenas/usr/local/libexec/freenas-debug/ldap/ldap.sh
  src/freenas/usr/local/libexec/freenas-debug/network/network.sh
  src/freenas/usr/local/libexec/freenas-debug/nfs/nfs.sh
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.nawk
  src/freenas/usr/local/libexec/freenas-debug/smart/smart.sh
  src/freenas/usr/local/libexec/freenas-debug/smb/smb.sh
  src/freenas/usr/local/libexec/freenas-debug/ssl/ssl.sh
  src/freenas/usr/local/libexec/freenas-debug/sysctl/sysctl.sh
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
  src/freenas/usr/local/libexec/freenas-debug/zfs/zfs.sh
Labels: jira

#12026 NAS-123782 / 24.04 / Update default recordsize for draid pool based datasets/zvols
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py
  src/middlewared/middlewared/plugins/pool_/pool.py
  src/middlewared/middlewared/plugins/pool_/utils.py
  tests/api2/test_draid_record_and_block_size.py
Labels: backport-23.10, backport-23.10-RC.1

#12051 NAS-123968 / 24.04 / Fix usage plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-23.10

#12052 NAS-123968 / 23.10 / Fix usage plugin (by anodos325)
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-23.10-RC.1

#12054 NAS-123981 / 24.04 / dramatically improve alert/license_status.py
  src/middlewared/middlewared/alert/source/license_status.py
Labels: jira, backport-23.10

#12057 NAS-123992 / 24.04 / Remove old rsync tests
  tests/api2/test_380_rsync.py
Labels: jira, backport-23.10, backport-23.10-RC.1

#12050 NAS-123960 / 24.04 / Add ability to convert mountinfo to tree
  src/middlewared/middlewared/pytest/unit/utils/test_mountinfo.py
  src/middlewared/middlewared/utils/osc/linux/mount.py
Labels: jira

#12013 NAS-123980 / 24.04 / Add syslog-ng mako files and syslog tests
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tndestinations.conf.mako
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
  src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
  src/middlewared/middlewared/etc_files/syslogd.py
  src/middlewared/middlewared/plugins/etc.py
  tests/api2/test_475_syslog.py
Labels: jira

#12060 NAS-123997 / 24.04 / Refactor SMB mountinfo validation to use getmnttree
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#12063 NAS-123948 / 24.04 / fix webUI zpool creation page
  src/middlewared/middlewared/plugins/disk_/availability.py
Labels: backport-23.10, backport-23.10-RC.1

#12067 NAS-124012 / 24.04 / Safely retrieve coredump exe attr
  src/middlewared/middlewared/plugins/system/coredump.py
Labels: jira, backport-23.10, backport-23.10-RC.1

#12066 NAS-124009 / 24.04 / Add some handling for RuntimeError in tdb library
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
Labels: jira, backport-23.10, backport-23.10-RC.1

#12072 NAS-124010 / 24.04 / Make `user` methods synchronous
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
Labels: backport-23.10

#12079 NAS-124054 / 24.04 / Mount /tmp filesystem noexec
  src/freenas/etc/systemd/system/tmp.mount
Labels: jira

#12080 NAS-124029 / 24.04 / Mark chart.release create/update method values as private
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: backport-23.10, backport-23.10-RC.1

#12078 NAS-124053 / 24.04 / Fix `script` schema arg in initshutdownscript plugin
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  tests/api2/test_240_initshutdownscript.py
  tests/api2/test_initshutdownscript.py
Labels: jira, backport-23.10

#12085 NAS-124079 / 22.12.4 / remove bad (failing) api tests
  tests/api2/test_080_auth.py
Labels: backport-23.10, backport-24.04

#12090 NAS-123969 / 24.04 / Handle file not found error in kubernetes stats
  src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py
Labels: backport-23.10, backport-23.10-RC.1

#12093 NAS-124088 / 24.04 / Fix dumping `List` that is `None`
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema/list_schema.py
Labels: backport-23.10, backport-23.10-RC.1

#12075 NAS-124058 / 24.04 / Stop doing runtime modifications of files in /usr
  src/freenas/debian/preinst
  src/freenas/etc/grub.d/10_truenas_linux
  src/freenas/usr/bin/install-dev-tools
  src/freenas/usr/bin/truenas-developer-enable.py
  src/freenas/usr/lib/netdata/conf.d/python.d.conf
  src/middlewared/middlewared/etc_files/generate_ssl_certs.py
  src/middlewared/middlewared/etc_files/netdata/python_conf.py
  src/middlewared/middlewared/plugins/bootenv.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#12096 NAS-124070 / 24.04 / Remove websocket message logging as it leaks private data
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/service/core_service.py
Labels: backport-22.12.4, backport-23.10, backport-23.10-RC.1

#12100 NAS-124108 / 24.04 / Toggle zfs readonly on /usr during binary mock
  src/middlewared/middlewared/test/integration/utils/mock_binary.py
Labels: jira

#12103 NAS-124118 / 24.04 / optimize reporting/events.py
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/reporting/events.py
  tests/api2/test_device_get_disk_names.py
Labels: jira, backport-23.10

#12102 NAS-124096 / 24.04 / Remove legacy / problematic SMB tests
  tests/api2/test_420_smb.py
Labels: backport-22.12.4, backport-23.10

#12105 NAS-124087 / 24.04 / retaste disks on standby on any pool create/delete op
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: backport-23.10, backport-23.10-RC.1

#12107 NAS-124121 / 24.04 / Rename developer script to discourage use in prod
  src/freenas/usr/bin/install-dev-tools
  src/freenas/usr/local/libexec/disable-rootfs-protection
Labels: jira

#12106 NAS-124115 / 24.04 / Fix draid integration test on HA vms
  tests/api2/test_draid_record_and_block_size.py
Labels: backport-23.10, backport-23.10-RC.1

#12115 NAS-124126 / 24.04 / raise better validation error on improper home dir
  src/middlewared/middlewared/plugins/account.py
Labels: backport-23.10

#12118 NAS-124093 / 24.04 / Fix error handling in `pool.dataset.recommended_zvol_blocksize`
  src/middlewared/middlewared/plugins/pool_/dataset_info.py
Labels: backport-23.10

#12120 NAS-124154 / 24.04 / fix flake8 issues in dataset_info.py
  src/middlewared/middlewared/plugins/pool_/dataset_info.py
Labels: jira

#12101 NAS-124062 / 13.0 / Mark minio service as deprecated
  src/middlewared/middlewared/plugins/service_/services/s3.py
  src/middlewared/middlewared/plugins/update_/install_freebsd.py
Labels: backport-13.1

#12124 NAS-124159 / 13.0 / Fix `take_systemdataset_samba4_snapshot`
  src/middlewared/middlewared/plugins/update.py
Labels: backport-23.10, backport-13.1, backport-24.04

#12130 NAS-124050 / 24.04 / Do not send the database from BACKUP to MASTER
  src/middlewared/middlewared/plugins/failover_/datastore.py
Labels: backport-23.10

#12133 NAS-124190 / 24.04 / mask ipmi usb ethernet on fseries platform
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-23.10

#12136 NAS-124194 / 24.04 / Silence a DeprecationWarning: invalid escape sequence warning, etc
  tests/api2/test_425_smb_protocol.py
Labels: jira

#12137 NAS-124209 / 23.10 / Add ESSLCERTVERIFICATIONERROR
  src/middlewared/middlewared/client/client.py
Labels: jira

#12138 NAS-124239 / 24.04 / Prevent testing suite to be green if pool creation fails
  src/middlewared/middlewared/test/integration/utils/__init__.py
  src/middlewared/middlewared/test/integration/utils/pytest.py
  tests/api2/test_001_ssh.py
  tests/api2/test_006_pool_and_sysds.py
  tests/conftest.py
Labels: backport-23.10

#11820 NAS-123999 / 24.04 / Add parser for audit messages
  src/middlewared/debian/control
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnaudit.conf.mako
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
  src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#12141 NAS-124245 / 13.0 / Fix handling pool with space in its name
  src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event.py
Labels: backport-13.1

#12143 NAS-124244 / 24.04 / add new NVDIMM info to mseries.nvdimm plugin
  src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Labels: backport-13.0, backport-23.10, backport-13.1

#12149 NAS-122711 / 13.1 / add ES102S to CORE
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
  src/middlewared/middlewared/utils/license.py
Labels: backport-13.0

#12151 NAS-123286 / 13.1 / add ES60G2 to CORE
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/enclosure_class.py
  src/middlewared/middlewared/utils/license.py
Labels: backport-13.0

#12131 NAS-124184 / 24.04 / Add support for FreeIPA netgroups
  src/middlewared/middlewared/plugins/ldap.py
  tests/api2/test_278_freeipa.py
Labels: jira, backport-23.10

#12157 NAS-124263 / 24.04 / Fix `pool.dataset.recommended_zvol_blocksize`
  src/middlewared/middlewared/plugins/pool_/dataset_info.py
  tests/api2/test_pool_dataset_info.py
Labels: backport-23.10

#12160 NAS-124207 / 24.04 / fix enclosure mapping for platforms with nvme
  src/middlewared/middlewared/plugins/enclosure_/map.py
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
Labels: backport-22.12.4, backport-23.10

#12153 NAS-124086 / 24.04 / Hide system reporting queries commands in SCALE CLI
  src/middlewared/middlewared/plugins/reporting/graphs.py
  src/middlewared/middlewared/plugins/reporting/update.py
Labels: backport-23.10

#12156 NAS-124292 / 24.04 / Fix defaults for SMB share auditing parameters
  src/middlewared/middlewared/alembic/versions/24.04/2023-09-19_16-05_smb_audit.py
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_420_smb.py
Labels: jira

#12161 NAS-124264 / 24.04 / hide failover CRUD from midcli
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: backport-22.12.4, backport-23.10

#12172 NAS-124310 / 24.04 / Clarify replica node count
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira, backport-23.10

#12175 NAS-124316 / 24.04 / dont run enclosure.detect on non-iX hardware
  src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
Labels: backport-23.10

#12177 NAS-124317 / 24.04 / Add more error handling for invalid passdb entries
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
Labels: jira, backport-13.0, backport-23.10, backport-13.1

#12182 NAS-124321 / 24.04 / Fix gluster.volume.query results
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira, backport-23.10

#12184 NAS-124326 / 24.04 / Fix API key based authentication cluster management
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira, backport-23.10

#12185 NAS-124327 / 24.04 / Fix crash in cluster.management.add_nodes
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira, backport-23.10

#12173 NAS-124312 / 24.04 / Add flag outlining if cpu temperatures are being retrieved
  src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira

#12189 NAS-123886 / 24.04 / Specify `--azureblob-chunk-size` to help with uploading large files
  src/middlewared/middlewared/rclone/remote/azureblob.py
Labels: backport-23.10

#12190 NAS-124324 / 24.04 / Remove bad autotune ZFS parameters
  src/freenas/usr/local/bin/truenas-autotune.py
Labels: backport-23.10

#11995 Set smbhash and unixhash to private
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#12188 NAS-124328 / 24.04 / Fix missing ip following removal of dev_test
  tests/api2/test_470_system.py
Labels: jira, backport-23.10

#12022 NAS-118579 / 24.04 / avahi-daemon is not announcing services
  src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
  src/middlewared/middlewared/plugins/service_/services/cifs.py
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/assets/websocket/__init__.py
  tests/api2/assets/websocket/server.py
  tests/api2/assets/websocket/service.py
  tests/api2/test_200_ftp.py
  tests/api2/test_310_service_announcement.py
  tests/requirements.txt
Labels: backport-23.10

#12193 NAS-124334 / 24.04 / Make passdb reinit check use case-insensitive filter
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: jira, backport-23.10

#12198 NAS-124346 / 24.04 / Add cluster.management.replace_node stub
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira, backport-23.10

#12164 NAS-124295 / 24.04 / Use username in provisioning uri
  src/middlewared/middlewared/plugins/account_/2fa.py
Labels: jira, backport-23.10

#12203 NAS-124352 / 24.04 / Add iSCSI initiator group test
  tests/api2/test_261_iscsi_cmd.py
Labels: jira, backport-23.10

#12205 NAS-124374 / 24.04 / Fix missing import when doing internal blackhole
  src/middlewared/middlewared/plugins/failover_/internal_interface.py
Labels: jira

#12206 NAS-124269 / 24.04 / Fix detection and reporting of network overlap
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-23.10

#12209 No longer shortcut alua_enabled when license contains FIBRECHANNEL
  src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
Labels: backport-22.12.4, backport-23.10

#12202 NAS-123504 / 24.04 / fix ix-zfs.service
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: backport-23.10

#12200 NAS-124348 / 24.04 / Add flag showing if a display device is available for a VM
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira, backport-23.10

#12216 NAS-124361 / 24.04 / Define ids when running cert tests
  tests/api2/test_certs.py
Labels: backport-23.10

#12218 NAS-124391 / 24.04 / Virtual IP portal address for iSCSI ALUA target not applied correctly
  src/middlewared/middlewared/etc_files/scst.conf.mako
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-23.10

#12213 NAS-124388 / 24.04 / Refactor and simplify test_420_smb
  tests/api2/test_420_smb.py
Labels: jira, backport-23.10

#12214 NAS-124128 / 24.04 / Improve performance for netdata retrieving graphs data
  src/middlewared/middlewared/plugins/reporting/graphs.py
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
  src/middlewared/middlewared/plugins/reporting/netdata/connector.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
  src/middlewared/middlewared/plugins/reporting/utils.py
Labels: backport-23.10
