Repository truenas/middleware, pull requests merged in 2023-07, with the labels that each got.

#11613 NAS-122331 / 22.12.4 / Fix VM dataset unlock test in bluefin
  tests/api2/test_pool_dataset_unlock_restart_vms.py
Labels: backport-23.10

#11617 NAS-122800 / 23.10 / Refactor replication tests
  src/middlewared/middlewared/test/integration/assets/replication.py
  tests/api2/test_370_replication.py
  tests/api2/test_replication.py
Labels: jira

#11620 NAS-122808 / 23.10 / Restrict permissions on gluster jwt seed
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
Labels: jira, backport-22.12.4

#11622 NAS-122813 / 23.10 / Add more protection for JWT usage in cluster event
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/webhooks/cluster_events.py
Labels: jira, backport-22.12.4

#11625 NAS-122818 / 23.10 / Fix gluster.volume.optset endpoint
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira, backport-22.12.4

#11624 NAS-122817 / 23.10 / simplify and improve vm.device.get_pci_devices
  src/middlewared/middlewared/plugins/vm/pci.py
Labels: jira, backport-22.12.4

#11618 NAS-122812 / 23.10 / Refactor snapshot task retention tests
  tests/api2/test_439_snapshottask_retention.py
  tests/api2/test_snapshot_task_retention.py
Labels: jira

#11629 NAS-122819 / 22.12.4 / Do not allow remote fuse mounts of ctdb_shared_vol
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira

#11633 NAS-122823 / 23.10 / Remove simplejson
  src/middlewared/debian/control
  src/middlewared/middlewared/plugins/support.py
Labels: jira

#11634 NAS-122829 / 23.10 / Configure 2fa for user after enabling it globally in tests
  tests/api2/test_twofactor_auth.py
Labels: jira

#11615 NAS-122782 / 23.10 / Remove hard-coded ctdb_shared_vol for glusterfs
  cluster-tests/config.py
  cluster-tests/init_gluster.py
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
  cluster-tests/utils.py
  src/middlewared/middlewared/alert/source/ctdb.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_setup.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/gluster_linux/filesystem.py
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/plugins/gluster_linux/peer.py
  src/middlewared/middlewared/plugins/gluster_linux/utils.py
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
  src/middlewared/middlewared/plugins/service_/services/glusterd.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/webhooks/cluster_events.py
Labels: jira

#11631 NAS-115723 / 23.10 / Add explanation for catalog label regex
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: backport-22.12.4

#11640 NAS-122844 / 23.10 / better iommu enabled detection
  src/middlewared/middlewared/plugins/vm/pci.py
Labels: jira, backport-22.12.4

#11636 NAS-122839 / 23.10 / Get rid of Flask
  src/middlewared/debian/control
  src/middlewared/middlewared/apidocs/__init__.py
  src/middlewared/middlewared/apidocs/proxy.py
  src/middlewared/middlewared/apidocs/templates/index.html
  src/middlewared/middlewared/apidocs/templates/websocket.html
  src/middlewared/middlewared/apidocs/templates/websocket/events.md
  src/middlewared/middlewared/apidocs/templates/websocket/jobs.md
  src/middlewared/middlewared/apidocs/templates/websocket/protocol.md
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/utils/mako.py
  src/middlewared/middlewared/utils/mako_filters.py
Labels: jira

#11635 NAS-122831 / 23.10 / Fix rsync tests
  tests/api2/test_380_rsync.py
Labels: jira

#11642 NAS-122859 / 23.10 / Improve schema handling for private items
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
Labels: jira

#11646 NAS-122871 / 23.10 / fix failing iscsi test
  tests/api2/test_iscsi.py
Labels: jira

#11623 NAS-122875 / 23.10 / [vm] Be more specific about which PCI device/controllers are "sensitive"
  src/middlewared/middlewared/utils/gpu.py
Labels: jira, backport-22.12.4

#11632 NAS-122750 / 23.10 / Explicitly specify BE names for HA upgrades
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/update.py
Labels: pending QA

#11645 NAS-122869 / 23.10 / Better REST error message
  src/middlewared/middlewared/restful.py
Labels: jira, backport-22.12.4

#11644 NAS-122865 / 23.10 / fix vm.device.passthrough_device_choices
  src/middlewared/middlewared/plugins/vm/pci.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_passthrough_choices.py
Labels: jira, backport-22.12.4

#11651 NAS-122933 / 23.10 / Support dual-homed servers
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
Labels: jira

#11655 NAS-122974 / 23.10 / Shift automation workloads to dedicated AD OU
  tests/api2/test_012_directory_service_ssh.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_036_ad_ldap.py
  tests/api2/test_040_ad_user_group_cache.py
Labels: jira

#11657 NAS-119331 / 23.10 / On bridge update, do not put its member down if it already was a member of the bridge before update.
  src/middlewared/middlewared/plugins/interface/bridge.py
Labels: backport-22.12.4

#11643 NAS-122919 / 23.10 / Improve ctdb private ips
  cluster-tests/config.py
  cluster-tests/init_cluster.py
  cluster-tests/init_gluster.py
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
  cluster-tests/tests/gluster/test_volume.py
  cluster-tests/tests/interfaces/test_001_base_interface_tests.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_private.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_public.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/gluster_linux/fuse.py
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/plugins/gluster_linux/peer.py
  src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
  src/middlewared/middlewared/plugins/gluster_linux/utils.py
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#11661 NAS-122697 / 23.10 / prevent crash when users doing things via the cli
  src/middlewared/middlewared/plugins/zfs_/utils.py
Labels: backport-22.12.4

#11660 NAS-122659 / 23.10 / Properly catch exception with invalid helm secret
  src/middlewared/middlewared/plugins/chart_releases_linux/secrets_management.py
Labels: backport-22.12.4

#11663 NAS-122363 / 23.10 / Fix vm display validation errors
  src/middlewared/middlewared/plugins/vm/devices/display.py
Labels: backport-22.12.4

#11667 NAS-123020 / 23.10 / Fix tests
  tests/api2/test_replication_role.py
Labels: jira

#11671 NAS-123029 / 23.10 / Fix nested subquestions on app upgrade
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
Labels: jira

#11669 NAS-122821 / 23.10 / Allow dot (.) through local username validation
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
Labels: backport-22.12.4

#11673 NAS-123037 / 23.10 / Add make to dev tools
  src/freenas/usr/bin/install-dev-tools
Labels: jira

#11679 NAS-123040 / 23.10 / Fix creating PCI device
  src/middlewared/middlewared/plugins/vm/pci.py
Labels: jira, backport-22.12.4

#11683 NAS-122891 / 23.10 / Fix rsync with remote path containing whitespace
  src/middlewared/middlewared/plugins/rsync.py
  tests/api2/test_rsync_ssh_authentication.py
Labels: backport-22.12.4

#11682 NAS-122863 / 23.10 / Generate passwd and shadow files after setting up the local administrator
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_user_admin.py
Labels: backport-22.12.4

#11668 NAS-123054 / 23.10 / Use preshared secret for localevents for clpwenc
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: jira

#11686 NAS-123053 / 23.10 / Send event to TrueCommand when node becomes leader
  src/freenas/usr/local/sbin/ctdb_glfs_lock
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
Labels: jira

#11670 NAS-123056 / 23.10 / Mark clustered service flakey
  cluster-tests/tests/smb/test_001_sharing_smb.py
Labels: jira

#11687 NAS-123057 / 23.10 / `failover.datastore.send` does not accept extra arguments
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira, backport-22.12.4

#11689 NAS-123062 / 23.10 / Encrypt gluster localevents payloads
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/webhooks/cluster_events.py
Labels: jira

#11690 NAS-123022 / 23.10 / flush "INPUT" chain in failover.firewall methods
  src/middlewared/middlewared/plugins/failover_/nftables.py
Labels: backport-22.12.4

#10033 NAS-118764 / 23.10 / Add CI for cluster mutex
  cluster-tests/config.py
  cluster-tests/tests/ctdb/__init__.py
  cluster-tests/tests/ctdb/test_001_base_interface_tests.py
  cluster-tests/tests/ctdb/test_002_mutex_helper_tests.py
  src/freenas/usr/local/sbin/ctdb_glfs_lock
Labels: jira

#11692 NAS-123068 / 23.10 / improve and fix service_remote and call_remote
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira, backport-22.12.4

#11695 NAS-123073 / 23.10 / Also catch self-emited `CallError` when `raise_connect_error` is spec…
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira

#11698 NAS-123088 / 23.10 / Use flake8-builtins
  .github/workflows/lint.yml
Labels: jira

#11699 NAS-123086 / 23.10 / Add option to rebalance volume when adding nodes
  cluster-tests/tests/gluster/test_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
  src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
Labels: jira

#11694 NAS-123069 / 23.10 / Prevent logged in iSCSI targets being included in get_disks
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/retaste.py
  tests/api2/test_261_iscsi_cmd.py
Labels: jira

#11706 NAS-123116 / 23.10 / Reduce log spam for clustered services file
  src/middlewared/middlewared/scripts/ctdb_events.py
Labels: jira

#11707 NAS-123118 / 23.10 / Do not log websocket messages from internal sessions
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#11701 NAS-123089 / 23.10 / Do not spam upsd errors
  src/middlewared/middlewared/plugins/ups.py
Labels: backport-22.12.4

#11714 NAS-123132 / 23.10 / Add validation for gluster volume creation
  cluster-tests/init_gluster.py
  cluster-tests/tests/gluster/test_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
  src/middlewared/middlewared/plugins/gluster_linux/rebalance.py
Labels: jira

#11715 NAS-123146 / 23.10 / Fix CTDB root dir migration
  src/middlewared/middlewared/plugins/gluster_linux/volume.py
Labels: jira

#11716 NAS-123147 / 23.10 / Mark gluster volume stop as flaky
  cluster-tests/tests/gluster/test_volume.py
Labels: jira

#11717 NAS-123148 / 23.10 / Use directories rather than mountpoints for bricks
  cluster-tests/config.py
  cluster-tests/init_cluster.py
  cluster-tests/tests/gluster/test_volume.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira

#11719 NAS-123033 / 23.10 / Ignore interfaces created by tailscale
  src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
Labels: backport-22.12.4

#11718 NAS-123170 / 23.10 / Add endpoint to validate pool name
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: jira

#11728 NAS-123222 / 23.10 / mark ipmi.sel.elist/info as transient=true
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: backport-22.12.4

#11730 NAS-123223 / 23.10 / Make Cluster Jobs payload private
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
Labels: jira

#11731 NAS-123211 / 23.10 / fix ipmi.lan.query crash on f-series
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: backport-22.12.4

#11734 NAS-123229 / 23.10 / Safely retrieve cpu temp stats
  src/middlewared/middlewared/plugins/reporting/cpu_temperatures.py
Labels: jira

#11733 NAS-123227 / 23.10 / use EINVAL for default errno for ValidationError
  src/middlewared/middlewared/service_exception.py
Labels: jira

#11736 NAS-123238 / 23.10 / add release_notes_url to update.check_available
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/update_/trains.py
Labels: jira

#11739 NAS-123240 / 23.10 / add final url for release notes
  src/middlewared/middlewared/plugins/system/product.py
Labels: jira

#11738 NAS-123239 / 23.10 / Add cluster.management.summary endpoint for TC
  cluster-tests/init_gluster.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira

#11741 NAS-123247 / 23.10 / account for new NR license model for f-series
  src/middlewared/middlewared/alert/source/license_status.py
Labels: jira

#11740 NAS-123246 / 23.10 / fix TypeError crash in failover.mismatch_disks
  src/middlewared/middlewared/plugins/failover.py
Labels: jira

#11746 NAS-123255 / 23.10 / Revert "Do not send events for transient jobs"
  src/middlewared/middlewared/job.py
Labels: backport-22.12.4

#11745 NAS-123264 / 23.10 / Allow auth tokens for cluster management
  cluster-tests/init_gluster.py
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira

#11753 NAS-123277 / 23.10 / Add error handling for CTDB nodes file mismatch
  src/middlewared/middlewared/plugins/cluster_linux/management.py
Labels: jira

#11752 NAS-123276 / 23.10 / Ignore ImportError for wbclient in our schema
  src/middlewared/middlewared/schema/string_schema.py
Labels: jira

#11758 NAS-123327 / 24.04 / fix ValueError crash in ipmi.sensors.query_impl
  src/middlewared/middlewared/plugins/ipmi_/sensors.py
Labels: jira, backport-23.10

#11760 NAS-123330 / 24.04 / fix crash in disk.temperature_agg
  src/middlewared/middlewared/plugins/disk_/temperature.py
Labels: jira, backport-23.10

#11761 NAS-123331 / 24.04 / optimize RealtimeEventSource
  src/middlewared/middlewared/plugins/reporting/events.py
Labels: jira, backport-23.10
