Repository truenas/middleware, pull requests merged in 2023-12, with the labels that each got.

#12612 NAS-125485 / 24.04 / Fix overly-strict netbios name regex
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema/string_schema.py
Labels: jira

#12613 NAS-125388 / 24.04 / Disable rpc.mountd logging with mountd_log NFS config setting
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-23.10.2

#12617 NAS-125491 / 24.04 / Allow `force` to bypass check for ctdb root dir
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12628 NAS-125506 / 24.04 / Fix the NFS syslog filter config
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira

#12631 NAS-125478 / 23.10.2 / DO not wait 24 hours to run `LicenseStatus` alert after applying new … (by themylogin)
  src/middlewared/middlewared/plugins/failover_/configure.py
  src/middlewared/middlewared/plugins/system/product.py
Labels: backport-23.10.1

#12627 NAS-125533 / 24.04 / Relax authorization requirements
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/system/info.py
  tests/api2/test_auth_me.py
Labels: jira

#12633 NAS-125540 / 24.04 / Add flag indicating whether role is builtin
  src/middlewared/middlewared/plugins/account_/privilege_roles.py
  src/middlewared/middlewared/role.py
Labels: jira

#12634 NAS-125546 / 24.04 / Make the bandwidth test more resilient.
  tests/api2/test_200_ftp.py
Labels: jira, backport-23.10.2

#12637 NAS-125550 / 24.04 / fix regression in boot.py:setup()
  src/middlewared/middlewared/plugins/boot.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12641 NAS-125557 / 24.04 / Fix ACL flag integration test in apps
  tests/api2/test_chart_release_acl_apply.py
Labels: jira

#12642 NAS-125558 / 24.04 / dont exc_info=True in usage_/firstboot.py
  src/middlewared/middlewared/plugins/usage_/firstboot.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12643 NAS-125559 / 24.04 / stop more netdata connection log spam
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12650 NAS-125566 / 24.04 / Fix LDAP middleware authentication tests
  src/middlewared/middlewared/plugins/idmap.py
  tests/api2/test_275_ldap.py
Labels: jira, backport-23.10.2

#12657 NAS-125581 / 24.04 / prevent more log spam
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
Labels: backport-23.10.1, backport-23.10.2

#12656 NAS-125579 / 24.04 / Make sure we gracefully handle certificate rotation for k3s
  src/middlewared/middlewared/plugins/kubernetes_linux/k8s/client.py
Labels: jira

#12645 NAS-125562 / 24.04 / Fix more log spam (network activity feature)
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/truecommand/connection.py
  src/middlewared/middlewared/plugins/vmware_/snapshot_delete.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12653 NAS-125577 / 24.04 / allow READONLY role to get NFS client status
  src/middlewared/middlewared/plugins/nfs_/status.py
Labels: jira

#12662 NAS-125584 / 24.04 / Add roles for interacting with auth sessions
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/role.py
Labels: jira

#12663 NAS-125586 / 24.04 / Allow authenticated users nenew own 2fa secret
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/account_/privilege_utils.py
  src/middlewared/middlewared/service/core_service.py
  src/middlewared/middlewared/utils/privilege.py
  tests/api2/test_twofactor_auth.py
Labels: jira

#12669 NAS-125598 / 24.04 / Fix typo in credential checking method
  src/middlewared/middlewared/utils/privilege.py
Labels: jira

#12654 NAS-125578 / 24.04 / Add more roles configuration for pool and dataset
  src/middlewared/middlewared/plugins/pool_/dataset_attachments.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
  src/middlewared/middlewared/plugins/pool_/dataset_mountpoint.py
  src/middlewared/middlewared/plugins/pool_/dataset_processes.py
  src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py
  src/middlewared/middlewared/plugins/pool_/dataset_recordsize.py
  src/middlewared/middlewared/plugins/pool_/info.py
  src/middlewared/middlewared/plugins/pool_/snapshot_count.py
  src/middlewared/middlewared/plugins/pool_/unlock.py
Labels: jira

#12675 NAS-125620 / 24.04 / Expand nfs.config to show whether keytab has NFS spn
  src/middlewared/middlewared/plugins/nfs.py
Labels: jira

#12671 NAS-125614 / 24.04 / More clustering teardown improvements
  cluster-tests/tests/cleanup/test_cluster_cleanup.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_root_dir.py
  src/middlewared/middlewared/plugins/service_/services/glusterd.py
Labels: jira, backport-23.10.2

#12674 NAS-125619 / 24.04 / Allow users with REPORTING_READ to access disk info
  src/middlewared/middlewared/plugins/disk_/availability.py
  src/middlewared/middlewared/plugins/disk_/temperature.py
  src/middlewared/middlewared/plugins/smart.py
Labels: jira

#12683 NAS-125628 / 24.04 / Allow unauthorized access to role information
  src/middlewared/middlewared/plugins/account_/privilege_roles.py
Labels: jira

#12680 NAS-125627 / 24.04 / Do not try to restart winbindd when sysdataset missing
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#12690 NAS-125638 / 24.04 / Add DATASET_READ to READONLY role
  src/middlewared/middlewared/role.py
Labels: jira

#12692 NAS-124988 / 24.04 / fix faulty HA logic
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-23.10.1, backport-23.10.2

#12700 NAS-125673 / 24.04 / Configure roles for service plugin
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/utils.py
  src/middlewared/middlewared/pytest/unit/utils/test_privilege.py
  src/middlewared/middlewared/role.py
  tests/api2/test_nfs_share_crud_roles.py
  tests/api2/test_smb_share_crud_roles.py
Labels: jira

#12701 NAS-125677 / 24.04 / Add statx attributes to middleware statx
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/stat_x.py
Labels: jira

#12707 NAS-125685 / 24.04 / Prevent locking out root / admin user
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/utils/privilege.py
Labels: jira, backport-23.10.2

#12710 NAS-125688 / 24.04 / Allow READONLY role to read update info
  src/middlewared/middlewared/plugins/update.py
Labels: jira

#12687 NAS-125633 / 24.04 / Add AUDIT_READ role
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/role.py
Labels: jira

#12715 NAS-125700 / 24.04 / Enhance testing of NFS 'allow_nonroot' setting
  tests/api2/test_300_nfs.py
  tests/protocols/nfs_proto.py
Labels: jira

#12644 NAS-125561 / 24.04 / REST API audit
  docs/source/middleware/audit.rst
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/audit/schema/middleware.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/schema/processor.py
  src/middlewared/middlewared/service/crud_service.py
  src/middlewared/middlewared/service/sharing_service.py
  src/middlewared/middlewared/test/integration/utils/audit.py
  src/middlewared/middlewared/utils/type.py
  tests/api2/test_account.py
  tests/api2/test_audit_rest.py
  tests/api2/test_audit_websocket.py
  tests/api2/test_rest_api_upload.py
  tests/conftest.py
Labels: jira

#12717 NAS-125713 / 23.10.2 / Do not store and use hardware addresses for non-physical interfaces
  src/middlewared/middlewared/alembic/versions/23.10/2023-10-24_14-28_network_interface_link_address.py
  src/middlewared/middlewared/plugins/interface/link_address.py
Labels: backport-23.10.1, backport-24.04

#12718 NAS-125718 / 24.04 / Allow READONLY role to check whether IPMI loaded
  src/middlewared/middlewared/plugins/ipmi.py
Labels: jira

#12721 NAS-125721 / 24.04 / Make network interface names unique
  src/middlewared/middlewared/alembic/versions/24.04/2023-12-14_19-18_network_interface_name_unique.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#12716 NAS-125710 / 24.04 / Add account_attributes to auth.me output
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_auth_me.py
Labels: jira

#12703 NAS-125600 / 24.04 / Mark chart release logs test as flaky
  tests/api2/test_027_kubernetes_logs.py
Labels: backport-23.10.2

#12729 NAS-125730 / 24.04 / Small optimization to check for 2fa required
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#12736 NAS-125738 / 24.04 / Fix typo in migration
  src/middlewared/middlewared/alembic/versions/23.10/2023-10-24_14-28_network_interface_link_address.py
Labels: jira, backport-23.10.1, backport-23.10.2

#12666 NAS-125593 / 24.04 / Make SHARING_MANAGER role a superset of READONLY
  src/middlewared/middlewared/role.py
Labels: jira

#12741 NAS-125734 / 24.04 / add another data point to collections metrics
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-23.10.2

#12732 NAS-125731 / 24.04 / Fix edge case while retrieving netdata dimensions
  src/middlewared/middlewared/plugins/reporting/realtime_reporting/utils.py
Labels: jira, backport-23.10.2

#12744 NAS-125770 / 24.04 / set SHARING_SMB role prefix for SMB service
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#12689 NAS-125642 / 24.04 / Enable discard for VM disks
  src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py
Labels: jira

#12688 NAS-125641 / 24.04 / Lift limitations of OVMF option collection
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira

#12743 NAS-125769 / 24.04 / Allow limited user to toggle enabled for services
  src/middlewared/middlewared/plugins/service.py
Labels: jira

#12752 NAS-125778 / 24.04 / Integration test for `pool.expand`
  tests/api2/test_pool_expand.py
Labels: jira, backport-23.10.2

#12755 NAS-125362 / 24.04 / Fix edge case for getting CPU temperature on AMD machines
  src/middlewared/middlewared/utils/cpu.py
Labels: backport-23.10.2

#12758 NAS-125781 / 24.04 / Add unit test for edge case related to AMD CPU temperature
  src/middlewared/middlewared/pytest/unit/utils/test_cpu_util_amd.py
Labels: jira, backport-23.10.2

#12759 NAS-125782 / 24.04 / Reduce log spamming from reporting plugin
  src/middlewared/middlewared/plugins/reporting/netdata/client.py
Labels: jira, backport-23.10.2

#12762 NAS-125786 / 24.04 / Clean before directive usage in ix-netif
  debian/debian/ix-netif.service
Labels: jira

#12765 NAS-125788 / 24.04 / Add roles for manipulating local accounts
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/role.py
Labels: jira

#12766 NAS-125790 / 24.04 / Assign roles for dataset_info.py
  src/middlewared/middlewared/plugins/pool_/dataset_info.py
Labels: jira

#12764 NAS-125787 / 24.04 / Add SUPPORT_READ and SUPPORT_WRITE roles
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/truenas.py
  src/middlewared/middlewared/role.py
Labels: jira

#12767 NAS-125792 / 24.04 / Expand roles configuration for interfaces
  src/middlewared/middlewared/plugins/interface/capabilities.py
  src/middlewared/middlewared/plugins/interface/lag_protocols.py
Labels: jira

#12768 NAS-125793 / 24.04 / Expand IPMI info available to READONLY role
  src/middlewared/middlewared/plugins/ipmi_/chassis.py
  src/middlewared/middlewared/plugins/ipmi_/lan.py
  src/middlewared/middlewared/plugins/ipmi_/mc.py
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: jira

#12773 NAS-125799 / 24.04 / Allow readonly admins access to read boot pool info
  src/middlewared/middlewared/plugins/boot.py
Labels: jira

#12772 NAS-125798 / 24.04 / Add KMIP roles configuration
  src/middlewared/middlewared/plugins/kmip/sync.py
  src/middlewared/middlewared/plugins/kmip/update.py
  src/middlewared/middlewared/role.py
Labels: jira

#12774 NAS-125801 / 24.04 / Allow READONLY role to access various public endpoints
  src/middlewared/middlewared/plugins/acme_protocol_/schema.py
  src/middlewared/middlewared/plugins/device.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/status.py
  src/middlewared/middlewared/plugins/vmware.py
Labels: jira

#12769 NAS-125794 / 24.04 / Add roles for reporting exporters
  src/middlewared/middlewared/plugins/reporting/export.py
  src/middlewared/middlewared/role.py
Labels: jira

#12757 NAS-125783 / 24.04 / Add query-filters for timestamps
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira

#12733 NAS-125732 / 24.04 / Handle and log exception while normalizing cpu temp
  src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
Labels: jira, backport-23.10.2

#12734 NAS-125632 / 24.04 / Update graphite exporter defaults
  src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py
  src/middlewared/middlewared/alembic/versions/24.04/2023-09-07_19-50_add_exporting_table_for_reporting.py
  src/middlewared/middlewared/plugins/reporting/exporters/graphite.py
Labels: backport-23.10.2

#12731 NAS-124823 / 24.04 / Make sure we mount all datasets we can when doing recursive mount
  src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
  tests/api2/test_dataset_mount.py
Labels: backport-23.10.2

#12781 NAS-125835 / 24.04 / Add tests for webui_access privilege flag
  src/middlewared/middlewared/plugins/account_/privilege.py
  tests/api2/test_auth_me.py
Labels: jira

#12783 NAS-125836 / 24.04 / Remove udp from NFS CI test.
  tests/api2/test_300_nfs.py
Labels: jira

#12782 NAS-125771 / 24.04 / add special handling for fseries
  src/freenas/usr/lib/systemd/network/10-enp135_141_s0f0np0.link
  src/freenas/usr/lib/systemd/network/10-enp135_141_s0f1np1.link
Labels: backport-23.10.2

#12785 NAS-125838 / 24.04 / Expand libpam_authenticate response
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  tests/api2/test_account_privilege_authentication.py
Labels: jira

#12664 NAS-125569 Don't enclose ipv6 addresses in square brackets in scst.conf
  src/middlewared/middlewared/etc_files/scst.conf.mako
Labels: backport-23.10.2

#12787 NAS-125857 / 24.04 / Fix typos in `enclosure2.py`
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
Labels: jira, backport-23.10.2

#12790 NAS-125822 / 24.04 / Show only most recent IPMI event alert
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: backport-23.10.2

#12789 NAS-125842 / 23.10.2 / Delete OneDrive cloud sync tasks
  src/middlewared/middlewared/alembic/versions/23.10/2023-12-22_11-29_delete_onedrive_cloud_sync_tasks.py
Labels: backport-24.04

#12794 NAS-125866 / 24.04 / add READONLY to pool.validate_name
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: jira

#12770 NAS-125795 / 24.04 / Add FAILOVER roles
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/role.py
  tests/api2/test_014_failover_related.py
Labels: jira

#12795 NAS-125862 / 24.04 / Fix swapping interface names when they both are part of LAGGs
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
Labels: backport-23.10.2

#12802 NAS-125919 / 24.04 / changes to sys_info for UI team
  src/middlewared/middlewared/plugins/webui/main_dashboard.py
Labels: jira

#12798 NAS-125839 / 24.04 / Fix `privilege.local_administrators` being empty if `privilege.always…
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/builtin_administrator.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  src/middlewared/middlewared/test/integration/assets/account.py
  tests/api2/test_account_privilege.py
  tests/api2/test_user_admin.py
Labels: backport-23.10.2

#12804 NAS-125829 / 24.04 / Do not upgrade boot pool automatically as users can't rollback to Bluefin then
  src/middlewared/middlewared/plugins/boot.py
Labels: backport-23.10.2

#12799 NAS-125823 / 24.04 / Remove deprecated stats plugin
  src/middlewared/middlewared/plugins/stats.py
  tests/api2/test_460_stats.py
Labels: backport-23.10.2

#12806 NAS-125841 / 24.04 / Gracefully handle case for aggregating disk temperatures when no temperatures have been retrieved
  src/middlewared/middlewared/plugins/disk_/temperature.py
Labels: backport-23.10.2

#12775 NAS-125548 / 24.04 / Retry starting truecommand after a small delay if TC container is down
  src/middlewared/middlewared/plugins/truecommand/portal.py
Labels: backport-23.10.2

#12809 NAS-125820 / 24.04 / Fix config data being exposed for chart releases
  src/middlewared/middlewared/alert/source/applications.py
  src/middlewared/middlewared/plugins/chart_releases_linux/upgrade.py
Labels: backport-23.10.2

#12813 NAS-125932 / 23.10.2 / Fix non-physical interface link address getting into database when it is updated
  src/middlewared/middlewared/alembic/versions/23.10/2023-12-28_10-16_delete_link_addresses_for_non_physical_interfaces.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-24.04

#12816 NAS-125930 / 24.04 / Fix validation for permitted keys in AD plugin
  src/middlewared/middlewared/plugins/activedirectory.py
  tests/api2/test_030_activedirectory.py
Labels: backport-23.10.2

#12819 NAS-125945 / 24.04 / Prevent disabling rootfs protection on SCALE_ENTERPRISE
  src/freenas/usr/bin/install-dev-tools
  src/freenas/usr/local/libexec/disable-rootfs-protection
Labels: jira

#12820 NAS-125966 / 24.04 / Fix regressions caused by cluster removal
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_001_ssh.py
Labels: jira

#12821 NAS-125967 / 24.04 / Fix permissions on disable-rootfs-protection script
  src/freenas/usr/local/libexec/disable-rootfs-protection
Labels: jira
