Repository truenas/middleware, pull requests merged in 2023-05, with the labels that each got.

#11191 NAS-121752 / 23.10 / Mark S3 service as deprecated
  src/middlewared/middlewared/plugins/service_/services/s3.py
Labels: backport-22.12.3

#11190 NAS-121764 / 22.12.3 / add ipmi.sel plugin
  src/middlewared/middlewared/plugins/ipmi.py
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: jira, backport-23.10

#11200 NAS-121480 / 23.10 / Fix race condition when trying to change mappings of disk identifiers…
  src/middlewared/middlewared/plugins/disk_/sync.py
  src/middlewared/middlewared/plugins/disk_/zfs_guid.py
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12.3

#11201 NAS-121781 / 23.10 / add -v and --no-header-output to ipmi.sel.elist
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: jira, backport-22.12.3

#11195 NAS-121777 / 23.10 / Simplify IPMI sel alerts
  src/middlewared/middlewared/alert/source/ipmi_sel.py
  src/middlewared/middlewared/pytest/unit/alert/source/test_ipmi_sel.py
Labels: jira, backport-22.12.3

#11207 NAS-121787 / 23.10 / Fix middleware reinstalls
  src/freenas/usr/bin/install-dev-tools
Labels: jira

#11211 NAS-121789 / 23.10 / fix hosts file when clustered
  src/middlewared/middlewared/etc_files/hosts.mako
Labels: jira, backport-22.12.3

#11208 NAS-121788 / 23.10 / Make DNS timeouts for AD checks configurable
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
Labels: jira, backport-22.12.3

#11215 NAS-121794 / 23.10 / Behavior of python enum.Flags has changed between 3.9 and 3.11.
  src/middlewared/middlewared/plugins/nfs_/debug.py
Labels: jira

#11196 NAS-121753 / 23.10 / Run truenas_install precheck
  src/middlewared/middlewared/plugins/update_/install.py
Labels: backport-22.12.3

#11222 NAS-121806 / 23.10 / Install relevant dependencies before running unit tests in CI
  .github/workflows/unittests.yml
Labels: WIP, jira

#11227 NAS-121812 / 23.10 / remove osc module from usage.py plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11229 NAS-121813 / 23.10 / simplify and speed up gather_network() in usage.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11232 NAS-121718 / 23.10 / add zpool list -o size output to usage.py plugin
  src/middlewared/middlewared/plugins/usage.py
Labels: backport-22.12.3

#11234 NAS-121817 / 23.10 / add top-level key "total_raw_capacity" to usage.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11236 NAS-121821 / 23.10 / further improvements to usage.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11242 NAS-121826 / 23.10 / add total_capacity to context in usage.py
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11240 NAS-121824 / 23.10 / Fix cut-n-paste issue.
  tests/protocols/nfs_proto.py
Labels: jira

#11244 NAS-121828 / 23.10 / Improve usage.py some more
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11248 NAS-121837 / 23.10 / Cleanup Flake8 errors in tests/protocols/nfs_proto.py
  tests/protocols/nfs_proto.py
Labels: jira

#11249 NAS-121846 / 23.10 / fix ipmi-sel log spam
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: jira, backport-22.12.3

#11250 NAS-121851 / 23.10 / fix cobia upgrades (again)
  src/freenas/etc/default/kexec.d/truenas
Labels: jira

#11252 NAS-121860 / 13.0 / Fix AttributeError crash
  src/middlewared/middlewared/plugins/pool.py
Labels: jira

#11254 NAS-121849 / 23.10 / Fix ix-appilcation dataset split bug
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
Labels: backport-22.12.3

#11253 NAS-121861 / 23.10 / remove python3-apt (not used)
  src/middlewared/debian/control
Labels: jira

#11260 NAS-121881 / 13.0 / Fix flapping enclosure alerts
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/enclosure_status.py
Labels: jira, backport-22.12.3

#11269 NAS-121886 / 23.10 / Remove encryption related invalid tests
  tests/api2/test_341_pool_dataset_encryption.py
Labels: jira, backport-22.12.3

#11270 NAS-121887 / 23.10 / Fix unencrypted parent edge case
  src/middlewared/middlewared/plugins/pool_/dataset.py
Labels: jira

#11273 NAS-121895 / 23.10 / remove unused dependency
  src/middlewared/debian/control
Labels: jira, backport-22.12.3

#11220 NAS-121696 / 23.10 / Properly cover the case where parent of VM disk device is encrypted
  src/middlewared/middlewared/plugins/pool_/unlock.py
Labels: backport-22.12.3

#11277 NAS-121897 / 23.10 / Fix encryption tests again
  tests/api2/test_341_pool_dataset_encryption.py
Labels: jira, backport-22.12.3

#11276 NAS-121896 / 22.12.3 / Replication encryption inherit
  src/middlewared/middlewared/alembic/versions/22.12/2023-05-10_13-44_repl_encryption_inherit.py
  src/middlewared/middlewared/plugins/replication.py
  src/middlewared/middlewared/plugins/zettarepl.py
Labels: jira, backported, backport-23.10

#11284 NAS-121910 / 13.0 / fix regression and edge-case crash in disk.sync_all
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: jira

#11283 NAS-121909 / 13.0 / fix MINI 3.0 X version 1.0 enclosure mapping
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
Labels: jira

#11285 NAS-121912 / 13.0 / Expect Enter an option instead of https:// in boot.exp
  tests/boot.exp
Labels: jira

#11288 NAS-121917 / 23.10 / Do not create swap partition when swap detected on boot drive
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
  src/middlewared/middlewared/plugins/pool_/format_disks.py
Labels: jira, backport-22.12.3

#11290 NAS-121918 / 23.10 / max_tasks_per_child for process pool workers
  src/middlewared/middlewared/main.py
Labels: jira

#11293 NAS-121924 / 23.10 / fix un-awaited coroutine in account.py
  src/middlewared/middlewared/plugins/account.py
Labels: jira, backport-22.12.3

#11295 NAS-121933 / 13.0 / this alert isn't needed anymore
  src/freenas/usr/local/lib/middlewared_truenas/alert/source/nvdimm.py
Labels: jira

#11299 NAS-121945 / 23.10 / Add validation to force encryption with LDAP SMB
  src/middlewared/middlewared/plugins/ldap.py
Labels: pending QA, jira, backport-22.12.3

#11302 NAS-121956 / 23.10 / Fix NFS proto test
  tests/protocols/nfs_proto.py
Labels: jira

#11307 NAS-121741 / 23.10 / add execute bit back to dpkg in dev tools script
  src/freenas/usr/bin/install-dev-tools
Labels: backport-22.12.3

#11210 NAS-120096 / 23.10 / Fix normalization of datasets
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: backport-22.12.3

#11314 NAS-121743 / 23.10 / NAS-121743
  tests/api2/test_261_iscsi_cmd.py
  tests/protocols/__init__.py
  tests/protocols/iscsi_proto.py
Labels: backport-23.10, backport-22.12.3

#11289 NAS-121786 / 23.10 / Get all unsupported md mirrors
  src/middlewared/middlewared/plugins/disk_/swap_mirror.py
Labels: backport-22.12.3

#11311 NAS-121976 / 23.10 / add ipmi.sensors plugin
  src/middlewared/middlewared/alert/source/sensors.py
  src/middlewared/middlewared/plugins/failover_/sensor.py
  src/middlewared/middlewared/plugins/ipmi_/sensors.py
Labels: jira, backport-22.12.3

#11313 NAS-121259 / 23.10 / add F1 product detection
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
  src/middlewared/middlewared/plugins/failover_/internal_interface.py
  src/middlewared/middlewared/plugins/truenas.py
Labels: backport-22.12.3

#11325 NAS-121993 / 13.0 / Improve IPMI password validation (#9251)
  src/middlewared/middlewared/plugins/ipmi.py
  src/middlewared/middlewared/schema.py
  src/middlewared/middlewared/validators.py
Labels: jira

#11326 NAS-122003 / 23.10 / protect against invalid high vlan IDs in IPMI
  src/middlewared/middlewared/plugins/ipmi.py
Labels: jira, backport-13.0, backport-22.12.3

#11324 NAS-121990 / 23.10 / remove redundant api calls
  src/middlewared/middlewared/etc_files/failover.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/network_/dns.py
  src/middlewared/middlewared/plugins/network_/route.py
Labels: jira

#11265 NAS-121881 / 22.12.3 / Fix flapping enclosure alerts (by themylogin)
  src/middlewared/middlewared/alert/source/enclosure_status.py
Labels: backport-23.10

#11331 NAS-122022 / 23.10 / Fix legacy mini bmc alert
  src/middlewared/middlewared/alert/legacy_mini_bmc.py
Labels: jira, backport-22.12.3

#11329 NAS-121816 / 23.10 / Also account for pylibzfs-initialed scrubs when checking last pool sc…
  src/middlewared/middlewared/plugins/pool_/scrub.py
Labels: backport-22.12.3

#11334 NAS-122023 / 23.10 / add ipmi.mc plugin
  src/middlewared/middlewared/plugins/ipmi_/mc.py
Labels: jira, backport-22.12.3

#11336 NAS-122025 / 23.10 / Fix API test failure for user creation
  src/middlewared/middlewared/plugins/account.py
Labels: jira, backport-22.12.3

#11341 NAS-122032 / 23.10 / Fix calling JobProgressBuffer from threads
  src/middlewared/middlewared/job.py
Labels: jira

#10994 NAS-121206 / 23.10 / Expand validation of user home directories
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: backport-22.12.3

#11348 NAS-121517 / 22.12.3 / Rename official catalog to "Truenas"
  src/middlewared/middlewared/alembic/versions/22.12/2023-05-18_08-00_official_catalog_rename.py
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: backport-23.10

#11347 NAS-122038 / 23.10 / Migrate existing installed apps to TrueNAS catalog
  src/middlewared/middlewared/plugins/kubernetes_linux/app_migrations/01_middleware_migrate_official_catalog.json
Labels: jira, backport-22.12.3

#11353 Fix NFS 'at boot' state
  debian/debian/postinst
Labels: jira

#11317 NAS-121981 / 23.10 / Add similarity score for retrieving similar apps
  src/middlewared/middlewared/plugins/catalogs_linux/apps.py
Labels: jira

#11357 NAS-122063 / 22.12.3 / Fix enclosure status alert
  src/middlewared/middlewared/alert/source/enclosure_status.py
Labels: jira, backport-23.10

#11350 NAS-122042 / 23.10 / Close SMB share in a few more cases
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_425_smb_protocol.py
Labels: jira, backport-22.12.3

#11344 NAS-122034 / 23.10 / Fix spacing in log message
  src/middlewared/middlewared/plugins/account_/privilege.py
Labels: jira

#11360 NAS-121907 / 23.10 / Remove immutable flag after mounting unlocked dataset too
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py
Labels: backport-22.12.3

#11362 NAS-122064 / 23.10 / use bmc-info --get-channel-info to fix ipmi.lan.query
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: jira

#11368 NAS-122083 / 22.12.3 / Fix enclosure alert
  src/middlewared/middlewared/alert/source/enclosure_status.py
Labels: jira, backport-23.10

#11372 NAS-122089 / 23.10 / Optimize and fix retrieval of SID info for AD user
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/cache.py
Labels: jira

#11373 NAS-122093 / 23.10 / Add schema validation for Windows SIDs
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/schema.py
Labels: jira, backport-22.12.3

#11377 NAS-122101 / 23.10 / remove dead collectd ALUA alert
  src/freenas/usr/local/libexec/collectd_alert.py
  src/middlewared/debian/control
  src/middlewared/middlewared/alert/source/collectd.py
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
Labels: jira

#11380 NAS-122106 / 22.12.3 / Allow iSCSI tests to support raw sense data
  tests/api2/test_261_iscsi_cmd.py
Labels: jira

#11375 NAS-122102 / 23.10 / Prefer sids privileges
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira, backport-22.12.3

#11383 NAS-122110 / 23.10 / skip cache lookup if directory services unhealthy
  src/middlewared/middlewared/plugins/account.py
Labels: pending QA, jira, backport-22.12.3

#11386 NAS-122127 / 23.10 / fix call_sync typo in async def
  src/middlewared/middlewared/plugins/network_/route.py
Labels: jira

#11387 NAS-122135 / 23.10 / fix usage reporting when it's restricted
  src/middlewared/middlewared/plugins/usage.py
Labels: jira, backport-22.12.3

#11389 NAS-122136 / 23.10 / remove "not installed" as a bad element status
  src/middlewared/middlewared/alert/source/enclosure_status.py
Labels: jira, backport-22.12.3

#11392 NAS-122139 / 23.10 / Respect empty attribute specified on schema
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
Labels: jira

#11393 NAS-122140 / 22.12.3 / improve verbiage for deprecated service alert
  src/middlewared/middlewared/alert/source/deprecated_service.py
Labels: jira, backport-23.10

#11378 NAS-122103 / 23.10 / Make domain admins middleware admins
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  src/middlewared/middlewared/plugins/cache.py
  tests/api2/test_030_activedirectory.py
Labels: WIP, jira

#11399 NAS-122156 / 23.10 / fix python-jwt usage
  src/middlewared/middlewared/plugins/gluster_linux/local_events.py
  src/middlewared/middlewared/webhooks/cluster_events.py
Labels: jira

#11400 NAS-122157 / 23.10 / Fix ipaddr
  src/middlewared/middlewared/pytest/unit/test_schema.py
  src/middlewared/middlewared/schema.py
Labels: jira

#11404 NAS-122176 / 23.10 / Fix KeyError in API tests
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#11405 NAS-122177 / 23.10 / Avoid tdb lookup during cluster start
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#11408 NAS-122212 / 23.10 / remove ipmi tests (they didn't do anything)
  tests/api2/test_250_ipmi.py
Labels: jira

#11403 NAS-122173 / 23.10 / Remove DynDNS, OpenVPN, rsyncd, WebDAV
  debian/debian/control
  debian/debian/postinst
  src/freenas/debian/control
  src/freenas/debian/preinst
  src/freenas/etc/default/inadyn
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
  src/middlewared/debian/control
  src/middlewared/middlewared/alembic/versions/23.10/2023-05-26_12-42_remove_legacy_services.py
  src/middlewared/middlewared/alert/source/certificates.py
  src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf.mako
  src/middlewared/middlewared/etc_files/local/apache24/httpd.conf.mako
  src/middlewared/middlewared/etc_files/local/apache24/webdav_config.py
  src/middlewared/middlewared/etc_files/local/inadyn.conf.mako
  src/middlewared/middlewared/etc_files/local/openvpn/client/openvpn_client.conf.mako
  src/middlewared/middlewared/etc_files/local/openvpn/server/openvpn_server.conf.mako
  src/middlewared/middlewared/etc_files/local/openvpn/server/perms.py
  src/middlewared/middlewared/etc_files/local/rsyncd.conf.mako
  src/middlewared/middlewared/plugins/crypto_/ca_profiles.py
  src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
  src/middlewared/middlewared/plugins/dyndns.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
  src/middlewared/middlewared/plugins/pool_/unlock.py
  src/middlewared/middlewared/plugins/pwenc.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/plugins/rsync_/__init__.py
  src/middlewared/middlewared/plugins/rsync_/port_attachments.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/dynamicdns.py
  src/middlewared/middlewared/plugins/service_/services/openvpn_client.py
  src/middlewared/middlewared/plugins/service_/services/openvpn_server.py
  src/middlewared/middlewared/plugins/service_/services/rsync.py
  src/middlewared/middlewared/plugins/service_/services/webdav.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/plugins/vpn.py
  src/middlewared/middlewared/plugins/vpn_/__init__.py
  src/middlewared/middlewared/plugins/vpn_/attachments.py
  src/middlewared/middlewared/plugins/vpn_/cert_attachments.py
  src/middlewared/middlewared/plugins/webdav.py
  src/middlewared/middlewared/plugins/webdav_/__init__.py
  src/middlewared/middlewared/plugins/webdav_/attachments.py
  src/middlewared/middlewared/plugins/webdav_/cert_attachments.py
  src/middlewared/middlewared/test/integration/assets/crypto.py
  tests/api2/test_180_dyndns.py
  tests/api2/test_380_rsync.py
  tests/api2/test_560_webdav.py
  tests/api2/test_client_configuration_generation.py
  tests/api2/test_port_delegates.py
Labels: jira

#11409 NAS-121891 / 22.12.4 / Consume update warnings and allow resuming the update after warning (by themylogin)
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/plugins/update_/install.py
  src/middlewared/middlewared/plugins/update_/install_linux.py
  src/middlewared/middlewared/plugins/update_/upload_location_linux.py
Labels: backport-22.12.3

#11412 NAS-122221 / 23.10 / Remove rsyncd stats from usage service
  src/middlewared/middlewared/plugins/usage.py
Labels: jira

#11415 NAS-122228 / 23.10 / add docstring to wait_to_hang_and_dump_core script
  src/middlewared/middlewared/scripts/wait_to_hang_and_dump_core.py
Labels: jira, backport-22.12.4

#11414 NAS-122218 / 23.10 / remove unnecessary core dump alert api tests
  tests/api2/test_050_alert.py
Labels: backport-22.12.4, backport-22.12.3
