Repository truenas/middleware, pull requests merged in 2023-03, with the labels that each got.

#10774 NAS-120569 / 23.10 / Cluster - change IPs under fcntl lock
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_ips.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_shared_volume.py
Labels: jira, backport-22.12.2

#10775 NAS-120568 / 23.10 / Improve error message for failed SRV lookup
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
Labels: jira, backport-22.12.2

#10782 NAS-119748 / 23.10 / add all nvme flash r30 to enclosure mgmt
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
Labels: backport-22.12.2

#10789 NAS-120596 / 23.10 / Fix filter for kerberos renewal job
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira, backport-22.12.2

#10788 NAS-120590 / 23.10 / call device.settle_udev_events in failover plugin
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12.2

#10793 NAS-120593 / 23.10 / add support for enclosure.sync_disk on R30
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/nvme.py
Labels: backport-22.12.2

#10787 NAS-120589 / 23.10 / Reflect GPU isolation changes on the system
  src/middlewared/middlewared/plugins/system_advanced/config.py
Labels: backport-22.12.2

#10564 NAS-120040 / 23.10 / Allow RO access to clustered config if DB healthy
  cluster-tests/tests/directoryservices/test_001_activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/ctdb.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  src/middlewared/middlewared/service.py
Labels: jira, backport-22.12.2

#10805 NAS-120643 / 23.10 / Add local smbtorture tests
  tests/api2/test_420_smb.py
Labels: jira, backport-13.0, backport-22.12.2

#10807 NAS-120644 / 23.10 / Compare casefolded strings for hostnames
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
Labels: jira, backport-22.12.2

#10801 NAS-120304 / 23.10 / Increase private docker images password length to 4096
  src/middlewared/middlewared/plugins/container_runtime_interface/images.py
Labels: backport-22.12.2

#10800 NAS-120623 / 23.10 / Only have one sudoers file entry as only the last one is taken into a…
  src/middlewared/middlewared/etc_files/local/sudoers.mako
Labels: jira, backport-22.12.2

#10811 NAS-120650 / 23.10 / Use standardized check for whether we're clustered
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_job.py
Labels: jira, backport-22.12.2

#10808 NAS-120647 / 23.10 / Add some casefolded filters
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira, backport-22.12.2

#10799 NAS-120607 / 23.10 / add nvdimm and bios alerts for m-series on SCALE
  src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
  src/middlewared/middlewared/alert/source/nvdimm.py
  src/middlewared/middlewared/plugins/hardware/__init__.py
  src/middlewared/middlewared/plugins/hardware/m_series_bios.py
  src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Labels: backport-22.12.2

#10818 NAS-120303 / 23.10 / fix pblocksize toggling
  src/middlewared/middlewared/etc_files/scst.conf.mako
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-22.12.2

#10821 NAS-120677 / 13.0 / Properly validate hostnames
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#10822 NAS-120679 / 23.10 / Fix sudo test
  tests/api2/test_011_user.py
Labels: backport-22.12.2

#10819 NAS-120665 / 23.10 / Fix user creation permissions on homedir
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: backport-22.12.2

#10829 NAS-120687 / 23.10 / Fix test asset for FTP group
  src/middlewared/middlewared/test/integration/assets/ftp.py
Labels: jira, backport-22.12.2

#10832 NAS-120672 / 23.10 / Do not explicitly request multipath support for NVMe.
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-22.12.2

#10827 NAS-120302 / 22.12.2 / Allow users to add TPM to VMs
  src/middlewared/middlewared/alembic/versions/22.12/2023-03-09_18-03_tpm.py
  src/middlewared/middlewared/plugins/vm/profiles.py
  src/middlewared/middlewared/plugins/vm/supervisor/domain_xml.py
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: backport-23.10

#10834 NAS-120685 / 23.10 / Fix system reboot alerts for SCALE HA
  src/middlewared/middlewared/alert/source/scheduled_reboot.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/scheduled_reboot_alert.py
  src/middlewared/middlewared/plugins/unscheduled_reboot_alert.py
Labels: skip jira status, backport-22.12.2

#10783 NAS-119809 / 23.10 / ZFS tunables
  src/freenas/usr/local/bin/truenas-initrd.py
  src/middlewared/middlewared/plugins/tunables.py
  src/middlewared/middlewared/utils/db.py
  tests/api2/test_tunables.py
Labels: skip jira status

#10837 NAS-120610 / 23.10 / Fix AD home shares in SCALE
  src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry_share.py
  tests/api2/test_030_activedirectory.py
Labels: backport-22.12.2

#10839 NAS-119515 / 23.10 / fix hot-spare not auto-detaching after replace
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
Labels: backport-13.0, backport-22.12.2

#10845 NAS-120571 / 23.10 / Ensure that share ACL is preserved
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_430_smb_sharesec.py
Labels: backport-22.12.2

#10840 NAS-120608 / 23.10 / fix alert being generated on user caused failover
  src/middlewared/middlewared/alert/source/failover_sync.py
  src/middlewared/middlewared/plugins/failover_/datastore.py
Labels: backport-22.12.2

#10848 NAS-119244 / 23.10 / add storcli /c<x> show all in debug
  src/freenas/usr/local/libexec/freenas-debug/hardware/hardware.sh
Labels: backport-22.12.2

#10851 NAS-120978 / 23.10 / Fix all supported controllers not being added to available controllers
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/utils.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10854 NAS-120999 / 23.10 / Remove legacy LDAP SMB support from clustered TrueNAS
  cluster-tests/tests/directoryservices/test_002_ldap.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-22.12.3

#10856 NAS-121009 / 23.10 / prevent log spam in failover.mismatch_disks
  src/middlewared/middlewared/plugins/failover.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10859 NAS-121016 / 23.10 / Add pool to option_list
  tests/runtest.py
Labels: jira

#10860 NAS-120967 / 23.10 / Adapt `assert_shell_works` to zsh changes
  src/middlewared/middlewared/test/integration/utils/shell.py
Labels: backport-22.12.3

#10864 NAS-121023 / 23.10 / Improve user homedir validation errors
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_011_user.py
Labels: backport-22.12.2, backport-22.12.3

#10863 NAS-121028 / 23.10 / add create_and_prepare_ws()
  src/middlewared/middlewared/main.py
Labels: jira, backport-22.12.3

#10865 NAS-121034 / 23.10 / generate a udev event after disk has been wiped
  src/middlewared/middlewared/plugins/disk_/wipe.py
  tests/api2/test_disk_wipe.py
Labels: backport-22.12.2, backport-22.12.3

#10872 prevent more unnecessary log spam in disk.sync_all
  src/middlewared/middlewared/plugins/disk_/sync.py
Labels: backport-22.12.2, backport-22.12.3

#10880 NAS-121064 / 23.10 / fix x controller position detection logic
  src/middlewared/middlewared/plugins/failover_/detect_enclosure.py
Labels: backport-22.12.3

#10877 NAS-121059 / 23.10 / add LOC_FAILOVER_ONGOING to HA disabled reasons
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira, backport-22.12.3

#10885 NAS-121067 / 23.10 / fix time of check, time of use race fenced plugin
  src/middlewared/middlewared/plugins/failover_/fenced.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10888 NAS-121072 / 23.10 / Fix bug to output hactl in debug file
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: jira, backport-22.12.2, backport-22.12.3

#10891 NAS-121073 / 23.10 / Add zectl to debug file
  src/freenas/usr/local/libexec/freenas-debug/system/system.sh
Labels: backport-22.12.2, backport-22.12.3

#10894 NAS-121080 / 23.10 / Remove local.compression test
  tests/api2/test_420_smb.py
Labels: jira

#10895 NAS-121086 / 23.10 / Fix libvirt socket closed edge case when querying VMs
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10899 NAS-121074 / 23.10 / fix failover.vip.get_states
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: backport-22.12.2, backport-22.12.3

#10906 NAS-121098 / 22.12.3 / Register chart releases certificate delegate
  src/middlewared/middlewared/plugins/chart_releases_linux/cert_attachments.py
Labels: jira, backport-22.12.2

#10908 NAS-121055 / 23.10 / add ipmi.chassis plugin
  src/middlewared/middlewared/plugins/ipmi.py
  src/middlewared/middlewared/plugins/ipmi_/chassis.py
Labels: skip jira status, backport-22.12.2, backport-22.12.3

#10878 NAS-121058 / 23.10 / Only register HA VIPs during AD dynamic DNS updates
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-22.12.2, backport-22.12.3

#10915 NAS-120955 / 23.10 / improve core file alert verbiage
  src/middlewared/middlewared/alert/source/cores.py
Labels: backport-22.12.3

#10879 NAS-120616 / 23.10 / Added support for wildcarded NFS hostnames
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/nfs_/utils.py
  tests/api2/test_300_nfs.py
Labels: backport-22.12.3

#10919 NAS-121127 / 23.10 / Add --tests parameter to runtest.py
  tests/runtest.py
Labels: jira

#10902 NAS-121090 / 23.10 / fix HA events on initial power on
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12.2, backport-22.12.3

#10918 NAS-121017 / 23.10 / fix disk.retaste and, hopefully, SCALE HA failover events
  src/middlewared/middlewared/plugins/disk_/retaste.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/pool_/export.py
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: backport-22.12.2, backport-22.12.3

#10927 NAS-121141 / 23.10 / Don't disable AD on passive controller
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10933 NAS-121128 / 22.12.3 / Remove cpu_in_percentage
  src/middlewared/middlewared/alembic/versions/22.12/2023-03-22_17-35_cpu_in_percentage.py
  src/middlewared/middlewared/etc_files/local/collectd.conf.mako
  src/middlewared/middlewared/plugins/reporting/plugins.py
  src/middlewared/middlewared/plugins/reporting/update.py
Labels: backport-23.10

#10941 NAS-121153 / 23.10 / Shift timing of fenced stop
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10944 NAS-121157 / 23.10 / avoid propagating keepalived restart
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10950 NAS-121161 / 23.10 / Define line max length settings at middleware project level
  src/middlewared/setup.cfg
Labels: jira

#10949 NAS-121093 / 23.10 / Configure zettarepl on failover `MASTER` event
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-22.12.2, backport-22.12.3

#10951 NAS-119809 / 23.10 / `--skip-unknown` in autotune so that installer that runs it does noth…
  src/freenas/usr/local/bin/truenas-autotune.py
Labels: skip jira status

#10956 NAS-121148 / 23.10 / fix mseries.nvdimm.info
  src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Labels: backport-22.12.2, backport-22.12.3

#10958 NAS-121147 / 23.10 / fix nvdimm alerts
  src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
Labels: backport-22.12.2, backport-22.12.3

#10957 NAS-121125 / 22.12.3 / Use VIP for apps when failover is licensed
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: backport-22.12.2, backport-23.10

#10967 NAS-121170 / 23.10 / Fix duplicate alerts
  src/middlewared/middlewared/plugins/alert.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10966 NAS-121169 / 23.10 / Fix false nvdimm alert
  src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
Labels: jira, backport-22.12.2, backport-22.12.3

#10928 NAS-121144 / 23.10 / Allow adding FULL_CONTROL to ACL for apps
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_linux.py
  tests/api2/test_340_pool_dataset.py
Labels: WIP, jira, backport-22.12.3

#10974 NAS-121197 / 23.10 / fix single-char typo
  src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
Labels: backport-22.12.2, backport-22.12.3

#10991 NAS-121088 / 23.10 / fix missing readonly property
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: backport-22.12.2, backport-22.12.3

#10996 NAS-121008 / 23.10 / catch AttributeError in websocket client
  src/middlewared/middlewared/client/client.py
Labels: backport-22.12.2, backport-22.12.3

#10955 NAS-121087 / 23.10 / Make `user.shell_choices` accept group IDs to prevent showing TrueNAS…
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  tests/api2/test_account_shell_choices.py
Labels: backport-22.12.3

#10999 NAS-119516 / 23.10 / Also send `Pool Status Is Not Healthy` alert for pool warnings
  src/middlewared/middlewared/alert/source/volume_status.py
Labels: backport-22.12.3

#11004 NAS-121223 / 23.10 / add new 2.6 qualified firmware to nvdimm alert
  src/middlewared/middlewared/alert/source/mseries_nvdimm_and_bios.py
  src/middlewared/middlewared/plugins/hardware/m_series_nvdimm.py
Labels: backport-22.12.2, backport-22.12.3

#11010 NAS-120155 / 23.10 / point vim.tiny to vim
  debian/debian/postinst
Labels: skip jira status, backport-22.12.3

#11014 NAS-121245 / 23.10 / Add more verbose error message for wrong name
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira, backport-22.12.3

#10898 NAS-121091 / 23.10 / Add tests for MS-RPC server
  src/middlewared/middlewared/test/integration/assets/smb.py
  tests/api2/test_428_smb_rpc.py
  tests/protocols/__init__.py
  tests/protocols/ms_rpc.py
Labels: jira, backport-22.12.3

#11024 NAS-121255 / 23.10 / Add pyotp
  tests/requirements.txt
Labels: jira

#11028 NAS-121270 / 23.10 / Do not enforce 2fa to be configured when making user create/update changes
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#11027 NAS-121269 / 23.10 / Add non-default parameter to retrieve SID info
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/idmap.py
  tests/api2/test_011_user.py
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-22.12.3
