Repository truenas/middleware, pull requests merged in 2024-05, with the labels that each got.

#13638 NAS-128677 / 24.10 / Loosen restrictions for LDAP idmap validation
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#13637 NAS-128661 / 24.10 / prevent disk_resize on nvme fabric devices
  src/freenas/usr/local/sbin/disk_resize
Labels: backport-24.04.1

#13647 NAS-128717 / 24.10 / Add missing level to MemorySizeMismatchAlertClass
  src/middlewared/middlewared/alert/source/memory_errors.py
Labels: jira

#13646 NAS-128716 / 24.10 / Only have one yield in fixture
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-24.04.1

#13645 NAS-128712 / 24.10 / Simplify user.get_user_obj and group.get_group_obj
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py
  src/middlewared/middlewared/plugins/rsync.py
Labels: jira

#13654 NAS-128436 / 24.10 / Fix DB migration crash when `int_vipv6address` is `None`
  src/middlewared/middlewared/alembic/versions/22.12/2022-03-01_14-40_simplify_network_interfaces.py
Labels: backport-24.04.1

#13652 NAS-128679 / 24.10 / Improve chart version mismatch error message
  src/middlewared/middlewared/plugins/catalogs_linux/items_util.py
  src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_items_utils.py
Labels: backport-24.04.1

#13659 NAS-128752 / 24.04.1 / fix catalog.query to stop calling zfs.dataset.query
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: backport-24.10, jira-high

#13640 NAS-128754 / 24.10 / Refactor SMB and Directory Services plugins
  src/middlewared/middlewared/etc_files/local/smb4.conf.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/nfs.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/constants.py
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/registry_share.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_global_smb.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/plugins/smb_/util_net_conf.py
  src/middlewared/middlewared/plugins/smb_/util_param.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/plugins/smb_/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/test_smb.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_435_smb_registry.py
Labels: jira

#13664 NAS-128787 / 24.10 / Fix catalog.query
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
Labels: jira, backport-24.04.1

#13663 NAS-128786 / 24.10 / Fix breakage in AD
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#13661 NAS-128762 / 24.10 / bump max_tasks_per_child to 20
  src/middlewared/middlewared/main.py
Labels: jira, backport-24.04.1, jira-low

#13666 NAS-128789 / 24.10 / Fix AD cache retrieval issue
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
Labels: jira

#13668 NAS-128800 / 24.10 / Improve validation of SMB options
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/util_param.py
Labels: jira

#13669 NAS-128802 / 24.10 / Improve configuration file generation
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/pytest/unit/utils/test_write_if_changed.py
  src/middlewared/middlewared/utils/io.py
Labels: jira

#13600 NAS-128404 / 24.10 / Improve file receive
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pwenc.py
Labels: jira, backport-24.04.1, jira-low

#13662 NAS-128772 / 24.10 / cache boot disks
  src/middlewared/middlewared/plugins/boot.py
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: jira, jira-low

#13673 NAS-128827 / 24.10 / Re-add recently removed import of pwd, grp
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira

#13681 NAS-128838 / 24.10 / Use proper util for writing kerberos keytab
  src/middlewared/middlewared/etc_files/krb5.keytab.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#13670 NAS-128814 / 24.10 / Remove legacy samba domain support
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  tests/api2/test_275_ldap.py
Labels: jira

#13680 NAS-127870 / 24.10 / fix starting apps with a bridge interface
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: backport-24.04.1

#13676 NAS-128835 / 24.10 / Add framework to have etc.generate return list of changes
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/pytest/unit/utils/test_write_if_changed.py
  src/middlewared/middlewared/utils/io.py
Labels: jira

#13684 NAS-128471 / 24.10 / Fix app stats when they are using host network
  src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py
Labels: backport-24.04.1

#13649 NAS-128631 / 24.10 / Make sure we redirect logs to relevant log files instead of copying them
  src/freenas/etc/logrotate.d/netdata_override
  src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
Labels: backport-24.04.1

#13689 NAS-128877 / 24.10 / Fix typo in etc.generate
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#13690 NAS-128879 / 24.10 / Make tests HA compatible using truenas_server.ip
  tests/api2/test_iscsi_auth_network.py
Labels: jira, backport-24.04.2

#13694 NAS-128884 / 24.10 / Fix home shares connectivity when AD enabled
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#13682 NAS-128839 / 24.10 / Fix modernize ad tests
  tests/api2/test_030_activedirectory.py
  tests/requirements.txt
Labels: jira

#13697 NAS-128895 / 24.10 / Move reset svcs to middleware test utils
  src/middlewared/middlewared/test/integration/utils/system.py
  tests/api2/test_300_nfs.py
Labels: jira

#13692 NAS-128882 / 24.10 / Improve mDNS configuration generation
  src/middlewared/middlewared/etc_files/local/avahi/avahi-daemon.conf.mako
  src/middlewared/middlewared/etc_files/local/avahi/avahi_services.py
  src/middlewared/middlewared/etc_files/local/avahi/services/ADISK.service.py
  src/middlewared/middlewared/etc_files/local/avahi/services/DEV_INFO.service.py
  src/middlewared/middlewared/etc_files/local/avahi/services/HTTP.service.py
  src/middlewared/middlewared/etc_files/local/avahi/services/SMB.service.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/pytest/unit/utils/test_mdns.py
  src/middlewared/middlewared/utils/mdns.py
Labels: jira

#13696 NAS-128892 / 24.10 / Minor time machine quality of life fixes
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-24.04.2

#13672 NAS-128822 / 24.10 / Log container registry exceptions in separate file
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/plugins/container_runtime_interface/update_alerts.py
Labels: jira

#13702 NAS-128911 / 24.10 / Add basic tests for statx wrapper
  src/middlewared/middlewared/plugins/filesystem_/stat_x.py
  src/middlewared/middlewared/pytest/unit/utils/test_statx.py
Labels: jira

#13709 NAS-128983 / 24.10 / Fix several API test files for HA
  tests/api2/test_330_pool_acltype.py
  tests/api2/test_340_pool_dataset.py
  tests/api2/test_345_acl_nfs4.py
  tests/api2/test_347_posix_mode.py
  tests/api2/test_348_posix_acl.py
  tests/api2/test_350_pool_dataset_quota_alert.py
  tests/api2/test_420_smb.py
  tests/api2/test_425_smb_protocol.py
  tests/api2/test_427_smb_acl.py
  tests/api2/test_428_smb_rpc.py
  tests/api2/test_430_smb_sharesec.py
  tests/api2/test_450_staticroutes.py
  tests/api2/test_470_system.py
  tests/protocols/ms_rpc.py
  tests/protocols/nfs_proto.py
  tests/protocols/smb_proto.py
Labels: jira

#13710 NAS-128988 / 24.04.1 / disable swap by default
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
Labels: jira, jira-high

#13712 NAS-128788 / 24.10 / Set vm.swappiness=1
  src/freenas/etc/sysctl.d/10-truenas.conf
Labels: backport-24.04.1, backport-24.10

#13717 NAS-128995 / 24.10 / Improve error message for invalid ix-apps pool
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: backport-24.04.1, backport-24.04.2

#13708 NAS-128996 / 24.10 / Improve filesystem apis (listdir and dosmode)
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl.py
  src/middlewared/middlewared/plugins/filesystem_/dosmode.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py
  src/middlewared/middlewared/plugins/pool_/utils.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
  src/middlewared/middlewared/pytest/unit/utils/test_directory.py
  src/middlewared/middlewared/pytest/unit/utils/test_filesystem_misc.py
  src/middlewared/middlewared/pytest/unit/utils/test_statx.py
  src/middlewared/middlewared/utils/__init__.py
  src/middlewared/middlewared/utils/filesystem/__init__.py
  src/middlewared/middlewared/utils/filesystem/acl.py
  src/middlewared/middlewared/utils/filesystem/attrs.py
  src/middlewared/middlewared/utils/filesystem/constants.py
  src/middlewared/middlewared/utils/filesystem/directory.py
  src/middlewared/middlewared/utils/filesystem/stat_x.py
  src/middlewared/middlewared/utils/filesystem/utils.py
  tests/api2/test_190_filesystem.py
Labels: jira

#13720 NAS-129001 / 24.10 / Fix default config test
  tests/api2/test_audit_basic.py
Labels: jira

#13705 NAS-128590 / 24.10 / Fix Range validator args
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
  src/middlewared/middlewared/pytest/unit/plugins/chart_releases/test_chart_releases_schema.py
Labels: backport-24.04.1, backport-24.04.2

#13721 NAS-129002 / 24.10 / More API test HA-related cleanups
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  src/middlewared/middlewared/test/integration/assets/smb.py
  src/middlewared/middlewared/test/integration/utils/ssh.py
  tests/api2/test_001_ssh.py
  tests/api2/test_002_system_license.py
  tests/api2/test_003_network_global.py
  tests/api2/test_006_pool_and_sysds.py
  tests/api2/test_007_early_settings.py
  tests/api2/test_011_user.py
  tests/api2/test_012_directory_service_ssh.py
  tests/api2/test_023_kubernetes.py
  tests/api2/test_024_container.py
  tests/api2/test_026_kubernetes_backup_chart_releases.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_036_ad_ldap.py
  tests/api2/test_040_ad_user_group_cache.py
  tests/api2/test_050_alert.py
  tests/api2/test_130_cloudsync.py
  tests/api2/test_140_core.py
  tests/api2/test_150_cronjob.py
  tests/api2/test_190_filesystem.py
  tests/api2/test_210_group.py
  tests/api2/test_260_iscsi.py
  tests/api2/test_275_ldap.py
  tests/api2/test_310_service_announcement.py
  tests/api2/test_330_pool_acltype.py
  tests/api2/test_340_pool_dataset.py
  tests/api2/test_341_pool_dataset_encryption.py
  tests/api2/test_345_acl_nfs4.py
  tests/api2/test_347_posix_mode.py
  tests/api2/test_348_posix_acl.py
  tests/api2/test_350_pool_dataset_quota_alert.py
  tests/api2/test_420_smb.py
  tests/api2/test_425_smb_protocol.py
  tests/api2/test_426_smb_vss.py
  tests/api2/test_427_smb_acl.py
  tests/api2/test_428_smb_rpc.py
  tests/api2/test_430_smb_sharesec.py
  tests/api2/test_438_snapshots.py
  tests/api2/test_450_staticroutes.py
  tests/api2/test_470_system.py
  tests/api2/test_475_syslog.py
  tests/api2/test_480_system_advanced.py
  tests/api2/test_490_system_general.py
  tests/api2/test_500_system_ntpservers.py
  tests/api2/test_550_vmware.py
  tests/api2/test_790_update.py
  tests/api2/test_900_docs.py
  tests/api2/test_999_pool_dataset_unlock.py
  tests/api2/test_api_key.py
  tests/api2/test_audit_basic.py
  tests/api2/test_auth_token.py
  tests/api2/test_rest_api_authentication.py
  tests/api2/test_vmware.py
  tests/runtest.py
Labels: jira

#13727 NAS-128998 / 24.04.2 / prevent middleware service from starting when config is reset
  src/middlewared/middlewared/plugins/reporting/netdata_configure.py
Labels: backport-24.04.1

#13728 NAS-128998 / 24.10 / Run middleware migrations on config upload
  src/middlewared/middlewared/plugins/migration.py
Labels: backport-24.04.1, backport-24.04.2

#13732 NAS-129012 / 24.04.1 / fix swapoff typo
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
Labels: jira, backport-24.04.2, jira-high

#13711 NAS-128993 / 24.10 / Enhance WebSocket Handling with Dynamic Connection Header for VM Display devices
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: jira

#13735 NAS-129018 / 24.10 / Improve statx performance
  src/middlewared/middlewared/utils/filesystem/stat_x.py
Labels: jira

#13736 NAS-129019 / 24.10 / More statx improvements
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/pytest/unit/utils/test_statx.py
  src/middlewared/middlewared/utils/filesystem/directory.py
  src/middlewared/middlewared/utils/filesystem/stat_x.py
Labels: jira

#13739 NAS-129033 / 24.10 / Fix CallError arguments in ACL plugin
  src/middlewared/middlewared/plugins/filesystem_/acl.py
Labels: jira, backport-24.04.2

#13737 NAS-129027 / 24.10 / Add some tests to check the state of things before all tests are done
  tests/api2/test_zzz_tests_completed.py
Labels: jira

#13738 NAS-129028 / 24.10 / Reintroduce device.settle_udev_events to avoid race
  src/middlewared/middlewared/plugins/disk_/format.py
Labels: jira

#13741 NAS-129038 / 24.10 / Add synchronous version of standard path validator
  src/middlewared/middlewared/async_validators.py
  src/middlewared/middlewared/pytest/unit/test_validators.py
  src/middlewared/middlewared/validators.py
Labels: jira

#13742 NAS-129042 / 24.10 / Do not crash `zfs.dataset.unlocked_zvols_fast` when `volmode=full` is…
  src/middlewared/middlewared/plugins/zfs_/utils.py
  tests/api2/test_zfs_dataset_list.py
Labels: jira, backport-24.04.2

#13743 NAS-129043 / 24.10 / HTOP Default Configuration
  src/freenas/etc/htoprc
Labels: jira, backport-24.04.2

#13744 NAS-129045 / 24.10 / Improve disk.get_partitions_quick
  src/middlewared/middlewared/plugins/disk_/format.py
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: jira

#13747 NAS-129046 / 24.10 / Fix several test regressions due to removing ip
  tests/api2/test_014_failover_related.py
  tests/api2/test_200_ftp.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_278_freeipa.py
  tests/api2/test_300_nfs.py
  tests/api2/test_330_pool_acltype.py
  tests/api2/test_440_snmp.py
  tests/api2/test_audit_basic.py
Labels: jira

#13750 NAS-129050 / 24.10 / Fix typo in recent commit: pathlib.path should be pathlib.Path
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: jira

#13751 NAS-129052 / 24.10 / Another ip -> truenas_server.ip fix
  tests/api2/test_200_ftp.py
  tests/api2/test_300_nfs.py
  tests/api2/test_440_snmp.py
  tests/api2/test_vmware.py
Labels: jira

#13752 NAS-129056 / 24.10 / Fix VSS and SMB quota tests for HA
  tests/protocols/smb_proto.py
Labels: jira

#13704 NAS-128961 / 24.10 / Improve CDROM device validation
  src/middlewared/middlewared/plugins/vm/devices/cdrom.py
Labels: jira

#13641 NAS-128723 / 24.10 / Enable cgroups plugin
  src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
  src/middlewared/middlewared/plugins/reporting/rest.py
  src/middlewared/middlewared/plugins/reporting/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
Labels: jira

#13753 NAS-129061 / 24.10 / Fix kubernetes delegate validation test
  tests/api2/test_kubernetes_delegate_validation.py
Labels: jira, backport-24.04.2

#13755 NAS-129064 / 24.10 / Fix sysdataset test
  tests/api2/test_system_dataset.py
Labels: jira

#13760 NAS-129112 / 24.10 / fix TypeError crash in disk.wipe
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: jira

#13761 NAS-129118 / 24.10 / Fix log spam during AD leave
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira-low

#13763 NAS-129126 / 24.10 / Do not spam middleware logs if path does not exist in smb share
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-24.04.2

#13757 NAS-128704 / 24.10 / Fix truecommand issues on HA
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
Labels: backport-24.04.2

#13766 NAS-129109 / 24.10 / Fix app stats event caching
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
Labels: backport-24.04.1, backport-24.04.2

#13772 NAS-129152 / 24.10 / Fix /data/license perms
  src/middlewared/middlewared/plugins/failover_/zpool_cachefile.py
  src/middlewared/middlewared/plugins/system/product.py
Labels: jira

#13765 NAS-129137 / 24.10 / Fix eula
  src/freenas/usr/local/share/truenas/eula.html
Labels: jira, backport-24.04.2

#13774 NAS-129148 / 24.04.2 / no really disable swap
  src/middlewared/middlewared/plugins/disk_/swap_configure.py
Labels: backport-24.04.1

#13777 NAS-129164 / 24.10 / Fix (recently) broken test test_058_create_new_user_knownfails
  tests/api2/test_011_user.py
Labels: jira

#13779 NAS-129170 / 24.10 / Fix nss wrapper
  src/middlewared/middlewared/pytest/unit/utils/test_nss.py
  src/middlewared/middlewared/utils/nss/grp.py
  src/middlewared/middlewared/utils/nss/pwd.py
Labels: jira

#13782 NAS-129171 / 24.10 / Also catch ValueError when looking up JbofModels
  src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Labels: backport-24.04.1, backport-24.04.2

#13785 NAS-129172 / 24.10 / Add setup_aapl_extensions to prevent test ERROR
  tests/api2/test_435_smb_registry.py
Labels: jira

#13788 NAS-129171 / 24.10 / add is_this_an_es24n function
  src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
Labels: backport-24.04.1, backport-24.04.2

#13794 NAS-129193 / 24.10 / Make test_disk_wipe_abort HA aware
  tests/api2/test_disk_wipe.py
Labels: jira

#13795 NAS-129194 / 24.10 / Fix HA breakage in test_create_a_normal_pool
  tests/api2/test_341_pool_dataset_encryption.py
Labels: jira

#13787 NAS-129188 / 24.10 / Refactored dhparam generation
  src/middlewared/middlewared/plugins/crypto_/dhparams.py
Labels: jira

#13793 NAS-129191 / 24.10 / Make test_changing_hostname HA aware
  tests/api2/test_network_configuration.py
Labels: jira

#13791 NAS-129197 / 24.10 / Fix failing app roles integration tests
  src/middlewared/middlewared/test/integration/assets/roles.py
  tests/api2/test_apps_roles.py
Labels: jira

#13796 NAS-129200 / 24.10 / fix start_sector assert (invalid test)
  tests/api2/test_disk_format.py
Labels: jira

#13799 NAS-129205 / 24.10 / Fix iscsi.host.batch_update
  src/middlewared/middlewared/plugins/iscsi_/host_crud.py
Labels: jira

#13800 NAS-129124 / 24.10 / Add temporary filter to non-critical SNMP warning.
  src/middlewared/middlewared/etc_files/syslog-ng/conf.d/tnfilters.conf.mako
Labels: backport-24.04.2

#13805 NAS-129187 / 24.10 / Add stats in chart.release entry schema
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: backport-24.04.1.1, backport-24.04.2

#13803 NAS-129150 / 24.10 / fix apps when interface has a description
  src/middlewared/middlewared/plugins/kubernetes_linux/lifecycle.py
  src/middlewared/middlewared/plugins/kubernetes_linux/update.py
Labels: backport-24.04.1.1, backport-24.04.2

#13810 NAS-129271 / 24.10 / Silence paramiko debug logs
  src/middlewared/middlewared/logger.py
Labels: backport-24.04.2

#13440 NAS-129269 / 24.10 / Make rsyslog support IPv6 destinations
  src/middlewared/middlewared/etc_files/syslog-ng/syslog-ng.conf.mako
  src/middlewared/middlewared/plugins/system_advanced/config.py
Labels: jira

#13781 NAS-129123 / 24.10 / Expand error recovery in AD health checks
  src/middlewared/middlewared/etc_files/krb5.conf.mako
  src/middlewared/middlewared/etc_files/krb5.conf.py
  src/middlewared/middlewared/etc_files/krb5.keytab.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/activedirectory_/krb5.py
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/directoryservices_/secrets.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/pytest/unit/utils/test_krb5.py
  src/middlewared/middlewared/utils/directoryservices/__init__.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5_conf.py
  src/middlewared/middlewared/utils/directoryservices/krb5_constants.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_036_ad_ldap.py
Labels: jira-medium

#13813 NAS-129280 / 24.10 / Reduce log spam on etc file generation
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#13814 NAS-129288 / 24.10 / Fix permissions and owner of snmpd.conf
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#13818 NAS-129305 / 24.10 / Remove execute permissions from smb.conf
  src/middlewared/middlewared/plugins/smb_/constants.py
Labels: jira

#13819 NAS-129308 / 24.10 / Remove cifs-utils from debian control
  debian/debian/control
Labels: jira

#13821 NAS-129327 / 24.10 / Fix the API tests that were (incorrectly) using disk.get_unused
  src/middlewared/middlewared/test/integration/assets/pool.py
  tests/api2/test_006_pool_and_sysds.py
  tests/api2/test_disk_format.py
  tests/api2/test_disk_wipe.py
Labels: jira
