Repository truenas/middleware, pull requests merged in 2024-01, with the labels that each got.

#12823 NAS-125876 / 24.04 / Reduce git subprocess spam in error logging
  src/middlewared/middlewared/utils/git.py
Labels: backport-23.10.2

#12829 NAS-125932 / 23.10.1.1 / Fix non-physical interface link address getting into database when it is updated
  src/middlewared/middlewared/alembic/versions/23.10/2024-01-02_15-09_delete_link_addresses_for_non_physical_interfaces.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-23.10.2

#12830 NAS-125932 / 23.10.2 / Fix non-physical interface link address getting into database when it is updated (by themylogin)
  src/middlewared/middlewared/alembic/versions/23.10/2024-01-02_15-09_delete_link_addresses_for_non_physical_interfaces.py
  src/middlewared/middlewared/alembic/versions/23.10/2024-01-02_15-15_merge.py
Labels: backport-24.04

#12822 NAS-125985 / 24.04 / Add SMB client tests for ZFS ACL compatibiltiy
  src/middlewared/middlewared/test/integration/assets/smb.py
  tests/api2/test_smb_client.py
Labels: jira

#12835 NAS-126011 / 24.04 / Do not include HA peer iSCSI ALUA sessions in global.iscsi.sessions
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Labels: jira, backport-23.10.2

#12840 NAS-126015 / 24.04 / Fix Authorization of remote middleware in HA
  src/middlewared/middlewared/auth.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/utils/privilege.py
Labels: jira

#12843 NAS-126026 / 24.04 / add READONLY role to system.host_id
  src/middlewared/middlewared/plugins/system/info.py
Labels: jira

#12844 NAS-126027 / 24.04 / add READONLY to truenas.is_production
  src/middlewared/middlewared/plugins/truenas.py
Labels: jira

#12847 NAS-126037 / 24.04 / Do not use floating point percents for jobs
  src/middlewared/middlewared/job.py
Labels: jira

#12849 NAS-126046 / 24.04 / Fix middleware not starting
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/role.py
Labels: jira

#12839 NAS-125877 / 24.04 / Make sure we don't exhaust /var/run with catalogs
  src/middlewared/middlewared/plugins/catalogs_linux/sync_catalogs.py
  src/middlewared/middlewared/plugins/catalogs_linux/update.py
  tests/api2/test_catalog_sync.py
Labels: backport-23.10.2

#12853 NAS-126064 / 13.1 / Remove "directory name cache size" parameter from smb4.conf
  src/middlewared/middlewared/etc_files/local/smb4.conf
Labels: jira

#12848 NAS-126045 / 24.04 / Fix ALUA support for multi-lun iSCSI targets
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/iscsi_/targets.py
  tests/api2/test_261_iscsi_cmd.py
Labels: jira, backport-23.10.2

#12856 NAS-126074 / 13.1 / Remove AD monitor thread
  src/middlewared/middlewared/alert/source/active_directory.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_420_smb.py
Labels: jira

#12859 NAS-126689 / 24.04 / Add more filesystem plugin roles
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira

#12858 NAS-126067 / 24.04 / Fix NFS manage-gids conf setting
  src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
  tests/api2/test_300_nfs.py
Labels: backport-23.10.2

#12865 NAS-126072 / 23.10.2 / fix ETOOMANYREFS on SCALE HA
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-23.10.1.1, backport-24.04

#12864 NAS-126697 / 23.10.2 / fix AttributeError crash in vrrp event thread
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
Labels: backport-23.10.1.1, backport-24.04

#12863 NAS-126698 / 23.10.2 / fix logic in failover.events.fenced_start_loop
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-23.10.1.1, backport-24.04

#12860 NAS-126691 / 23.10.2 / fix TypeError crash in failover.vip.check_failover_group
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: backport-23.10.1.1, backport-24.04

#12874 NAS-126705 / 24.04 / Fix hactl returning UNKNOWN status
  src/freenas/usr/local/sbin/hactl
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira, backport-23.10.2

#12879 NAS-126724 / 24.04 / NFS syslog filter test: Add samples and widen search to eliminate false failures
  tests/api2/test_300_nfs.py
Labels: WIP, jira

#12882 NAS-126734 / 24.04 / Add delay to allow syslog flush
  tests/api2/test_300_nfs.py
Labels: jira

#12883 NAS-126739 / 24.04 / Remove deprecated smb.sharesec APIs
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: jira

#12895 NAS-126792 / 24.04 / Fail tests early when `another_pool` fixture fails to teardown
  src/middlewared/middlewared/test/integration/assets/pool.py
Labels: jira

#12896 NAS-126794 / 24.04 / Fix test_011 missing user
  tests/api2/test_011_user.py
Labels: jira

#12893 NAS-126788 / 24.04 / Fix VM device attributes schema
  src/middlewared/middlewared/plugins/vm/devices/__init__.py
  src/middlewared/middlewared/plugins/vm/devices/display.py
  src/middlewared/middlewared/plugins/vm/info.py
  src/middlewared/middlewared/plugins/vm/vm_devices.py
  src/middlewared/middlewared/plugins/vm/vm_display_info.py
  src/middlewared/middlewared/plugins/vm/vm_memory_info.py
  src/middlewared/middlewared/plugins/vm/vms.py
  tests/api2/test_account_privilege_role_private_fields.py
Labels: jira

#12894 NAS-126791 / 24.04 / Improve handling for SIDS S-1-22-1 and S-1-22-2
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/cache.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/idmap_/gencache.py
  src/middlewared/middlewared/plugins/idmap_/utils.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/smb_/util_sd.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/schema.py
  src/middlewared/middlewared/plugins/tdb/utils.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  tests/api2/test_430_smb_sharesec.py
  tests/api2/test_account_idmap.py
Labels: jira

#12900 NAS-126802 / 24.04 / Fix app available schema
  src/middlewared/middlewared/plugins/catalogs_linux/apps.py
Labels: jira

#12899 NAS-126799 / 24.04 / Try to fix random pruning integration test failure
  tests/api2/test_024_container.py
Labels: jira

#12902 NAS-126813 / 24.04 / Fix regressions in CI tests
  tests/api2/test_account_privilege.py
  tests/api2/test_account_privilege_role.py
Labels: jira

#12905 NAS-126782 / 24.04 / PoolScrubService.__run: reduce memory usage during zpool history (by rkojedzinszky)
  src/middlewared/middlewared/plugins/pool_/scrub.py
Labels: backported, backport-23.10.2

#12909 NAS-126823 / 24.04 / Fix cluster_mode_targets
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: jira, backport-23.10.2

#12911 NAS-126825 / 24.04 / Fix regressions caused by SID handling refactor
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#12907 NAS-126817 / 24.04 / Fail tests if required groups are missing
  tests/api2/test_001_ssh.py
Labels: jira

#12913 NAS-126833 / 24.04 / Fix VM integration tests
  tests/api2/test_vm_roles.py
Labels: jira

#12916 NAS-126850 / 24.10 / Add dedicated endpoint to download audit reports
  src/middlewared/middlewared/plugins/audit/audit.py
  tests/api2/test_audit_basic.py
Labels: jira, backport-24.04

#12919 NAS-126859 / 24.10 / fix typo in log message
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira, backport-24.04-RC.1

#12921 NAS-126862 / 24.10 / Mock catalog sync unconfigure pool
  tests/api2/test_catalog_sync.py
Labels: jira, backport-24.04-RC.1

#12923 NAS-126866 / 24.10 / Fix kubernetes integration test
  tests/api2/test_kubernetes_delegate_validation.py
Labels: jira, backport-24.04-RC.1

#12922 NAS-126865 / 24.10 / Test audit report generation for non-root users
  tests/api2/test_audit_basic.py
Labels: jira, backport-24.04-RC.1

#12928 NAS-126871 / 24.10 / Fix variable not declared usage
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-24.04-RC.1

#12933 NAS-126878 / 24.10 / Forcibly disable AD service if misconfigured
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#12936 NAS-126899 / 24.10 / Add roles for crypto plugin
  src/middlewared/middlewared/plugins/crypto_/ca_profiles.py
  src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
  src/middlewared/middlewared/plugins/crypto_/certificate_authorities.py
  src/middlewared/middlewared/plugins/crypto_/certificates.py
  src/middlewared/middlewared/plugins/crypto_/sign_csr.py
  src/middlewared/middlewared/role.py
  tests/api2/test_certificate_roles.py
Labels: jira, backport-24.04-RC.1

#12880 NAS-126722 / 24.10 / handle iface fault events on SCALE HA
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
Labels: backport-23.10.1.2, backport-24.04-RC.1, backport-23.10.2

#12944 NAS-126922 / 24.10 / properly handle bond/vlan interfaces in virtual_ips.py
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: backport-23.10.1.2, backport-24.04-RC.1, backport-23.10.2

#12943 NAS-126921 / 24.10 / Convert directory service updates to jobs
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/ad.py
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  tests/api2/assets/REST/__init__.py
  tests/api2/assets/REST/directory_services.py
  tests/api2/test_012_directory_service_ssh.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_036_ad_ldap.py
  tests/api2/test_040_ad_user_group_cache.py
  tests/api2/test_275_ldap.py
  tests/api2/test_278_freeipa.py
Labels: jira

#12938 NAS-126912 / 24.10 / Add electric eel migration directory for alembic
  src/middlewared/middlewared/alembic.ini
  src/middlewared/middlewared/alembic/versions/24.10/.gitkeep
Labels: jira

#12953 NAS-126867 / 24.10 / Fix documentation markup
  src/middlewared/middlewared/apidocs/templates/websocket.html
Labels: backport-24.04-RC.1

#12952 NAS-125699 / 24.04-RC.1 / Remove system birthday
  src/middlewared/middlewared/alembic/versions/24.04/2024-01-23_10-38_remove_system_birthday.py
  src/middlewared/middlewared/plugins/system/info.py
  src/middlewared/middlewared/plugins/system/lifecycle.py
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: backport-24.10

#12948 NAS-126860 / 24.10 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or…
  src/middlewared/middlewared/plugins/interface/lag.py
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
Labels: backport-23.10.1.3, backport-24.04-RC.1, backport-23.10.2

#12958 NAS-126860 / 24.04-RC.1 / Fix `NOT NULL constraint failed: network_lagginterfacemembers.lagg_or… (by themylogin)
  src/middlewared/middlewared/plugins/interface/lag.py
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/plugins/interface/netif_linux/interface.py
  src/middlewared/middlewared/plugins/interface/netif_linux/vrrp.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
Labels: backported, backport-24.04-BETA.1

#12951 NAS-126829 / 24.10 / Improve invalid AD config alert verbosity
  src/middlewared/middlewared/alert/source/active_directory.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
Labels: backport-24.04-RC.1, backport-23.10.2

#12962 NAS-126940 / 24.10 / Undo some breakage wrt iscsi incremental tests
  src/middlewared/middlewared/test/integration/assets/iscsi.py
Labels: jira

#12963 NAS-126941 / 24.10 / Fix `KeyError` in `persist_link_addresses`
  src/middlewared/middlewared/plugins/interface/link_address.py
Labels: jira, backport-24.04-BETA.1, backport-23.10.1.3, backport-23.10.2

#12969 NAS-125859 / 24.10 / Allow multiple NVIDIA gpus to be shared to a single app
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
Labels: backport-24.04-RC.1

#12939 NAS-126800 / 24.10 / fix ipmi.lan.query for UI
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: backport-24.04-RC.1

#12973 NAS-126969 / 13.1 / middlewared: point dependency to correct path
  nas_ports/freenas/py-middlewared/Makefile
Labels: jira

#12968 NAS-126959 / 24.10 / add truenas.is_ix_hardware for UI team (RBAC required changes)
  src/middlewared/middlewared/alert/source/ipmi_sel.py
  src/middlewared/middlewared/etc_files/smartd.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/disk_/smartctl.py
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
  src/middlewared/middlewared/plugins/network.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/truenas.py
Labels: backport-24.04-RC.1

#12976 NAS-126980 / 24.10 / Fix `RuntimeError: Method ipmi.lan.query is public but has no @accept…
  src/middlewared/middlewared/plugins/ipmi_/lan.py
  src/middlewared/middlewared/service/core_service.py
Labels: jira, backport-24.04-RC.1

#12949 NAS-126842 / 24.10 / Fix UPS reporting plugin
  src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
  src/freenas/usr/lib/netdata/conf.d/charts.d.conf
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Labels: backport-24.04-RC.1

#12974 NAS-126975 / 24.10 / Update NUT driver systemctl stop function.
  src/middlewared/middlewared/plugins/service_/services/ups.py
  tests/api2/test_015_services.py
Labels: WIP, jira

#12980 NAS-126984 / 24.10 / Update the error message with a helpful hint.
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
Labels: jira

#12979 NAS-126986 / 24.10 / Improve logging wrt reestablishment on failover RemoteClient connection
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#12986 NAS-126989 / 24.10 / Get rid of AsyncMock in interface tests
  src/middlewared/middlewared/pytest/unit/plugins/test_interface.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#12981 NAS-126960 / 24.10 / fix interface.lag_ports_choices and API
  src/middlewared/middlewared/plugins/network.py
Labels: backport-24.04-RC.1, backport-23.10.2

#12993 NAS-126991 / 24.10 / fix typo in network.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira, backport-24.04-RC.1

#12991 NAS-126990 / 24.10 / Fix typo
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira, backport-24.04-RC.1

#12992 NAS-126972 / 24.10 / fix low sel space alert
  src/middlewared/middlewared/alert/source/ipmi_sel.py
Labels: backport-24.04-RC.1, backport-23.10.2

#12998 NAS-126995 / 24.10 / Properly prevent endless `Failed to write to console` errors
  src/middlewared/middlewared/main.py
Labels: jira, backport-24.04-RC.1

#12985 NAS-126988 / 24.10 / Fix edge case in container pruning test
  tests/api2/test_023_kubernetes.py
  tests/api2/test_024_container.py
Labels: jira

#13005 NAS-127018 / 24.10 / Add test coverage for resolving names in acl templates
  tests/api2/test_344_acl_templates.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#13010 NAS-127024 / 24.10 / Fix missing import in AD alert
  src/middlewared/middlewared/alert/source/active_directory.py
Labels: jira, backport-24.04-RC.1

#13011 NAS-127025 / 24.10 / fix disk.wipe progress reporting
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-24.04-RC.1

#12999 NAS-127006 / 24.10 / Add a text field schema in catalog format for UI
  src/middlewared/middlewared/plugins/chart_releases_linux/schema.py
  tests/api2/test_charts_schema.py
Labels: jira

#13003 NAS-127008 / 24.10 / Do not use interface rename logic on systems that have NICs with dupl…
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#13015 NAS-127053 / 24.10 / Add max length validation to the support ticket title and description
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/schema/string_schema.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_charts_schema.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#13024 NAS-126979 / 24.10 / fix SCALE HA failover logic
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
  src/middlewared/middlewared/plugins/network.py
Labels: backport-24.04-RC.1, backport-23.10.2

#13025 NAS-127058 / 24.10 / add READONLY_ADMIN to system.debug
  src/middlewared/middlewared/plugins/system/debug.py
Labels: backport-24.04-RC.1

#13029 NAS-126809 / 24.10 / Preserve partition start when expanding a pool
  src/middlewared/middlewared/plugins/disk_/resize.py
  src/middlewared/middlewared/plugins/pool_/expand.py
  tests/api2/test_pool_expand.py
Labels: backport-24.04-RC.1, backport-23.10.2

#13014 NAS-126857 / 24.10 / Prevent combination of DISCARD aclmode and NFSv4 acltype
  src/middlewared/middlewared/plugins/pool_/dataset.py
  tests/api2/test_011_user.py
  tests/api2/test_345_acl_nfs4.py
Labels: backport-24.04-RC.1, backport-23.10.2

#13035 NAS-127085 / 24.10 / Fix returns decorator for audit query items
  src/middlewared/middlewared/plugins/audit/audit.py
Labels: backport-24.04-RC.1

#13038 NAS-127017 / 24.10 / `bootenv.promote_current_be_datasets`
  src/middlewared/middlewared/plugins/bootenv.py
  tests/api2/test_bootenv.py
Labels: backport-24.04-RC.1

#13039 NAS-127096 / 23.10.2 / Fix catalog sync tests in cobia
  tests/api2/test_catalog_sync.py
Labels: jira

#13040 NAS-127097 / 24.10 / Enhance NFS rpc port configuration test
  tests/api2/test_300_nfs.py
Labels: jira

#13028 NAS-127079 / 24.10 / Optimize role based integration tests
  src/middlewared/middlewared/test/integration/assets/roles.py
  tests/api2/test_apps_roles.py
  tests/api2/test_certificate_roles.py
  tests/api2/test_iscsi_auth_crud_roles.py
  tests/api2/test_iscsi_extent_crud_roles.py
  tests/api2/test_iscsi_global_crud_roles.py
  tests/api2/test_iscsi_host_crud_roles.py
  tests/api2/test_iscsi_initiator_crud_roles.py
  tests/api2/test_iscsi_portal_crud_roles.py
  tests/api2/test_iscsi_target_crud_roles.py
  tests/api2/test_iscsi_targetextent_crud_roles.py
  tests/api2/test_nfs_share_crud_roles.py
  tests/api2/test_smb_share_crud_roles.py
  tests/api2/test_vm_roles.py
Labels: jira

#13037 NAS-126993 / 24.04-RC.1 / Change graphite hostname attribute
  src/middlewared/middlewared/alembic/versions/24.04/2024-01-29_10-05_update_graphite_hostname_attribute.py
  src/middlewared/middlewared/etc_files/netdata/exporting.conf.mako
  src/middlewared/middlewared/plugins/reporting/exporters/graphite.py
Labels: backport-24.10

#13045 NAS-127109 / 24.10 / fix TypeError crash in ipmi.lan.update
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: backport-24.04-RC.1

#12970 NAS-126080 / 24.10 / Fix pagination parameters
  src/middlewared/middlewared/service/crud_service.py
  tests/api2/test_crud.py
Labels: backport-13.1, backport-24.04-RC.1, backport-23.10.2

#13052 NAS-127123 / 24.10 / Add NFS CI test for v4_domain configuration option
  tests/api2/test_300_nfs.py
Labels: jira

#13051 NAS-127026 / 24.10 / Abort underlying thread when aborting disk wipe
  src/middlewared/middlewared/plugins/disk_/wipe.py
  tests/api2/test_disk_wipe.py
Labels: backport-24.04-RC.1, backport-23.10.2

#13059 NAS-127133 / 24.10 / Fix failing integration tests
  tests/api2/test_apps_roles.py
  tests/api2/test_certificate_roles.py
Labels: jira
