Repository truenas/middleware, pull requests merged in 2024-07, with the labels that each got.

#13908 NAS-129689 / 24.10 / Properly manage readonly state when executing initrd script
  src/freenas/usr/local/bin/truenas-initrd.py
Labels: jira

#13944 NAS-129791 / 24.10 / Fix validation for homedir mountinfo
  src/middlewared/middlewared/plugins/account.py
Labels: jira-medium

#13960 NAS-129827 / 24.10 / Force alphabetical ordering id_to_name results
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-24.04.3

#13942 NAS-129780 / 24.10 / Simplify API for querying directory services users and groups
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/test/integration/assets/ftp.py
  tests/api2/test_036_ad_ldap.py
  tests/api2/test_040_ad_user_group_cache.py
Labels: jira-medium

#13962 NAS-129862 / 24.10 / fix failover.mismatch_nics
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/network.py
Labels: jira, jira-high

#13967 NAS-129882 / 24.10 / Prevent deletion of immutable users
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#13972 NAS-129889 / 24.10 / Fix schema for directory services users
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#13974 NAS-129811 / 24.10 / Perform additional fixup wrt CORE ctl device names
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Labels: backport-24.04.3

#13978 NAS-129907 / 24.10 / Fix logrotate to work properly
  src/freenas/debian/preinst
Labels: jira

#13981 Close persistent client connection at end of run
  tests/api2/test_zzz_tests_completed.py
Labels: jira

#13980 NAS-129922 / 24.10 / Fix groupmap test for nsswitch changes
  tests/api2/test_210_group.py
Labels: jira

#13982 NAS-129925 / 24.10 / Fix test cleanup after creating temporary admin user
  tests/api2/test_user_admin.py
Labels: jira

#13912 NAS-129692 / 24.10 / rate limit methods that have @no_auth_required
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/rate_limit/__init__.py
  src/middlewared/middlewared/plugins/system/info.py
  src/middlewared/middlewared/pytest/unit/test_service.py
  src/middlewared/middlewared/service/__init__.py
  src/middlewared/middlewared/service/throttle.py
  src/middlewared/middlewared/utils/rate_limit/__init__.py
  src/middlewared/middlewared/utils/rate_limit/cache.py
  src/middlewared/middlewared/utils/rate_limit/zz.py
  tests/api2/assets/websocket/server.py
  tests/api2/test_014_failover_related.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_200_ftp.py
  tests/api2/test_300_nfs.py
  tests/api2/test_470_system.py
  tests/api2/test_rate_limit.py
  tests/functions.py
  zz.py
Labels: jira, jira-high

#13985 NAS-129930 / 24.10 / remove empty test file
  tests/api2/test_280_lldp.py
Labels: jira, jira-low

#13986 NAS-129934 / 24.10 / reset rate limit in client asset for integration tests
  src/middlewared/middlewared/test/integration/utils/client.py
Labels: jira, jira-medium

#13987 NAS-129946 / 24.10 / clean up API quota tests
  tests/api2/test_340_pool_dataset.py
  tests/api2/test_810_delete_user.py
  tests/api2/test_pool_dataset_set_quota.py
  tests/api2/test_quotas.py
Labels: jira

#13991 NAS-129955 / 24.10 / add back simplified APPs acl tests
  tests/api2/test_pool_dataset_acl.py
Labels: jira

#13988 NAS-129951 / 24.10 / Clean up system advanced tests
  tests/api2/test_480_system_advanced.py
  tests/api2/test_system_advanced.py
  tests/api2/test_system_advanced_login_banner.py
Labels: jira, jira-low

#13983 NAS-129927 / 24.10 / Fix cloudsync HA test
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/api2/test_cloud_sync.py
Labels: jira

#13992 NAS-129958 / 24.10 / Fix a minor regression in NFS api tests
  tests/api2/test_300_nfs.py
Labels: jira

#13993 NAS-129963 / 24.10 / Remove fail from test runs on network issues
  src/middlewared/middlewared/test/integration/assets/directory_service.py
Labels: jira

#13994 NAS-129972 / 24.10 / fix test_simple_share_validation
  tests/api2/test_011_user.py
Labels: jira

#13995 NAS-129973 / 24.10 / More verbosely indicate unexpected test state in SMB simple share test
  tests/api2/test_simple_share.py
Labels: jira

#13997 NAS-129976 / 24.10 / Fix disk format api test
  src/middlewared/middlewared/plugins/disk_/disk_info.py
  tests/api2/test_disk_format.py
Labels: jira, backport-24.04.3

#14007 NAS-129999 / 24.10 / Fix login banner perms
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/system_advanced/config.py
Labels: jira

#14008 NAS-130001 / 24.10 / Catch exception thrown by ftp QUIT.
  tests/api2/test_200_ftp.py
Labels: jira-low

#13984 NAS-129929 / 24.10 / Improve SID handling
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/constants.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/smb_/sid.py
  src/middlewared/middlewared/plugins/smb_/util_groupmap.py
  src/middlewared/middlewared/plugins/smb_/utils.py
  src/middlewared/middlewared/pytest/unit/utils/test_groupmap.py
  src/middlewared/middlewared/pytest/unit/utils/test_sid.py
  src/middlewared/middlewared/utils/sid.py
  src/middlewared/middlewared/utils/tdb.py
  tests/api2/test_011_user.py
  tests/api2/test_210_group.py
  tests/api2/test_420_smb.py
  tests/api2/test_smb_groupmap.py
Labels: jira

#14013 NAS-130007 / 24.10 / Finish addressing review of SID handling PR
  src/middlewared/middlewared/plugins/smb_/groupmap.py
Labels: jira

#14014 NAS-130014 / 24.10 / Fix regression in restrict admin account query
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
Labels: jira

#13976 NAS-129905 / 24.10 / Mark GPU as critical if it has devices which are in an iommu group which has a critical device
  src/middlewared/middlewared/plugins/vm/pci.py
  src/middlewared/middlewared/plugins/vm/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/test_gpu_critical.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_pci_device_iommu_groups.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py
  src/middlewared/middlewared/utils/gpu.py
  src/middlewared/middlewared/utils/iommu.py
  src/middlewared/middlewared/utils/pci.py
Labels: jira

#14015 NAS-130015 / 24.10 / Fix failing SMB CI tests
  tests/api2/test_420_smb.py
  tests/api2/test_427_smb_acl.py
  tests/api2/test_435_smb_registry.py
Labels: jira

#14017 NAS-130018 / 24.10 / Fix access issue for SMB quotas for local admins
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/util_groupmap.py
  src/middlewared/middlewared/pytest/unit/utils/test_groupmap.py
Labels: jira

#14019 NAS-130037 / 24.10 / Run DRAID tests on HA
  tests/api2/test_draid_record_and_block_size.py
Labels: jira

#14020 NAS-130042 / 24.10 / Add custom exit code for fail() in test runs
  tests/conftest.py
Labels: jira

#14004 NAS-129993 / 24.10 / Add basic app management in place
  src/middlewared/debian/control
  src/middlewared/middlewared/etc_files/docker/daemon.json.py
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/apps/__init__.py
  src/middlewared/middlewared/plugins/apps/app_scale.py
  src/middlewared/middlewared/plugins/apps/compose_utils.py
  src/middlewared/middlewared/plugins/apps/crud.py
  src/middlewared/middlewared/plugins/apps/ix_apps/__init__.py
  src/middlewared/middlewared/plugins/apps/ix_apps/docker/__init__.py
  src/middlewared/middlewared/plugins/apps/ix_apps/docker/query.py
  src/middlewared/middlewared/plugins/apps/ix_apps/docker/utils.py
  src/middlewared/middlewared/plugins/apps/ix_apps/lifecycle.py
  src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py
  src/middlewared/middlewared/plugins/apps/ix_apps/path.py
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
  src/middlewared/middlewared/plugins/apps/ix_apps/rollback.py
  src/middlewared/middlewared/plugins/apps/ix_apps/setup.py
  src/middlewared/middlewared/plugins/apps/ix_apps/upgrade.py
  src/middlewared/middlewared/plugins/apps/ix_apps/utils.py
  src/middlewared/middlewared/plugins/apps/metadata.py
  src/middlewared/middlewared/plugins/apps/rollback.py
  src/middlewared/middlewared/plugins/apps/schema_normalization.py
  src/middlewared/middlewared/plugins/apps/schema_utils.py
  src/middlewared/middlewared/plugins/apps/schema_validation.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
  src/middlewared/middlewared/plugins/apps/utils.py
  src/middlewared/middlewared/plugins/apps/version_utils.py
  src/middlewared/middlewared/plugins/catalog/app_version.py
  src/middlewared/middlewared/plugins/catalog/apps.py
  src/middlewared/middlewared/plugins/catalog/apps_details.py
  src/middlewared/middlewared/plugins/catalog/apps_util.py
  src/middlewared/middlewared/plugins/docker/state_management.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/service_/services/docker.py
Labels: jira

#14024 NAS-130070 / 24.10 / Run pool disk replacement tests on HA
  tests/api2/test_pool_replace_disk.py
Labels: jira

#14026 NAS-130072 / 24.10 / Fix test for pool encryption unlock on services
  tests/api2/test_999_pool_dataset_unlock.py
Labels: jira

#14021 NAS-130078 / 24.10 / Add features support for apps in app schema
  src/middlewared/middlewared/plugins/apps/crud.py
  src/middlewared/middlewared/plugins/apps/ix_apps/path.py
  src/middlewared/middlewared/plugins/apps/resources.py
  src/middlewared/middlewared/plugins/apps/rollback.py
  src/middlewared/middlewared/plugins/apps/schema_action_context.py
  src/middlewared/middlewared/plugins/apps/schema_normalization.py
  src/middlewared/middlewared/plugins/apps/schema_utils.py
  src/middlewared/middlewared/plugins/apps/schema_validation.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
  src/middlewared/middlewared/plugins/apps/utils.py
  src/middlewared/middlewared/plugins/catalog/apps_details.py
Labels: jira

#14031 NAS-130086 / 24.10 / Add certificate attachments for apps
  src/middlewared/middlewared/plugins/apps/app_scale.py
  src/middlewared/middlewared/plugins/apps/cert_attachments.py
  src/middlewared/middlewared/plugins/apps/crud.py
  src/middlewared/middlewared/plugins/apps/ix_apps/metadata.py
  src/middlewared/middlewared/plugins/apps/ix_apps/path.py
  src/middlewared/middlewared/plugins/apps/metadata.py
  src/middlewared/middlewared/plugins/docker/state_management.py
Labels: jira

#14011 NAS-130004 / 24.10 / Add ability to join IPA domains
  src/freenas/usr/local/libexec/ipa_ctl.py
  src/middlewared/middlewared/alert/source/active_directory.py
  src/middlewared/middlewared/alert/source/ipa.py
  src/middlewared/middlewared/alert/source/ldap.py
  src/middlewared/middlewared/etc_files/ipa/ca.crt.py
  src/middlewared/middlewared/etc_files/ipa/default_conf.py
  src/middlewared/middlewared/etc_files/ipa/smb.keytab.py
  src/middlewared/middlewared/etc_files/krb5.conf.py
  src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/dns.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_health_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/directoryservices_/health.py
  src/middlewared/middlewared/plugins/directoryservices_/ipa_health_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/join.py
  src/middlewared/middlewared/plugins/directoryservices_/kerberos_health_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/ldap_health_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/ldap_join_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/secrets.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/idmap_/idmap_sss.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/nfs_/krb5.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/smbconf/reg_service.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/pytest/unit/plugins/test_smb.py
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  src/middlewared/middlewared/utils/directoryservices/ad.py
  src/middlewared/middlewared/utils/directoryservices/ad_constants.py
  src/middlewared/middlewared/utils/directoryservices/constants.py
  src/middlewared/middlewared/utils/directoryservices/health.py
  src/middlewared/middlewared/utils/directoryservices/ipa.py
  src/middlewared/middlewared/utils/directoryservices/ipa_constants.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5_constants.py
  src/middlewared/middlewared/utils/directoryservices/ldap_utils.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_032_ad_kerberos.py
  tests/api2/test_035_ad_idmap.py
  tests/api2/test_278_freeipa.py
  tests/api2/test_ipa_join.py
Labels: jira

#14033 NAS-130089 / 24.10 / fix copy and paste error
  src/middlewared/middlewared/plugins/enclosure_/jbof/utils.py
Labels: jira

#14035 NAS-130095 / 24.10 / Fix typos in directory services plugin
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: jira

#14037 NAS-130097 / 24.10 / Clean up LDAP CI test file
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  tests/api2/test_275_ldap.py
Labels: jira

#14038 NAS-130098 / 24.10 / Fix initial cache fill for LDAP and IPA
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
Labels: jira

#14039 NAS-130099 / 24.10 / Fix test regressions related to krb5 ccache change
  src/middlewared/middlewared/utils/directoryservices/krb5_constants.py
  tests/api2/test_032_ad_kerberos.py
Labels: jira

#14040 NAS-130102 / 24.10 / Remove test for auditing nfs.add_principal
  tests/api2/test_audit_nfs.py
Labels: jira

#14041 NAS-130111 / 24.10 / fix failing test
  tests/api2/test_nfs_share_crud_roles.py
Labels: jira

#14042 NAS-130113 / 24.10 / Fix alert test for legacy IPA bind
  tests/api2/test_278_freeipa.py
Labels: jira

#14047 NAS-130127 / 24.10 / Extra temporary file created by __tmp_krb5_keytab
  src/middlewared/middlewared/utils/directoryservices/krb5.py
Labels: jira-low

#14044 NAS-130124 / 24.10 / Cleanup dead code and remove extra parameters
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/auth_/2fa.py
  src/middlewared/middlewared/plugins/cluster_linux/__init__.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_event_scripts.py
  src/middlewared/middlewared/plugins/cluster_linux/ctdb_general.py
  src/middlewared/middlewared/plugins/cluster_linux/utils.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/scripts/ctdb_events.py
Labels: jira

#14048 NAS-130140 / 24.10 / Fixed status directoryservices.py
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: jira

#14043 NAS-130116 / 24.10 / Fix ipa join admin privileges and keytab
  src/middlewared/middlewared/etc_files/krb5.conf.py
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/directoryservices_/health.py
  src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
  src/middlewared/middlewared/plugins/ldap.py
  tests/api2/test_275_ldap.py
  tests/api2/test_ipa_join.py
Labels: jira

#14053 NAS-130158 / 24.10 / Shift around checks in add_to_acl
  src/middlewared/middlewared/plugins/filesystem_/acl.py
  tests/api2/test_pool_dataset_acl.py
Labels: jira

#14054 NAS-130159 / 24.10 / Add IPA leave and expand testing
  src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/join.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/pytest/unit/plugins/test_smb.py
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  tests/api2/test_ipa_join.py
  tests/api2/test_ipa_leave.py
Labels: jira

#14055 NAS-130174 / 24.10 / Prevent test run state pollution from test
  tests/api2/test_420_smb.py
Labels: jira

#14059 NAS-130178 / 24.10 / Disable IPv6 link_local addresses in Send Targets output
  src/middlewared/middlewared/etc_files/scst.conf.mako
Labels: jira-low

#14063 NAS-130190 / 24.10 / Fix the case when container consumes port on the container but not the host
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Labels: jira

#14066 NAS-130193 / 24.10 / Correctly reference used ports key when validating app ports
  src/middlewared/middlewared/plugins/apps/schema_validation.py
Labels: jira

#14070 NAS-130199 / 24.10 / Make sure docker networks get recreated with compose up action
  src/middlewared/middlewared/plugins/apps/compose_utils.py
Labels: jira

#14074 NAS-130214 / 24.10 / Make `Job.wait_sync` signature match `Job.wait`
  src/middlewared/middlewared/job.py
Labels: jira

#14064 NAS-130192 / 24.10 / Include errno in exc_info for jobs
  src/middlewared/middlewared/job.py
  tests/api2/test_job_errno.py
Labels: jira

#14045 NAS-130142 / 24.10 / Default to redacting result from core.get_jobs
  src/middlewared/middlewared/service/core_service.py
  tests/api2/test_job_result.py
Labels: jira

#14075 NAS-130225 / 24.10 / Add changes to allow retrieving app version details and config when querying apps
  src/middlewared/middlewared/plugins/apps/crud.py
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Labels: jira

#14077 NAS-130234 / 24.10 / Add errno entry to exc_info in core.get_jobs schema
  src/middlewared/middlewared/service/core_service.py
Labels: jira

#14078 NAS-130240 / 24.10 / skip known failing test
  tests/api2/test_001_ssh.py
Labels: jira

#14080 NAS-130243 / 24.10 / really skip the final remaining failing test
  tests/api2/test_001_ssh.py
Labels: jira

#14079 NAS-130242 / 24.10 / improve test_002
  tests/api2/test_002_system_license.py
Labels: jira

#14081 NAS-130244 / 24.10 / Replace disk test
  tests/api2/test_pool_replace_disk.py
Labels: jira

#14086 NAS-130255 / 24.10 / Avoid DNS lookup when disabling Active Directory
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira

#14087 NAS-130256 / 24.10 / Avoid deadlocking during DS health initialization
  src/middlewared/middlewared/plugins/directoryservices_/health.py
Labels: jira

#14089 NAS-130263 / 24.10 / There is no need to stop when redeploying app now
  src/middlewared/middlewared/plugins/apps/app_scale.py
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Labels: jira

#14096 NAS-130295 / 24.10 / fix test_pool_replace_disk.py api failures
  tests/api2/test_pool_replace_disk.py
Labels: jira-low

#14097 NAS-130297 / 24.10 / Fix interface test
  tests/api2/test_005_interface.py
Labels: jira-low

#14100 NAS-130312 / 24.10 / Clear JBOFTearDownFailure alert following reboot
  src/middlewared/middlewared/plugins/jbof/crud.py
Labels: jira-low

#14092 NAS-130273 / 24.10 / Add failback to ALUA config test
  tests/api2/test_261_iscsi_cmd.py
  tests/protocols/iscsi_proto.py
Labels: jira-low

#14099 NAS-130315 / 24.10 / Fix nfs syslog filter test
  tests/api2/test_300_nfs.py
Labels: jira-low

#14102 NAS-130317 / 24.10 / Robustize nfs manage gids and v4 domain tests
  tests/api2/test_300_nfs.py
Labels: no-time-tracked, jira-low

#14103 NAS-130324 / 24.10 / Treat ix-apps dataset specially in pool.dataset namespace
  src/middlewared/middlewared/alert/source/datasets.py
  src/middlewared/middlewared/plugins/catalog/apps_details.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared/middlewared/plugins/pool_/export.py
  src/middlewared/middlewared/plugins/pool_/import_pool.py
  src/middlewared/middlewared/validators.py
Labels: jira

#14106 NAS-130326 / 24.10 / Properly exclude ix-apps dataset from filesystem.listdir
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira

#14107 NAS-130327 / 24.10 / Remove ix-apps reference to path validator
  src/middlewared/middlewared/validators.py
Labels: jira

#14108 NAS-130328 / 24.10 / Fix catalog.apps example
  src/middlewared/middlewared/plugins/catalog/apps_details.py
Labels: jira

#14109 NAS-130330 / 24.10 / Fix switching docker pools
  src/middlewared/middlewared/plugins/docker/update.py
Labels: jira

#13817 NAS-129295 / 24.10 / Audit changes to the SMB server configuration
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/util_sd.py
  tests/api2/test_audit_smb.py
Labels: jira

#14114 NAS-130341 / 24.10 / Allow port choices for apps to start from 1
  src/middlewared/middlewared/plugins/catalog/apps_details.py
Labels: jira

#14115 NAS-130345 / 24.10 / Fix KeyError in acltemplate plugin
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira

#14116 NAS-130346 / 24.10 / Fix audit messages for SMB shares
  src/middlewared/middlewared/plugins/smb.py
Labels: jira
