Repository truenas/middleware, pull requests merged in 2024-02, with the labels that each got.

#13058 NAS-127132 / 24.10 / Add roles to subscriptions for CRUD services
  src/middlewared/middlewared/service/crud_service.py
Labels: jira, backport-24.04-RC.1

#13043 NAS-126939 / 24.10 / Add earlier validation to prevent enabling AD without pool
  src/middlewared/middlewared/plugins/activedirectory.py
  tests/api2/test_006_pool_and_sysds.py
Labels: backport-24.04-RC.1

#13064 NAS-127143 / 24.10 / `promote_current_be_datasets` fixes
  src/middlewared/middlewared/plugins/bootenv.py
Labels: jira, backport-24.04-RC.1

#13000 NAS-126880 / 24.10 / Disable apt-daily.service
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
Labels: backport-24.04-RC.1

#13062 NAS-127137 / 24.10 / Expand developer documentation related to roles
  docs/source/middleware/jobs.rst
  docs/source/middleware/roles.rst
Labels: jira, backport-24.04-RC.1

#13061 NAS-127134 / 24.10 / Add roles for directory services
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/role.py
Labels: jira, backport-24.04-RC.1

#13069 NAS-127087 / 24.10 / Support roles for event sources
  src/middlewared/middlewared/common/event_source/manager.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
  src/middlewared/middlewared/plugins/reporting/events.py
  tests/api2/test_reporting_realtime.py
Labels: backport-24.04-RC.1

#12286 NAS-127148 / 24.10 / Include information about allocation size
  src/middlewared/middlewared/plugins/filesystem.py
Labels: jira, backport-24.04-RC.1

#13001 NAS-127007 / 24.10 / Refactor directoryservices plugin
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/directoryservices_/__init__.py
  src/middlewared/middlewared/plugins/directoryservices_/secrets.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  tests/api2/test_030_activedirectory.py
  tests/api2/test_035_ad_idmap.py
Labels: jira

#13076 NAS-127156 / 24.10 / Fix typo documentation example
  docs/source/middleware/roles.rst
Labels: jira, backport-24.04-RC.1

#13063 NAS-127070 / 24.10 / `core.bulk` and roles
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/service/core_service.py
  src/middlewared/middlewared/service/decorators.py
  tests/api2/test_core_bulk.py
Labels: backport-24.04-RC.1

#13084 NAS-127199 / 24.10 / robustized truenas-nvdimm.py
  src/freenas/usr/local/bin/truenas-nvdimm.py
Labels: backport-24.04-RC.1, backport-23.10.2, backport-23.10.3

#13088 NAS-127223 / 24.10 / Prevent users from editing roles for builtin privileges
  src/middlewared/middlewared/plugins/account_/privilege.py
  tests/api2/test_account_privilege.py
Labels: backport-24.04-BETA.1, backport-24.04-RC.1

#13094 NAS-127158 / 24.10 / change format of rsync push in module mode
  src/middlewared/middlewared/plugins/rsync.py
Labels: backport-24.04-RC.1

#13095 NAS-127230 / 24.10 / initshutdownscript tests
  tests/api2/test_initshutdownscript.py
Labels: jira, backport-24.04-RC.1

#13092 NAS-127220 / 24.10 / Fix logic error in NFS share validation.
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-24.04-RC.1

#13106 NAS-127100 / 24.10 / Fix netdata boot order
  src/freenas/etc/systemd/system/netdata.service.d/override.conf
Labels: backport-24.04-RC.1, backport-23.10.2, backport-23.10.3

#13113 NAS-127302 / 24.10 / Fix app authentication error
  src/middlewared/middlewared/main.py
Labels: jira

#13118 NAS-127317 / 24.10 / fix output of zpool.status when dev is removed
  src/middlewared/middlewared/plugins/zfs_/pool_status.py
Labels: jira, backport-24.04-RC.1

#13117 NAS-127267 / 24.10 / Fix webui access flag in auth.me for custom privileges
  src/middlewared/middlewared/utils/privilege.py
  tests/api2/test_auth_me.py
Labels: backport-24.04-RC.1

#13123 NAS-127268 / 24.10 / Fix schema for privilege plugin
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/privilege.py
Labels: backport-24.04-RC.1

#12967 NAS-126731 / 24.10 / Improve failover handling of a large number of targets
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/dlm.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/iscsi_/alua.py
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  src/middlewared/middlewared/plugins/iscsi_/scst.py
  src/middlewared/middlewared/plugins/iscsi_/target_to_extent.py
  src/middlewared/middlewared/plugins/iscsi_/targets.py
  src/middlewared/middlewared/plugins/service.py
  src/middlewared/middlewared/plugins/service_/services/base.py
  src/middlewared/middlewared/plugins/service_/services/base_interface.py
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-24.04-RC.1, backport-23.10.2, backport-23.10.3

#13122 NAS-127319 / 24.10 / Make sure middleware socket is present
  src/freenas/usr/bin/install-dev-tools
Labels: jira

#13121 NAS-127318 / 24.10 / Pass arguments to disable-rootfs-protection
  src/freenas/usr/bin/install-dev-tools
Labels: jira, backport-24.04-RC.1

#13130 NAS-127336 / 24.10 / Fix TypeError on lookup failure for DS users
  src/middlewared/middlewared/plugins/cache.py
Labels: backport-24.04-RC.1

#13112 NAS-127258 / 24.10 / Bring back `HasUpdateAlertClass`
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/update.py
  src/middlewared/middlewared/plugins/update.py
Labels: backport-24.04-RC.1

#13136 NAS-127300 / 24.10 / Expose `cloudsync.providers` to `READONLY`
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-24.04-RC.1

#13131 NAS-127341 / 24.10 / idmap: add validation to prevent duplicate DNS names
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira, backport-24.04-RC.1

#13135 NAS-127269 / 24.10 / Handle missing k3s network stats in k3s netdata plugin
  src/freenas/usr/lib/netdata/python.d/k3s_stats.chart.py
Labels: backport-24.04-RC.1

#13105 NAS-126925 / 24.10 / Mark app's config as private
  src/middlewared/middlewared/plugins/chart_releases_linux/chart_release.py
Labels: backport-24.04-RC.1

#13141 NAS-127359 / 24.10 / fix another HA logic issue
  src/middlewared/middlewared/plugins/device_/vrrp_events.py
Labels: jira, backport-24.04-RC.1, backport-23.10.2

#13150 NAS-127367 / 24.10 / Changed set_ldap_secret call to set_ldap_idmap_secret
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira

#13134 NAS-127350 / 24.10 / Add ability to filter by keys in list objects
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira

#13142 NAS-127362 / 24.10 / Properly reflect bridge members when updating bridge settings
  src/middlewared/middlewared/plugins/network.py
Labels: jira

#13114 NAS-127157 / 24.10 / Mark HA nodes as active/standby in debug
  src/middlewared/middlewared/plugins/system/debug.py
Labels: backport-24.04-RC.1

#13140 NAS-127355 / 13.1 / Set `compatibility=grub2` when creating a boot pool in installer
  src/freenas-installer/etc/install.sh
Labels: jira

#13153 NAS-127375 / 24.10 / Do not double-encode stdin passed to `run`
  src/middlewared/middlewared/plugins/account.py
Labels: jira

#13155 NAS-127366 / 24.10 / fix failover group logic
  src/middlewared/middlewared/etc_files/keepalived.conf.mako
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/vrrp.py
Labels: backport-24.04-RC.1, backport-23.10.2, backport-23.10.3

#13159 NAS-127380 / 24.10 / Fix indentation error that was logging errors inside loop
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: jira, backport-24.04-RC.1, backport-23.10.3

#13162 NAS-127381 / 24.10 / Fix another indentation error that was logging errors inside loop
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: jira, backport-24.04-RC.1, backport-23.10.3

#13173 NAS-127385 / 24.10 / fix EBADF error in HA logic
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backport-24.04-RC.1, backport-23.10.2, backport-23.10.3

#13177 NAS-127393 / 24.10 / Get iface name from server
  tests/runtest.py
Labels: jira

#13154 NAS-127378 / 24.10 / Update k8s to 1.29
  src/middlewared/middlewared/etc_files/rancher/k3s/flags.py
Labels: jira

#13179 NAS-126877 / 24.10 / Bump AMD k8s device plugin image tag
  src/middlewared/middlewared/plugins/kubernetes_linux/gpu.py
Labels: backport-24.04-RC.1

#13172 NAS-127271 / 24.10 / Remove the html code in the Support Ticket created by TN Enterprise/HA
  src/middlewared/middlewared/plugins/alert.py
Labels: backport-24.04-RC.1

#13152 NAS-127344 / 24.10 / Add roles for truecommand plugin
  src/middlewared/middlewared/plugins/truecommand/update.py
  src/middlewared/middlewared/role.py
  tests/api2/test_truecommand_roles.py
Labels: backport-24.04-RC.1

#13185 NAS-127416 / 24.10 / Do not crash if DB already has a pool that is being imported
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: backport-24.04-RC.1, backport-23.10.3

#13183 NAS-127151 / 24.10 / Make sure there is no sensitive information in apps/tc/vm events plugins
  src/middlewared/middlewared/plugins/chart_releases_linux/events.py
  src/middlewared/middlewared/plugins/truecommand/portal.py
  src/middlewared/middlewared/plugins/truecommand/update.py
  src/middlewared/middlewared/plugins/vm/events.py
Labels: backport-24.04-RC.1, backport-23.10.3

#13190 NAS-127432 / 13.0 / fix off-by-1 on R50B nvme drives
  src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/rseries_nvme.py
Labels: backport-13.1

#13193 NAS-127453 / 24.10 / fix regression in pool_status.py
  src/middlewared/middlewared/plugins/zfs_/pool_status.py
Labels: jira, backport-24.04-RC.1

#13197 NAS-127422 / 24.10 / Fix schema for idmap DNS domain name
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-24.04-RC.1

#13201 NAS-125764 / 24.10 / Add a little more padding to audit quota test
  tests/api2/test_audit_basic.py
Labels: backport-24.04-RC.1

#13199 NAS-127457 / 24.10 / Improve speed of jbof.create and jbof.delete APIs
  src/middlewared/middlewared/plugins/jbof/crud.py
Labels: jira, backport-24.04-RC.1

#13203 NAS-127467 / 24.10 / add disk details to webui.enclosure.dashboard
  src/middlewared/middlewared/plugins/webui/enclosure.py
Labels: jira

#13205 NAS-127470 / 24.10 / always include disk details in enclosure.dashboard
  src/middlewared/middlewared/plugins/webui/enclosure.py
Labels: jira

#13209 Add test to ensure we don't regress on invalid key handling
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
Labels: jira

#13200 NAS-127460 / 24.10 / Improve disk partitioning
  src/middlewared/middlewared/plugins/disk_/format.py
  src/middlewared/middlewared/plugins/disk_/wipe.py
  src/middlewared/middlewared/plugins/pool_/format_disks.py
  tests/api2/test_disk_format.py
  tests/api2/test_disk_wipe.py
Labels: jira

#13210 NAS-127498 / 24.10 / Fix check for whether a dataset is internal
  src/middlewared/middlewared/plugins/pool_/dataset.py
Labels: jira, backport-24.04-RC.1

#13213 NAS-127074 / 24.10 / Fix permissions check for services plugin using api key
  src/middlewared/middlewared/plugins/service_/utils.py
  tests/api2/test_api_key.py
Labels: backport-24.04-RC.1

#13218 NAS-127301 / 24.10 / add codename to webui.dashboard.sys_info
  src/middlewared/middlewared/plugins/webui/main_dashboard.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-24.04-RC.1

#13221 NAS-127452 / 24.10 / Retry starting kerberos during DS initialization
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-24.04-RC.1

#13225 NAS-127552 / 24.10 / simplify and clean-up nvme/jbof functions
  src/middlewared/middlewared/plugins/jbof/crud.py
  src/middlewared/middlewared/plugins/jbof/functions.py
Labels: jira, backport-24.04-RC.1

#13228 NAS-127553 / 24.10 / Fix test for local accounts on HA platform
  tests/api2/test_001_ssh.py
Labels: jira, backport-24.04-RC.1

#13232 Fail test runs if we start hitting socket timeouts
  src/middlewared/middlewared/test/integration/utils/client.py
Labels: jira, backport-24.04-RC.1

#13234 NAS-127560 / 24.10 / Robustize waiting_for_iscsi_to_disconnect
  tests/api2/test_260_iscsi.py
Labels: jira, backport-24.04-RC.1

#13222 NAS-127561 / 24.10 / Fix runtest.py for HA VMs
  tests/runtest.py
Labels: jira

#13236 NAS-127576 / 24.10 / Fix failing AD test related to ds_auth for middleware
  tests/api2/test_030_activedirectory.py
Labels: jira, backport-24.04-RC.1

#13238 NAS-127579 / 24.10 / Skip catalog tests on HA platform
  tests/api2/test_catalog_sync.py
  tests/runtest.py
Labels: jira, backport-24.04-RC.1

#13242 NAS-127372 / 24.10 / vm.log_file_download
  src/middlewared/middlewared/plugins/vm/vms.py
Labels: backport-24.04-RC.1

#13220 NAS-127032 / 24.10 / Make sure console keymap changes persist
  src/freenas/usr/local/bin/truenas-initrd.py
  src/middlewared/middlewared/plugins/boot.py
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: backport-24.04-RC.1

#13252 NAS-127543 / 24.10 / Remove `VMWareLoginFailed` alerts on VMware snapshot update and delete
  src/middlewared/middlewared/plugins/vmware.py
Labels: backport-24.04-RC.1

#13253 NAS-123837 / 24.10 / add ES24N JBoF to enclosure management
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
  src/middlewared/middlewared/plugins/enclosure_/enums.py
  src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
  src/middlewared/middlewared/plugins/enclosure_/map2.py
  src/middlewared/middlewared/plugins/enclosure_/slot_mappings.py
  src/middlewared/middlewared/plugins/jbof/crud.py
  src/middlewared/middlewared/plugins/jbof/redfish/client.py
  src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_enclosure2_query.py
Labels: backport-24.04-RC.1

#13262 NAS-127610 / 24.10 / Make some minor improvements in kerberos.py
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#13266 NAS-127622 / 24.04.0 / Make `truenas-initrd.py` behave correctly on read-only root (by themylogin)
  src/freenas/usr/local/bin/truenas-initrd.py
Labels: backport-24.04-RC.1

#13265 NAS-117880 / 24.10 / Change SCST extent threading for performance
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/iscsi_/extents.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13274 NAS-127622 / 24.10 / Do not change `readonly` property when we are running in the installe…
  src/freenas/usr/local/bin/truenas-initrd.py
Labels: backport-24.04-RC.1, backport-24.04.0
