Repository truenas/middleware, pull requests merged in 2024-11, with the labels that each got.

#14839 NAS-132157 / 25.04 / Robustize dmi_pci_slot_info
  src/middlewared/middlewared/plugins/fc/utils.py
Labels: jira

#14838 NAS-132156 / 25.04 / Fix cloud backup test
  tests/api2/test_cloud_backup.py
Labels: jira, backport-24.10.1

#14844 NAS-132164 / 25.04 / Fix `ReadonlyRootfsManager` not really making rootfs writeable
  src/middlewared/middlewared/plugins/boot.py
  src/middlewared/middlewared/utils/rootfs.py
Labels: backport-24.10.1

#14827 NAS-132070 / 25.04 / `docker.nvidia_status` method and event source to substitude `docker.…
  src/middlewared/middlewared/api/v25_04_0/docker.py
  src/middlewared/middlewared/plugins/docker/update.py
Labels: backport-24.10.1

#14847 NAS-132177 / 25.04 / fix disk.sync_all edge-case crash
  src/middlewared/middlewared/plugins/enclosure.py
Labels: backport-24.10.0.1, backport-24.10.1, jira-high

#14840 NAS-132158 / 25.04 / Convert rdma.interface to new api_method
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/rdma_interface.py
  src/middlewared/middlewared/plugins/rdma/interface/crud.py
Labels: jira

#14851 NAS-132187 / 25.04 / prevent empty critical bond interfaces on HA
  src/middlewared/middlewared/plugins/network.py
Labels: backport-24.10.0.1, backport-24.10.1, jira-medium

#14854 NAS-132191 / 25.04 / Fix docker roles tests
  tests/api2/test_docker_roles.py
Labels: backport-24.10.1

#14843 use filterable_api_method in smb.sharesec and idmap
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
Labels: jira

#14859 NAS-132192 / 25.04 / Fix incorrect translation of LDAP basedn to realm
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/utils/directoryservices/ipa.py
  tests/unit/test_directory_services.py
Labels: backport-24.10.1

#14856 NAS-132202 / 25.04 / Mark app as having upgrade available if it's a custom app and there are image updates available
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
  src/middlewared/middlewared/plugins/apps/pull_images.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
Labels: backport-24.10.1

#14869 NAS-132270 / 25.04 / Improve fcport.status when ALUA is disabled
  src/middlewared/middlewared/plugins/fcport.py
Labels: jira-low

#14855 NAS-132196 / 25.04 / Fix bugs in ACME DNS auth service and convert schemas to new api style
  src/middlewared/middlewared/alembic/versions/25.04/2024-11-05_23-35_authenticator_normalization.py
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
  src/middlewared/middlewared/api/v25_04_0/acme_registration.py
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/base.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/ovh.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/route53.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/shell.py
  src/middlewared/middlewared/plugins/acme_protocol_/challenge.py
  src/middlewared/middlewared/plugins/acme_protocol_/schema.py
Labels: jira

#14872 NAS-132284 / 25.04 / Fix nvidia drivers status
  src/middlewared/middlewared/plugins/docker/update.py
Labels: jira, backport-24.10.1

#14874 NAS-132302 / 25.04 / remove usage of legacy bootenv calls
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/update_/install.py
Labels: jira-low

#14875 NAS-132271 / 25.04 / ignore USB NICs on enterprise platforms
  src/middlewared/middlewared/plugins/network.py
Labels: backport-24.10.1

#14877 NAS-132304 / 25.04 / remove dead code
  tests/boot.exp
  tests/install.exp
  tests/iso/.keepme
Labels: jira-low

#14879 NAS-132305 / 25.04 / Fix and improve tests/README.md
  tests/README.md
Labels: jira-low

#14876 NAS-132303 / 25.04 / remove strftime call in boot.environment.query
  src/middlewared/middlewared/plugins/boot_/environments.py
Labels: jira-low

#14880 NAS-132306 / 25.04 / Fix --tests handling
  tests/runtest.py
Labels: jira-low

#14881 NAS-132307 / 25.04 / remove accepts from CacheService plugin
  src/middlewared/middlewared/plugins/cache.py
Labels: jira-low

#14883 NAS-132311 / 25.04 / Convert snmp to new api method.
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/snmp.py
  src/middlewared/middlewared/plugins/snmp.py
  tests/api2/test_440_snmp.py
Labels: jira

#14868 NAS-132267 / 25.04 / Convert iscsi.extent.* to new api
  src/middlewared/middlewared/api/base/types/iscsi.py
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_extent.py
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  tests/api2/test_261_iscsi_cmd.py
Labels: jira

#14867 NAS-132072 / 24.10.1 / Add transfer setting to Truecloud Backup
  src/middlewared/middlewared/alembic/versions/24.10/2024-11-04_20-26_cloud_backup_transfer_setting.py
  src/middlewared/middlewared/plugins/cloud/crud.py
  src/middlewared/middlewared/plugins/cloud/model.py
  src/middlewared/middlewared/plugins/cloud_backup/crud.py
  src/middlewared/middlewared/plugins/cloud_backup/sync.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_cloud_backup.py
Labels: backported, backport-25.04

#14890 NAS-132077 / 25.04 / Make sure helm secret is safely serialized when listing k8s backups
  src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py
Labels: backport-24.10.1

#14889 NAS-132265 / 24.10.1 / VM Device attributes should be encrypted
  src/middlewared/middlewared/alembic/versions/24.10/2024-11-06_12-49_make_vm_device_attributes_encrypted.py
  src/middlewared/middlewared/plugins/vm/vm_devices.py
Labels: backport-25.04

#14828 NAS-132140 / 25.04 / Remove auth.two_factor_auth endpoint
  src/middlewared/middlewared/api/v25_04_0/auth.py
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#14899 NAS-132339 / 25.04 / Fix integration test for ACME DNS authenticator
  tests/api2/test_account_privilege_role_private_fields.py
Labels: jira

#14903 NAS-132361 / 25.04 / Fix runtest.py when an absolute path is provided to --tests
  tests/runtest.py
Labels: jira

#14902 NAS-132351 / 25.04 / Fix disk device serial migration
  src/middlewared/middlewared/alembic/versions/25.04/2024-10-29_12-43_vm_zvol_serial.py
Labels: jira

#14905 NAS-132352 / 25.04 / Fix new cloud backup test
  tests/api2/test_cloud_backup.py
Labels: backport-24.10.1

#14910 NAS-132420 / 25.04 / The conint function has been deprecated.
  src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_04_0/docker.py
  src/middlewared/middlewared/api/v25_04_0/pool.py
Labels: jira-low

#14914 NAS-132431 / 25.04 / Fix random false positives in OTP tests
  src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
  tests/api2/test_twofactor_auth.py
Labels: backport-24.10.1, jira-medium

#14917 NAS-132407 / 25.04 / be smarter about checking ports in use
  src/middlewared/middlewared/plugins/system_general/update.py
Labels: backport-24.10.1

#14909 NAS-132248 / 25.04 / Avoid potentially unnecessary kerberos.start when activating AD
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
Labels: backport-24.10.1

#14913 NAS-132377 / 25.04 / fix MINI-3.0-X vers 1.0 enclosure page
  src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Labels: backport-24.10.1

#14908 NAS-132402 / 25.04 / Refactor dtype key in VM device attrs
  src/middlewared/middlewared/alembic/versions/25.04/2024-11-10_12-23_vm_device_dtype.py
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
  src/middlewared/middlewared/plugins/pool_/unlock.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/plugins/vm/attachments.py
  src/middlewared/middlewared/plugins/vm/clone.py
  src/middlewared/middlewared/plugins/vm/devices/cdrom.py
  src/middlewared/middlewared/plugins/vm/devices/display.py
  src/middlewared/middlewared/plugins/vm/devices/nic.py
  src/middlewared/middlewared/plugins/vm/devices/pci.py
  src/middlewared/middlewared/plugins/vm/devices/storage_devices.py
  src/middlewared/middlewared/plugins/vm/devices/usb.py
  src/middlewared/middlewared/plugins/vm/supervisor/supervisor.py
  src/middlewared/middlewared/plugins/vm/vm_devices.py
  src/middlewared/middlewared/plugins/vm/vm_display_info.py
  src/middlewared/middlewared/plugins/vm/vm_lifecycle.py
  src/middlewared/middlewared/plugins/vm/vms.py
  src/middlewared/middlewared/pytest/unit/plugins/test_interface_link_address.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_attachments.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_validation.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_devices_xml.py
Labels: jira

#14898 NAS-132340 / 25.04 / Move reporting exporters service to new api style
  src/middlewared/middlewared/alembic/versions/25.04/2024-11-12_09-09_reporting_exporters.py
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/reporting_exporters.py
  src/middlewared/middlewared/etc_files/netdata/exporting.conf.mako
  src/middlewared/middlewared/plugins/reporting/export.py
  src/middlewared/middlewared/plugins/reporting/exporters/base.py
  src/middlewared/middlewared/plugins/reporting/exporters/graphite.py
Labels: jira

#14920 NAS-132457 / 25.04 / Minor ACME logic refactors
  src/middlewared/middlewared/plugins/acme_protocol_/acme_svc.py
  src/middlewared/middlewared/plugins/acme_protocol_/client_utils.py
  src/middlewared/middlewared/plugins/acme_protocol_/issue_cert.py
Labels: jira

#14900 NAS-131723 / 25.04 / Add exclusion support for TrueCloud backup tasks
  src/middlewared/middlewared/plugins/cloud_backup/sync.py
Labels: backport-24.10.1

#14901 NAS-132347 / 25.04 / Fix Fibre Channel ALUA
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/iscsi_/alua.py
  src/middlewared/middlewared/plugins/iscsi_/scst.py
  tests/api2/test_fibre_channel.py
Labels: jira

#14927 NAS-132464 / 25.04 / Do not use `Field(...`, its the default
  src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_04_0/alert.py
  src/middlewared/middlewared/api/v25_04_0/reporting.py
Labels: jira

#14931 NAS-132470 / 25.04 / Add explicit validation errors for mixing DS and local accounts
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_account.py
Labels: jira, backport-24.10.1

#14938 NAS-132483 / 25.04 / There is no need to query all apps when clearing upgrade alerts for all apps
  src/middlewared/middlewared/alert/source/applications.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
Labels: jira, backport-24.10.1

#14941 NAS-132489 / 25.04 / Fix SMB external paths
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#14942 NAS-132492 / 25.04 / Fix VM integration test
  tests/api2/test_account_privilege_role_private_fields.py
  tests/api2/test_pool_dataset_unlock_restart_vms.py
Labels: jira

#14940 NAS-132486 / 25.04 / Fix removing details/environment vars from virt instance
  src/middlewared/middlewared/plugins/virt/instance.py
  tests/api2/test_virt_002_instance.py
Labels: jira

#14929 NAS-132467 / 25.04 / Always serialize method results
  src/middlewared/middlewared/api/base/handler/result.py
  src/middlewared/middlewared/api/v25_04_0/auth.py
  src/middlewared/middlewared/api/v25_04_0/fcport.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_extent.py
  src/middlewared/middlewared/api/v25_04_0/keychain.py
  src/middlewared/middlewared/api/v25_04_0/virt.py
  src/middlewared/middlewared/plugins/fcport.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/service/sharing_service.py
  tests/api2/test_300_nfs.py
  tests/api2/test_posix_acl.py
  tests/api2/test_user_create_dir.py
Labels: jira

#14952 NAS-132524 / 25.04 / remove unnecessary test
  tests/api2/test_legacy_websocket.py
Labels: jira-low

#14955 NAS-132530 / 25.04 / Fix API for rdma.get_card_choices
  src/middlewared/middlewared/api/v25_04_0/rdma.py
  src/middlewared/middlewared/plugins/rdma/rdma.py
Labels: jira-low

#14954 NAS-132529 / 25.04 / Validate results of CRUDService methods
  src/middlewared/middlewared/main.py
Labels: jira

#14956 NAS-132539 / 25.04 / Fix vm integration test
  tests/api2/test_541_vm.py
Labels: jira

#14957 NAS-132544 / 25.04 / Follow-up to https://github.com/truenas/middleware/pull/14954
  src/middlewared/middlewared/main.py
Labels: jira

#14965 NAS-132563 / 25.04 / Fix typo in validation message
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-24.10.1

#14975 NAS-132599 / 25.04 / Increase ES24n import timeout
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/jbof/crud.py
Labels: backport-24.10.1

#14937 NAS-132169 / 25.04 / Make sure ix-apps mountpoint is correct
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: backport-24.10.1

#14974 NAS-132595 / 25.04 / Handle non-JSON progress messages in TrueCloud Backup
  src/middlewared/middlewared/plugins/cloud_backup/restic.py
Labels: backport-24.10.1

#14986 NAS-132629 / 25.04 / Increase the timeout wrt ES24n import in import_on_boot
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: jira, backport-24.10.1

#14988 NAS-132626 / 25.04 / call proactive_support_allowed()
  src/middlewared/middlewared/plugins/support.py
Labels: backport-24.10.1

#14951 NAS-132505 / 25.04 / Remove accepts style decorator from catalog plugin
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/app.py
  src/middlewared/middlewared/api/v25_04_0/catalog.py
  src/middlewared/middlewared/plugins/catalog/app_version.py
  src/middlewared/middlewared/plugins/catalog/apps.py
  src/middlewared/middlewared/plugins/catalog/apps_details.py
  src/middlewared/middlewared/plugins/catalog/sync.py
  src/middlewared/middlewared/plugins/catalog/update.py
  tests/api2/test_catalog_roles.py
Labels: jira

#14990 NAS-131797 / 25.04 / Properly capture IP on which a port is bound to in apps port delegate
  src/middlewared/middlewared/plugins/apps/port_attachments.py
Labels: backport-24.10.1

#14992 NAS-132122 / 25.04 / Do casefolded comparison of netbios names
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: backport-24.10.1

#14969 NAS-132572 / 25.04 / Safely extract user config
  src/middlewared/middlewared/plugins/config.py
Labels: jira, backport-24.10.1

#14995 NAS-132654 / 25.04 / Tidy test_261_iscsi_cmd
  tests/api2/test_261_iscsi_cmd.py
Labels: jira-low

#14996 NAS-132212 / 25.04 / Improve handling for legacy IPA bind with kerberos principal
  src/middlewared/middlewared/plugins/ldap.py
  tests/api2/test_ipa_join.py
Labels: backport-24.10.1

#14958 NAS-132516 / 25.04 / Use `/usr/share/truenas/sysext-extensions/functioning-dpkg.raw` to temporarily allow `dpkg`
  src/middlewared/middlewared/utils/rootfs.py
Labels: backport-24.10.2

#14999 NAS-132359 / 25.04 / Use systemd-sysext to load pre-built nvidia drivers
  src/middlewared/middlewared/api/v25_04_0/docker.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/nvidia.py
Labels: backport-24.10.2

#15002 NAS-132359 / 24.10.2 / Use systemd-sysext to load pre-built nvidia drivers (by themylogin)
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/nvidia.py
Labels: backport-24.10.1

#15006 NAS-132681 / 25.04 / Reload iscsitarget on iscsi.auth.delete
  src/middlewared/middlewared/plugins/iscsi_/auth.py
Labels: jira-low, backport-24.10.2

#15007 NAS-132681 / 24.10.2 / Reload iscsitarget on iscsi.auth.delete (by bmeagherix)
  src/middlewared/middlewared/plugins/iscsi_/auth.py
Labels: backport-24.10.1

#14998 NAS-132662 / 25.04 / Add test for maximum SMB valid pwrite range
  tests/api2/test_smb_write_offset.py
Labels: jira, backport-24.10.2

#15012 NAS-132684 / 25.04 / Handle case where netbiosalias is omitted from AD payload
  src/middlewared/middlewared/plugins/activedirectory.py
Labels: jira, backport-24.10.1, backport-24.10.2

#15000 NAS-132668 / 25.04 / Make FIPS not use `ReadonlyRootfsManager` as due to `systemd-sysext` …
  debian/debian/preinst
  src/freenas/debian/preinst
  src/middlewared/middlewared/scripts/configure_fips.py
Labels: backport-24.10.1, backport-24.10.2

#15005 NAS-132679 / 25.04 / Allow BRIDGED and MACVLAN type of NICs
  src/middlewared/middlewared/api/v25_04_0/virt.py
  src/middlewared/middlewared/plugins/virt/device.py
  src/middlewared/middlewared/plugins/virt/instance_device.py
  tests/api2/test_virt_002_instance.py
Labels: jira

#15010 NAS-130509 / 25.04 / Add CI test for discovery auth
  tests/api2/test_261_iscsi_cmd.py
  tests/protocols/__init__.py
  tests/protocols/iscsi_proto.py
Labels: WIP

#15016 NAS-132668 / 24.10.2 / Make FIPS not use `ReadonlyRootfsManager` as due to `systemd-sysext` … (by themylogin)
  debian/debian/preinst
  src/freenas/debian/preinst
  src/middlewared/middlewared/scripts/configure_fips.py
Labels: backported, backport-24.10.1

#15019 NAS-132692 / 25.04 / fix regression in docker role API tests
  tests/api2/test_docker_roles.py
Labels: backport-24.10.1, jira-low, backport-24.10.2

#15018 NAS-132691 / 25.04 / remove dead bootenv plugin
  src/middlewared/middlewared/plugins/bootenv.py
Labels: jira-low

#15027 NAS-132664 / 25.04 / Handle k8s apps migration edge case
  src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
Labels: backport-24.10.1, backport-24.10.2

#15025 NAS-132712 / 25.04 / Fix alert text format for Mattermost.
  src/middlewared/middlewared/alert/service/mattermost.py
Labels: jira-low, backport-24.10.2

#15030 NAS-132712 / 24.10.2 / Fix alert text format for Mattermost. (by nicodemusjls)
  src/middlewared/middlewared/alert/service/mattermost.py
Labels: backport-24.10.1

#15043 NAS-132742 / 25.04 / fix key collision in zpool.status
  src/middlewared/middlewared/plugins/zfs_/pool_status.py
  tests/api2/test_alert.py
  tests/api2/test_zpool_status.py
Labels: backport-24.10.1, backport-24.10.2

#15047 NAS-132742 / 24.10.1 / fix key collision in zpool.status (by yocalebo)
  src/middlewared/middlewared/plugins/zfs_/pool_status.py
  tests/api2/test_zpool_status.py
Labels: backport-24.10.2

#15041 NAS-132743 / 25.04 / Fix cloud backup tests
  src/middlewared/middlewared/api/base/types/base/string.py
  src/middlewared/middlewared/api/v25_04_0/cloud_backup.py
  src/middlewared/middlewared/pytest/unit/api/base/types/test_base.py
  tests/api2/test_account_privilege_role_private_fields.py
Labels: jira

#14977 NAS-132604 / 25.04 / Add support for ipv6 in docker plugin
  src/middlewared/middlewared/alembic/versions/25.04/2024-11-15_12-14_docker_ipv6_support.py
  src/middlewared/middlewared/api/v25_04_0/docker.py
  src/middlewared/middlewared/etc_files/docker/daemon.json.py
  src/middlewared/middlewared/plugins/apps/ix_apps/portals.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/docker/validation_utils.py
  src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_address_pools_validtaion.py
  src/middlewared/middlewared/test/integration/assets/docker.py
  tests/api2/test_docker_setup.py
Labels: jira

#15046 NAS-132752 / 25.04 / Refactor out zvol create function and include wait_zvol check
  tests/api2/assets/websocket/pool.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_262_iscsi_alua.py
  tests/api2/test_fibre_channel.py
Labels: jira-low

#15050 NAS-132764 / 25.04 / Make sure there aren't pending interface changes
  src/middlewared/middlewared/plugins/virt/instance_device.py
Labels: jira-low

#15052 NAS-132769 / 25.04 / Fix `NOTICE: s3: s3 provider "" not known - please set correctly` als…
  src/middlewared/middlewared/rclone/remote/s3.py
  src/middlewared/middlewared/rclone/remote/storjix.py
Labels: jira, backport-24.10.1, backport-24.10.2

#15056 NAS-132775 / 24.10.2 / `docker.nvidia_present`
  src/middlewared/middlewared/plugins/docker/update.py
Labels: backport-24.10.1

#15055 NAS-132775 / 25.04 / `docker.nvidia_present`
  src/middlewared/middlewared/api/v25_04_0/docker.py
  src/middlewared/middlewared/plugins/docker/update.py
Labels: jira
