Repository truenas/middleware, pull requests merged in 2024-06, with the labels that each got.

#13824 NAS-129341 / 24.10 / Change scope of unprivileged_user_fixture fixture to module
  src/middlewared/middlewared/test/integration/assets/roles.py
Labels: backport-24.04.2, jira-low

#13828 NAS-129355 / 24.10 / Fix dhparam permissions
  src/middlewared/middlewared/plugins/crypto_/dhparams.py
Labels: jira

#13827 NAS-129354 / 24.10 / Make sure vendor key exists before trying string operation
  src/middlewared/middlewared/common/smart/smartctl.py
Labels: jira

#13829 NAS-129332 / 24.10 / Set rclone logging to trace
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-24.04.2

#13831 NAS-129370 / 24.10 / Minor logical fix in enclosure_class._get_model_and_controller
  src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Labels: jira, backport-24.04.2

#13842 NAS-129408 / 24.10 / add missing log statement when importing pool
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: jira, jira-low

#13843 NAS-129414 / 24.10 / fix makefile
  src/middlewared/Makefile
Labels: jira, jira-low

#13845 NAS-129423 / 24.10 / Fix tests
  src/middlewared/Makefile
Labels: jira

#13846 NAS-129429 / 24.10 / fix docstring for disk.get_unused
  src/middlewared/middlewared/plugins/disk_/availability.py
Labels: jira, jira-low

#13847 NAS-129433 / 24.10 / Fix `python.rst` doc
  docs/source/os/python.rst
Labels: jira, jira-low

#13844 NAS-128872 / 24.10 / When deleting a target attempt to cleanup associated initiator
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: backport-24.04.2

#13851 NAS-129442 / 24.10 / Update python-truenas-requirements doc
  docs/source/os/python.rst
Labels: jira

#13848 NAS-129436 / 24.10 / remove dead code
  src/freenas/etc/default/locale
  src/freenas/usr/bin/install-dev-tools
  src/middlewared/debian/control
  src/middlewared/middlewared/locale/messages.pot
  src/middlewared/middlewared/locale/ru/LC_MESSAGES/middlewared.po
  src/middlewared/setup.py
Labels: jira, jira-low

#13853 NAS-129457 / 24.10 / Update iSCSI test to take account of initiator autodelete
  tests/api2/test_iscsi_auth_network.py
Labels: jira

#13854 NAS-129458 / 24.10 / Fix syslog tests
  src/middlewared/middlewared/main.py
  tests/api2/test_475_syslog.py
Labels: jira

#13857 NAS-129466 / 24.10 / Fix failing tests because of apps removal
  src/middlewared/middlewared/apidocs/templates/websocket/events.md
  src/middlewared/middlewared/apidocs/templates/websocket/query.md
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
  src/middlewared/middlewared/pytest/unit/plugins/test_port_attachments.py
  src/middlewared/middlewared/test/integration/assets/apps.py
Labels: jira

#13856 NAS-129464 / 24.10 / call truenas.is_ix_hardware
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
  src/middlewared/middlewared/pytest/unit/plugins/enclosure/test_enclosure2_query.py
Labels: jira, jira-low

#13855 NAS-129459 / 24.10 / Adjust netdata db size after k8s removal
  src/middlewared/middlewared/plugins/reporting/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
Labels: jira

#13861 NAS-129471 / 24.10 / add mini slot tracking to new enclosure
  src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Labels: jira, jira-low

#13858 NAS-129469 / 24.10 / Improve python-truenas-requirements doc
  docs/source/os/python.rst
Labels: jira

#13867 NAS-129532 / 24.10 / Add generators for pwd and grp
  src/middlewared/middlewared/pytest/unit/utils/test_nss.py
  src/middlewared/middlewared/utils/nss/grp.py
  src/middlewared/middlewared/utils/nss/pwd.py
Labels: jira

#13868 NAS-128598 / 24.10 / Add IANA Enterprise numbers file to truenas-files
  src/freenas/debian/rules
Labels: backport-24.04.2

#13866 NAS-129531 / 24.10 / Break large winbind requests into smaller chunks
  src/middlewared/middlewared/plugins/idmap_/utils.py
  src/middlewared/middlewared/utils/itertools.py
Labels: backport-24.04.2, jira-high

#13871 NAS-129470 / 24.10 / Restart idmap service after SMB has been configured
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: backport-24.04.2

#13874 NAS-129560 / 24.10 / Add more user-friendly error message on NSS wrapper fn
  src/middlewared/middlewared/plugins/account.py
Labels: backport-24.04.2, jira-medium

#13875 NAS-129561 / 24.10 / Fix get_instance usage for catalog service
  src/middlewared/middlewared/plugins/catalog/update.py
Labels: jira

#13873 NAS-129559 / 24.10 / Replace int(x/y) pattern with x // y
  src/freenas/usr/local/bin/snmp-agent.py
  src/middlewared/middlewared/etc_files/nfs.conf.d/local.conf.mako
  src/middlewared/middlewared/plugins/boot_/format.py
  src/middlewared/middlewared/plugins/disk_/power_management_linux.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/jbof/crud.py
  src/middlewared/middlewared/plugins/smart_/event_source.py
  src/middlewared/middlewared/service/core_service.py
  tests/api2/test_200_ftp.py
  tests/api2/test_disk_wipe.py
  tests/api2/test_snapshots.py
Labels: jira

#13879 NAS-129569 / 24.10 / Add missing str() in is_in_use_by_portals_targets
  src/middlewared/middlewared/plugins/iscsi_/auth.py
Labels: backport-24.04.2

#13860 NAS-129384 / 24.10 / Fix netdata spamming logs
  src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
  src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
Labels: backport-24.04.2

#13877 NAS-129576 / 24.10 / Add ability to manage docker state
  debian/debian/control
  src/freenas/usr/lib/systemd/system-preset/10-truenas.preset
  src/middlewared/middlewared/etc_files/docker.py
  src/middlewared/middlewared/plugins/catalog/git_utils.py
  src/middlewared/middlewared/plugins/catalog/sync.py
  src/middlewared/middlewared/plugins/catalog/update.py
  src/middlewared/middlewared/plugins/docker/state_management.py
  src/middlewared/middlewared/plugins/docker/state_setup.py
  src/middlewared/middlewared/plugins/docker/state_utils.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/docker.py
Labels: jira

#13886 NAS-129610 / 24.10 / Fix typos related to directory services
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira, backport-24.04.2

#13888 NAS-129619 / 24.10 / Fix docker etc file
  src/middlewared/middlewared/etc_files/docker/daemon.json.py
  src/middlewared/middlewared/plugins/etc.py
Labels: jira

#13889 NAS-129541 / 24.10 / only query UP ifaces in virtual ip plugin
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: backport-24.04.2

#13883 NAS-129488 / 24.10 / Do not cloud sync `ix-applications` directory
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-24.04.2

#13865 NAS-129515 / 24.04.3 / Robustize ALUA
  src/freenas/usr/local/bin/scst_util.sh
  src/middlewared/middlewared/plugins/dlm.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/iscsi_/alua.py
  src/middlewared/middlewared/plugins/iscsi_/scst.py
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: backport-24.04.2, backport-24.10, jira-high

#13884 NAS-129384 / 24.04.3 / Fix netdata spamming logs (by Qubad786)
  src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
  src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
Labels: backport-24.04.2

#13903 NAS-129677 / 24.10 / Remove unnecessary dumping of args
  src/middlewared/middlewared/main.py
Labels: jira

#13823 NAS-129661 / 24.10 / Add basic FreeIPA connection control script
  src/freenas/usr/local/libexec/ipa_ctl.py
  src/middlewared/middlewared/utils/directoryservices/ipactl_constants.py
Labels: jira

#13901 NAS-129675 / 24.10 / Avoid forking for basic krb5 ticket checks
  src/middlewared/debian/control
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/pytest/unit/utils/test_krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
Labels: jira

#13900 NAS-127142 / 24.10 / Strengthen security and clean-up unused methods
  src/freenas/etc/find_alias_for_smtplib.py
  src/freenas/usr/local/libexec/nas/post-install
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/etc_files/local/proftpd.py
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/ec2.py
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/system/info.py
  src/middlewared/middlewared/plugins/system/product.py
Labels: backport-24.04.3

#13909 NAS-129481 / 24.10 / dont hang shutdown for vms that arent started
  src/middlewared/middlewared/plugins/vm/lifecycle.py
Labels: backport-24.04.3

#13898 NAS-129663 / 24.10 / Use SSS to perform SID conversion when enabled
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/constants.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/activedirectory_/health.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/idmap_/gencache.py
  src/middlewared/middlewared/plugins/idmap_/idmap_constants.py
  src/middlewared/middlewared/plugins/idmap_/idmap_sss.py
  src/middlewared/middlewared/plugins/idmap_/idmap_winbind.py
  src/middlewared/middlewared/plugins/idmap_/utils.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/utils/directoryservices/constants.py
  tests/api2/test_011_user.py
  tests/api2/test_030_activedirectory.py
Labels: jira

#13902 NAS-129676 / 24.10 / Regenerate nsswitch.conf as-needed
  src/middlewared/middlewared/etc_files/nsswitch.conf.mako
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/ldap.py
Labels: jira

#13914 NAS-129693 / 24.10 / Change audit dataset quota setting from 'refquota' to 'quota'
  src/middlewared/middlewared/plugins/audit/audit.py
Labels: backport-24.04.3, backport-24.04.2, jira-high

#13918 NAS-129588 / 24.10 / Properly reference event name when subscribing to event sources
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/reporting/processes.py
Labels: backport-24.04.3

#13907 NAS-129688 / 24.10 / Do not use ps for determining upsmon service status
  src/freenas/usr/lib/netdata/charts.d/nut_ups.chart.sh
Labels: jira

#13917 NAS-129695 / 24.10 / Change download method from call to call_with_audit.
  src/middlewared/middlewared/service/core_service.py
Labels: jira-medium

#13923 NAS-129719 / 24.10 / Replace hard-coded defaults with values from the audit/utils.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
  tests/api2/test_audit_basic.py
Labels: jira-medium

#13904 NAS-129683 / 24.10 / Improve kerberos credential handling
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/pytest/unit/utils/test_krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5_error.py
  tests/api2/test_032_ad_kerberos.py
Labels: jira

#13926 NAS-129735 / 24.10 / Force directory service cache insertion on share ACL read
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira, backport-24.04.3

#13928 NAS-129740 / 24.10 / Add tests for SMB client encryption
  tests/api2/test_smb_encryption.py
  tests/protocols/smb_proto.py
Labels: jira

#13932 NAS-129712 / 24.10 / Do not attempt to cleanup None initiator
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: backport-24.04.3

#13931 NAS-129751 / 24.10 / Fix audit export test
  src/middlewared/middlewared/service/core_service.py
Labels: jira

#13935 NAS-129758 / 24.10 / Try to use persistent connection for CI tests
  src/middlewared/middlewared/test/integration/utils/call.py
  src/middlewared/middlewared/test/integration/utils/client.py
  tests/conftest.py
Labels: jira

#13934 NAS-129752 / 24.10 / Fix log spam related to kerberos ticket renewal
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira

#13938 NAS-129756 / 24.04.3 / Do not spam logs with alert formatting errors
  src/middlewared/middlewared/alert/base.py
Labels: backport-24.04.2, backport-24.10

#13924 NAS-129734 / 24.10 / Prepare directory services cache for IPA changes
  src/middlewared/middlewared/etc_files/cron.d/middlewared.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/activedirectory_/cache.py
  src/middlewared/middlewared/plugins/directoryservices.py
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/directoryservices_/secrets.py
  src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/idmap_/gencache.py
  src/middlewared/middlewared/plugins/idmap_/idmap_constants.py
  src/middlewared/middlewared/plugins/ldap.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/sharesec.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/tdb/__init__.py
  src/middlewared/middlewared/plugins/tdb/base.py
  src/middlewared/middlewared/plugins/tdb/connection.py
  src/middlewared/middlewared/plugins/tdb/utils.py
  src/middlewared/middlewared/plugins/tdb/wrapper.py
  src/middlewared/middlewared/plugins/zfs_/dataset.py
  src/middlewared/middlewared/plugins/zfs_/snapshot.py
  src/middlewared/middlewared/plugins/zfs_/utils.py
  src/middlewared/middlewared/pytest/unit/utils/test_tdb.py
  src/middlewared/middlewared/utils/directoryservices/constants.py
  src/middlewared/middlewared/utils/tdb.py
  tests/api2/test_040_ad_user_group_cache.py
  tests/api2/test_account_idmap.py
Labels: jira

#13937 NAS-129763 / 24.10 / Expose ability for users to configure SMB encryption behavior
  src/middlewared/middlewared/alembic/versions/24.10/2024-06-26_19-44_add_smb_encryption.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/constants.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/pytest/unit/plugins/test_smb.py
  tests/api2/test_smb_encryption.py
Labels: jira

#13946 NAS-129792 / 24.10 / Add settle delay after snmp start
  tests/api2/test_snmp_agent.py
Labels: jira-low

#13947 NAS-129793 / 24.10 / Create tdb directories if needed
  src/middlewared/middlewared/utils/tdb.py
Labels: jira

#13949 NAS-129533 / 24.10 / Tune ARC memory pressure parameters
  src/freenas/usr/lib/modprobe.d/truenas.conf
Labels: backport-24.04.3, backport-24.04.2

#13943 NAS-129782 / 24.10 / Add auditing of audit ops
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/audit/utils.py
  tests/api2/test_audit_audit.py
  tests/api2/test_audit_basic.py
Labels: jira

#13945 NAS-129750 / 24.10 / fix scrambing start sector of data partitions in pool.expand
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/disk_/disk_info.py
Labels: backport-24.04.3, backport-24.04.2

#13954 NAS-129802 / 24.10 / Make target_login_test_linux more robust by increasing retries
  src/middlewared/middlewared/test/integration/assets/iscsi.py
Labels: jira-low
