Repository truenas/middleware, pull requests merged in 2024-03, with the labels that each got.

#13271 NAS-127627 / 24.10 / Try to use sql filters in audit.query calls
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/audit/backend.py
  src/middlewared/middlewared/plugins/audit/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/audit/test_audit_utils.py
  src/middlewared/middlewared/sqlalchemy.py
Labels: jira, backport-24.04.0

#13263 NAS-127612 / 24.10 / Remove unnecessary keys in webui.enclosure.dashboard endpoint
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/webui/enclosure.py
Labels: jira

#13278 NAS-127637 / 24.10 / Fix disk temperature logs not being retrieved when smartd interval is changed
  src/freenas/usr/lib/netdata/conf.d/python.d/smart_log.conf
  src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
  src/middlewared/middlewared/etc_files/netdata/python.d/smart_log.conf.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/service_/services/smartd.py
Labels: jira, backport-24.04.0, backport-23.10.3

#13283 NAS-127671 / 24.10 / Fix error message for errors umounting sysdataset
  src/middlewared/middlewared/plugins/pool_/dataset_processes.py
  src/middlewared/middlewared/plugins/sysdataset.py
  tests/api2/test_pool_dataset_track_processes.py
Labels: jira, backport-24.04.0

#13287 NAS-127707 / 24.10 / Fix typo in memory error alert
  src/middlewared/middlewared/alert/source/memory_errors.py
Labels: jira

#13292 NAS-127724 / 24.10 / Try much harder to not break the system dataset
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira, backport-24.04.0

#13293 NAS-127710 / 24.10 / Apply share_type preset prior to validation
  src/middlewared/middlewared/plugins/pool_/dataset.py
  tests/api2/test_340_pool_dataset.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13289 NAS-127697 / 24.10 / Allow RDMA capable interfaces to be exposed for regular networking
  src/middlewared/middlewared/plugins/interface/configure.py
  src/middlewared/middlewared/plugins/rdma/interface/crud.py
  src/middlewared/middlewared/plugins/rdma/rdma.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13303 NAS-127772 / 24.10 / Remove reference to AD kerberos principal
  src/middlewared/middlewared/plugins/kerberos.py
Labels: jira, backport-24.04.0

#13307 NAS-127776 / 24.10 / Do not spam HA logs with `OSError: [Errno 22] Invalid argument` on F-…
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira, backport-24.04.0

#13306 NAS-127685 / 24.10 / Fix schema for tunable
  src/middlewared/middlewared/plugins/tunables.py
Labels: backport-24.04.0

#13301 NAS-127766 / 24.10 / Add roles for system.* services
  src/middlewared/middlewared/plugins/system_advanced/config.py
  src/middlewared/middlewared/plugins/system_advanced/gpu.py
  src/middlewared/middlewared/plugins/system_general/ui.py
  src/middlewared/middlewared/plugins/system_general/update.py
  src/middlewared/middlewared/role.py
  tests/api2/test_system_settings_roles.py
Labels: jira, backport-24.04.0

#13313 NAS-127695 / 24.10 / Disable http2 for Storj as they recommend
  src/middlewared/middlewared/rclone/remote/storjix.py
Labels: backport-24.04.0

#13314 NAS-127795 / 24.10 / Fix cloud sync schema
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: backport-24.04.0

#13317 NAS-127807 / 24.10 / Add vrrp_sync_group when both IPv4 and IPv6 virtual addresses are pre…
  src/middlewared/middlewared/etc_files/keepalived.conf.mako
Labels: jira, backport-24.04-RC.1, backport-24.04.0

#13321 NAS-127812 / 24.10 / Fix es24n disk mapping
  src/middlewared/middlewared/plugins/enclosure_/jbof_enclosures.py
  src/middlewared/middlewared/plugins/jbof/functions.py
Labels: jira, backport-24.04.0

#13323 NAS-127813 / 24.10 / Fix iscsi.portal.listen_ip_choices
  src/middlewared/middlewared/plugins/iscsi_/portal.py
Labels: jira, backport-24.04.0

#13329 NAS-127803 / 24.10 / Add optional force parameter to jbof.delete API
  src/middlewared/middlewared/plugins/jbof/crud.py
Labels: backport-24.04.0

#13333 NAS-127851 / 24.10 / Update flush_chain_INPUT to flush both ip4 and ip6 tables
  src/middlewared/middlewared/plugins/failover_/nftables.py
Labels: jira, backport-24.04.0

#13331 NAS-127839 / 24.10 / Flush buffers in `disk.wipe`
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-24.04.0

#13336 NAS-127853 / 24.10 / Handle `WebSocketConnectionClosedException` in `Client._send`
  src/middlewared/middlewared/client/client.py
Labels: jira, backport-24.04-RC.1, backport-24.04.0

#13335 NAS-127839 / 24.04.0 / Flush buffers in `disk.wipe` (by themylogin)
  src/middlewared/middlewared/plugins/disk_/wipe.py
Labels: backport-24.04-RC.1

#13332 NAS-127850 / 24.10 / Check for properly setup system dataset before SMB configure
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-24.04.0

#13343 NAS-127852 / 24.10 / fix license alert for ES12
  src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13347 NAS-127863 / 24.10 / Display enclosures in a stable order
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
Labels: jira, backport-24.04-RC.1, backport-24.04.0

#13350 NAS-127863 / 24.10 / Always show head unit controller first
  src/middlewared/middlewared/plugins/enclosure.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
  src/middlewared/middlewared/pytest/unit/plugins/enclosure/test-cases/M60-WITH-12-ES102/expected.json
Labels: backport-24.04-RC.1, backport-24.04.0

#13341 NAS-127856 / 24.10 / Detect and save mgmt_ip2 if not supplied during jbof.create
  src/middlewared/middlewared/plugins/jbof/crud.py
  src/middlewared/middlewared/plugins/jbof/redfish/client.py
Labels: jira, backport-24.04.0

#13342 NAS-127771 / 24.10 / Fix `KeyError` in `rdma.get_link_choices`
  src/middlewared/middlewared/plugins/rdma/rdma.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13327 NAS-127836 / 24.10 / Enable Netdata Web
  debian/debian/control
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/logger.py
  src/middlewared/middlewared/plugins/reporting/netdata_web.py
  tests/api2/test_reporting_netdataweb.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13358 NAS-127872 / 24.10 / Do not repeat IPs in ISCSIPortalIPAlertSource.check
  src/middlewared/middlewared/alert/source/iscsi.py
Labels: jira

#13353 NAS-127868 / 24.10 / NAS-127868 - Hide Passwords for SPICE Viewer
  src/freenas/debian/preinst
  src/freenas/usr/share/spice-html5/spice-password-20240315.patch
  src/freenas/usr/share/spice-html5/spice.css
  src/freenas/usr/share/spice-html5/spice_auto.html
Labels: backport-24.04-RC.1, backport-24.04.0

#13362 NAS-127873 / 24.10 / Improve error messages for disable-rootfs-protection
  src/freenas/usr/local/libexec/disable-rootfs-protection
Labels: jira, backport-24.04.0

#13328 NAS-127840 / 24.10 / Add tests for boot pool configuration
  tests/api2/test_001_ssh.py
Labels: jira, backport-24.04.0

#13378 NAS-127903 / 13.3 / Fix build and runtime dependencies for middleware
  nas_ports/freenas/py-middlewared/Makefile
Labels: jira

#13380 NAS-127864 / 24.10 / Fix returns decorator for privilege.roles endpoint
  src/middlewared/middlewared/plugins/account_/privilege_roles.py
Labels: backport-24.04.0

#13355 NAS-127867 / 24.10 / Normalize root-level dataset properties on import
  src/middlewared/middlewared/plugins/pool_/import_pool.py
Labels: backport-24.04-RC.1, backport-24.04.0

#13385 NAS-127922 / 24.10 / Fix error handling for configuration upload
  src/middlewared/middlewared/plugins/service_/on_config_upload.py
Labels: jira, backport-24.04.0

#13250 NAS-127357 / 24.10 / Retrieve PCI slots in a new endpoint so that they are easily consumed by UI
  src/middlewared/middlewared/plugins/system_advanced/gpu.py
  src/middlewared/middlewared/pytest/unit/plugins/test_pci_ids_for_gpu_isolation.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py
Labels: backport-24.04.0

#13389 NAS-127933 / 13.3 / Fix LLDP plugin etc generate
  src/middlewared/middlewared/plugins/service_/services/lldp.py
Labels: jira

#13379 NAS-127905 / 24.10 / Add jbof.set_mgmt_ip API
  src/middlewared/middlewared/plugins/jbof/crud.py
  src/middlewared/middlewared/plugins/jbof/redfish/client.py
Labels: jira, backport-24.04.0

#13393 NAS-127947 / 24.10 / Handle misconfigured AD idmap backends better in acltemplate
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
Labels: jira, backport-24.04.0

#13391 NAS-127942 / 13.3 / Update wsdd configuration for version in Samba 4.19
  src/middlewared/middlewared/etc_files/local/wsdd.conf
Labels: jira

#13396 NAS-127956 / 24.10 / Silence some syslog DEBUG spam from passlib.utils.compat
  src/middlewared/middlewared/logger.py
Labels: jira, backport-24.04.0

#13398 NAS-127967 / 13.3 / Adjust ix.rc.d scripts for new rc.subr
  src/freenas/etc/ix.rc.d/ix-bsdloader
  src/freenas/etc/ix.rc.d/ix-chelsio
  src/freenas/etc/ix.rc.d/ix-etc
  src/freenas/etc/ix.rc.d/ix-kinit
  src/freenas/etc/ix.rc.d/ix-netif
  src/freenas/etc/ix.rc.d/ix-nfsbind
  src/freenas/etc/ix.rc.d/ix-nsswitch
  src/freenas/etc/ix.rc.d/ix-preinit
  src/freenas/etc/ix.rc.d/ix-savehostid
  src/freenas/etc/ix.rc.d/ix-sed
  src/freenas/etc/ix.rc.d/ix-shutdown
  src/freenas/etc/ix.rc.d/ix-syncdisks
  src/freenas/etc/ix.rc.d/ix-syncmultipaths
  src/freenas/etc/ix.rc.d/ix-update
  src/freenas/etc/ix.rc.d/ix-zfs
Labels: jira

#13399 NAS-127969 / 13.3 / Fail test run if pool not created
  tests/api2/test_008_pool.py
  tests/conftest.py
  tests/functions.py
Labels: jira

#13400 NAS-127973 / 13.3 / Expand situations in which 13.3 will terminate test runs
  tests/api2/test_001_ssh.py
  tests/api2/test_003_network.py
  tests/api2/test_007_systemdataset.py
  tests/api2/test_008_pool.py
Labels: jira

#13402 Additional RC script fixes
  src/freenas/etc/rc.d/ix-haready
  src/freenas/etc/rc.d/ix-postinit
  src/freenas/etc/rc.d/ix-update-scripts
Labels: jira

#13404 Do not require the system to be HA-capable for non-HA licenses
  src/middlewared/middlewared/plugins/system/product.py
Labels: backport-24.04.0

#13388 NAS-127927 / 24.10 / Expand SMB client testing
  src/middlewared/middlewared/test/integration/assets/smb.py
  tests/api2/test_425_smb_protocol.py
  tests/api2/test_smb_client.py
Labels: jira

#13047 NAS-127116 / 24.10 / Simplify filesystem plugin for ACLs
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl.py
  src/middlewared/middlewared/plugins/filesystem_/acl_base.py
  src/middlewared/middlewared/plugins/filesystem_/acl_template.py
  src/middlewared/middlewared/plugins/filesystem_/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/test_acl_inherit.py
Labels: jira

#13407 NAS-127975 / 24.10 / Fix cloud sync pre-/post-scripts
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_cloud_sync.py
  tests/api2/test_cloud_sync_config.py
  tests/api2/test_cloud_sync_custom_s3.py
  tests/api2/test_cloud_sync_script.py
  tests/api2/test_cloud_sync_storj.py
Labels: backport-24.04.0

#13410 NAS-127976 / 24.10 / Forbid access to cloud sync task scripts to non-FULL_ADMIN users
  src/middlewared/middlewared/plugins/cloud/crud.py
  src/middlewared/middlewared/plugins/cloud_backup/crud.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  src/middlewared/middlewared/role.py
  tests/api2/test_account_privilege_role_forbidden_fields.py
Labels: backport-24.04.0

#13408 NAS-127900 / 24.10 / Fix CPU temperature unit label
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Labels: backport-24.04.0

#13412 NAS-128021 / 13.3 / Fix collectd-daemon RC script
  src/freenas/usr/local/etc/rc.d/collectd-daemon
  tests/api2/test_007_systemdataset.py
Labels: jira

#13420 NAS-128040 / 24.10 / Fix aux parameter comment parsing in services->SMB
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/registry_global.py
  src/middlewared/middlewared/plugins/smb_/registry_share.py
  src/middlewared/middlewared/plugins/smb_/utils.py
  tests/api2/test_435_smb_registry.py
Labels: jira, backport-24.04.0

#13419 NAS-127978 / 24.10 / Allow NFS client to maintain file system processing across an HA failover
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/service_/services/all.py
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: backport-24.04.0

#13424 NAS-128058 / 13.3 / Set low winbind request timeout for standalone severs
  src/middlewared/middlewared/etc_files/local/smb4.conf
Labels: jira

#13425 NAS-128059 / 24.10 / fix HA API
  tests/api2/test_006_pool_and_sysds.py
Labels: jira, backport-24.04.0

#13431 NAS-128083 / 24.10 / Fix `vmware.update` breaking the entire system
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/vmware.py
Labels: jira, backport-24.04.0

#13430 NAS-128082 / 24.10 / Mark `test_client_job_callback` as flaky
  src/middlewared/middlewared/client/client.py
  tests/api2/test_client_job.py
Labels: jira, backport-24.04.0

#13428 NAS-128079 / 24.10 / Fix cloudsync `sync_onetime` test failure
  src/middlewared/middlewared/plugins/cloud_sync.py
Labels: jira, backport-24.04.0

#13429 NAS-128081 / 24.10 / Fix UI caching test
  tests/api2/test_ui_caching.py
Labels: jira, backport-24.04.0

#13406 NAS-127981 / 24.10 / Restrict changes to SMB aux parameters to FULL_ADMIN
  src/middlewared/middlewared/plugins/smb.py
  tests/api2/test_smb_share_crud_roles.py
Labels: jira, backport-24.04.0

#13437 NAS-128100 / 24.10 / Switch iSCSI tests from REST to websocket
  tests/api2/test_261_iscsi_cmd.py
Labels: jira
