Repository truenas/middleware, pull requests merged in 2025-01, with the labels that each got.

#15294 NAS-133337 / 25.04 / Silence CryptographyDeprecationWarning
  src/middlewared/middlewared/logger.py
Labels: jira

#15286 NAS-133326 / 25.04 / Add enterprise license check for virt plugin
  src/middlewared/middlewared/plugins/virt/global.py
  src/middlewared/middlewared/plugins/virt/instance.py
  src/middlewared/middlewared/plugins/virt/license.py
  src/middlewared/middlewared/pytest/unit/plugins/virt/test_virt_license.py
Labels: jira

#15297 NAS-133364 / 25.04 / Improve keytab validation
  src/middlewared/middlewared/plugins/kerberos.py
Labels: backport-24.10.2

#15301 NAS-133167 / 25.04 / Fix netbiosname validation logic if AD enabled
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-24.10.2

#15307 NAS-133388 / 25.04 / Avoid querying audit config early in middleware startup
  src/middlewared/middlewared/plugins/audit/backend.py
Labels: jira

#15308 NAS-133387 / 25.04 / Fix type for empty shares
  src/middlewared/middlewared/plugins/smb.py
Labels: jira

#15309 NAS-133391 / 25.04 / Convert iscsi.initiator.* to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_initiator.py
  src/middlewared/middlewared/plugins/iscsi_/initiator.py
  tests/api2/test_261_iscsi_cmd.py
Labels: jira

#15310 NAS-133396 / 25.04 / Fix regression in AD-related validation
  src/middlewared/middlewared/plugins/activedirectory.py
  src/middlewared/middlewared/plugins/smb.py
Labels: jira, backport-24.10.2

#15313 NAS-133398 / 25.04 / Dramatically speed up processing messages
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
  src/middlewared/middlewared/pytest/unit/api/base/server/ws_handler.py
Labels: jira-medium

#15314 NAS-133405 / 25.04 / Disable process pool
  src/middlewared/middlewared/plugins/zfs_/dataset.py
  src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
  src/middlewared/middlewared/plugins/zfs_/dataset_quota.py
  src/middlewared/middlewared/plugins/zfs_/disks.py
  src/middlewared/middlewared/plugins/zfs_/pool.py
  src/middlewared/middlewared/plugins/zfs_/pool_actions.py
  src/middlewared/middlewared/plugins/zfs_/pool_wait.py
  src/middlewared/middlewared/plugins/zfs_/snapshot.py
  src/middlewared/middlewared/plugins/zfs_/snapshot_actions.py
Labels: jira-low

#15317 NAS-133426 / 25.04 / Remove unused NFS setting: v4_owner_major
  src/middlewared/middlewared/alembic/versions/25.04/25.04-2025-01-06_17-16_remove-nfs-v4_owner_major.py
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: jira

#15318 NAS-133428 / 25.04 / Fixup name of migration file.
  src/middlewared/middlewared/alembic/versions/25.04/2025-01-06_17-16_remove-nfs-v4_owner_major.py
Labels: jira

#15323 NAS-133447 / 25.04 / remove use of samba's safe_tarfile mitigation
  src/middlewared/middlewared/plugins/config.py
Labels: jira-low

#15322 NAS-133414 / 25.04 / fix internal/front slots reporting for r30
  src/middlewared/middlewared/plugins/enclosure_/nvme2.py
Labels: backport-24.10.2

#15326 NAS-133451 / 25.04 / fix edge-case crashes in rpc.py
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
Labels: jira-low

#15321 NAS-133444 / 25.04 / Expose authenticator level in login_ex response
  src/middlewared/middlewared/api/v25_04_0/auth.py
  src/middlewared/middlewared/plugins/auth.py
  tests/api2/test_authenticator_assurance_level.py
Labels: jira

#15331 NAS-133381 / 25.04 / Fix uploaded database secret not being used when running migrations
  src/freenas/usr/local/sbin/migrate
  src/middlewared/middlewared/plugins/config.py
  src/middlewared/middlewared/plugins/mail.py
Labels: backport-24.10.2

#15340 NAS-133468 / 25.04 / Convert iscsi.portal.* to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_portal.py
  src/middlewared/middlewared/plugins/iscsi_/portal.py
  tests/api2/assets/websocket/iscsi.py
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_audit_iscsi.py
  tests/api2/test_iscsi_auth_network.py
Labels: jira

#15342 NAS-133474 / 25.04 / Fix authorization checks for subscriptions with args
  src/middlewared/middlewared/main.py
  tests/api2/test_account_privilege_role.py
Labels: jira

#15337 NAS-133465 / 25.04 / Add POOL_READ and POOL_WRITE roles
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/pool_/dedup.py
  src/middlewared/middlewared/plugins/pool_/expand.py
  src/middlewared/middlewared/plugins/pool_/export.py
  src/middlewared/middlewared/plugins/pool_/import_pool.py
  src/middlewared/middlewared/plugins/pool_/info.py
  src/middlewared/middlewared/plugins/pool_/pool.py
  src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py
  src/middlewared/middlewared/plugins/pool_/pool_operations.py
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
  src/middlewared/middlewared/plugins/pool_/resilver.py
  src/middlewared/middlewared/role.py
Labels: jira

#15339 NAS-133250 / 25.04 / fix loading nvidia kernel modules
  src/middlewared/middlewared/plugins/docker/update.py
Labels: backport-24.10.2

#15338 NAS-133466 / 25.04 / Add RBAC role for directory sevices status events
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: jira

#15344 NAS-133475 / 25.04 / add front_loaded key to r30
  src/middlewared/middlewared/plugins/enclosure_/nvme2.py
Labels: jira-medium, backport-24.10.2

#15348 NAS-133235 / 25.04 / Make recovery attempt when initializing directory services
  src/middlewared/middlewared/plugins/directoryservices.py
Labels: backport-24.10.2

#15327 NAS-133453 / 25.04 / Prevent users from generating auth tokens when STIG
  src/middlewared/middlewared/plugins/auth.py
  tests/api2/test_authenticator_assurance_level.py
Labels: jira

#15351 NAS-133489 / 25.04 / Revert "disable process pool (#15314)"
  src/middlewared/middlewared/plugins/zfs_/dataset.py
  src/middlewared/middlewared/plugins/zfs_/dataset_actions.py
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
  src/middlewared/middlewared/plugins/zfs_/dataset_quota.py
  src/middlewared/middlewared/plugins/zfs_/disks.py
  src/middlewared/middlewared/plugins/zfs_/pool.py
  src/middlewared/middlewared/plugins/zfs_/pool_actions.py
  src/middlewared/middlewared/plugins/zfs_/pool_wait.py
  src/middlewared/middlewared/plugins/zfs_/snapshot.py
  src/middlewared/middlewared/plugins/zfs_/snapshot_actions.py
Labels: jira-low

#15352 NAS-133490 / 25.04 / Do not require authorization for `core.subscribe` since it does its o…
  src/middlewared/middlewared/service/core_service.py
Labels: jira

#15353 NAS-133491 / 25.04 / Always add `MOCK` role when running tests
  src/middlewared/middlewared/plugins/test/mock.py
  tests/conftest.py
Labels: jira

#15354 NAS-133492 / 25.04 / Fix AWS S3 endpoint URL for restic
  src/middlewared/middlewared/plugins/cloud_backup/init.py
  src/middlewared/middlewared/rclone/remote/s3.py
Labels: jira, backport-24.10.2

#15356 NAS-133493 / 25.04 / fix unit test name
  src/middlewared/middlewared/pytest/unit/api/base/server/test_ws_handler.py
Labels: jira-low

#15358 NAS-133497 / 25.04 / fix test_ws_handler unit test
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
  src/middlewared/middlewared/pytest/unit/api/base/server/test_ws_handler.py
Labels: jira-low

#15360 NAS-132518 / 25.04 / fix SED disk unlock at boot
  debian/debian/ix-zfs.service
Labels: backport-24.10.2

#15347 NAS-133480 / 25.04 / Crash if public api_method does not have roles
  src/middlewared/middlewared/api/base/decorator.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/account_/builtin_administrator.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/boot_/environments.py
  src/middlewared/middlewared/plugins/cloud_backup/restore.py
  src/middlewared/middlewared/plugins/cloud_backup/snapshot.py
  src/middlewared/middlewared/plugins/cloud_backup/sync.py
  src/middlewared/middlewared/plugins/config.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure_label.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/plugins/pool_/scrub.py
  src/middlewared/middlewared/plugins/snapshot.py
  src/middlewared/middlewared/plugins/snapshot_/task_retention.py
  src/middlewared/middlewared/plugins/system/lifecycle.py
  src/middlewared/middlewared/plugins/truenas.py
  src/middlewared/middlewared/plugins/virt/volume.py
  src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py
  src/middlewared/middlewared/role.py
Labels: jira

#15365 NAS-133506 / 25.04 / move sed methods to sed.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira-low, backport-24.10.2

#15368 NAS-133508 / 25.04 / fix missing import in sed.py
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira-low, backport-24.10.2

#15371 NAS-133510 / 25.04 / Improve error message when an app fails to install
  src/middlewared/middlewared/plugins/apps/compose_utils.py
Labels: jira-low, backport-24.10.2

#15334 NAS-133462 / 25.04 / Clean-up no_auth_required decorator usage
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
  src/middlewared/middlewared/plugins/system_advanced/config.py
  src/middlewared/middlewared/plugins/truenas.py
  tests/api2/test_events.py
Labels: jira-medium

#15374 NAS-133519 / 25.04 / require role_prefix for public CRUD / Config services
  src/middlewared/middlewared/plugins/acme_protocol.py
  src/middlewared/middlewared/plugins/auth_/2fa.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  src/middlewared/middlewared/plugins/ipmi_/lan.py
  src/middlewared/middlewared/plugins/mail.py
  src/middlewared/middlewared/plugins/network_/global_config.py
  src/middlewared/middlewared/plugins/network_/static_routes.py
  src/middlewared/middlewared/plugins/ntp.py
  src/middlewared/middlewared/plugins/pool_/user_props.py
  src/middlewared/middlewared/plugins/rsync.py
  src/middlewared/middlewared/plugins/smart.py
  src/middlewared/middlewared/plugins/snmp.py
  src/middlewared/middlewared/plugins/ssh.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/tunables.py
  src/middlewared/middlewared/plugins/ups.py
  src/middlewared/middlewared/plugins/vmware.py
  src/middlewared/middlewared/role.py
  src/middlewared/middlewared/service/config_service.py
  src/middlewared/middlewared/service/crud_service.py
Labels: jira

#15379 NAS-133534 / 25.04 / update debian/copyright and LICENSE.IX
  LICENSE.IX
  debian/debian/copyright
Labels: jira-low

#15269 NAS-133258 / 25.04 / Add auditd systemd unit override
  src/freenas/etc/systemd/system/auditd.service.d/override.conf
Labels: jira

#15381 NAS-133536 / 25.04 / Add iSER to rdma.capable_protocols
  src/middlewared/middlewared/api/v25_04_0/rdma.py
  src/middlewared/middlewared/plugins/rdma/constants.py
  src/middlewared/middlewared/plugins/rdma/rdma.py
Labels: jira

#15395 NAS-133573 / 25.04 / Deinfe role for TNC config events
  src/middlewared/middlewared/plugins/truenas_connect/update.py
Labels: jira

#15396 NAS-133576 / 25.04 / Convert webui.enclosure.dashboard to api_method
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/webui_enclosure.py
  src/middlewared/middlewared/plugins/webui/enclosure.py
Labels: jira-low

#15399 NAS-133583 / 25.04 / Convert webui.main.dashboard.sys_info to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/webui_main_dashboard.py
  src/middlewared/middlewared/plugins/webui/main_dashboard.py
Labels: jira-low

#15400 NAS-133584 / 25.04 / Allow bootstrapping virt VM with zvol
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
  tests/api2/test_virt_vm.py
Labels: jira

#15357 NAS-133496 / 25.04 / Generate audit trail for when middleware session changes cred
  src/middlewared/middlewared/plugins/auth.py
Labels: jira

#15404 NAS-133588 / 25.04 / Exclude SYSTEM audit db from generic audit.query
  src/middlewared/middlewared/plugins/audit/audit.py
Labels: jira

#15315 NAS-133594 / 25.04 / feat: add digitalocean ACME Authenticator
  src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/digitalocean.py
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/factory.py
Labels: jira

#15407 NAS-133595 / 25.04 / Fix `MSG_SIZE_EXTENDED_METHODS`
  src/middlewared/middlewared/utils/limits.py
Labels: jira

#15408 NAS-133597 / 25.04 / Fix out `HttpUrl` being overwrittn by `import *` from files that do not define `__all__`
  src/middlewared/middlewared/api/base/types/urls.py
  src/middlewared/middlewared/api/base/validators.py
Labels: jira

#15409 NAS-133602 / 24.10.2 / self.query -> self.middleware.call('disk.query')
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira-high

#15403 NAS-133587 / 25.04 / Use system generated cert after TNC has been revoked
  src/middlewared/middlewared/plugins/truenas_connect/update.py
Labels: jira

#15410 NAS-133603 / 25.04 / fix type annotation for dashboard.sys_info
  src/middlewared/middlewared/api/v25_04_0/webui_main_dashboard.py
Labels: jira-low

#15412 NAS-133608 / 25.04 / Fix star import in account.py
  src/middlewared/middlewared/plugins/account.py
Labels: jira-low

#15411 NAS-133606 / 25.04 / convert cert/csr profiles to new api
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/crypto_cert_profiles.py
  src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
  src/middlewared/middlewared/plugins/truenas_connect/cert_utils.py
  src/middlewared/middlewared/plugins/webui/crypto.py
Labels: jira-low

#15417 NAS-133619 / 25.04 / Convert ca_profiles.py to new api
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/crypto_ca_profiles.py
  src/middlewared/middlewared/api/v25_04_0/crypto_cert_profiles.py
  src/middlewared/middlewared/plugins/crypto_/ca_profiles.py
  src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
  src/middlewared/middlewared/plugins/webui/crypto.py
Labels: jira-low

#15419 NAS-133626 / 25.04 / Prevent enabling TrueNAS connect while in STIG mode
  src/middlewared/middlewared/role.py
Labels: jira

#15402 NAS-133586 / 25.04 / Fix domain join in Samba 4.21
  src/middlewared/middlewared/etc_files/krb5.keytab.py
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
  src/middlewared/middlewared/plugins/kerberos.py
  src/middlewared/middlewared/plugins/smb_/constants.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
  src/middlewared/middlewared/utils/directoryservices/krb5_constants.py
Labels: jira

#15426 NAS-133637 / 25.04 / Add role manage sanity check and tests
  src/middlewared/middlewared/role.py
  tests/unit/test_role_manager.py
Labels: jira

#15424 NAS-133636 / 25.04 / Add unit test for concatenating keytabs
  tests/unit/test_krb5.py
Labels: jira

#15427 NAS-133638 / 25.04 / Add unit test for role_manager FULL_ADMIN allowlist
  src/middlewared/middlewared/plugins/account_/privilege_roles.py
  src/middlewared/middlewared/plugins/cron.py
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  tests/unit/test_role_manager.py
Labels: jira

#15429 NAS-133641 / 25.04 / Convert iscsi.global.* to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
  src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
  src/middlewared/middlewared/plugins/iscsi_/status.py
Labels: jira

#15428 NAS-133640 / 25.04 / Use ALLOW_LIST_FULL_ADMIN where practical
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/role.py
  src/middlewared/middlewared/utils/allowlist.py
  src/middlewared/middlewared/utils/privilege.py
  src/middlewared/middlewared/utils/privilege_constants.py
Labels: jira

#15433 NAS-133661 / 25.04 / simplify country_choices endpoints
  src/middlewared/middlewared/plugins/crypto_/cert_info.py
  src/middlewared/middlewared/plugins/system_general/country.py
  src/middlewared/middlewared/utils/country_codes.py
Labels: jira-low

#15438 NAS-133667 / 25.04 / Add docs to fields of cloud_backup endpoints
  src/middlewared/middlewared/api/v25_04_0/cloud_backup.py
  src/middlewared/middlewared/api/v25_04_0/common.py
  src/middlewared/middlewared/plugins/cloud_backup/crud.py
  src/middlewared/middlewared/plugins/cloud_backup/sync.py
Labels: jira

#15430 NAS-133651 / 25.04 / Reduce situations in which hard-coded root privilege returned
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/utils/auth.py
  src/middlewared/middlewared/utils/origin.py
  tests/unit/test_stig.py
Labels: jira

#15444 NAS-133681 / 25.04 / Revert "Only retrieve aggregated CPU temperature"
  src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
  src/middlewared/middlewared/plugins/reporting/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
Labels: jira

#15440 NAS-133670 / 25.04 / Convert cert related choices to use new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/crypto_cert_info.py
  src/middlewared/middlewared/plugins/crypto_/cert_info.py
  src/middlewared/middlewared/plugins/system_general/country.py
Labels: jira-low

#15449 NAS-133689 / 25.04 / remove dead endpoint (get_instance_by_name)
  src/middlewared/middlewared/plugins/pool_/pool.py
Labels: jira-low

#15448 NAS-133688 / 25.04 / convert snapshot_count.py to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/pool_snapshot_count.py
  src/middlewared/middlewared/plugins/pool_/snapshot_count.py
Labels: jira-low

#15447 NAS-133687 / 25.04 / remove dead endpoint (unlock_services_restart_choices)
  src/middlewared/middlewared/plugins/pool_/unlock.py
Labels: jira-low

#15443 NAS-133677 / 25.04 / Convert pool.dataset.details to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/pool_dataset_details.py
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: jira-low

#15446 NAS-133686 / 25.04 / remove user_props.py plugin
  src/middlewared/middlewared/plugins/pool_/user_props.py
Labels: jira-low

#15450 NAS-133691 / 25.04 / Convert ipmi.is_loaded to new API
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/ipmi.py
  src/middlewared/middlewared/plugins/ipmi.py
Labels: jira-low

#15452 NAS-133703 / 25.04 / Raise ValidationError on perm change for readonly paths
  src/middlewared/middlewared/plugins/filesystem_/acl.py
Labels: jira

#15434 NAS-133616 / 25.04 / Introduce support for app config migrations
  src/middlewared/middlewared/plugins/apps/migration_utils.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
  src/middlewared/middlewared/pytest/unit/plugins/apps/test_migration_utils.py
  src/middlewared/middlewared/pytest/unit/plugins/apps/test_upgrade_values.py
Labels: pending QA

#15423 NAS-133635 / 25.04 / Fix nameserver validation logic
  src/middlewared/middlewared/plugins/network_/global_config.py
  src/middlewared/middlewared/utils/__init__.py
  tests/unit/test_are_indices_in_consecutive_order.py
Labels: jira-low, backport-24.10.2

#15459 NAS-133717 / 25.04 / Properly compare helm secrets version numbers
  src/middlewared/middlewared/plugins/kubernetes_to_docker/secrets_utils.py
Labels: jira

#15458 NAS-133716 / 25.04 / Skip /usr fs check when disabling protection if forced
  src/freenas/usr/local/libexec/disable-rootfs-protection
Labels: jira

#15461 NAS-133721 / 25.04 / Make onetime password more readable
  src/middlewared/middlewared/alert/source/api_key.py
  src/middlewared/middlewared/utils/auth.py
Labels: jira

#15464 NAS-133734 / 25.04 / Fix replication test
  tests/api2/test_replication.py
Labels: jira

#15467 NAS-133752 / 25.04 / Change default URI of docker registry
  src/middlewared/middlewared/api/v25_04_0/app_registry.py
Labels: jira

#15455 NAS-133709 / 25.04 / Do not import middleware API in ZFS process pool
  src/middlewared/middlewared/api/__init__.py
  src/middlewared/middlewared/api/base/types/urls.py
  src/middlewared/middlewared/api/current.py
  src/middlewared/middlewared/api/v25_04_0/api_key.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/datastore/connection.py
  src/middlewared/middlewared/plugins/datastore/read.py
  src/middlewared/middlewared/plugins/zettarepl.py
  src/middlewared/middlewared/pytest/unit/test_service_cli_descriptions.py
  src/middlewared/middlewared/service/__init__.py
  src/middlewared/middlewared/service/core_service.py
  src/middlewared/middlewared/service/crud_service.py
  src/middlewared/middlewared/service/decorators.py
  src/middlewared/middlewared/utils/__init__.py
  src/middlewared/middlewared/utils/allowlist.py
  src/middlewared/middlewared/utils/plugins.py
  src/middlewared/middlewared/worker.py
Labels: jira

#15468 NAS-133754 / 25.04 / Fix check for https in ConnectionOrigin
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
  src/middlewared/middlewared/utils/origin.py
Labels: jira-low

#15470 NAS-133759 / 25.04 / Add missing await in sed_unlock_all
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira-low

#15471 NAS-133761 / 25.04 / Include event handler name in error message
  src/middlewared/middlewared/main.py
Labels: jira

#15474 NAS-133766 / 25.04 / Improve validation for virt volumes
  src/middlewared/middlewared/plugins/virt/volume.py
Labels: jira

#15476 NAS-133770 / 25.04 / Fix typo in CA profile
  src/middlewared/middlewared/api/v25_04_0/crypto_ca_profiles.py
Labels: jira

#15479 NAS-133768 / 25.04 / Validate groups on user create/update
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/datastore/write.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
  tests/api2/test_account.py
Labels: backport-24.10.2

#15483 NAS-133778 / 25.04 / Make root device in virt instance to be configurable on creation
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: jira

#15477 NAS-133772 / 25.04 / Ignore cloud based images in virt plugin for VMs
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: jira

#15487 NAS-133334 / 25.10 / Only add wireguard address if wireguard interface is up
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-25.04-RC.1

#15490 NAS-133819 / 25.10 / Also increase `config.on_upload` timeout in `failover.sync_to_peer`
  src/middlewared/middlewared/plugins/failover.py
Labels: jira

#15482 NAS-133764 / 25.10 / Delete DB row for invalid tunables
  src/middlewared/middlewared/plugins/tunables.py
  tests/api2/test_tunables.py
Labels: backport-25.04

#15445 NAS-133683 / 25.04 / Refactor CPU reporting
  src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
  src/freenas/usr/lib/netdata/python.d/truenas_cpu_usage.chart.py
  src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
  src/middlewared/middlewared/plugins/reporting/realtime_reporting/cpu.py
  src/middlewared/middlewared/plugins/reporting/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_approximation.py
  src/middlewared/middlewared/pytest/unit/plugins/reporting/test_netdata_stats_func.py
  src/middlewared/middlewared/pytest/unit/utils/test_cpu_usage_util.py
  src/middlewared/middlewared/utils/metrics/cpu_usage.py
Labels: jira, backport-25.04-RC.1

#15485 NAS-133793 / 25.10 / Add roles configuration for RDMA
  src/middlewared/middlewared/plugins/rdma/interface/crud.py
  src/middlewared/middlewared/plugins/rdma/rdma.py
Labels: backport-25.04-RC.1

#15495 NAS-133834 / 25.10 / Ensure we populate node_name and parent_host for NPIV
  src/middlewared/middlewared/etc_files/scst.conf.mako
Labels: jira, backport-25.04-RC.1

#15478 NAS-132231 / 25.10 / Schema + documentation for API events
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/api/__init__.py
  src/middlewared/middlewared/api/base/__init__.py
  src/middlewared/middlewared/api/base/event.py
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/api/base/server/api.py
  src/middlewared/middlewared/api/base/server/doc.py
  src/middlewared/middlewared/api/base/server/event.py
  src/middlewared/middlewared/api/v25_04_0/alert.py
  src/middlewared/middlewared/event.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/service/base.py
  src/middlewared/middlewared/service/core_service.py
  src/middlewared/middlewared/service/crud_service.py
  src/middlewared/middlewared/service/service.py
  src/middlewared_docs/docs/index.rst
  src/middlewared_docs/generate_docs.py
Labels: backport-25.04-RC.1

#15500 NAS-133837 / 25.10 / add hypervisor info to usage
  src/middlewared/middlewared/plugins/usage.py
Labels: jira-low, backport-25.04-RC.1

#15503 NAS-133840 / 25.10 / Fix `get_event`
  src/middlewared/middlewared/event.py
Labels: jira, backport-25.04-RC.1

#15502 NAS-133839 / 25.10 / Improve file download and allow in STIG mode
  src/middlewared/middlewared/api/v25_04_0/auth.py
  src/middlewared/middlewared/apps/file_app.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/service/core_service.py
  src/middlewared/middlewared/webui_auth.py
  tests/api2/test_auth_token.py
Labels: jira-high, backport-25.04-RC.1

#15506 NAS-133842 / 25.10 / Fix `core.get_services`
  src/middlewared/middlewared/service/core_service.py
Labels: jira, backport-25.04-RC.1

#15508 NAS-133844 / 25.10 / validate download token generation
  src/middlewared/middlewared/plugins/auth.py
  tests/api2/test_auth_token.py
Labels: jira, backport-25.04-RC.1

#15472 NAS-133762 / 25.10 / Allow password change for OTPW sessions
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_password_reset.py
Labels: jira, backport-25.04-RC.1

#15512 NAS-133854 / 25.10 / Show root disk size of virt VMs
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: jira, backport-25.04-RC.1

#15513 NAS-133856 / 25.10 / Make sure app portal URI is properly normalized
  src/middlewared/middlewared/plugins/apps/ix_apps/query.py
Labels: jira, backport-25.04-RC.1

#15515 NAS-133859 / 25.10 / Make sure virt instance is not created if create call fails
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: jira, backport-25.04-RC.1

#15484 NAS-133788 / 25.10 / Turn off tagging when null is passed to `ipmi.lan.update.vlan`
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: jira, backport-25.04-RC.1

#15521 NAS-133862 / 25.10 / Prevent fcport.status exception when CORE config not migrated
  src/middlewared/middlewared/plugins/fcport.py
Labels: backport-25.04-RC.1

#15527 NAS-133885 / 25.10 / More Fibre Channel NPIV fixes
  src/middlewared/middlewared/etc_files/scst.conf.mako
  tests/api2/test_fibre_channel.py
Labels: jira, backport-25.04-RC.1

#15462 NAS-133728 / 25.10 / Add `NotRequired` default value to our API
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/pytest/unit/api/base/test_excluded.py
  src/middlewared/middlewared/pytest/unit/api/handler/result/test_alias.py
Labels: jira

#15529 NAS-133888 / 25.10 / Initial round of disk enumeration improvements
  src/middlewared/middlewared/utils/disks_/__init__.py
  src/middlewared/middlewared/utils/disks_/get_disks.py
  src/middlewared/middlewared/utils/disks_/private_utils.py
Labels: jira-low

#15533 NAS-133899 / 25.10 / Reduce number of 2FA public endpoints
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  tests/unit/test_role_manager.py
Labels: jira, backport-25.10

#15536 Fix `sed_unlock`
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira, backport-25.04-RC.1

#15542 NAS-133918 / 25.10 / fix usage plugin crash
  src/middlewared/middlewared/plugins/zfs_/utils.py
Labels: jira-low, backport-25.04-RC.1

#15543 NAS-133924 / 25.10 / fix usage reporting api test
  tests/api2/test_usage_reporting.py
Labels: jira-low, backport-25.04-RC.1

#15546 NAS-133928 / 25.10 / Fix test_usage_reporting
  tests/api2/test_usage_reporting.py
Labels: jira, backport-25.04-RC.1

#15548 NAS-132992 / 25.10 / Clean up SMB ACL API docs
  src/middlewared/middlewared/api/v25_04_0/smb.py
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-25.04-RC.1
