Repository truenas/middleware, pull requests merged in 2025-02, with the labels that each got.

#15551 NAS-133941 / 25.10 / Move filesystem access check functions outside of the filesystem plugin
  src/middlewared/middlewared/plugins/filesystem_/perm_check.py
  src/middlewared/middlewared/utils/filesystem/access.py
Labels: jira, backport-25.04-RC.1

#15532 NAS-133892 / 25.04-RC.1 / Unlock SED drives using disk `real_name` (by themylogin)
  src/middlewared/middlewared/plugins/disk.py
  src/middlewared/middlewared/plugins/disk_/sed.py
  src/middlewared/middlewared/utils/disks_/__init__.py
  src/middlewared/middlewared/utils/disks_/get_disks.py
  src/middlewared/middlewared/utils/disks_/private_utils.py
Labels: backport-25.10

#15555 NAS-133873 / 25.10 / Fix Outlook OAuth error about refresh token exceeding 1024 on save
  src/middlewared/middlewared/plugins/mail.py
Labels: backport-25.04-RC.1

#15498 NAS-133757 / 25.10 / Prevent crashes when `pwenc_secret` is missing
  src/middlewared/middlewared/plugins/pwenc.py
Labels: backport-25.04-RC.1

#15530 NAS-133959 / 25.10 / Add `secureboot` to image choices
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: backport-25.04-BETA.1, jira-low, backport-25.04-RC.1

#15562 NAS-133962 / 25.10 / Fix typo in crypto cert profiles
  src/middlewared/middlewared/api/v25_04_0/crypto_cert_profiles.py
Labels: jira, backport-25.04-BETA.1, backport-25.04-RC.1

#15520 NAS-133965 / 25.10 / fixes a typo in version checking for apps
  src/middlewared/middlewared/plugins/catalog/apps_util.py
  src/middlewared/middlewared/pytest/unit/plugins/catalog/test_min_max_scale_version_update.py
Labels: jira, backport-25.04-RC.1

#15525 NAS-133870 / 25.10 / Give proper error response to STIG auth
  src/middlewared/middlewared/plugins/auth.py
  tests/api2/test_authenticator_assurance_level.py
  tests/api2/test_stig.py
Labels: backport-25.04-RC.1

#15568 NAS-133971 / 25.10 / Fix typo in `parse_unlock_info`
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira, backport-25.04-RC.1

#15571 NAS-133973 / 25.10 / Remove samba dataset snapshot on upgrade
  src/middlewared/middlewared/plugins/update.py
Labels: backport-25.04-BETA.1, jira-low, backport-25.04-RC.1

#15570 NAS-133910 / 25.10 / Add schema handling for unmapped groups in privileges
  src/middlewared/middlewared/api/v25_04_0/privilege.py
  src/middlewared/middlewared/plugins/account_/privilege.py
Labels: backport-25.04-RC.1

#15572 NAS-133972 / 25.10 / Fix public view of version string
  src/middlewared/middlewared/plugins/support.py
  src/middlewared/middlewared/plugins/system/info.py
  src/middlewared/middlewared/plugins/webui/main_dashboard.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-25.04-BETA.1, jira-low, backport-25.04-RC.1

#15579 NAS-133989 / 25.10 / Failing to import removed symbol
  src/middlewared/middlewared/plugins/update.py
Labels: jira, backport-25.04-BETA.1, backport-25.04-RC.1

#15583 NAS-134001 / 25.10 / Sed unlock exitcode
  src/middlewared/middlewared/plugins/disk_/sed.py
Labels: jira, backport-25.04-RC.1

#15586 NAS-133848 / 25.10 / Read iSCSI session transport from kernel sys interface
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Labels: backport-25.04-RC.1

#15587 NAS-134005 / 25.10 / cache immutable type in get_country_codes
  src/middlewared/middlewared/plugins/crypto_/cert_info.py
  src/middlewared/middlewared/plugins/system_general/country.py
  src/middlewared/middlewared/utils/country_codes.py
Labels: jira-low, backport-25.04-RC.1

#15592 NAS-134016 / 25.10 / remove unused private plugin
  src/middlewared/middlewared/plugins/hardware/cpu.py
Labels: jira-low

#15591 NAS-133685 / 25.10 / Robustize complex ALUA tests
  src/middlewared/middlewared/test/integration/assets/hostkvm.py
  tests/api2/test_262_iscsi_alua.py
  tests/iscsi_target.py
Labels: backport-25.04-RC.1

#15593 NAS-134017 / 25.10 / change lan_channels cache to immutable type
  src/middlewared/middlewared/plugins/ipmi_/lan.py
Labels: jira-low

#15596 NAS-134020 / 25.10 / stop double-caching HA_MODE
  src/middlewared/middlewared/plugins/failover.py
Labels: jira-low

#15597 NAS-134026 / 25.10 / change timezone_choices cache to immutable type
  src/middlewared/middlewared/plugins/system_general/timezone.py
  src/middlewared/middlewared/utils/timezone_choices.py
Labels: jira-low

#15599 NAS-133449 / 25.10 / Fix system.security.update on HA
  src/middlewared/middlewared/plugins/security/update.py
Labels: backport-25.04-RC.1

#15585 NAS-133988 / 25.10 / Do not version private API methods
  src/middlewared/middlewared/api/base/decorator.py
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/acl.py
  src/middlewared/middlewared/api/v25_04_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_04_0/alert.py
  src/middlewared/middlewared/api/v25_04_0/filesystem.py
  src/middlewared/middlewared/api/v25_04_0/initshutdownscript.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_target.py
  src/middlewared/middlewared/api/v25_04_0/keychain.py
  src/middlewared/middlewared/api/v25_04_0/netdata.py
  src/middlewared/middlewared/api/v25_04_0/rdma.py
  src/middlewared/middlewared/api/v25_04_0/smb.py
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/api/v25_04_0/vendor.py
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/acl.py
  src/middlewared/middlewared/api/v25_10_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_10_0/alert.py
  src/middlewared/middlewared/api/v25_10_0/filesystem.py
  src/middlewared/middlewared/api/v25_10_0/initshutdownscript.py
  src/middlewared/middlewared/api/v25_10_0/iscsi_target.py
  src/middlewared/middlewared/api/v25_10_0/keychain.py
  src/middlewared/middlewared/api/v25_10_0/netdata.py
  src/middlewared/middlewared/api/v25_10_0/rdma.py
  src/middlewared/middlewared/api/v25_10_0/smb.py
  src/middlewared/middlewared/api/v25_10_0/user.py
  src/middlewared/middlewared/api/v25_10_0/vendor.py
  src/middlewared/middlewared/plugins/account_/2fa.py
  src/middlewared/middlewared/plugins/acme_protocol_/challenge.py
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/filesystem_/acl.py
  src/middlewared/middlewared/plugins/init_shutdown_script.py
  src/middlewared/middlewared/plugins/iscsi_/targets.py
  src/middlewared/middlewared/plugins/keychain.py
  src/middlewared/middlewared/plugins/rdma/rdma.py
  src/middlewared/middlewared/plugins/reporting/rest.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/system_vendor/vendor.py
Labels: backport-25.04-RC.1

#15606 NAS-134039 / 25.10 / Fix tests
  src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py
Labels: jira, backport-25.04-RC.1

#15604 NAS-134037 / 25.10 / Fix `NotRequired`
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/pytest/unit/api/base/test_excluded.py
Labels: jira

#15610 NAS-134063 / 25.10 / Add audit trail for k8s to docker migration
  src/middlewared/middlewared/plugins/kubernetes_to_docker/migrate.py
Labels: jira, backport-25.04-RC.1

#15463 NAS-133556 / 25.10 / Implement TNC Heartbeat service
  src/middlewared/middlewared/alembic/versions/25.04/2025-01-20_22-00_tnc_heartbeat.py
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/truenas_connect.py
  src/middlewared/middlewared/api/v25_04_0/tn_connect.py
  src/middlewared/middlewared/api/v25_10_0/tn_connect.py
  src/middlewared/middlewared/plugins/reporting/events.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/truenas_connect/acme.py
  src/middlewared/middlewared/plugins/truenas_connect/heartbeat.py
  src/middlewared/middlewared/plugins/truenas_connect/mixin.py
  src/middlewared/middlewared/plugins/truenas_connect/update.py
  src/middlewared/middlewared/plugins/truenas_connect/urls.py
  src/middlewared/middlewared/plugins/truenas_connect/utils.py
  src/middlewared/middlewared/utils/version.py
Labels: backport-25.04-RC.1

#15607 NAS-134040 / 25.10 / Display proper roles in the API doc (from the role manager)
  src/middlewared/middlewared/api/base/server/doc.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/role.py
Labels: jira, backport-25.04-RC.1

#15582 NAS-133996 / 25.10 / Send error when middleware response fails to serialize
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
Labels: jira, backport-25.04-RC.1

#15622 NAS-134073 / 25.10 / Remove redundant get_identifiers in cpu graph
  src/middlewared/middlewared/plugins/reporting/netdata/graphs.py
Labels: jira, backport-25.04-RC.1

#15612 NAS-133562 / 25.10 / Gather virt plugin metrics
  src/middlewared/middlewared/plugins/usage.py
  tests/api2/test_usage_reporting.py
Labels: backport-25.04-RC.1

#15617 NAS-133954 / 25.10 / Fix keychaincredentials schema errors
  src/middlewared/middlewared/api/v25_04_0/keychain.py
  src/middlewared/middlewared/api/v25_10_0/keychain.py
Labels: backport-25.04-RC.1

#15625 NAS-134060 / 25.10 / Use app registry credentials when retrieving dockerhub limit
  src/middlewared/middlewared/plugins/apps_images/client.py
  src/middlewared/middlewared/plugins/apps_images/dockerhub_ratelimit.py
Labels: backport-25.04-BETA.1, backport-25.04-RC.1

#15630 NAS-134078 / 25.10 / Fix virt VM test
  tests/api2/test_virt_vm.py
Labels: jira, backport-25.04-RC.1

#15620 NAS-134071 / 25.10 / add ht_map to CpuInfo
  src/middlewared/middlewared/utils/cpu.py
Labels: jira-low, backport-25.04-RC.1

#15626 NAS-133934 / 25.10 / Allow updating root disk size for virt VM instances
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/api/v25_10_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
  src/middlewared/middlewared/plugins/virt/utils.py
  tests/api2/test_virt_002_instance.py
Labels: backport-25.04-RC.1

#15621 NAS-133727 / 25.10 / Make CORS policy exception for internal URLs like TrueConnect
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-25.04-RC.1

#15639 NAS-134081 / 25.10 / rename stig api test file so it runs last
  tests/api2/test_zzzz_stig.py
Labels: jira-medium, backport-25.04-RC.1

#15638 NAS-134080 / 25.10 / Generate single-use API tokens for failover plugin
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/datastore.py
  src/middlewared/middlewared/restful.py
Labels: jira, backport-25.04-RC.1

#15643 NAS-134094 / 25.10 / fix hactl calling private methods
  src/freenas/usr/local/sbin/hactl
Labels: jira-low, backport-25.04-RC.1

#15647 NAS-134090 / 25.10 / Restrict CORS exception to registered TrueConnect hosts
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-25.04-RC.1

#15641 NAS-134082 / 25.10 / remove legacy vm tests
  tests/api2/test_541_vm.py
  tests/api2/test_vm_roles.py
Labels: jira-low, backport-25.04-RC.1

#15553 NAS-133945 / 25.10 / Make `run_with_user_context` crash if multiprocessing worker tries to import API
  src/middlewared/middlewared/plugins/filesystem_/perm_check.py
  src/middlewared/middlewared/utils/user_context.py
Labels: jira, backport-25.04-RC.1

#15511 NAS-133849 / 25.10 / Remove handling for POST requests for legacy TC
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: jira, backport-25.04-RC.1

#15654 NAS-134119 / 25.10 / Specify secure boot key in image choices
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
Labels: backport-25.04-RC.1

#15550 NAS-133930 / 25.10 / Clean-up device info plugin
  src/middlewared/middlewared/plugins/device.py
  src/middlewared/middlewared/plugins/device_/device_info.py
  src/middlewared/middlewared/plugins/ups.py
  src/middlewared/middlewared/pytest/unit/plugins/device/test_device_info.py
Labels: jira-low

#15656 NAS-134132 / 25.10 / Fix STIG API tests
  tests/api2/test_zzzz_stig.py
Labels: jira-low, backport-25.04-RC.1

#15661 NAS-134133 / 25.10 / Privatize certain failover endpoints
  src/middlewared/middlewared/plugins/failover.py
Labels: jira-low

#15660 NAS-134104 / 25.10 / Fix netmask being empty string
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/api/v25_10_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: backport-25.04-RC.1

#15650 NAS-134087 / 25.10 / Use a proper job id for download token test
  tests/api2/test_audit_websocket.py
Labels: backport-25.04-RC.1

#15514 NAS-133858 / 25.10 / Make sure CPU temperature is reported for virtual cores
  src/freenas/usr/lib/netdata/python.d/cputemp.chart.py
  src/middlewared/middlewared/utils/cpu.py
Labels: jira, backport-25.04-RC.1

#15669 NAS-134150 / 25.10 / fix typo in device.get_info
  src/middlewared/middlewared/plugins/device.py
Labels: jira-low

#15663 NAS-134140 / 25.10 / remove schema validation for private dataset_encryption endpoints
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
Labels: jira-low

#15668 NAS-134149 / 25.10 / remove unnecessary api test
  tests/api2/test_device_get_disk_names.py
Labels: jira-low

#15667 NAS-134148 / 25.10 / clarify ACME DNS-Authenticators cloudflare error message
  src/middlewared/middlewared/plugins/acme_protocol_/authenticators/cloudflare.py
Labels: jira

#15651 NAS-131853 / 25.10 / Remove unused API endpoints
  src/middlewared/middlewared/api/v25_04_0/vm_device.py
  src/middlewared/middlewared/api/v25_10_0/vm_device.py
  src/middlewared/middlewared/plugins/crypto_/ca_profiles.py
  src/middlewared/middlewared/plugins/crypto_/cert_profiles.py
  src/middlewared/middlewared/plugins/disk_/availability.py
  src/middlewared/middlewared/plugins/system/info.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/system/time.py
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
  src/middlewared/middlewared/plugins/vm/pci.py
  src/middlewared/middlewared/pytest/unit/plugins/vm/test_vm_gpu_pci_choices.py
  tests/api2/test_certificate_roles.py
  tests/api2/test_system_general.py
  tests/api2/test_truecommand_roles.py
Labels: backport-25.04-RC.1

#15679 NAS-134179 / 25.10 / fix dataset encryption API test failures
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
Labels: jira-low

#15680 NAS-134182 / 25.10 / Restore default to `disk.get_unused.join_partitions`
  src/middlewared/middlewared/plugins/disk_/availability.py
Labels: jira, backport-25.04-RC.1

#15670 NAS-134160 / 25.10 / remove schema validation on zfs_/dataset.py
  src/middlewared/middlewared/plugins/zfs_/dataset.py
Labels: jira-low

#15672 NAS-134168 / 25.10 / remove schema validation on zfs_/pool_wait.py
  src/middlewared/middlewared/plugins/zfs_/pool_wait.py
Labels: jira-low

#15673 NAS-134169 / 25.10 / Remove schema validation zfs_/pool_status.py
  src/middlewared/middlewared/plugins/zfs_/pool_status.py
Labels: jira-low

#15686 NAS-134025 / 25.10 / Stop apps when pool attr for docker service is changed
  src/middlewared/middlewared/plugins/docker/update.py
Labels: backport-25.04-RC.1

#15693 NAS-134196 / 25.10 / make FIPS tests run last
  tests/api2/test_zzzzz_openssl.py
Labels: jira-low, backport-25.04-RC.1

#15699 NAS-134175 / 25.10 / Ensure failover has not been disabled
  tests/api2/test_261_iscsi_cmd.py
  tests/api2/test_262_iscsi_alua.py
Labels: backport-25.04-RC.1

#15698 NAS-134170 / 25.04 / Add iser setting to iscsi.global
  src/middlewared/middlewared/alembic/versions/25.04/2025-02-11_22-45_iser.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
  src/middlewared/middlewared/plugins/iscsi_/iscsi_global.py
  src/middlewared/middlewared/plugins/iscsi_/iser.py
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Labels: backport-25.10

#15702 NAS-134085 / 25.10 / Fix random failures in apps tests
  tests/api2/test_apps.py
Labels: backport-25.04-RC.1

#15690 NAS-133751 / 25.10 / Allow importing/exporting disk images in virt plugin
  src/middlewared/middlewared/api/v25_04_0/virt_device.py
  src/middlewared/middlewared/api/v25_10_0/virt_device.py
  src/middlewared/middlewared/plugins/virt/disk.py
Labels: backport-25.04-RC.1

#15706 NAS-132120 / 25.04-RC.1 / Add API to enable ZFS snapdir access over NFS
  src/middlewared/middlewared/alembic/versions/25.04/2025-02-14_15-13_nfs_add_snapdir.py
  src/middlewared/middlewared/api/v25_04_0/nfs.py
  src/middlewared/middlewared/etc_files/exports.mako
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_nfs_snapdir.py
  tests/protocols/nfs_proto.py
Labels: backport-25.10

#15713 NAS-134235 / 25.10 / Add expose_snapshots to 25.10 schema
  src/middlewared/middlewared/api/v25_10_0/nfs.py
Labels: jira

#15714 NAS-134187 / 25.04-RC.1 / Remove unused iscsi.host API
  src/middlewared/middlewared/alembic/versions/25.04/2025-02-14_21-59_remove_iscsi_host.py
  src/middlewared/middlewared/api/v25_04_0/iscsi_global.py
  src/middlewared/middlewared/etc_files/scst.conf.mako
  src/middlewared/middlewared/plugins/iscsi_/host_crud.py
  src/middlewared/middlewared/plugins/iscsi_/host_initiator.py
  src/middlewared/middlewared/plugins/iscsi_/host_injection.py
  src/middlewared/middlewared/plugins/iscsi_/host_target.py
  src/middlewared/middlewared/plugins/iscsi_/status.py
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
  src/middlewared/middlewared/test/integration/assets/iscsi.py
  tests/api2/test_audit_iscsi.py
  tests/api2/test_iscsi_host_crud_roles.py
Labels: backport-25.10

#15710 NAS-134229 / 25.10 / Convert ipmi_/sel.py to new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/ipmi_sel.py
  src/middlewared/middlewared/plugins/ipmi_/sel.py
Labels: jira-low

#15675 NAS-134058 / 25.10 / Add roles for public pool.dataset namespace
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_info.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_lock.py
  src/middlewared/middlewared/plugins/pool_/dataset_encryption_operations.py
  src/middlewared/middlewared/plugins/pool_/dataset_processes.py
Labels: backport-25.04-RC.1

#15709 NAS-134228 / 25.10 / remove ipmi_/sensors.py from public api
  src/middlewared/middlewared/plugins/ipmi_/sensors.py
Labels: jira-low

#15720 NAS-134261 / 25.10 / Fix unit tests
  src/middlewared/middlewared/api/base/model.py
Labels: jira, backport-25.04-RC.1

#15691 NAS-134124 / 25.10 / Replication New API
  src/middlewared/middlewared/api/base/jsonschema.py
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/api/base/server/doc.py
  src/middlewared/middlewared/api/base/types/__init__.py
  src/middlewared/middlewared/api/base/types/list.py
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/common.py
  src/middlewared/middlewared/api/v25_10_0/pool_snapshottask.py
  src/middlewared/middlewared/api/v25_10_0/replication.py
  src/middlewared/middlewared/plugins/replication.py
Labels: backported, backport-25.04-RC.1

#15719 NAS-134091 / 25.10 / Mark `test_system_general_ui_rollback` as flaky
  src/middlewared/middlewared/plugins/system_general/ui.py
  tests/api2/test_system_general_ui_rollback.py
Labels: backport-25.04-RC.1

#15707 NAS-134183 / 25.10 / nvme-of: wait for timeout to pass if shelf was empty
  src/freenas/usr/local/bin/nvmf-connect.sh
Labels: backport-25.04-RC.1

#15736 NAS-134277 / 25.10 / Allow file downloads STIG mode
  src/middlewared/middlewared/api/v25_04_0/auth.py
  src/middlewared/middlewared/api/v25_10_0/auth.py
  src/middlewared/middlewared/auth.py
  src/middlewared/middlewared/service/core_service.py
Labels: jira-high, backport-25.04-RC.1

#15738 NAS-134202 / 25.10 / Add alert for missing SMB user hashes
  src/middlewared/middlewared/alert/source/smb.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
Labels: backport-25.04-RC.1

#15740 NAS-133680 / 25.10 / Disable SMB2 lease support in multiprotocol SMB mode
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/constants.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  tests/unit/test_smb_service.py
  tests/unit/test_smb_share.py
Labels: backport-25.04-RC.1

#15742 NAS-133911 / 25.10 / Increase auth failure delay to minimum of 4 seconds
  src/middlewared/middlewared/etc_files/pam.d/common-auth.mako
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/utils/auth.py
Labels: backport-25.04-RC.1

#15746 NAS-134279 / 25.10 / Use `LongString` for cloud credential errors
  src/middlewared/middlewared/api/v24_10/cloud_sync.py
  src/middlewared/middlewared/api/v25_04_0/cloud_sync.py
  src/middlewared/middlewared/api/v25_04_0/keychain.py
  src/middlewared/middlewared/api/v25_10_0/cloud_sync.py
  src/middlewared/middlewared/api/v25_10_0/keychain.py
Labels: backport-25.04-RC.1

#15743 NAS-134281 / 25.10 / Fix bad support-proxy error verbiage
  src/middlewared/middlewared/plugins/support.py
Labels: jira, backport-25.04-RC.1

#15745 NAS-134214 / 25.10 / Fix parsing `power_on_hours_ago`
  src/middlewared/middlewared/api/v25_04_0/smartctl.py
  src/middlewared/middlewared/api/v25_10_0/smartctl.py
  src/middlewared/middlewared/plugins/smart.py
Labels: backport-25.04-RC.1

#15659 NAS-134059 / 25.10 / Add roles to enclosure2 and update plugins
  src/middlewared/middlewared/api/v25_04_0/__init__.py
  src/middlewared/middlewared/api/v25_04_0/enclosure2.py
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/enclosure2.py
  src/middlewared/middlewared/plugins/enclosure_/enclosure2.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/role.py
Labels: backported, backport-25.04-RC.1

#15721 NAS-134262 / 25.10 / Load legacy API lazily to decrease startup time and RAM usage
  src/middlewared/middlewared/api/base/handler/model_provider.py
  src/middlewared/middlewared/api/base/handler/version.py
  src/middlewared/middlewared/api/base/server/legacy_api_method.py
  src/middlewared/middlewared/api/base/server/method.py
  src/middlewared/middlewared/apps/websocket_app.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/pytest/unit/api/base/server/test_legacy_api_method.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_default.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_excluded_field.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_nested_model_list.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_shortcuts.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_union.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/test_adapt_validation.py
  src/middlewared/middlewared/pytest/unit/api/handler/version/utils.py
  src/middlewared/middlewared/pytest/unit/helpers.py
Labels: jira, backport-25.04-RC.1

#15752 NAS-134288 / 25.10 / Fix auth failure delay
  src/middlewared/middlewared/utils/auth.py
Labels: jira, backport-25.04-RC.1

#15757 NAS-134293 / 25.10 / Convert update plugin to use SYSTEM_UPDATE_WRITE
  src/middlewared/middlewared/plugins/update.py
Labels: jira, backport-25.04-RC.1

#15756 NAS-134292 / 25.10 / Always build roles array when composing privilege
  src/middlewared/middlewared/role.py
Labels: jira, backport-25.04-RC.1

#15760 NAS-134295 / 25.10 / Fix initrd test timeout
  tests/api2/test_system_advanced.py
Labels: jira

#15751 NAS-134287 / 25.10 / Cloud sync new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/cloud.py
  src/middlewared/middlewared/api/v25_10_0/cloud_backup.py
  src/middlewared/middlewared/api/v25_10_0/cloud_credential.py
  src/middlewared/middlewared/api/v25_10_0/cloud_sync.py
  src/middlewared/middlewared/plugins/cloud/model.py
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_account_privilege_role_private_fields.py
Labels: jira

#15735 NAS-134276 / 25.10 / Convert truecommand plugin to new api style
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/truecommand.py
  src/middlewared/middlewared/plugins/truecommand/__init__.py
  src/middlewared/middlewared/plugins/truecommand/enums.py
  src/middlewared/middlewared/plugins/truecommand/portal.py
  src/middlewared/middlewared/plugins/truecommand/update.py
  src/middlewared/middlewared/plugins/truecommand/wireguard.py
  src/middlewared/middlewared/plugins/truenas.py
Labels: jira

#15761 NAS-134234 / 25.10 / fix deserialization of IPvAnyAddress for rdma api
  src/middlewared/middlewared/api/v25_04_0/rdma_interface.py
  src/middlewared/middlewared/api/v25_10_0/rdma_interface.py
Labels: backport-25.04-RC.1

#15725 NAS-134263 / 25.10 / Move kmip service to use new api style
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/kmip.py
  src/middlewared/middlewared/plugins/kmip/sync.py
  src/middlewared/middlewared/plugins/kmip/update.py
  src/middlewared/middlewared/plugins/kmip/utils.py
Labels: jira

#15765 NAS-134065 / 25.10 / Disable API_KEY role in GPOS STIG mode
  src/middlewared/middlewared/plugins/api_key.py
  src/middlewared/middlewared/role.py
Labels: backport-25.04-RC.1

#15767 NAS-134045 / 25.10 / Prevent enabling STIG if apps / vms are configured
  src/middlewared/middlewared/plugins/security/update.py
Labels: backport-25.04-RC.1

#15769 NAS-134311 / 25.10 / Make sure pid is reported as integer
  src/middlewared/middlewared/plugins/pool_/dataset_processes.py
Labels: jira, backport-25.04-RC.1

#15771 NAS-134316 / 25.10 / Fix API key deletion
  src/middlewared/middlewared/plugins/api_key.py
Labels: jira-high, backport-25.04-RC.1

#15772 NAS-132269 / 25.10 / Adjust IPC path for samba changes
  tests/api2/test_428_smb_rpc.py
Labels: backport-25.04-RC.1

#15776 NAS-134258 / 25.10 / Allow config save/upload for all full administrators
  src/middlewared/middlewared/plugins/config.py
Labels: backport-25.04-RC.1

#15779 NAS-134332 / 25.10 / Move interface listen endpoint to new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/interface_listen.py
  src/middlewared/middlewared/plugins/interface/listen.py
Labels: jira-low

#15733 NAS-134092 / 25.10 / Add PCI support for virt VM instances
  src/middlewared/middlewared/api/v25_04_0/virt_device.py
  src/middlewared/middlewared/api/v25_10_0/virt_device.py
  src/middlewared/middlewared/plugins/virt/device.py
  src/middlewared/middlewared/plugins/virt/instance_device.py
  src/middlewared/middlewared/utils/gpu.py
  src/middlewared/middlewared/utils/iommu.py
  src/middlewared/middlewared/utils/pci.py
Labels: backport-25.04-RC.1

#15781 NAS-134336 / 25.10 / move failover.disabled.reasons to new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/failover_disabled_reasons.py
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira-low

#15780 NAS-134199 / 25.10 / add compressratio to pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: backport-25.04-RC.1

#15678 NAS-133968 / 25.10 / Add scheduled cryptographic verification of OS file system for STIG
  src/middlewared/middlewared/alert/source/truenas_verify.py
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/audit/utils.py
Labels: backport-25.04-RC.1

#15788 NAS-134344 / 25.10 / Fix proc pid tests
  tests/api2/test_pool_dataset_track_processes.py
Labels: jira, backport-25.04-RC.1

#15718 NAS-134249 / 25.10 / convert failover.* to new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/failover.py
  src/middlewared/middlewared/plugins/failover.py
Labels: pending QA, jira-low

#15791 NAS-132536 / 25.10 / fix find_vdev() ordering to resolve USED spare detach failure
  src/middlewared/middlewared/plugins/zfs_/pool_utils.py
Labels: backport-25.04-RC.1

#15792 NAS-134345 / 25.10 / dont wipe disks on zpool detach
  src/middlewared/middlewared/plugins/pool_/pool_disk_operations.py
Labels: backport-25.04-RC.1

#15790 NAS-132911 / 25.04-RC.1 / Forcefully remove known-bad share-level aux params
  src/middlewared/middlewared/alembic/versions/25.04/2025-02-19_18-47_remove_blacklisted_aux_params.py
Labels: backport-25.10

#15795 NAS-134346 / 25.10 / Force passdb.tdb username keys to lower case
  src/middlewared/middlewared/plugins/smb_/util_passdb.py
  tests/api2/test_smb_camelcase.py
Labels: backport-25.04-RC.1

#15786 NAS-134340 / 25.10 / Remove takeover/giveback sub-commands in hactl
  src/freenas/usr/local/sbin/hactl
  tests/api2/test_014_failover_related.py
Labels: jira-low

#15754 NAS-134291 / 25.10 / Fix registry test for multiprotocol NFS
  tests/api2/test_435_smb_registry.py
Labels: jira, backport-25.04-RC.1

#15784 NAS-134338 / 25.10 / move failover.call_remote to private api
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira-low

#15796 NAS-134204 / 25.10 / Properly validate virt volume names
  src/middlewared/middlewared/api/v25_04_0/virt_volume.py
  src/middlewared/middlewared/api/v25_10_0/virt_volume.py
  tests/api2/test_virt_vm.py
Labels: backport-25.04-RC.1

#15806 NAS-134362 / 25.10 / Do not show a PCI device in choices if there is an error
  src/middlewared/middlewared/plugins/virt/device.py
Labels: jira, backport-25.04-RC.1

#15802 NAS-134353 / 25.10 / Adjust unit test for API_KEY STIG
  tests/unit/test_role_manager.py
Labels: jira, backport-25.04-RC.1

#15809 NAS-133925 / 25.10 / Do not start iscsitarget on STANDBY node unless ALUA is enabled.
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Labels: backport-25.04-RC.1

#15799 NAS-133386 / 25.10 / Display 24.10.2 node is pending reboot
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: backport-25.04-RC.1

#15813 NAS-134365 / 25.10 / Add GE migration directory for alembic
  src/middlewared/middlewared/alembic.ini
  src/middlewared/middlewared/alembic/versions/25.10/.gitkeep
Labels: jira

#15815 NAS-134378 / 25.10 / Ensure that SMB attachment delegate properly removes share
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/test/integration/assets/smb.py
  tests/api2/test_smb_delete_share_dataset.py
Labels: backport-25.04.0, jira-high, backport-25.04-RC.1

#15812 NAS-134250 / 25.10 / Expose specifying IO bus for disk devices
  src/middlewared/middlewared/api/v25_04_0/virt_device.py
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/api/v25_10_0/virt_device.py
  src/middlewared/middlewared/api/v25_10_0/virt_instance.py
  src/middlewared/middlewared/plugins/virt/instance.py
  src/middlewared/middlewared/plugins/virt/instance_device.py
  src/middlewared/middlewared/plugins/virt/utils.py
  tests/api2/test_virt_002_instance.py
  tests/api2/test_virt_vm.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15804 NAS-134266 / 25.10 / Fix discarded pool alerts
  src/middlewared/middlewared/plugins/alert.py
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15822 NAS-134391 / 25.10 / Add iSCSI CI test__initiators
  tests/api2/assets/websocket/iscsi.py
  tests/api2/test_261_iscsi_cmd.py
Labels: jira-medium

#15827 NAS-134271 / 25.10 / fix a few more dangling copyright issues
  src/freenas/usr/local/sbin/firmware_update.py
  src/freenas/usr/local/share/truenas/eula.html
  src/middlewared/middlewared/etc_files/motd.mako
  src/middlewared_docs/docs/conf.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15830 NAS-134351 / 25.10 / Prevent rpcbind from starting at boot by default
  debian/debian/postinst
  tests/unit/test_after_boot_services.py
Labels: backport-25.04.0

#15832 NAS-134425 / 25.04.0 / Add userns_idmap field to accounts
  src/middlewared/middlewared/alembic/versions/25.04/2025-02-24_13-55_userns_idmap.py
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/api/v25_04_0/group.py
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/etc_files/subgid.mako
  src/middlewared/middlewared/etc_files/subuid.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/account_/constants.py
  src/middlewared/middlewared/plugins/account_/privilege.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/service_/services/incus.py
  src/middlewared/middlewared/plugins/virt/instance.py
  tests/unit/test_account_userns.py
Labels: jira, backport-25.04-RC.1, backport-25.10

#15826 NAS-134360 / 25.10 / Add a description for PCI devices
  src/middlewared/middlewared/plugins/virt/device.py
  src/middlewared/middlewared/plugins/virt/instance_device.py
  src/middlewared/middlewared/plugins/virt/utils.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15835 NAS-134432 / 25.10 / Fix call processing of truenas_verify.
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/audit/utils.py
  tests/api2/test_truenas_verify.py
  tests/unit/test_truenas_verify.py
Labels: backport-25.04.0, jira-high

#15841 NAS-134361 / 25.10 / Mark PCI host bridge device as critical
  src/middlewared/middlewared/utils/iommu.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15844 NAS-134446 / 25.10 / use a deque in error path in virt.instance.start
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: backport-25.04.0, jira-low

#15839 NAS-134440 / 25.10 / Apply idmap configuration to incus instances
  src/middlewared/middlewared/plugins/virt/instance.py
  tests/api2/test_virt_002_instance.py
Labels: backport-25.04.0, jira-high, backport-25.04-RC.1

#15823 NAS-134473 / 25.10 / Add efficient method for reading GPT partitions on drives
  src/middlewared/middlewared/utils/disks_/get_disks.py
  src/middlewared/middlewared/utils/disks_/gpt_parts.py
  src/middlewared/middlewared/utils/disks_/private_utils.py
  tests/unit/test_gpt_parts.py
Labels: jira-low

#15852 NAS-134478 / 25.10 / Add name filters to get_disks()
  src/middlewared/middlewared/utils/disks_/get_disks.py
  src/middlewared/middlewared/utils/disks_/gpt_parts.py
  tests/unit/test_get_disks.py
Labels: jira-low

#15850 NAS-134474 / 25.10 / Drop Legacy VM tables
  src/middlewared/middlewared/alembic/versions/25.10/2025-02-26_09-34_drop_vm_tables.py
Labels: jira

#15851 NAS-134476 / 25.10 / Add functional test for NFSv4 ACL in containers
  src/middlewared/middlewared/test/integration/assets/virt.py
  tests/api2/test_virt_instance_acl.py
Labels: backport-25.04.0, jira-medium

#15854 NAS-134449 / 25.10 / On service restart avoid injecting iSER module while deactivating
  src/middlewared/middlewared/plugins/service_/services/iscsitarget.py
Labels: backport-25.04.0

#15856 NAS-134481 / 25.10 / Refactor get_disks() implementation
  src/middlewared/middlewared/utils/disks_/disk_class.py
  src/middlewared/middlewared/utils/disks_/get_disks.py
  src/middlewared/middlewared/utils/disks_/gpt_parts.py
  src/middlewared/middlewared/utils/disks_/private_utils.py
  tests/unit/test_gpt_parts.py
Labels: jira-low

#15858 NAS-134484 / 25.10 / Use common test assets for incus instance
  src/middlewared/middlewared/test/integration/assets/virt.py
  tests/api2/test_virt_002_instance.py
  tests/api2/test_virt_instance_acl.py
Labels: jira, backport-25.04.0

#15825 NAS-134309 / 25.10 / Make data partition slightly smaller than the disk
  src/middlewared/debian/control
  src/middlewared/middlewared/plugins/disk_/format.py
  src/middlewared/middlewared/plugins/pool_/attach_disk.py
  src/middlewared/middlewared/plugins/pool_/expand.py
  src/middlewared/middlewared/plugins/pool_/format_disks.py
  src/middlewared/middlewared/plugins/pool_/replace_disk.py
  src/middlewared/middlewared/test/integration/assets/pool.py
  src/middlewared/middlewared/test/integration/utils/disk.py
  tests/api2/test_pool_attach.py
  tests/api2/test_pool_expand.py
  tests/api2/test_pool_replace_disk.py
Labels: backport-25.04.0, backport-25.04-RC.1

#15861 NAS-134479 / 25.10 / Prevent rogue NFS configurations
  src/middlewared/middlewared/etc_files/nfs.conf.mako
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/nfs.py
  tests/api2/test_300_nfs.py
Labels: backport-25.04.0

#15857 NAS-134483 / 25.10 / Expand validation for incus paths in middleware
  src/middlewared/middlewared/plugins/virt/instance_device.py
  src/middlewared/middlewared/test/integration/assets/virt.py
  tests/api2/test_virt_002_instance.py
Labels: backport-25.04.0, backport-25.04-RC.1
