Repository truenas/middleware, pull requests merged in 2025-07, with the labels that each got.

#16691 NAS-136519 / 25.10 / Expand docs on disabling and leaving domains
  src/middlewared/middlewared/api/v25_10_0/directory_services.py
  src/middlewared/middlewared/plugins/directoryservices_/datastore.py
Labels: jira-medium

#16694 NAS-136525 / 25.10 / Fix service.control call in NFS and FTP test assets
  src/middlewared/middlewared/test/integration/assets/ftp.py
  src/middlewared/middlewared/test/integration/assets/nfs.py
Labels: jira-medium

#16698 NAS-136539 / 25.10 / Do not crash in `accept_params` when `alias` is used
  src/middlewared/middlewared/api/base/handler/accept.py
  src/middlewared/middlewared/pytest/unit/api/handler/accept/test_accept_1.py
Labels: jira-medium

#16699 NAS-136554 / 25.10 / Fixup support for the sharing_protocol CI tests.
  tests/runtest.py
  tests/sharing_protocols/conftest.py
Labels: jira-low

#16704 NAS-136537 / 25.10 / Fix broken certificate alerts
  src/middlewared/middlewared/alert/source/certificates.py
  tests/api2/test_certificate_expired_alert.py
Labels: backport-25.04.2

#16714 NAS-136629 / 25.10 / Fix SMB service unit test
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  tests/unit/test_smb_service.py
Labels: jira-medium

#16495 NAS-135869 / 25.10 / Update profiles
  src/middlewared/middlewared/alembic/versions/25.10/2025-07-10_10-24_update.py
  src/middlewared/middlewared/alert/source/update.py
  src/middlewared/middlewared/api/v25_10_0/failover.py
  src/middlewared/middlewared/api/v25_10_0/update.py
  src/middlewared/middlewared/etc_files/cron.d/middlewared.mako
  src/middlewared/middlewared/migration/0014_update_profile.py
  src/middlewared/middlewared/plugins/catalog/update.py
  src/middlewared/middlewared/plugins/docker/backup.py
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/failover_/reboot.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/plugins/update.py
  src/middlewared/middlewared/plugins/update_/config.py
  src/middlewared/middlewared/plugins/update_/download.py
  src/middlewared/middlewared/plugins/update_/download_linux.py
  src/middlewared/middlewared/plugins/update_/install.py
  src/middlewared/middlewared/plugins/update_/pending_linux.py
  src/middlewared/middlewared/plugins/update_/profile_.py
  src/middlewared/middlewared/plugins/update_/status.py
  src/middlewared/middlewared/plugins/update_/trains.py
  src/middlewared/middlewared/plugins/update_/update.py
  src/middlewared/middlewared/plugins/update_/utils.py
  src/middlewared/middlewared/plugins/update_/version.py
  src/middlewared/middlewared/pytest/unit/plugins/test_update.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_profile.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_status.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_trains.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_version.py
Labels: jira-medium

#16720 NAS-136658 / 25.10 / Robustize nvmet CI test__global_sessions_loopback
  tests/api2/test_nvmet_tcp.py
Labels: jira-low

#16721 NAS-136660 / 25.10 / Properly validate ports in virt plugin
  src/middlewared/middlewared/plugins/virt/global.py
Labels: jira-medium, backport-25.04.2

#16722 NAS-136661 / 25.10 / Add ha_settle
  src/middlewared/middlewared/test/integration/utils/__init__.py
  src/middlewared/middlewared/test/integration/utils/ha.py
  tests/directory_services/conftest.py
  tests/sharing_protocols/conftest.py
  tests/stig/conftest.py
Labels: jira-low

#16725 NAS-136664 / 25.10 / Avoid MISMATCH_NICS by forcing another persist_link_addresses
  src/middlewared/middlewared/plugins/failover.py
Labels: jira-low

#16715 NAS-136630 / 25.10 / Remove idmap_autorid as a choice for idmap backends
  src/middlewared/middlewared/alembic/versions/25.10/2025-07-14_12-22_autorid-migration.py
  src/middlewared/middlewared/api/v25_10_0/directory_services.py
  src/middlewared/middlewared/plugins/directoryservices_/datastore.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  tests/directory_services/test_activedirectory_idmap.py
Labels: jira-medium

#16733 NAS-136694 / 25.10 / Perform better NQN validation
  src/middlewared/middlewared/api/base/types/__init__.py
  src/middlewared/middlewared/api/base/types/nvmet.py
  src/middlewared/middlewared/api/v25_10_0/nvmet_global.py
  src/middlewared/middlewared/api/v25_10_0/nvmet_host.py
  src/middlewared/middlewared/api/v25_10_0/nvmet_subsys.py
  tests/api2/test_audit_nvmet.py
  tests/api2/test_nvmet_tcp.py
Labels: pending QA, jira-low

#16737 NAS-136698 / 25.10 / Generate a new claim token automatically for TNC
  src/middlewared/middlewared/plugins/truenas_connect/register.py
Labels: jira-medium

#16741 NAS-136709 / 25.10 / Disable EA support on SMB shares
  src/middlewared/middlewared/plugins/smb_/util_smbconf.py
  tests/unit/test_smb_share.py
Labels: jira-medium

#16742 NAS-136717 / 25.10 / allow unauthenticated calls to core.ping
  src/middlewared/middlewared/service/core_service.py
Labels: jira-high

#16750 NAS-136734 / 25.10 / Fix handle license update
  src/middlewared/middlewared/plugins/docker/state_management.py
Labels: jira-low

#16753 NAS-136737 / 25.10 / Send directoryservices.status events more often
  src/middlewared/middlewared/plugins/directoryservices_/health.py
  src/middlewared/middlewared/utils/directoryservices/health.py
Labels: jira-medium

#16743 NAS-136719 / 25.10 / Initialize FailoverRebootService.remote_reboot_reasons
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: jira-low

#16764 NAS-136753 / 25.10 / Fix model_validator for directoryservices entry
  src/middlewared/middlewared/api/v25_10_0/directory_services.py
  tests/directory_services/test_activedirectory_basic.py
Labels: jira-high

#16765 NAS-136755 / 25.10 / Add timeouts for IPACTL operations
  src/middlewared/middlewared/plugins/directoryservices_/ipa_join_mixin.py
Labels: jira-medium

#16771 NAS-136759 / 25.10 / Persist KDC affinity across HA failovers
  src/middlewared/middlewared/utils/directoryservices/krb5.py
Labels: jira-medium

#16736 NAS-136696 / 25.10 / Ensure ix-apps is mounted at it's proper place
  src/middlewared/middlewared/plugins/docker/fs_manage.py
Labels: jira-medium

#16785 NAS-136782 / 25.10 / Fix filter for checking time machine share
  src/middlewared/middlewared/etc_files/local/avahi/services/ADISK.service.py
  tests/api2/test_310_service_announcement.py
Labels: jira-medium

#16777 NAS-136771 / 25.10 / Factor in partitions as well when generating disk identifier
  src/middlewared/middlewared/utils/disks_/disk_class.py
Labels: jira-high

#16796 NAS-136814 / 25.10 / Fix `pool.dataset.get_quota` failing when the quota's user no longer exists
  src/middlewared/middlewared/plugins/pool_/dataset_quota.py
Labels: jira-high

#16797 NAS-136796 / 25.10 / Do not crash `pool.scrub.run` if `grep` finds no results
  src/middlewared/middlewared/plugins/pool_/scrub.py
Labels: backport-25.04.2

#16744 NAS-136720 / 25.10 / Allow case-sensitive rename of share
  src/middlewared/middlewared/plugins/smb.py
Labels: jira-low

#16801 NAS-136841 / 25.10 / Fix health state management when leaving domain
  src/middlewared/middlewared/plugins/directoryservices_/datastore.py
Labels: jira-medium

#16803 NAS-136819 / 25.10 / Limit NVMe RDMA I/O queues to 16 for ES24N shelves
  src/freenas/usr/local/bin/nvmf-connect.sh
Labels: backport-25.04.2

#16776 NAS-136770 / 25.10 / Fix multiple failover issues with directory services
  src/middlewared/middlewared/etc_files/sssd/sssd.conf.mako
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_health_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/activedirectory_join_mixin.py
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/directoryservices_/connection.py
  src/middlewared/middlewared/plugins/directoryservices_/datastore.py
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/smb_/groupmap.py
  src/middlewared/middlewared/plugins/system_dataset/hierarchy.py
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  src/middlewared/middlewared/test/integration/utils/failover.py
  src/middlewared/middlewared/test/integration/utils/ha.py
  src/middlewared/middlewared/utils/directoryservices/common.py
  src/middlewared/middlewared/utils/directoryservices/krb5.py
  src/middlewared/middlewared/utils/gencache.py
  tests/directory_services/test_zzz_truenas_ha.py
Labels: jira-medium

#16817 NAS-136894 / 25.10 / Add validation to prevent setting external path in SMB share
  src/middlewared/middlewared/plugins/smb.py
Labels: jira-medium

#16819 NAS-136898 / 25.10 / Regenerate the users.oath file when DS becomes healthy
  src/middlewared/middlewared/plugins/directoryservices_/health.py
Labels: jira-medium

#16825 NAS-136910 / 25.10 / Properly dump REST API payload for audit insertion
  src/middlewared/middlewared/restful.py
  src/middlewared/middlewared/test/integration/assets/api_key.py
  tests/api2/test_audit_rest.py
Labels: backport-25.04.2.1

#16834 NAS-136932 / 25.10 / Add log entry to middleware log on HA reboot
  src/middlewared/middlewared/plugins/failover_/scheduled_reboot_alert.py
Labels: jira-medium

#16827 NAS-136916 / 25.10 / Have consolidated app update alert instead of separate alerts for each app
  src/middlewared/middlewared/alert/source/applications.py
  src/middlewared/middlewared/plugins/apps/crud.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
Labels: jira-low

#16835 NAS-136936 / 25.10 / fix smart selftest alert
  src/middlewared/middlewared/alert/source/smart.py
Labels: jira-high
