Repository truenas/middleware, pull requests merged in 2025-04, with the labels that each got.

#16151 NAS-134051 / 25.10 / Validate enclosure id in `enclosure.label.set`
  src/middlewared/middlewared/plugins/enclosure_/enclosure_label.py
Labels: backport-25.04.1

#16152 NAS-134462 / 25.10 / Only generate an alert when the scrub starts. When the scrub is finished, then delete any existing scrub alerts for the pool
  src/middlewared/middlewared/plugins/zfs_/zfs_events.py
Labels: backport-25.04.1

#16153 NAS-134649 / 25.10 / remove blocking IO from schema
  src/middlewared/middlewared/api/v25_04_0/virt_volume.py
  src/middlewared/middlewared/api/v25_10_0/virt_volume.py
  src/middlewared/middlewared/plugins/virt/volume.py
Labels: backport-25.04.1

#16157 NAS-134463 / 25.10 / fix {ref}quota_warning properties in pool.dataset.details
  src/middlewared/middlewared/plugins/pool_/dataset_details.py
Labels: backport-25.04.1

#16115 NAS-134576 / 25.10 / STIG rule: All users individually identified and authenticated
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/security/update.py
  src/middlewared/middlewared/pytest/unit/plugins/test_user_ssh_enabled_validation.py
  tests/api2/test_zzzz_stig.py
Labels: backported, no-time-tracked, backport-25.04.1

#16162 NAS-134988 / 25.10 / synchronize DNS on HA master event
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: backported, no-time-tracked, backport-25.04.1

#16164 NAS-135120 / 25.10 / convert systemdataset.*
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/systemdataset.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: no-time-tracked, jira-medium

#16161 NAS-135118 / 25.10 / Convert network.general.summary
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/network_general.py
  src/middlewared/middlewared/plugins/network_/general.py
Labels: no-time-tracked, jira-medium

#16166 NAS-135123 / 25.10 / Fix validation error for FailoverRebootOtherNodeResult
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: backported, no-time-tracked, jira-high, backport-25.04.1

#16159 NAS-134540 / 25.10 / Fix phantom "Reboot Required" notifications after failover
  src/middlewared/middlewared/plugins/failover_/event.py
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: backport-25.04.1

#16174 NAS-135133 / 25.10 / fix test_audit_ha_query
  tests/api2/test_audit_basic.py
Labels: backported, no-time-tracked, jira-low, backport-25.04.1

#16160 NAS-135115 / 25.04.1 / Add STIG local password rules compliance
  src/middlewared/middlewared/alembic/versions/25.04/2025-03-26_18-30_stig-local-passwords.py
  src/middlewared/middlewared/alert/base.py
  src/middlewared/middlewared/alert/source/security.py
  src/middlewared/middlewared/api/v25_04_1/system_security.py
  src/middlewared/middlewared/api/v25_04_1/user.py
  src/middlewared/middlewared/etc_files/shadow.mako
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
  src/middlewared/middlewared/plugins/etc.py
  src/middlewared/middlewared/plugins/idmap.py
  src/middlewared/middlewared/plugins/security/update.py
  src/middlewared/middlewared/plugins/smb.py
  src/middlewared/middlewared/plugins/smb_/passdb.py
  src/middlewared/middlewared/plugins/smb_/util_account_policy.py
  src/middlewared/middlewared/plugins/smb_/util_passdb.py
  src/middlewared/middlewared/utils/security.py
  src/middlewared/middlewared/utils/time_utils.py
  tests/api2/test_011_user.py
  tests/api2/test_smb_account_expire.py
  tests/unit/test_passdb.py
  tests/unit/test_shadow_account_policy.py
Labels: jira-high, backport-25.10

#16173 NAS-135114 / 25.10 / `/api/versions`
  src/middlewared/middlewared/main.py
Labels: backport-25.04.0, backport-25.04.1

#16180 NAS-135114 / 25.10 / `/api/versions` test
  tests/api2/test_api.py
Labels: backport-25.04.0, backport-25.04.1

#16170 NAS-135126 / 25.10 / Handle platforms without FC PCI slot info
  src/middlewared/middlewared/plugins/fc/fc.py
  src/middlewared/middlewared/plugins/fc/fc_host.py
  tests/api2/test_fibre_channel.py
Labels: backport-25.04.1

#16181 NAS-135136 / 25.10 / set resttest methods private individually
  src/middlewared/middlewared/plugins/test/rest.py
Labels: jira-high

#16186 NAS-135137 / 25.10 / Fix SMB guest account on HA when standalone
  src/middlewared/middlewared/plugins/smb.py
Labels: jira-medium, backport-25.04.1

#16188 NAS-135144 / 25.10 / Fix initial admin user setup
  src/freenas/usr/local/bin/truenas-set-authentication-method.py
Labels: jira-high, backport-25.04.1

#16148 NAS-135103 / 25.10 / Convert ID_TYPE_BOTH to either USER or GROUP
  src/middlewared/middlewared/plugins/idmap_/idmap_winbind.py
Labels: jira-high, backport-25.04.1

#16149 NAS-135104 / 25.10 / Convert dns namespace
  src/middlewared/middlewared/api/base/types/list.py
  src/middlewared/middlewared/api/base/types/network.py
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/dns.py
  src/middlewared/middlewared/plugins/network_/dns.py
Labels: jira-medium

#16193 NAS-135169 / 25.10 / Adjust LDAP-related tests for new LDAP server
  src/middlewared/middlewared/test/integration/assets/directory_service.py
  tests/api2/test_275_ldap.py
Labels: jira-medium, backport-25.04.1

#16147 NAS-135100 / 25.10 / Move datastore/* plugins to new API (make them private)
  src/middlewared/middlewared/plugins/datastore/event.py
  src/middlewared/middlewared/plugins/datastore/read.py
  src/middlewared/middlewared/plugins/datastore/util.py
  src/middlewared/middlewared/plugins/datastore/write.py
Labels: jira-medium

#16169 NAS-135127 / 25.10 / Convert remaining system.advanced namespace
  src/middlewared/middlewared/api/v25_10_0/system_advanced.py
  src/middlewared/middlewared/plugins/system_advanced/config.py
  src/middlewared/middlewared/plugins/system_advanced/serial.py
  src/middlewared/middlewared/plugins/system_advanced/syslog.py
Labels: jira-medium

#16150 NAS-135106 / 25.10 / Convert route namespace
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/route.py
  src/middlewared/middlewared/plugins/network_/route.py
Labels: jira-medium

#16117 NAS-134949 / 25.10 / Clearer error message in `disk.format`
  src/middlewared/middlewared/plugins/disk_/format.py
Labels: backport-25.04.1

#16197 NAS-135186 / 25.10 / convert system/product.py to new API
  src/middlewared/middlewared/api/v25_10_0/__init__.py
  src/middlewared/middlewared/api/v25_10_0/system_product.py
  src/middlewared/middlewared/plugins/system/product.py
  src/middlewared/middlewared/role.py
Labels: jira-medium

#16205 NAS-135215 / 25.10 / Expand whitelist of FULL_ADMIN endpoints
  tests/unit/test_role_manager.py
Labels: jira-low

#16211 NAS-135222 / 25.10 / Fix ability to su to root
  src/middlewared/middlewared/utils/security.py
Labels: backport-25.04.1

#16217 NAS-135245 / 25.10 / Fix directoryservices.cache._retrieve
  src/middlewared/middlewared/plugins/directoryservices_/cache.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: jira-medium

#16218 NAS-135243 / 25.10 / Do not delete initiator group when last target in use is deleted
  src/middlewared/middlewared/plugins/iscsi_/targets.py
Labels: pending QA, backport-25.04.1

#16221 NAS-135265 / 25.10 / Fix validation for local usernames
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/api/v25_04_0/user.py
  src/middlewared/middlewared/api/v25_04_1/user.py
  src/middlewared/middlewared/api/v25_10_0/user.py
  tests/api2/test_account.py
Labels: jira-high, backport-25.04.1

#16223 NAS-135274 / 25.10 / Fix empty shell entry in DS cache
  src/middlewared/middlewared/plugins/directoryservices_/util_cache.py
  src/middlewared/middlewared/plugins/idmap.py
Labels: backport-25.04.0, backport-25.04.1

#16224 NAS-135268 / 25.10 / Fix two factor authentication for directory services
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/test/integration/assets/two_factor_auth.py
  tests/api2/test_twofactor_auth.py
Labels: backport-25.04.1

#16229 NAS-132373 / 25.10 / Fix ALUA breakage with particular input
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  src/middlewared/middlewared/plugins/iscsi_/scst.py
  src/middlewared/middlewared/plugins/iscsi_/targets.py
  src/middlewared/middlewared/plugins/iscsi_/utils.py
  tests/api2/test_261_iscsi_cmd.py
Labels: backport-25.04.1

#16234 NAS-135287 / 25.10 / dont unlock all disks in pool.format_disks
  src/middlewared/middlewared/plugins/pool_/format_disks.py
Labels: jira-high, backport-25.04.1

#16236 NAS-135289 / 25.10 / Fix typo in alert message.
  src/middlewared/middlewared/plugins/test/mock.py
Labels: jira-low

#16237 NAS-135291 / 25.10 / Restrict the size of AdminSession Alerts
  src/middlewared/middlewared/alert/source/auth.py
Labels: jira-medium, backport-25.04.1

#16239 NAS-135292 / 25.10 / Add failover.datastore.sql to message size whitelist
  src/middlewared/middlewared/utils/limits.py
Labels: jira-high, backport-25.04.1

#16242 NAS-135294 / 25.10 / Fix handling of frozenset
  src/middlewared/middlewared/plugins/security/update.py
Labels: jira-medium, backport-25.04.1

#16246 NAS-135316 / 25.10 / Fix deleting cloud credentials that is used by a cloud backup task
  src/middlewared/middlewared/plugins/cloud_sync.py
  tests/api2/test_cloud_backup.py
Labels: jira-medium, backport-25.04.1

#16249 NAS-135320 / 25.10 / Fix regex filters on nullable string fields
  src/middlewared/middlewared/pytest/unit/utils/test_filter_list.py
  src/middlewared/middlewared/utils/__init__.py
Labels: jira-medium, backport-25.04.1

#16241 NAS-135221 / 25.10 / Rewire when FC HBAs are added or replaced
  src/middlewared/middlewared/alert/source/fibre_channel.py
  src/middlewared/middlewared/plugins/fc/fc_host.py
  src/middlewared/middlewared/test/integration/assets/alert.py
  tests/api2/test_fibre_channel.py
Labels: backport-25.04.1

#16232 NAS-135242 / 25.10 / Bring back pool.dataset.destroy_snasphots
  src/middlewared/middlewared/api/base/decorator.py
  src/middlewared/middlewared/api/base/server/doc.py
  src/middlewared/middlewared/api/v25_04_1/__init__.py
  src/middlewared/middlewared/api/v25_04_1/pool_dataset.py
  src/middlewared/middlewared/api/v25_10_0/pool_dataset.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
  src/middlewared_docs/generate_docs.py
Labels: backport-25.04.1

#16257 NAS-135335 / 25.10 / Fix incorrect `system.reboot.info` handler
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: backport-25.04.1

#16259 NAS-135323 / 25.10 / fix network iface check on HA
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
  src/middlewared/middlewared/plugins/failover_/virtual_ips.py
Labels: backported, backport-25.04.1

#16261 NAS-135342 / 25.10 / fix firmware version ident for ES60
  src/middlewared/middlewared/plugins/enclosure_/enclosure_class.py
Labels: backport-25.04.1

#16267 NAS-135349 / 25.10 / Fix recent pytest breakage
  src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_update_validation.py
Labels: jira-low, backport-25.04.1

#16269 NAS-135367 / 25.10 / fix SSH service with aux params
  src/middlewared/middlewared/etc_files/local/ssh/sshd_config.mako
Labels: backport-25.04.1

#16266 NAS-135117 / 25.10 / Add disable of 'usage' reporting when GPOS STIG is enabled.
  src/middlewared/middlewared/plugins/security/update.py
  src/middlewared/middlewared/plugins/system_general/update.py
  tests/api2/test_zzzz_stig.py
Labels: jira-medium, backport-25.04.1

#16275 NAS-135376 / 25.10 / Fix enabling the root account
  src/freenas/usr/local/bin/truenas-set-authentication-method.py
Labels: jira-high

#16273 NAS-135372 / 25.10 / Fix test_060_immutable_user_validation
  tests/api2/test_011_user.py
Labels: jira-low

#16265 NAS-135348 / 25.10 / Add ability to query utmp file to middleware
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/plugins/auth_/authenticate.py
  src/middlewared/middlewared/plugins/security/sessions.py
  src/middlewared/middlewared/utils/account/__init__.py
  src/middlewared/middlewared/utils/account/constants.py
  src/middlewared/middlewared/utils/account/utmp.py
  src/middlewared/middlewared/utils/security.py
Labels: jira-medium, backport-25.04.1

#16279 NAS-135386 / 25.10 / hide macvlan interfaces from network API
  src/middlewared/middlewared/plugins/interface/netif_linux/utils.py
Labels: backport-25.04.1

#16278 NAS-135354 / 25.10 / Correct validation when attempting to start docker on boot
  src/middlewared/middlewared/plugins/docker/state_management.py
  src/middlewared/middlewared/plugins/docker/state_setup.py
Labels: backport-25.04.1

#16264 NAS-134549 / 25.10 / improve network check in HA check
  src/middlewared/middlewared/plugins/failover.py
  src/middlewared/middlewared/plugins/interface/link_address.py
  src/middlewared/middlewared/pytest/unit/plugins/test_failover.py
Labels: backport-25.04.1

#16285 NAS-135399 / 25.10 / rewrite README.md
  README.md
Labels: backport-25.04.1

#16288 NAS-135406 / 25.10 / Convert dnsclient
  src/middlewared/middlewared/plugins/dns_client.py
Labels: jira-medium

#16276 NAS-135377 / 25.10 / Expand possible incus instance status results in API
  src/middlewared/middlewared/api/v25_04_0/virt_instance.py
  src/middlewared/middlewared/api/v25_04_1/virt_instance.py
  src/middlewared/middlewared/api/v25_10_0/virt_instance.py
Labels: jira-medium, backport-25.04.1

#16283 NAS-134491 / 25.10 / Shorten TrueCloud Backup log excerpt
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/plugins/cloud_backup/restic.py
Labels: backport-25.04.1

#16294 NAS-135425 / 25.04.1 / Fix typo in failover.disabled.get_reasons
  src/middlewared/middlewared/plugins/failover_/disabled_reasons.py
Labels: jira-high

#16297 NAS-135430 / 25.10 / Fix cloud_backup test
  tests/api2/test_cloud_backup.py
Labels: jira-low, backport-25.04.1

#16302 Persist updated GMail OAuth refresh token
  src/middlewared/middlewared/plugins/mail_/gmail.py
Labels: backport-25.04.1

#16301 NAS-135361 / 25.10 / `get_tcp_ip_info` should determine socket family based on `X-Real-Remote-Addr`
  src/middlewared/middlewared/utils/origin.py
Labels: backport-25.04.1

#16310 NAS-135480 / 25.10 / Fix another_pool used by CI
  src/middlewared/middlewared/test/integration/assets/pool.py
Labels: jira-low, backport-25.04.1

#16315 NAS-135489 / 25.10 / Do not enforce boot priority for ISO volumes
  src/middlewared/middlewared/plugins/virt/instance_device.py
Labels: jira-low

#16314 NAS-135371 / 25.10 / Allow same host path to be mounted inside multiple containers
  src/middlewared/middlewared/plugins/virt/instance_device.py
Labels: backport-25.04.1

#16308 NAS-135477 / 25.10 / Make sure certs are only renewed on active node
  src/middlewared/middlewared/plugins/crypto_/renew_certs.py
  src/middlewared/middlewared/plugins/failover_/event.py
Labels: jira-medium

#16305 NAS-135471 / 25.10 / convert AuditBackend to new api
  src/middlewared/middlewared/plugins/audit/backend.py
Labels: jira-medium

#16311 NAS-135481 / 25.10 / Add validation checks for STIG enable.
  src/middlewared/middlewared/plugins/security/update.py
  tests/api2/test_zzzz_stig.py
Labels: jira-medium, backport-25.04.1

#16323 NAS-135510 / 25.10 / Fix passwd and shadow file generation
  src/middlewared/middlewared/plugins/etc.py
  tests/unit/test_container_root.py
Labels: jira-high, backport-25.04.1

#16322 NAS-135270 / 25.10 / Better group name validation
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/api/v25_10_0/group.py
  src/middlewared/middlewared/pytest/unit/api/base/types/test_user.py
  tests/api2/test_account.py
Labels: backport-25.04.1

#16329 NAS-135531 / 25.10 / Improve validation for ZFS resource creation
  src/middlewared/middlewared/plugins/pool_/dataset.py
Labels: jira-low, backport-25.04.1

#16326 NAS-135515 / 24.10.2.2 / Backport app config migrations to EE
  src/middlewared/middlewared/plugins/apps/migration_utils.py
  src/middlewared/middlewared/plugins/apps/upgrade.py
  src/middlewared/middlewared/pytest/unit/plugins/apps/test_migration_utils.py
  src/middlewared/middlewared/pytest/unit/plugins/apps/test_upgrade_values.py
Labels: jira-high

#16332 NAS-135238 / 25.04.1 / Try querying `system.reboot.info` once more in case the system is really upgraded, and the failure was just a hiccup.
  src/middlewared/middlewared/plugins/failover_/reboot.py
Labels: backport-25.10

#16335 NAS-135537 / 25.10 / Fix check for enabled generic accounts
  src/middlewared/middlewared/plugins/account.py
  src/middlewared/middlewared/plugins/security/update.py
Labels: backport-25.04.1

#16312 NAS-135336 / 25.10 / if FIPS is disabled but FIPS provider is active, raise alert
  src/middlewared/middlewared/alert/source/fips.py
Labels: backport-25.04.1

#16341 NAS-135550 / 25.10 / fix IndexError in account.update
  src/middlewared/middlewared/plugins/account.py
Labels: backport-25.04.1

#16343 NAS-135551 / 25.10 / better validation error when group is None
  src/middlewared/middlewared/plugins/account.py
Labels: backported, jira-low, backport-25.04.1

#16340 NAS-135543 / 25.10 / Allow SQLAlchemy default values to be callable to match SQLAlchemy ORM behavior
  src/middlewared/middlewared/plugins/datastore/write.py
  src/middlewared/middlewared/pytest/unit/plugins/test_datastore.py
Labels: jira-medium

#16348 NAS-135588 / 25.10 / Avoid JSON decode error on failed failover send
  src/middlewared/middlewared/plugins/failover_/remote.py
Labels: jira-medium, backport-25.04.1

#16337 NAS-135538 / 25.10 / Remove all references to `pydantic.SecretStr`
  .github/workflows/lint.yml
  src/middlewared/middlewared/api/base/validators_/passwd_complexity.py
  src/middlewared/middlewared/api/v25_10_0/acme_dns_authenticator.py
  src/middlewared/middlewared/api/v25_10_0/api_key.py
  src/middlewared/middlewared/api/v25_10_0/ipmi_lan.py
  src/middlewared/middlewared/api/v25_10_0/truecommand.py
  src/middlewared/setup.cfg
Labels: jira-high

#16355 NAS-135595 / 25.10 / Remove nvmet from cli
  src/middlewared/middlewared/plugins/nvmet/global.py
  src/middlewared/middlewared/plugins/nvmet/host.py
  src/middlewared/middlewared/plugins/nvmet/host_subsys.py
  src/middlewared/middlewared/plugins/nvmet/namespace.py
  src/middlewared/middlewared/plugins/nvmet/port.py
  src/middlewared/middlewared/plugins/nvmet/port_subsys.py
  src/middlewared/middlewared/plugins/nvmet/subsys.py
Labels: jira-low

#16354 NAS-135427 / 25.10 / Add 'support' to the list of denied activities allowed in STIG mode.
  src/middlewared/middlewared/plugins/security/update.py
  tests/api2/test_zzzz_stig.py
Labels: backport-25.04.1

#16358 NAS-135599 / 25.10 / Slightly drop password prompt age
  src/middlewared/middlewared/utils/security.py
Labels: backport-25.04.1

#16362 NAS-135603 / 25.10 / Expand documentation for password_history_length
  src/middlewared/middlewared/api/v25_04_1/system_security.py
  src/middlewared/middlewared/api/v25_10_0/system_security.py
Labels: jira-medium, backport-25.04.1

#16361 NAS-135475 / 25.10 / Do not allow to unset userns_idmap for builtins
  src/middlewared/middlewared/plugins/account.py
  tests/api2/test_account_idmap.py
Labels: backport-25.04.1

#16365 NAS-135605 / 25.10 / Robustize AlertMixin.clear_alert
  src/middlewared/middlewared/test/integration/assets/alert.py
Labels: jira-low, backport-25.04.1

#16357 NAS-135598 / 25.10 / persist MAC addresses in sync_to_peer
  src/middlewared/middlewared/plugins/failover.py
Labels: jira-high, backport-25.04.1

#16369 NAS-135614 / 25.10 / Fix copy&paste error in 25.04.1 API
  src/middlewared/middlewared/api/v25_04_1/cloud_sync.py
Labels: jira-medium, backport-25.04.1

#16359 NAS-135601 / 25.10 / Add status validation for instance start
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: jira-medium, backport-25.04.1

#16375 NAS-135492 / 25.10 / Improve root file system verify alert message.
  src/middlewared/middlewared/alert/source/truenas_verify.py
Labels: backport-25.04.1

#16379 NAS-135308 / 25.10 / Fix virt instance attachment delegate
  src/middlewared/middlewared/plugins/virt/attachments.py
  src/middlewared/middlewared/pytest/unit/plugins/virt/test_attachment_delegate.py
Labels: backport-25.04.1

#16378 NAS-135429 / 25.10 / Remove `cipher` from `system_keychaincredential` table in case it has been re-added
  src/middlewared/middlewared/alembic/versions/25.04/2025-04-29_16-48_remove-cipher-column.py
  src/middlewared/middlewared/alembic/versions/25.10/2025-04-02_15-40_merge-migration.py
Labels: backport-25.04.1

#16383 NAS-135623 / 25.10 / Relax security check for password aging data
  src/middlewared/middlewared/utils/security.py
Labels: backport-25.04.1

#16371 NAS-135620 / 25.10 / Simplify middleware audit startup
  docs/source/middleware/index.rst
  docs/source/middleware/state.rst
  src/middlewared/middlewared/alert/source/audit.py
  src/middlewared/middlewared/plugins/audit/__init__.py
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/system/__init__.py
  src/middlewared/middlewared/plugins/system/lifecycle.py
  src/middlewared/middlewared/plugins/system/utils.py
  src/middlewared/middlewared/utils/__init__.py
  tests/api2/test_audit_alerts.py
Labels: jira-medium, backport-25.04.1

#16388 NAS-135634 / 25.10 / Avoid vacuum operation on audit databases
  src/middlewared/middlewared/plugins/audit/backend.py
Labels: jira-medium, backport-25.04.1

#16393 NAS-135641 / 25.10 / fix invalid AuditService.setup log message
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/audit/utils.py
Labels: jira-medium, backport-25.04.1
