Repository truenas/middleware, pull requests merged in 2025-08, with the labels that each got.

#16842 NAS-136921 / 26.04 / plug a slow memory leak in service.* api
  src/middlewared/middlewared/plugins/service_/services/base.py
  src/middlewared/middlewared/plugins/service_/services/incus.py
Labels: backport-25.10-RC.1

#16774 NAS-136763 / 26.04 / Allow no args on some API methods
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/pytest/unit/api/base/test_model.py
Labels: jira-low

#16847 NAS-136960 / 26.04 / Add halfmoon migration directory for alembic
  src/middlewared/middlewared/alembic.ini
  src/middlewared/middlewared/alembic/versions/26.04/.gitkeep
Labels: jira-low

#16851 NAS-136974 / 26.04 / fix private zfs.resource.query_impl
  src/middlewared/middlewared/plugins/zfs/resource_crud.py
Labels: jira-low

#16848 NAS-136961 / 26.04 / remove zfs.dataset.query from apps/ix_volumes.py
  src/middlewared/middlewared/plugins/apps/ix_volumes.py
Labels: jira-low

#16852 NAS-136979 / 26.04 / add raise_on_nonent to zfs.resource.query_impl
  src/middlewared/middlewared/api/v26_04_0/zfs_resource_crud.py
  src/middlewared/middlewared/plugins/zfs/query_impl.py
Labels: jira-low

#16782 NAS-136779 / 26.04 / Fix some query endpoints' options schemas
  src/middlewared/middlewared/api/base/model.py
  src/middlewared/middlewared/api/v26_04_0/acl.py
  src/middlewared/middlewared/api/v26_04_0/audit.py
  src/middlewared/middlewared/api/v26_04_0/iscsi_global.py
  src/middlewared/middlewared/api/v26_04_0/pool_dataset.py
  src/middlewared/middlewared/plugins/audit/audit.py
  src/middlewared/middlewared/plugins/filesystem.py
  src/middlewared/middlewared/plugins/iscsi_/global_linux.py
Labels: jira-low

#16859 NAS-136989 / 25.10-RC.1 / Fix cdrom device path validation
  src/middlewared/middlewared/api/v25_10_0/vm_device.py
  src/middlewared/setup.cfg
Labels: backport-25.10-BETA.1, jira-medium, backport-26.04

#16857 NAS-136985 / 26.04 / remove zfs.dataset.query from docker/update.py
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_update_validation.py
Labels: jira-low

#16864 NAS-136994 / 25.04.2.1 / Do not configure directoryservices nsswitch on standby
  src/middlewared/middlewared/etc_files/nsswitch.conf.mako
Labels: jira-high

#16865 NAS-137002 / 26.04 / Expand type hints in `main.py`
  src/middlewared/middlewared/main.py
Labels: jira-low

#16856 NAS-136984 / 26.04 / remove unused VM api endpoints
  src/middlewared/middlewared/api/v26_04_0/virt_device.py
  src/middlewared/middlewared/api/v26_04_0/vm.py
  src/middlewared/middlewared/plugins/virt/disk.py
  src/middlewared/middlewared/plugins/vm/disk_utils.py
Labels: jira-low

#16867 NAS-137006 / 26.04 / Properly grab update status error
  src/middlewared/middlewared/plugins/update_/status.py
Labels: backport-25.10-BETA.1, jira-medium, backport-25.10-RC.1

#16845 NAS-136935 / 26.04 / Add method usage stats to usage plugin
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/utils/origin.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16875 NAS-137015 / 26.04 / Fix API for directory services cert choices
  src/middlewared/middlewared/api/v26_04_0/directory_services.py
Labels: jira-high

#16879 NAS-137016 / 26.04 / remove zfs.dataset.query from test_acltype.py
  tests/api2/test_acltype.py
Labels: jira-low

#16874 NAS-136946 / 26.04 / Make sure incus VMs do not start automatically on boot
  src/middlewared/middlewared/plugins/virt/global.py
  src/middlewared/middlewared/plugins/virt/instance.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16885 NAS-137023 / 26.04 / remove zfs.dataset.query from test_docker_backup.py
  tests/api2/test_docker_backup.py
Labels: jira-low

#16883 NAS-137020 / 26.04 / add trains_v2.json
  src/middlewared/middlewared/plugins/update_/trains.py
  src/middlewared/middlewared/pytest/unit/plugins/update/test_trains.py
  src/middlewared/middlewared/utils/__init__.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16893 NAS-137029 / 26.04 / Remove global 2fa check to unset 2FA token
  src/middlewared/middlewared/plugins/account_/2fa.py
Labels: jira-medium, backport-25.10-RC.1

#16866 NAS-137010 / 26.04 / Cache function pointers to nss module functions
  src/middlewared/middlewared/utils/nss/nss_common.py
Labels: jira-medium, backport-25.10-RC.1

#16901 NAS-136937 / 26.04 / Do not get CPU model choices from libvirt
  src/middlewared/middlewared/plugins/vm/info.py
  src/middlewared/middlewared/plugins/vm/pci.py
  src/middlewared/middlewared/plugins/vm/utils.py
Labels: backport-25.10-RC.1

#16897 NAS-137033 / 26.04 / remove zfs.dataset.query from docker/state_setup.py
  src/middlewared/middlewared/plugins/docker/state_setup.py
Labels: jira-low

#16899 NAS-137035 / 26.04 / fix create_snapshot()
  src/middlewared/middlewared/plugins/cloud/snapshot.py
  src/middlewared/middlewared/pytest/unit/plugins/test_cloud_sync.py
Labels: jira-low

#16898 NAS-137034 / 26.04 / remove zfs.dataset.query from pool_/dataset.py
  src/middlewared/middlewared/plugins/pool_/dataset.py
Labels: jira-low

#16903 NAS-137042 / 26.04 / remove zfs.dataset.query from zfs_/dataset_encryption.py
  src/middlewared/middlewared/plugins/zfs_/dataset_encryption.py
Labels: jira-low

#16905 NAS-137044 / 26.04 / remove zfs.dataset.query from virt/volume.py
  src/middlewared/middlewared/plugins/virt/volume.py
Labels: jira-low

#16915 NAS-137056 / 26.04 / fix legacy API client test
  tests/api2/test_legacy_api.py
Labels: jira-low

#16907 NAS-137048 / 26.04 / Add CI test for pool.filesystem_choices
  tests/api2/test_pool_dataset_info.py
Labels: jira-low

#16923 NAS-137067 / 26.04 / add get_encryption_info helper function
  src/middlewared/middlewared/plugins/docker/update.py
  src/middlewared/middlewared/plugins/sysdataset.py
  src/middlewared/middlewared/plugins/zfs/utils.py
  src/middlewared/middlewared/pytest/unit/plugins/docker/test_docker_update_validation.py
Labels: jira-low

#16925 NAS-137072 / 26.04 / remove zfs.dataset.query from usage.py
  src/middlewared/middlewared/plugins/usage.py
  src/middlewared/middlewared/plugins/zfs/query_impl.py
Labels: jira-low

#16926 NAS-137074 / 26.04 / remove pool.dataset.query from docker/backup_to_pool.py
  src/middlewared/middlewared/plugins/docker/backup_to_pool.py
Labels: jira-low

#16929 NAS-137078 / 26.04 / fix another KeyEror in sysdataset.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira-low

#16931 NAS-137083 / 26.04 / fix typo in sysdataset.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira-low

#16932 NAS-137084 / 26.04 / remove pool.dataset.get_instance from sysdataset.py
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira-low

#16928 NAS-137063 / 26.04 / Raise an alert for expiration of cert selectively
  src/middlewared/middlewared/alert/source/certificates.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16943 NAS-137110 / 26.04 / Fix audit alert CI test.
  tests/api2/test_audit_alerts.py
Labels: jira-low

#16944 NAS-137112 / 26.04 / Fix API schema for reporting data
  src/middlewared/middlewared/api/v26_04_0/reporting.py
  src/middlewared/middlewared/plugins/reporting/netdata/graph_base.py
Labels: backport-25.10-BETA.1, jira-medium, backport-25.10-RC.1

#16948 NAS-137114 / 26.04 / fix query_pools_for_system_dataset
  src/middlewared/middlewared/plugins/sysdataset.py
Labels: jira-medium

#16937 NAS-137097 / 26.04 / Comprehensive type hints for central middleware components
  src/middlewared/middlewared/api/base/server/ws_handler/rpc.py
  src/middlewared/middlewared/apps/file_app.py
  src/middlewared/middlewared/apps/websocket_app.py
  src/middlewared/middlewared/auth.py
  src/middlewared/middlewared/common/event_source/manager.py
  src/middlewared/middlewared/event.py
  src/middlewared/middlewared/job.py
  src/middlewared/middlewared/main.py
  src/middlewared/middlewared/plugins/auth.py
  src/middlewared/middlewared/service/crud_service.py
  src/middlewared/middlewared/types.py
  src/middlewared/middlewared/utils/audit.py
  src/middlewared/middlewared/utils/origin.py
  src/middlewared/middlewared/utils/privilege.py
  src/middlewared/middlewared/utils/profile.py
  src/middlewared/middlewared/utils/service/call.py
Labels: jira-low

#16952 NAS-137127 / 26.04 / Fix API docs code blocks not rendering
  src/middlewared_docs/docs/conf.py
  src/middlewared_docs/docs/jobs.rst
  src/middlewared_docs/docs/jsonrpc.rst
  src/middlewared_docs/docs/query_methods.rst
Labels: jira-low

#16960 NAS-137126 / 26.04 / Fix proper disk syncing in Xen VMs
  src/middlewared/middlewared/pytest/unit/plugins/disk/test_dev_to_ident.py
  src/middlewared/middlewared/pytest/unit/utils/test_disk_names.py
  src/middlewared/middlewared/utils/disks.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16967 NAS-137105 / 26.04 / Adjust maximum timeout value for directory services
  src/middlewared/middlewared/api/v25_10_0/directory_services.py
  src/middlewared/middlewared/api/v26_04_0/directory_services.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16979 NAS-137179 / 26.04 / Fix default value for WORM grace period
  src/middlewared/middlewared/plugins/smb.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16978 NAS-137061 / 26.04 / Fix `alertservice.create` for Mattermost and OpsGenie types
  src/middlewared/middlewared/api/v25_10_0/alertservice_attributes.py
  src/middlewared/middlewared/api/v26_04_0/alertservice_attributes.py
Labels: backport-25.10-RC.1

#16984 NAS-137180 / 26.04 / Properly fix disk syncing in xen VMs
  src/middlewared/middlewared/utils/disks.py
  src/middlewared/middlewared/utils/disks_/disk_class.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16990 NAS-137199 / 26.04 / Fix certificate source alert
  src/middlewared/middlewared/alert/source/certificates.py
  src/middlewared/middlewared/plugins/crypto_/renew_certs.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16982 NAS-137171 / 26.04 / Add 'scope' setting to support HA.
  src/middlewared/middlewared/etc_files/nfs.conf.mako
  src/middlewared/middlewared/plugins/etc.py
  tests/api2/test_300_nfs.py
Labels: pending QA, backport-25.10-RC.1

#17041 NAS-137255 / 26.04 / Update nvmet become_active to start the service if necessary
  src/middlewared/middlewared/plugins/service_/services/pseudo/misc.py
Labels: backport-25.10-RC.1

#17043 NAS-137267 / 26.04 / Properly send snapshot to snapshot exists endpoint
  src/middlewared/middlewared/plugins/docker/backup.py
Labels: jira-medium

#17048 NAS-137261 / 26.04 / Update R60 drive map
  src/middlewared/middlewared/plugins/enclosure_/nvme2.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#17044 NAS-137259 / 26.04 / Sanitize filepath in sharing_task_determine_locked for iSCSI and nvmet
  src/middlewared/middlewared/plugins/iscsi_/extents.py
  src/middlewared/middlewared/plugins/nvmet/namespace.py
Labels: backport-25.10-BETA.1, backport-25.10-RC.1

#16989 NAS-137198 / 26.04 / Relax validation of email address in query results
  src/middlewared/middlewared/api/v25_10_0/user.py
  src/middlewared/middlewared/api/v26_04_0/user.py
Labels: backport-25.10-RC.1

#17066 NAS-137303 / 26.04 / fix snapshot role test
  tests/api2/test_account_privilege_role.py
Labels: jira-low

#17079 NAS-137325 / 26.04 / use upstream nginx logrotate.d file
  src/freenas/etc/logrotate.d/nginx
Labels: jira-high

#17080 NAS-137326 / 26.04 / Use common error code for `NetworkActivityDisabled` (`ENONET`)
  src/middlewared/middlewared/service_exception.py
Labels: jira-medium, backport-25.10-RC.1

#17082 NAS-137327 / 26.04 / remove nginx/error.log from nginx.conf
  src/freenas/etc/logrotate.d/nginx-truenas
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: jira-high

#17088 NAS-121593 / 26.04 / Add logic for renewing DNS entries
  src/middlewared/middlewared/alert/source/directory_services.py
  src/middlewared/middlewared/plugins/directoryservices_/connection.py
  src/middlewared/middlewared/utils/directoryservices/constants.py
  src/middlewared/middlewared/utils/directoryservices/dns.py
  src/middlewared/middlewared/utils/directoryservices/health.py
Labels: backport-25.10-RC.1

#17089 NAS-136353 / 26.04 / add more security headers to nginx.conf
  src/middlewared/middlewared/etc_files/local/nginx/nginx.conf.mako
Labels: backport-25.10-RC.1

#17087 NAS-137329 / 26.04 / Convert audit event schema to pydantic models
  src/middlewared/middlewared/api/base/types/user.py
  src/middlewared/middlewared/api/v26_04_0/audit.py
  src/middlewared/middlewared/plugins/audit/schema/common.py
  src/middlewared/middlewared/plugins/audit/schema/middleware.py
  src/middlewared/middlewared/plugins/audit/schema/smb.py
  src/middlewared/middlewared/plugins/audit/schema/sudo.py
  src/middlewared/middlewared/plugins/audit/utils.py
  tests/api2/test_420_smb.py
Labels: jira-low
